// @ts-nocheck
import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const db=createClient(Deno.env.get('SUPABASE_URL')||'',Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'',{auth:{persistSession:false}});
const BRIDGE='https://buivecgahhmrhlmfujgt.supabase.co/functions/v1/qrpay-ai-order-bridge';
const H={'content-type':'application/json','access-control-allow-origin':'*','access-control-allow-methods':'POST,OPTIONS','access-control-allow-headers':'content-type,x-qrpay-ai-token','cache-control':'no-store'};
const out=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H});
const t=(x:any)=>x==null?'':String(x).trim(),mt=(m:any)=>t(m.text_content||m.caption),at=(m:any)=>Date.parse(m.sent_at||m.created_at||'')||0,min=(a:number,b:number)=>Math.abs(a-b)/60000;
const fn=(m:any)=>t(m.raw_payload?.data?.raw?.message?.document?.filename||m.raw_payload?.data?.raw?.message?.image?.filename||m.media_metadata?.file_name||m.media_metadata?.filename);
const phone=(x:any)=>{let d=t(x).replace(/\D/g,'');if(!d)return'';if(d[0]=='0')d='60'+d.slice(1);else if(d[0]=='1')d='60'+d;else if(!d.startsWith('60'))d='60'+d;return d};
const wa=(x:any)=>x?`https://wa.me/${phone(x)}`:'',money=(x:any)=>Number(Number(x||0).toFixed(2));
const exact=(s:string,a:number)=>[...s.replace(/,/g,' ').matchAll(/(?:rm\s*)?(\d{1,5}(?:\.\d{1,2})?)/gi)].some(m=>Math.abs(Number(m[1])-a)<.011);
const paid=(s:string)=>/(dah|dh|sudah|done|already|telah|settle|paid).{0,24}(bayar|payment|transfer|pay)|done payment|dah bayar|dh bayar/i.test(s);
const payPrompt=(s:string)=>/qrpay|qr pay|bagi qr|bg qr|send qr|nom(?:bor)? acc|akaun|account|payment|bayar|total\s*(?:rm)?\s*\d/i.test(s);
const receipt=(m:any)=>{const s=(mt(m)+' '+fn(m)+' '+JSON.stringify(m.media_metadata||{})).toLowerCase();if(m.message_type==='document')return /m2u|cimb\s*octo|bimb.*receipt|receipt|resit|duitnow|payment|transfer|bank.*slip/.test(s);if(m.message_type==='image')return /receipt|resit|duitnow|payment|transfer|bayar|qrpay|qr pay/.test(s);return false};
async function orderCall(token:string,body:any){const r=await fetch(BRIDGE,{method:'POST',headers:{'content-type':'application/json','x-qrpay-ai-token':token},body:JSON.stringify(body)});const j=await r.json().catch(()=>({error:'Invalid bridge response'}));if(!r.ok||j.ok===false)throw Error(j.error||`Bridge HTTP ${r.status}`);return j}
async function auth(req:Request){const k=req.headers.get('x-qrpay-ai-token')||'',r=await db.from('private_runtime_settings').select('setting_value').eq('setting_key','qrpay_ai_worker_token').maybeSingle();return!!k&&!r.error&&k===r.data?.setting_value}
const cols='id,conversation_id,direction,message_type,text_content,caption,sent_at,created_at,sender_phone,provider_message_id,media_url,media_metadata,raw_payload';
async function windowMsgs(ts:number){const s=new Date(ts-150*60000).toISOString(),e=new Date(ts+15*60000).toISOString(),[a,b]=await Promise.all([db.from('messages').select(cols).eq('channel','whatsapp').gte('sent_at',s).lte('sent_at',e),db.from('messages').select(cols).eq('channel','whatsapp').is('sent_at',null).gte('created_at',s).lte('created_at',e)]);if(a.error)throw a.error;if(b.error)throw b.error;const z=new Map();for(const m of [...(a.data||[]),...(b.data||[])])z.set(m.id,m);return[...z.values()].sort((p,q)=>at(p)-at(q))}
async function context(id:string,ts:number){const s=new Date(ts-36*3600000).toISOString(),e=new Date(ts+15*60000).toISOString(),r=await db.from('messages').select(cols).eq('conversation_id',id).gte('created_at',s).lte('created_at',e).order('created_at').limit(180);if(r.error)throw r.error;return r.data||[]}
function score(ms:any[],amt:number,ts:number){let n=0,c=99999,why:any[]=[],hasExact=false;for(const m of ms){const d=min(at(m),ts),v=mt(m);c=Math.min(c,d);if(m.direction==='inbound'&&receipt(m))n+=d<=15?320:d<=60?220:100;if(m.direction==='inbound'&&paid(v))n+=d<=20?45:28;if(m.direction==='outbound'&&exact(v,amt)){n+=260;hasExact=true}if(m.direction==='outbound'&&payPrompt(v))n+=8}if(ms.some(receipt))why.push('receipt_near_payment');if(ms.some(m=>paid(mt(m))))why.push('customer_payment_claim');if(hasExact)why.push('exact_amount_quote');n+=Math.max(0,22-c/8);why.push(`closest_message_${Math.round(c)}m`);return{n,why,hasExact}}
async function best(job:any){const ts=Date.parse(job.payment_received_at),all=await windowMsgs(ts),g:any={},excluded=new Set<string>((Array.isArray(job?.evidence?.excluded_conversation_ids)?job.evidence.excluded_conversation_ids:[]).map((x:any)=>String(x)));for(const m of all)(g[m.conversation_id]??=[]).push(m);const cs:any[]=Object.entries(g).filter(([id])=>!excluded.has(String(id))).map(([id,ms]:any)=>({id,ms,...score(ms,Number(job.amount),ts)})).sort((a,b)=>b.n-a.n).slice(0,5);for(const c of cs){const q=await db.from('conversations').select('customer_id').eq('id',c.id).maybeSingle(),cid=q.data?.customer_id;let name='WhatsApp Customer',p=phone(c.ms.find((m:any)=>m.sender_phone)?.sender_phone);if(cid){const[a,b]=await Promise.all([db.from('customers').select('display_name').eq('id',cid).maybeSingle(),db.from('customer_identities').select('normalized_phone,external_id').eq('customer_id',cid).eq('channel','whatsapp')]);name=t(a.data?.display_name)||name;p=phone(b.data?.find((i:any)=>i.normalized_phone)?.normalized_phone||b.data?.[0]?.external_id||p)}c.name=name;c.phone=p}if(cs[0])cs[0].why.push(`score_margin_${Math.round(cs[0].n-(cs[1]?.n||0))}`);return{top:cs[0]||null,alts:cs.slice(1).map(c=>({conversation_id:c.id,score:c.n,name:c.name,phone:c.phone})),excluded_conversation_ids:[...excluded]}}
const autoNoise=(s:string)=>/HARGA ACRYLIC|RUJUKAN SAIZ MAKSIMUM|Menerima order:|save for order:|Terima kasih hubungi DecoCake/i.test(s);
function anchor(ms:any[],amt:number,ts:number){let idx=ms.length-1,d=Infinity;for(let i=0;i<ms.length;i++){const v=mt(ms[i]);if(receipt(ms[i])||paid(v)||(ms[i].direction==='outbound'&&exact(v,amt))){const x=min(at(ms[i]),ts);if(x<d){idx=i;d=x}}}return idx}
function around(ms:any[],amt:number,ts:number){const a=anchor(ms,amt,ts);return ms.slice(Math.max(0,a-24),Math.min(ms.length,a+5)).filter(m=>!autoNoise(mt(m)))}
const catRe:any={edible:/\bedible\b|\bei\b|print gambar|icing sheet/i,acrylic:/acrylic|akrilik|ayrlic|arylic|arcylic/i,wafer:/\bwafer\b/i,burnaway:/burn\s*away|burnaway/i,printed:/\btopper\b|glossy|printed topper|topper tema/i,mirror:/mirror gold artpaper|artpaper/i};
function categories(ms:any[],job:any,active:Set<string>){const rel=around(ms,Number(job.amount),Date.parse(job.payment_received_at)),z=new Set<string>();for(const m of rel){const s=mt(m);if(!s)continue;if(m.direction==='outbound'&&!active.has('preserve_distinct_products')&&!/\brm\s*\d/i.test(s))continue;for(const[k,re]of Object.entries(catRe))if((re as RegExp).test(s))z.add(k)}if(z.has('burnaway')){z.delete('edible');z.delete('wafer')}if(z.has('acrylic')&&!rel.some(m=>m.direction==='inbound'&&catRe.printed.test(mt(m))))z.delete('printed');if(!z.size)z.add('printed');return[...z]}
function categoryMessages(ms:any[],cat:string){const re=catRe[cat]||catRe.printed,idx=new Set<number>();for(let i=0;i<ms.length;i++)if(re.test(mt(ms[i])))for(let j=Math.max(0,i-3);j<=Math.min(ms.length-1,i+3);j++)idx.add(j);return[...idx].map(i=>ms[i]).filter(m=>!autoNoise(mt(m)))}
function explicitRm(line:string){const a=[...line.matchAll(/\brm\s*(\d{1,5}(?:\.\d{1,2})?)/gi)];return a.length?Number(a.at(-1)![1]):null}
function sellerPrices(ms:any[]){const p:any={};for(const m of ms.filter(x=>x.direction==='outbound'))for(const raw of mt(m).split(/\n+/)){const v=raw.trim();if(!v||autoNoise(v)||/\btotal\b/i.test(v))continue;const rm=explicitRm(v);if(rm==null||rm>500)continue;if(catRe.edible.test(v))p.edible=rm;if(catRe.acrylic.test(v))p.acrylic=rm;if(catRe.wafer.test(v))p.wafer=rm;if(catRe.burnaway.test(v))p.burnaway=rm;if(catRe.printed.test(v)&&!catRe.acrylic.test(v))p.printed=rm;if(catRe.mirror.test(v))p.mirror=rm}return p}
function qty(ms:any[],cat:string,active:Set<string>){const re=catRe[cat]||catRe.printed;for(const m of [...ms].reverse()){const v=mt(m);if(!v||/\brm\s*\d/i.test(v)&&!re.test(v))continue;let x=v.match(new RegExp(`(?:${re.source}).{0,24}?(\\d{1,2})\\s*(?:pcs?|pc|keping|set|unit|design)?\\b`,'i'))||v.match(new RegExp(`\\b(\\d{1,2})\\s*(?:pcs?|pc|keping|set|unit|design)?\\s*(?:x\\s*)?(?:${re.source})`,'i'));if(x){const n=Number(x[1]);if(n>=1&&n<=50&&!/\bA[4-7]\b/i.test(x[0]))return n}if(active.has('qty_from_nearest_explicit_item_count')&&re.test(v)){x=v.match(/\b(?:qty\s*)?(\d{1,2})\b/i);if(x){const n=Number(x[1]);if(n>=1&&n<=50&&!new RegExp(`A${n}`,'i').test(v)&&!new RegExp(`RM\\s*${n}`,'i').test(v))return n}}}return 1}
function size(ss:string[]){const ps=[/\b(\d+(?:\.\d+)?\s*[x×]\s*\d+(?:\.\d+)?\s*(?:inch|inci|in)?)\b/i,/\b(\d+(?:\.\d+)?\s*(?:inch|inci|inches|in))\b/i,/(\d+(?:\.\d+)?)\s*\"/i,/\b(A[4-7])\b/i];for(const r of ps)for(let i=ss.length-1;i>=0;i--){const m=ss[i].match(r);if(m)return m[1]}return''}
function style(ss:string[]){const colors=['rose gold','silver mirror','gold mirror','silver','gold','black','white','clear','pink','blue','red','green','orange','yellow','purple','lilac'];let c='',sh='';for(let i=ss.length-1;i>=0;i--){const v=ss[i].toLowerCase();if(!c)c=colors.find(x=>v.includes(x))||'';if(!sh){if(/bulat|circle|round/.test(v))sh='Round / Bulat';else if(/petak|square/.test(v))sh='Square / Petak';else if(/hati|love shape/.test(v))sh='Love Shape / Hati'}if(c&&sh)break}return[c&&c.replace(/\b\w/g,x=>x.toUpperCase()),sh].filter(Boolean).join(' — ')}
function validW(v:string){v=v.trim();return!!v&&!/^(OK|YA|YE|SAMA|BAIK|SALAM|BOLEH|CONFIRM)$/i.test(v)&&!/payment|alamat|address|total|spx|jnt|postcode|poskod|pickup|proses|kirim|bagi total/i.test(v)}
function explicitWording(v:string){for(const line of v.split(/\n+/)){const m=line.match(/^\s*(?:wording|tulisan|custom\s*name|nama|huruf)\s*[:=-]\s*(.+?)\s*$/i);if(m&&validW(m[1]))return m[1].trim()}return''}
function wording(ms:any[],active:Set<string>){const inbound=ms.filter(m=>m.direction==='inbound');for(const m of [...inbound].reverse()){const w=explicitWording(mt(m));if(w)return w}const a=inbound.map(mt).filter(Boolean),c=[];for(let i=0;i<a.length;i++){let v=a[i].trim();if(/^(wording|tulisan|custom\s*name|nama|huruf)\s*[:=-]?/i.test(v)){v=v.replace(/^(wording|tulisan|custom\s*name|nama|huruf)\s*[:=-]?/i,'').trim();if(validW(v))c.push(v);if(active.has('wording_from_explicit_label')&&a[i+1]&&validW(a[i+1]))c.push(a[i+1])}else if(/^(happy|selamat|the wedding|mubarak|congrat|welcome|birthday)/i.test(v)&&validW(v))c.push(v)}return[...new Set(c)].slice(-2).join('\n').slice(0,300)}
function shortTitle(ms:any[],cat:string,fallback:string){const re=catRe[cat]||catRe.printed;for(const m of [...ms].reverse()){if(m.direction!=='inbound')continue;let v=mt(m);if(!re.test(v)||autoNoise(v))continue;v=v.replace(/\brm\s*\d+(?:\.\d+)?/ig,' ').replace(/\b(?:nak|mahu|mau|buat|order|oder|topper|cake topper|edible image|edible|acrylic|akrilik|wafer paper|wafer|burn away|glossy|paper|size|saiz|qty|pcs?|set)\b/ig,' ').replace(/\bA[4-7]\b/ig,' ').replace(/\b\d+(?:\.\d+)?\s*(?:inch|inci|in)?\b/ig,' ').replace(/\s+/g,' ').trim().replace(/^[-,:]+|[-,:]+$/g,'').trim();if(v.length>=2&&v.length<=60)return v.replace(/\b\w/g,x=>x.toUpperCase())}return fallback}
function delivery(ms:any[],active:Set<string>){const rel=[...ms].filter(m=>!autoNoise(mt(m)));if(active.has('shipping_from_latest_explicit_quote')){for(const m of [...rel].reverse()){const v=mt(m);if(/pickup|ambil|ambik|self collect/i.test(v))return{method:'pickup',fee:0,evidence:m.id};if(/\bspx\b/i.test(v))return{method:'spx',fee:explicitRm(v)??4.5,evidence:m.id};if(/\bj\s*&?\s*t\b|\bjnt\b/i.test(v))return{method:'jnt',fee:explicitRm(v)??5.9,evidence:m.id};if(/ninja/i.test(v))return{method:'ninja',fee:explicitRm(v)??6.9,evidence:m.id}}}const inbound=rel.filter(m=>m.direction==='inbound');for(const m of [...inbound].reverse()){const v=mt(m);if(/pickup|ambil|ambik|self collect/i.test(v))return{method:'pickup',fee:0,evidence:m.id};if(/\bspx\b/i.test(v))return{method:'spx',fee:4.5,evidence:m.id};if(/\bj\s*&?\s*t\b|\bjnt\b/i.test(v))return{method:'jnt',fee:5.9,evidence:m.id};if(/ninja/i.test(v))return{method:'ninja',fee:6.9,evidence:m.id}}for(const m of [...rel].reverse()){const v=mt(m);if(/\bspx\b[^\n]*\brm\s*4\.50/i.test(v))return{method:'spx',fee:4.5,evidence:m.id};if(/\bj(?:&|n)?t\b[^\n]*\brm\s*5\.90/i.test(v))return{method:'jnt',fee:5.9,evidence:m.id}}return{method:'unknown',fee:0,evidence:null}}
function dateNeed(ms:any[],ts:number,active:Set<string>){const src=active.has('date_from_latest_customer_need')?ms:ms.filter(m=>m.direction==='inbound'),s=src.map(mt).join('\n');let z=[...s.matchAll(/(?:guna|pakai|need|before|sebelum|pickup|ambil|ambik|dapat|sampai)?[^\n]{0,18}\b(\d{1,2})[\/.\-](\d{1,2})(?:[\/.\-](\d{2,4}))?\b/gi)].at(-1);if(z){let y=z[3]?Number(z[3]):new Date(ts).getFullYear();if(y<100)y+=2000;return`${y}-${String(z[2]).padStart(2,'0')}-${String(z[1]).padStart(2,'0')}`}const hb=[...s.matchAll(/\b(\d{1,2})\s*(?:hb|haribulan)\b/gi)].at(-1);const local=new Date(ts+8*3600000);if(hb){let day=Number(hb[1]),mo=local.getUTCMonth()+1,y=local.getUTCFullYear();if(day<local.getUTCDate()-3)mo++;if(mo>12){mo=1;y++}return`${y}-${String(mo).padStart(2,'0')}-${String(day).padStart(2,'0')}`}const b=new Date(Date.UTC(local.getUTCFullYear(),local.getUTCMonth(),local.getUTCDate()));if(/esok|tomorrow/i.test(s)){b.setUTCDate(b.getUTCDate()+1);return b.toISOString().slice(0,10)}return null}
function refs(ms:any[]){return ms.filter(m=>['image','document'].includes(m.message_type)).slice(-12).map(m=>({message_id:m.id,provider_message_id:m.provider_message_id,type:m.message_type,media_url:m.media_url||null,caption:mt(m)||null,file_name:fn(m)||null}))}
function makeItems(ms:any[],job:any,c:any,active:Set<string>){const rel=around(ms,Number(job.amount),Date.parse(job.payment_received_at)),cs=categories(ms,job,active),prices=sellerPrices(rel),r=refs(rel),inbound=rel.filter(m=>m.direction==='inbound').map(mt).join('\n').toLowerCase(),newd=/new design|design baru|custom topper|tema|buat design/.test(inbound)&&!/design sama|repeat|tukar nama|change name|edit|template sama/.test(inbound),fallback:any={edible:'Edible Image',acrylic:'Acrylic Cake Topper',wafer:'Wafer Paper',burnaway:'Burn Away Combo',printed:newd?'New Design Cake Topper':'Cake Topper',mirror:'Mirror Gold Topper'};return cs.map((cat,i)=>{const cm=categoryMessages(rel,cat),ss=(cm.length?cm:rel).map(mt).filter(Boolean),q=qty(cm.length?cm:rel,cat,active),w=wording(cm.length?cm:rel,active),title=shortTitle(cm.length?cm:rel,cat,fallback[cat]||'Cake Topper'),jt=cat==='printed'?(newd?'topper_new_design_glossy':'topper_editing_glossy'):cat;return{k:cat,product_type:cat,title,qty:q,price:money(prices[cat]||0),size:size(ss),style:cat==='printed'?`${newd?'New Design':'Editing / Existing Design'} — Glossy`:style(ss),wording:w,custom_text:w,review:'Need Review',review_required:true,customization:{ai_generated:true,ai_job_type:jt,ai_pending_confirmation:true,conversation_id:c.id,whatsapp_phone:c.phone,whatsapp_link:wa(c.phone),qrpay_transaction_id:job.transaction_id,qrpay_amount:Number(job.amount),qrpay_received_at:job.payment_received_at,match_score:Number(Math.min(.99,c.n/150).toFixed(3)),match_reason:c.why,reference_message_ids:r.map(v=>v.message_id),reference_media:r,source:'whatsapp_qrpay_ai',set_hint:i+1},product_snapshot:{source:'whatsapp_qrpay_ai',image_url:r.find(v=>v.type==='image'&&v.media_url)?.media_url||null,ai_job_type:jt,reference_message_ids:r.map(v=>v.message_id)}}})}
function payload(ms:any[],c:any,job:any,alts:any[],rules:any[]){const active=new Set(rules.map(x=>t(x.strategy_key))),rel=around(ms,Number(job.amount),Date.parse(job.payment_received_at)),its=makeItems(ms,job,c,active),del=delivery(rel,active),dn=dateNeed(rel,Date.parse(job.payment_received_at),active),ins=rel.filter(m=>m.direction==='inbound').map(mt).filter(Boolean),ad=[...ins].reverse().find(v=>/\b\d{5}\b/.test(v)&&v.length>18)||'',pc=ad.match(/\b(\d{5})\b/)?.[1]||'',p=phone(c.phone||rel.find(m=>m.sender_phone)?.sender_phone),sc=Number(Math.max(.35,Math.min(.99,c.n/150)).toFixed(3)),missing=[];if(!dn)missing.push('date_need');if(del.method==='unknown')missing.push('shipping_method');if(!its.some(x=>x.wording||x.product_snapshot?.image_url))missing.push('wording_or_reference');if(!ad&&del.method!=='pickup'&&del.method!=='unknown')missing.push('delivery_address');if(its.some(x=>Number(x.price||0)<=0))missing.push('item_price');const sum=its.map((x,i)=>`${i+1}. ${x.title} x${x.qty} | RM${Number(x.price||0).toFixed(2)}${x.size?' | '+x.size:''}${x.wording?' | '+x.wording.replace(/\n/g,' / '):''}`).join('\n'),remark=['AI DRAFT ONLY — belum create Order / ClickUp.',`QRPay: RM${Number(job.amount).toFixed(2)} | ${job.transaction_id}`,`AI customer match: ${Math.round(sc*100)}% | ${c.why.join(', ')}`,missing.length?`Admin check: ${missing.join(', ')}`:'Detail utama extracted; admin tetap wajib confirm.',sum].join('\n');return{customer:{name:c.name||'WhatsApp Customer',phone:p,address_line1:ad,postcode:pc,city:'',state:''},items:its,delivery:del.method,delivery_fee:del.fee,date_need:dn,admin_remark:remark,conversation_id:c.id,transaction_id:job.transaction_id,payment_received_at:job.payment_received_at,match_score:sc,match_reason:c.why.join(','),evidence:{conversation_id:c.id,alternatives:alts,messages:rel.slice(-50).map(m=>({id:m.id,direction:m.direction,type:m.message_type,at:m.sent_at||m.created_at,text:mt(m).slice(0,600)})),receipt_message_ids:rel.filter(receipt).map(m=>m.id),reference_media:refs(rel),whatsapp_link:wa(p),worker_version:'qrpay-ai-draft-v10-rematch',excluded_conversation_ids:Array.isArray(job?.evidence?.excluded_conversation_ids)?job.evidence.excluded_conversation_ids:[],active_learning_rules:rules.map(x=>({id:x.id,strategy_key:x.strategy_key,occurrence_count:x.occurrence_count,title:x.title}))}}}
async function run(j:any,k:string,rules:any[]){const b=await best(j);if(!b.top||b.top.n<42){await orderCall(k,{action:'update_job',job_id:j.id,patch:{status:'unmatched',match_score:b.top?.n||0,match_reason:'no_strong_whatsapp_candidate',evidence:{alternatives:b.alts,excluded_conversation_ids:b.excluded_conversation_ids||[]},locked_at:null,completed_at:new Date().toISOString()}});return{job_id:j.id,status:'unmatched'}}const c=b.top,ms=await context(c.id,Date.parse(j.payment_received_at)),p=payload(ms,c,j,b.alts,rules);await orderCall(k,{action:'update_job',job_id:j.id,patch:{status:'matched',matched_conversation_id:c.id,matched_phone:p.customer.phone,matched_customer_name:p.customer.name,match_score:p.match_score,match_reason:p.match_reason,extraction:p,evidence:p.evidence}});if(j.mode==='dry_run'){await orderCall(k,{action:'update_job',job_id:j.id,patch:{status:'dry_run_complete',locked_at:null,completed_at:new Date().toISOString()}});return{job_id:j.id,status:'dry_run_complete',payload:p}}const z=await orderCall(k,{action:'create_draft',job_id:j.id,payload:p});return{job_id:j.id,status:'draft_created',draft:z.result,matched_phone:p.customer.phone,conversation_id:c.id}}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:H});if(req.method!=='POST')return out({ok:false,error:'POST required'},405);if(!await auth(req))return out({ok:false,error:'Unauthorized'},401);const k=req.headers.get('x-qrpay-ai-token')||'';let body:any={};try{body=await req.json()}catch{}try{const q=await orderCall(k,{action:'claim',batch_size:Math.max(1,Math.min(10,Number(body.batch_size||3)))}),learning=await orderCall(k,{action:'learning_context'}).catch(()=>({rules:[]})),rules=Array.isArray(learning.rules)?learning.rules:[],rs=[];for(const j of q.jobs||[])try{rs.push(await run(j,k,rules))}catch(e){const m=e instanceof Error?e.message:String(e),fin=Number(j.attempts||0)>=5;await orderCall(k,{action:'update_job',job_id:j.id,patch:{status:fin?'failed':'retry',next_attempt_at:new Date(Date.now()+(fin?86400000:300000)).toISOString(),locked_at:null,last_error:m.slice(0,2000),completed_at:fin?new Date().toISOString():null}});rs.push({job_id:j.id,status:fin?'failed':'retry',error:m})}return out({ok:true,worker:'qrpay-ai-draft-v10-rematch',mode:'draft_only',active_learning_rules:rules.length,claimed:q.jobs?.length||0,results:rs})}catch(e){console.error('qrpay-ai-order-worker',e);return out({ok:false,error:e instanceof Error?e.message:String(e)},500)}});
