import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const db=createClient(Deno.env.get('SUPABASE_URL')||'',Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'',{auth:{persistSession:false}});
const BRIDGE='https://buivecgahhmrhlmfujgt.supabase.co/functions/v1/qrpay-ai-order-bridge';
async function orderCall(token,body){const r=await fetch(BRIDGE,{method:'POST',headers:{'content-type':'application/json','x-qrpay-ai-token':token},body:JSON.stringify(body)});const j=await r.json().catch(()=>({error:'Invalid bridge response'}));if(!r.ok||j.ok===false)throw Error(j.error||`Bridge HTTP ${r.status}`);return j}
const H={'content-type':'application/json','access-control-allow-origin':'*','access-control-allow-methods':'POST,OPTIONS','access-control-allow-headers':'content-type,x-qrpay-ai-token','cache-control':'no-store'};
const out=(x,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H});
const t=x=>x==null?'':String(x).trim();
const mt=m=>t(m.text_content||m.caption);
const fn=m=>t(m.raw_payload?.data?.raw?.message?.document?.filename||m.raw_payload?.data?.raw?.message?.image?.filename||m.media_metadata?.file_name||m.media_metadata?.filename);
const at=m=>Date.parse(m.sent_at||m.created_at||'')||0;
const min=(a,b)=>Math.abs(a-b)/60000;
const phone=x=>{let d=t(x).replace(/\D/g,'');if(!d)return'';if(d[0]=='0')d='60'+d.slice(1);else if(d[0]=='1')d='60'+d;else if(!d.startsWith('60'))d='60'+d;return d};
const wa=x=>x?`https://wa.me/${phone(x)}`:'';
const money=x=>Number(Number(x||0).toFixed(2));
const exact=(s,a)=>[...s.replace(/,/g,' ').matchAll(/(?:rm\s*)?(\d{1,5}(?:\.\d{1,2})?)/gi)].some(m=>Math.abs(Number(m[1])-a)<.011);
const paid=s=>/(dah|dh|sudah|done|already|telah|settle|paid).{0,24}(bayar|payment|transfer|pay)|done payment|dah bayar|dh bayar/i.test(s);
const prompt=s=>/qrpay|qr pay|bagi qr|bg qr|send qr|nom(?:bor)? acc|akaun|account|payment|bayar|total\s*(?:rm)?\s*\d/i.test(s);
const receipt=m=>{const s=(mt(m)+' '+fn(m)+' '+JSON.stringify(m.media_metadata||{})).toLowerCase();if(m.message_type==='document')return /m2u|cimb\s*octo|bimb.*receipt|receipt|resit|duitnow|payment|transfer|bank.*slip/.test(s);if(m.message_type==='image')return /receipt|resit|duitnow|payment|transfer|bayar|qrpay|qr pay/.test(s);return false};

async function auth(req){const k=req.headers.get('x-qrpay-ai-token')||'';const r=await db.from('private_runtime_settings').select('setting_value').eq('setting_key','qrpay_ai_worker_token').maybeSingle();return !!k&&!r.error&&k===r.data?.setting_value}
function inbox(){return db}
const cols='id,conversation_id,direction,message_type,text_content,caption,sent_at,created_at,sender_phone,provider_message_id,media_url,media_metadata,raw_payload';
async function windowMsgs(x,ts){const s=new Date(ts-150*60000).toISOString(),e=new Date(ts+15*60000).toISOString();const [a,b]=await Promise.all([x.from('messages').select(cols).eq('channel','whatsapp').gte('sent_at',s).lte('sent_at',e),x.from('messages').select(cols).eq('channel','whatsapp').is('sent_at',null).gte('created_at',s).lte('created_at',e)]);if(a.error)throw a.error;if(b.error)throw b.error;const z=new Map();for(const m of [...(a.data||[]),...(b.data||[])])z.set(m.id,m);return [...z.values()].sort((p,q)=>at(p)-at(q))}
async function context(x,id,ts){const s=new Date(ts-36*3600000).toISOString(),e=new Date(ts+15*60000).toISOString(),r=await x.from('messages').select(cols).eq('conversation_id',id).gte('created_at',s).lte('created_at',e).order('created_at').limit(160);if(r.error)throw r.error;return r.data||[]}
function score(ms,amt,ts){let n=0,c=99999,why=[],hasExact=false;for(const m of ms){const d=min(at(m),ts),v=mt(m);c=Math.min(c,d);if(m.direction==='inbound'&&receipt(m))n+=d<=15?320:d<=60?220:100;if(m.direction==='inbound'&&paid(v))n+=d<=20?45:28;if(m.direction==='outbound'&&exact(v,amt)){n+=260;hasExact=true}if(m.direction==='outbound'&&prompt(v))n+=8}if(ms.some(m=>receipt(m)))why.push('receipt_near_payment');if(ms.some(m=>paid(mt(m))))why.push('customer_payment_claim');if(hasExact)why.push('exact_amount_quote');n+=Math.max(0,22-c/8);why.push(`closest_message_${Math.round(c)}m`);return{n,why,hasExact}}
async function best(x,job){const ts=Date.parse(job.payment_received_at),all=await windowMsgs(x,ts),g={};for(const m of all)(g[m.conversation_id]??=[]).push(m);let cs=Object.entries(g).map(([id,ms])=>({id,ms,...score(ms,Number(job.amount),ts)})).sort((a,b)=>b.n-a.n).slice(0,5);for(const c of cs){const q=await x.from('conversations').select('customer_id').eq('id',c.id).maybeSingle();const cid=q.data?.customer_id;let name='WhatsApp Customer',p=phone(c.ms.find(m=>m.sender_phone)?.sender_phone);if(cid){const [a,b]=await Promise.all([x.from('customers').select('display_name').eq('id',cid).maybeSingle(),x.from('customer_identities').select('normalized_phone,external_id').eq('customer_id',cid).eq('channel','whatsapp')]);name=t(a.data?.display_name)||name;p=phone(b.data?.find(i=>i.normalized_phone)?.normalized_phone||b.data?.[0]?.external_id||p)}c.name=name;c.phone=p}if(cs[0])cs[0].why.push(`score_margin_${Math.round(cs[0].n-(cs[1]?.n||0))}`);return{top:cs[0]||null,alts:cs.slice(1).map(c=>({conversation_id:c.id,score:c.n,name:c.name,phone:c.phone}))}}
function delivery(ms){const i=ms.filter(m=>m.direction==='inbound').map(mt).join('\n').toLowerCase(),a=ms.map(mt).join('\n').toLowerCase();if(/pickup|ambil|ambik|self collect/.test(i))return{method:'pickup',fee:0};if(/\bj\s*&?\s*t\b|\bjnt\b/.test(i))return{method:'jnt',fee:5.9};if(/ninja/.test(i))return{method:'ninja',fee:6.9};if(/\bspx\b/.test(i))return{method:'spx',fee:4.5};if(/jnt[^\n]{0,20}5\.90/.test(a))return{method:'jnt',fee:5.9};if(/spx[^\n]{0,20}4\.50/.test(a))return{method:'spx',fee:4.5};return{method:'pickup',fee:0}}
function dateNeed(ms,ts){const s=ms.filter(m=>m.direction==='inbound').map(mt).join('\n'),z=[...s.matchAll(/(?:guna|pakai|need|before|sebelum|pickup|ambil|ambik|dapat|sampai)?[^\n]{0,18}\b(\d{1,2})[\/.\-](\d{1,2})(?:[\/.\-](\d{2,4}))?\b/gi)].at(-1);if(z){let y=z[3]?Number(z[3]):new Date(ts).getFullYear();if(y<100)y+=2000;return`${y}-${String(z[2]).padStart(2,'0')}-${String(z[1]).padStart(2,'0')}`}const d=new Date(ts+8*3600000),b=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate()));if(/esok|tomorrow/i.test(s))b.setUTCDate(b.getUTCDate()+1);else if(!/hari ini|harini|today/i.test(s)){const ds={ahad:0,isnin:1,selasa:2,rabu:3,khamis:4,jumaat:5,sabtu:6},k=Object.keys(ds).find(k=>new RegExp(`\b${k}\b`,'i').test(s));if(!k)return null;let n=(ds[k]-b.getUTCDay()+7)%7;if(!n)n=7;b.setUTCDate(b.getUTCDate()+n)}return b.toISOString().slice(0,10)}
function size(ss){const patterns=[/\b(\d+(?:\.\d+)?\s*[x×]\s*\d+(?:\.\d+)?\s*(?:inch|inci|in)?)\b/i,/\b(\d+(?:\.\d+)?\s*(?:inch|inci|inches|in))\b/i,/(\d+(?:\.\d+)?)\s*\"/i,/\b(A[4-7])\b/i];for(const r of patterns)for(let i=ss.length-1;i>=0;i--){const m=ss[i].match(r);if(m)return m[1]}return''}
function acrylicSize(ss){for(let i=ss.length-1;i>=0;i--){const m=ss[i].match(/\b(A[4-7])\b/i);if(m)return m[1]}return size(ss)}
function style(ss){const colors=['rose gold','silver','gold','black','white','clear','pink','blue','red','green','orange','yellow','purple','lilac'];let c='',sh='';for(let i=ss.length-1;i>=0;i--){const v=ss[i].toLowerCase(),found=colors.filter(x=>v.includes(x));if(!c&&found.length===1)c=found[0];if(!sh){if(/bulat|circle|round/.test(v))sh='Round / Bulat';else if(/petak|square/.test(v))sh='Square / Petak';else if(/hati|love shape/.test(v))sh='Love Shape / Hati'}if(c&&sh)break}return[c&&c.replace(/\b\w/g,x=>x.toUpperCase()),sh].filter(Boolean).join(' — ')}
function wording(ms){const a=ms.filter(m=>m.direction==='inbound').map(mt).filter(Boolean),c=[];const valid=(v)=>{v=v.trim();if(!v||/^(OK|YA|YE|SAMA|BAIK|SALAM|BOLEH|CONFIRM)$/i.test(v)||/payment|alamat|address|total|spx|jnt|postcode|poskod|proses|kirim|bagi total|nak ni|macam ni|contoh/i.test(v))return false;return /^[A-Za-z]{1,20}\s*&\s*[A-Za-z]{1,20}$/.test(v)||/^[A-Z]{1,6}$/.test(v)||(/^[A-Z0-9&❤️❤' .\-\n]{3,}$/.test(v)&&/[A-Z]/.test(v))||/^(happy|selamat|the wedding|mubarak|congrat|welcome|one year|birthday)/i.test(v)};for(let i=0;i<a.length;i++){let v=a[i].trim();if(/^(wording|tulisan|nama|huruf)\s*[:=-]?/i.test(v)){v=v.replace(/^(wording|tulisan|nama|huruf)\s*[:=-]?/i,'').trim();if(valid(v))c.push(v);if(a[i+1]&&valid(a[i+1]))c.push(a[i+1])}else if(valid(v))c.push(v)}return[...new Set(c.map(x=>x.trim()))].slice(-3).join('\n').slice(0,300)}
function qty(ss,cat){for(const v of [...ss].reverse()){if(cat==='acrylic'&&!/acrylic|akrilik|ayrlic|arylic|arcylic/i.test(v))continue;const m=v.match(/\b(\d{1,3})\s*(pcs?|keping|set|orang|design)\b/i);if(m)return Math.max(1,Math.min(100,Number(m[1])))}return 1}
function refs(ms){return ms.filter(m=>['image','document'].includes(m.message_type)).slice(-12).map(m=>({message_id:m.id,provider_message_id:m.provider_message_id,type:m.message_type,media_url:m.media_url||null,caption:mt(m)||null,file_name:fn(m)||null}))}
function cats(ms,amt,ts){let ai=ms.length-1,d=99999;for(let i=0;i<ms.length;i++){const m=ms[i],v=mt(m);if(receipt(m)||paid(v)||(m.direction==='outbound'&&exact(v,amt))){const x=min(at(m),ts);if(x<d){d=x;ai=i}}}const recent=ms.slice(Math.max(0,ai-18),ai+4).filter(m=>m.direction==='inbound').map(mt).join('\n').toLowerCase(),full=ms.filter(m=>m.direction==='inbound').map(mt).join('\n').toLowerCase(),z=new Set();const add=q=>{if(/burn\s*away|burnaway/.test(q))z.add('burnaway');if(/\bwafer\b/.test(q))z.add('wafer');if(/\bedible\b|print gambar|gambar.*(?:inch|inci)|\b5\s*[x×]\s*5\b/.test(q))z.add('edible');if(/acrylic|akrilik|ayrlic|arylic|arcylic/.test(q))z.add('acrylic');if(/\btopper\b|printed topper|glossy/.test(q))z.add('printed');if(z.has('acrylic')&&!/printed topper|glossy|custom topper|topper tema|tema topper/.test(q))z.delete('printed')};add(recent);if(!z.size)add(full);if(!z.size)z.add('printed');return[...z]}
function catMsgs(ms,cat){const re=cat==='edible'?/edible|\bei\b|print gambar|\d+\s*[x×]\s*\d+|circle|bulat/i:cat==='acrylic'?/acrylic|akrilik|ayrlic|arylic|arcylic|\bA[567]\b/i:cat==='wafer'||cat==='burnaway'?/wafer|burn\s*away|burnaway/i:/topper|glossy|tema/i,idx=[];for(let i=0;i<ms.length;i++)if(re.test(mt(ms[i])))for(let j=Math.max(0,i-4);j<=Math.min(ms.length-1,i+4);j++)idx.push(j);return[...new Set(idx)].map(i=>ms[i]).filter(m=>!/HARGA ACRYLIC|RUJUKAN SAIZ MAKSIMUM|Menerima order:|save for order:|Terima kasih hubungi DecoCake/i.test(mt(m)))}
function catTexts(ms,cat){return catMsgs(ms,cat).map(mt).filter(Boolean)}
function prices(ms){const p={};for(const m of ms.filter(x=>x.direction==='outbound')){for(const raw of mt(m).toLowerCase().split(/\n+/)){const v=raw.trim();if(!v||/total/.test(v))continue;const num=(re)=>{const x=v.match(re);return x?Number(x[1]):null};let n=num(/(?:edible|\bei\b)[^0-9]{0,18}(?:rm\s*)?(\d+(?:\.\d{1,2})?)/i);if(n&&n<=200)p.edible=n;n=num(/(?:acrylic|akrilik|ayrlic|arylic|arcylic|\ba[567]\b)[^0-9]{0,18}(?:rm\s*)?(\d+(?:\.\d{1,2})?)/i);if(n&&n<=200)p.acrylic=n;n=num(/wafer[^0-9]{0,18}(?:rm\s*)?(\d+(?:\.\d{1,2})?)/i);if(n&&n<=200)p.wafer=n;n=num(/(?:cake\s*)?topper[^0-9]{0,18}(?:rm\s*)?(\d+(?:\.\d{1,2})?)/i);if(n&&n<=200&&!/acrylic|akrilik|ayrlic|arylic|arcylic|\ba[567]\b/.test(v))p.printed=n}}return p}
function items(ms,job,c){const all=ms.map(mt).filter(Boolean),cs=cats(ms,Number(job.amount),Date.parse(job.payment_received_at)),r=refs(ms),del=delivery(ms),remain=Math.max(0,Number(job.amount)-del.fee),full=ms.filter(m=>m.direction==='inbound').map(mt).join('\n').toLowerCase(),globalW=wording(ms),newd=/new design|design baru|custom topper|tema|ikut contoh|buat design/.test(full)&&!/design sama|repeat|tukar nama|change name|edit|template sama/.test(full),titles={edible:'Edible Image',wafer:'Wafer Paper',burnaway:'Burn Away Combo',acrylic:'Acrylic Cake Topper',printed:newd?'New Design Cake Topper':'Cake Topper Editing'},ks={edible:'edible',wafer:'wafer',burnaway:'burnaway',acrylic:'acrylic',printed:'printed'},ph=prices(ms);if(cs.includes('acrylic')&&!cs.includes('printed')&&!ph.acrylic&&ph.printed){ph.acrylic=ph.printed;delete ph.printed}const hinted=cs.reduce((n,x)=>n+(ph[x]||0),0),unknown=cs.filter(x=>!ph[x]),fallback=unknown.length?Math.max(0,remain-hinted)/unknown.length:0;return cs.map((x,i)=>{const relMsgs=catMsgs(ms,x),rel=relMsgs.map(mt).filter(Boolean),q=qty(rel.length?rel:all,x),catTotal=ph[x]||fallback||remain/cs.length,p=money(catTotal/q),jt=x==='printed'?(newd?'topper_new_design_glossy':'topper_editing_glossy'):x,im=r.find(v=>v.type==='image'&&v.media_url)?.media_url||null,sz=x==='acrylic'?acrylicSize(rel.length?rel:all):size(rel.length?rel:all),st=style(rel.length?rel:all),w=wording(relMsgs)||((x==='acrylic'||x==='printed')?globalW:'');return{k:ks[x],title:titles[x],qty:q,price:p,size:sz,style:x==='printed'?`${newd?'New Design':'Editing / Existing Design'} — Glossy`:st,wording:w,review:'Need Review',review_required:true,customization:{ai_generated:true,ai_job_type:jt,ai_pending_confirmation:true,conversation_id:c.id,whatsapp_phone:c.phone,whatsapp_link:wa(c.phone),qrpay_transaction_id:job.transaction_id,qrpay_amount:Number(job.amount),qrpay_received_at:job.payment_received_at,match_score:Number(Math.min(.99,c.n/150).toFixed(3)),match_reason:c.why,reference_message_ids:r.map(v=>v.message_id),reference_media:r,source:'whatsapp_qrpay_ai',set_hint:i+1},product_snapshot:{source:'whatsapp_qrpay_ai',image_url:im,ai_job_type:jt,reference_message_ids:r.map(v=>v.message_id)}}})}
function payload(ms,c,job,alts){const its=items(ms,job,c),del=delivery(ms),dn=dateNeed(ms,Date.parse(job.payment_received_at)),ins=ms.filter(m=>m.direction==='inbound').map(mt).filter(Boolean),ad=[...ins].reverse().find(v=>/\b\d{5}\b/.test(v)&&v.length>18)||'',pc=ad.match(/\b(\d{5})\b/)?.[1]||'',p=phone(c.phone||ms.find(m=>m.sender_phone)?.sender_phone),sc=Number(Math.max(.35,Math.min(.99,c.n/150)).toFixed(3)),missing=[];if(!dn)missing.push('date_need');if(!its.some(x=>x.wording))missing.push('wording_or_reference_check');if(!ad&&del.method!=='pickup')missing.push('delivery_address');const sum=its.map((x,i)=>`${i+1}. ${x.title} x${x.qty}${x.size?' | '+x.size:''}${x.wording?' | '+x.wording.replace(/\n/g,' / '):''}`).join('\n'),remark=['AI PENDING CONFIRMATION — semak task dalam ClickUp sebelum production.',`WhatsApp: ${wa(p)}`,`QRPay: RM${Number(job.amount).toFixed(2)} | ${job.transaction_id} | ${job.payment_received_at}`,`AI match: ${Math.round(sc*100)}% | ${c.why.join(', ')}`,`Conversation: ${c.id}`,missing.length?`Belum lengkap: ${missing.join(', ')}`:'Detail utama berjaya diextract.',sum].join('\n');return{customer:{name:c.name||'WhatsApp Customer',phone:p,address_line1:ad,postcode:pc,city:'',state:''},items:its,total:Number(job.amount),delivery:del.method,delivery_fee:del.fee,date_need:dn,admin_remark:remark,conversation_id:c.id,transaction_id:job.transaction_id,payment_received_at:job.payment_received_at,match_score:sc,match_reason:c.why.join(','),evidence:{alternatives:alts,messages:ms.slice(-40).map(m=>({id:m.id,direction:m.direction,type:m.message_type,at:m.sent_at||m.created_at,text:mt(m).slice(0,500)})),whatsapp_link:wa(p),worker_version:'qrpay-ai-mvp-v8'}}}
async function link(x,c,r,p){if(!r?.order_id)return;const row={conversation_id:c.id,source_project:'icetak-order-system',external_order_id:r.order_db_id||null,order_system_order_id:r.order_db_id||null,order_no:r.order_id,is_primary:true,match_method:'qrpay_ai',match_confidence:p.match_score,linked_by_label:'qrpay-ai-worker',metadata:{transaction_id:p.transaction_id,amount:p.total,whatsapp_link:p.evidence.whatsapp_link,worker_version:'qrpay-ai-mvp-v8'}};const z=await x.from('conversation_order_links').insert(row);if(z.error&&!/duplicate/i.test(z.error.message))console.error('link failed',z.error.message)}
async function run(x,j,k){const b=await best(x,j);if(!b.top||b.top.n<42){await orderCall(k,{action:'update_job',job_id:j.id,patch:{status:'unmatched',match_score:b.top?.n||0,match_reason:'no_strong_whatsapp_candidate',evidence:{alternatives:b.alts},locked_at:null,completed_at:new Date().toISOString()}});return{job_id:j.id,status:'unmatched'}}const c=b.top,ms=await context(x,c.id,Date.parse(j.payment_received_at)),p=payload(ms,c,j,b.alts);await orderCall(k,{action:'update_job',job_id:j.id,patch:{status:'matched',matched_conversation_id:c.id,matched_phone:p.customer.phone,matched_customer_name:p.customer.name,match_score:p.match_score,match_reason:p.match_reason,extraction:p,evidence:p.evidence}});if(j.mode==='dry_run'){await orderCall(k,{action:'update_job',job_id:j.id,patch:{status:'dry_run_complete',locked_at:null,completed_at:new Date().toISOString()}});return{job_id:j.id,status:'dry_run_complete',payload:p}}const z=await orderCall(k,{action:'create_order',job_id:j.id,payload:p});await link(x,c,z.result,p);await orderCall(k,{action:'update_job',job_id:j.id,patch:{status:'order_created',locked_at:null,completed_at:new Date().toISOString()}});return{job_id:j.id,status:'order_created',result:z.result,matched_phone:p.customer.phone,conversation_id:c.id}}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:H});if(req.method!=='POST')return out({error:'POST required'},405);if(!await auth(req))return out({error:'Unauthorized'},401);const k=req.headers.get('x-qrpay-ai-token')||'';let body={};try{body=await req.json()}catch{}try{const x=inbox(),q=await orderCall(k,{action:'claim',batch_size:Math.max(1,Math.min(10,Number(body.batch_size||3)))});const rs=[];for(const j of q.jobs||[])try{rs.push(await run(x,j,k))}catch(e){const m=e instanceof Error?e.message:String(e),fin=Number(j.attempts||0)>=5;await orderCall(k,{action:'update_job',job_id:j.id,patch:{status:fin?'failed':'retry',next_attempt_at:new Date(Date.now()+(fin?86400000:300000)).toISOString(),locked_at:null,last_error:m.slice(0,2000),completed_at:fin?new Date().toISOString():null}});rs.push({job_id:j.id,status:fin?'failed':'retry',error:m})}return out({ok:true,worker:'qrpay-ai-mvp-v8',claimed:q.jobs?.length||0,results:rs})}catch(e){console.error(e);return out({ok:false,error:e instanceof Error?e.message:String(e)},500)}});
