-- Service-role gateway contracts, on the target database, with all business data rolled back.
begin;
set local role service_role;
do $$
declare a uuid:=gen_random_uuid(); b uuid:=gen_random_uuid(); r jsonb; s jsonb; new_s jsonb; lines jsonb; extras jsonb; failed boolean; v integer;
begin
  s:=public.finance_material_settings();
  insert into public.marketplace_orders(id,order_sn,currency,current_status,first_seen_at,placed_at) values(a,'QA-PROFIT-'||a,'MYR','COMPLETED','2026-10-01','2026-10-01');
  insert into public.marketplace_order_items(order_id,line_no,item_sku,title,quantity,line_subtotal) values(a,1,'QA-TOPPER','Birthday Cake Topper',1,10);
  insert into public.marketplace_order_financials(order_id,currency,buyer_paid,escrow_amount,commission_fee,settlement_status) values(a,'MYR',10,7.14,1.67,'pending_release');
  r:=public.finance_order_profit_detail(a);
  assert (r->>'profit')::numeric=5.87 and r->>'income_state'='escrow','Correct net less material, without fee double deduction or false release';
  assert (r->>'margin')::numeric=58.7 and (r->>'cost_version')::integer=1,'Goods margin and one captured snapshot';
  perform public.finance_order_profit_detail(a);assert (select count(*) from finance.marketplace_order_costs where order_id=a)=1,'Idempotent detail';
  lines:='[{"line_no":1,"amount":1,"mode":"actual","category":"topper"}]';
  select jsonb_object_agg(key,jsonb_build_object('amount',case when key='ads' then 2 else 0 end,'mode','actual')) into extras from jsonb_each(finance.empty_order_extras());
  r:=public.finance_order_costs_save(a,1,lines,extras,'20',true,'Exact external ads','admin1');
  assert (r->>'profit')::numeric=4.14 and r->>'profit_state'='estimated','Real costs remain estimated until release';
  update public.marketplace_order_financials set released_amount=7,settlement_status='released',released_at=now() where order_id=a;
  r:=finance.order_profit_row(a);assert r->>'profit_state'='actual' and (r->>'profit')::numeric=4 and (r->>'profit_per_hour')::numeric=12,'Actual release precedence and labor-time comparison';
  failed:=false;begin perform public.finance_order_costs_save(a,1,lines,extras,'20',true,'Stale','admin1');exception when others then failed:=true;end;assert failed,'Stale write rejected';
  v:=(r->>'cost_version')::integer;extras:=jsonb_set(extras,'{ads,mode}','"allocated"');
  failed:=false;begin perform public.finance_order_costs_save(a,v,lines,extras,'20',true,'Allocated','admin1');exception when others then failed:=true;end;assert failed,'Allocated cannot confirm actual';
  r:=public.finance_order_costs_save(a,v,lines,extras,'20',false,'Allocated ads','admin1');assert r->>'profit_state'='estimated','Allocated ads labelled estimated';
  update public.marketplace_order_financials set released_amount=0 where order_id=a;r:=finance.order_profit_row(a);assert (r->>'nett')::numeric=0 and (r->>'profit')::numeric=-3,'Zero payout and negative profit';
  update public.marketplace_order_items set line_subtotal=null,unit_original_price=null,unit_discounted_price=null where order_id=a;
  r:=public.finance_order_costs_save(a,(r->>'cost_version')::integer,lines,extras,'20',false,'Known cost, unknown goods price','admin1');assert (r->>'profit')::numeric=-3 and r->>'margin' is null,'Known actual cost supports profit while missing goods price makes margin unknown';
  update public.marketplace_order_financials set currency='USD' where order_id=a;r:=finance.order_profit_row(a);assert r->>'nett' is null and r->>'profit' is null,'Do not mix currencies';
  update public.marketplace_order_financials set currency='MYR' where order_id=a;
  update public.marketplace_order_items set quantity=2,line_subtotal=20 where order_id=a;r:=finance.order_profit_row(a);assert r->>'cost_state'='detail_changed' and r->>'profit' is null,'Changed item facts require re-review';
  update public.marketplace_orders set current_status='CANCELLED' where id=a;r:=finance.order_profit_row(a);assert r->>'profit_state'='lifecycle_review' and r->>'profit' is null,'Cancelled/refund not final profit';
  insert into public.marketplace_orders(id,order_sn,currency,current_status,first_seen_at) values(b,'QA-PROFIT-'||b,'MYR','READY_TO_SHIP','2026-10-01');
  insert into public.marketplace_order_items(order_id,line_no,item_sku,title,quantity,line_subtotal) values(b,1,'QA-TOPPER','Cake Topper',1,10),(b,2,'QA-EDIBLE','Edible Image',1,20);
  new_s:=public.finance_material_settings_save((s->>'version')::bigint,jsonb_set(s->'rates','{topper}','50'),'{"qa-unit":{"category":"topper","unit_cost":2}}','admin1');
  r:=finance.order_profit_row(b);assert (r->>'material_total')::numeric=9.77 and (r->>'settings_version')::bigint=1,'Mixed item costs and uncaptured old settings stay frozen';
  assert (select (material_lines->0->>'amount')::numeric from finance.marketplace_order_costs where order_id=a)=1,'New defaults cannot overwrite manual cost';
  failed:=false;begin perform public.finance_material_settings_save((s->>'version')::bigint,s->'rates','{}','admin1');exception when others then failed:=true;end;assert failed,'Settings stale editor rejected';
  failed:=false;begin perform public.finance_material_settings_save((new_s->>'version')::bigint,jsonb_set(s->'rates','{topper}','101'),'{}','admin1');exception when others then failed:=true;end;assert failed,'Percentage must be <=100';
  failed:=false;begin perform finance.cost_number('"NaN"');exception when others then failed:=true;end;assert failed,'Invalid numeric rejected';
  insert into public.marketplace_orders(id,order_sn,currency,current_status,first_seen_at) values(gen_random_uuid(),'QA-PROFIT-'||gen_random_uuid(),'MYR','READY_TO_SHIP',clock_timestamp()) returning id into b;
  insert into public.marketplace_order_items(order_id,line_no,item_sku,title,quantity,line_subtotal) values(b,1,'QA-UNIT','Custom work',3,30);
  set constraints capture_finance_order_cost_after_item immediate;
  assert exists(select 1 from finance.marketplace_order_costs where order_id=b and settings_version=(new_s->>'version')::bigint),'Deferred item trigger captures new order without a finance UI read';
  r:=public.finance_order_profit_detail(b);assert (r->>'material_total')::numeric=6 and r->'material_lines'->0->>'basis'='sku_unit','SKU fixed cost multiplied by quantity';
  update public.marketplace_order_items set item_sku='UNKNOWN' where order_id=b;r:=finance.order_profit_row(b);assert r->>'material_total' is null and r->>'profit' is null,'Missing material not zero';
  assert not has_function_privilege('anon','public.finance_order_costs_save(uuid,integer,jsonb,jsonb,jsonb,boolean,text,text)','EXECUTE'),'No anonymous writes';
  assert not has_function_privilege('authenticated','public.finance_order_profit_list(jsonb)','EXECUTE'),'No direct staff reads';
end $$;
rollback;
