begin;
set local role service_role;
do $$
declare a uuid:=gen_random_uuid();b uuid:=gen_random_uuid();raw jsonb;r jsonb;p jsonb;preview jsonb;filt jsonb;bad boolean;
begin
 raw:='{"order_income":{"original_cost_of_goods_sold":10,"buyer_paid_shipping_fee":0,"actual_shipping_fee":4.9,"estimated_shipping_fee":4.9,"final_shipping_fee":-4.9,"shopee_shipping_rebate":4.9,"shipping_fee_sst":0,"seller_return_refund":0,"reverse_shipping_fee":0,"commission_fee":1.67,"service_fee":0.7,"seller_transaction_fee":0.38,"credit_card_transaction_fee":0.38,"ads_escrow_top_up_fee_or_technical_support_fee":0.11,"voucher_from_seller":0,"seller_coin_cash_back":0,"escrow_amount":7.14,"escrow_amount_after_adjustment":7.14,"total_adjustment_amount":0},"buyer_payment_info":{"shipping_fee_sst_amount":0.29}}';
 r:=finance.order_finance_metrics(finance.order_finance_fields(raw));assert r->>'reconciliation'='matched' and (r->>'reconstructed_nett')::numeric=7.14,'No double deduction';assert finance.order_finance_metrics('{}')->>'shipping_net' is null,'Missing is not zero';
 insert into public.marketplace_orders(id,order_sn,shop_id,currency,current_status,first_seen_at,placed_at)values(a,'QA-FULL-'||a,'999999991','MYR','COMPLETED','2026-10-01','2026-10-01'),(b,'QA-FULL-'||b,'999999991','MYR','COMPLETED','2026-10-01','2026-10-01');
 insert into public.marketplace_order_items(order_id,line_no,item_sku,title,quantity,line_subtotal,unit_original_price)values(a,1,'QA-TOPPER','Cake Topper',1,10,10),(b,1,'QA-TOPPER','Cake Topper',1,10,10);
 insert into public.marketplace_order_financials(order_id,currency,escrow_amount,provider_payload,last_enriched_at)values(a,'MYR',7.14,jsonb_build_object('shopee_finance',raw,'finance_ingest_event_id',gen_random_uuid()),now());
 r:=public.finance_order_profit_detail(a);assert (r->>'profit')::numeric=5.87 and jsonb_array_length(r->'finance_history')=1,'Initial finance snapshot';perform finance.capture_order_finance(a);assert(select count(*)from finance.order_finance_snapshots where order_id=a)=1,'Idempotent capture';
 raw:=raw||jsonb_build_object('order_income',(raw->'order_income')||'{"seller_return_refund":-10,"shopee_shipping_rebate":0,"shipping_fee_sst":0.29,"escrow_amount":-5.19,"escrow_amount_after_adjustment":-5.19,"commission_fee":0,"service_fee":0,"seller_transaction_fee":0,"ads_escrow_top_up_fee_or_technical_support_fee":0}');
 update public.marketplace_order_financials set released_amount=7.14,settlement_status='released',released_at=now(),provider_payload=jsonb_build_object('shopee_finance',raw,'finance_ingest_event_id',gen_random_uuid()),last_enriched_at=now() where order_id=a;
 r:=public.finance_order_profit_detail(a);assert (r->>'nett')::numeric=-5.19 and (r->>'profit')::numeric=-6.46 and r->>'profit_state'='estimated','Refund loss preserves material without old release proof';assert r->'finance_metrics'->>'reconciliation'='matched' and jsonb_array_length(r->'finance_history')=2,'Refund reconciliation/history';
 filt:='{"from":"2026-10-01","to":"2026-10-03","shop_id":"999999991","state":"loss","reason":"shipping_loss","status":"all"}';r:=public.finance_order_report(filt);assert (r->>'total')::int=1 and (r->'summary'->>'estimated_profit')::numeric=-6.46 and (r->'trend'->0->>'profit')::numeric=-6.46,'List/summary/chart reconcile';assert public.finance_order_report(filt||'{"metric":"return_shipping","min":1}')->>'total'='0','Numeric filter';
 p:=jsonb_build_array(jsonb_build_object('order_sn','QA-FULL-'||a,'financials','{"escrow_amount":99}'::jsonb));preview:=public.finance_import_order_finance(p,999999991,'MYR','admin1');assert preview->>'valid'='true' and preview->'rows'->0->>'state'='reference_only','Excel API priority';perform public.finance_import_order_finance(p,999999991,'MYR','admin1',true,preview->>'hash');assert(finance.order_profit_row(a)->>'nett')::numeric=-5.19,'Excel never overwrites webhook';preview:=public.finance_import_order_finance(p,999999991,'MYR','admin1');assert preview->'rows'->0->>'state'='duplicate','Excel dedup';
 bad:=false;begin perform public.finance_import_order_finance(p,999999991,'MYR','admin1',true,'stale');exception when others then bad:=true;end;assert bad,'Stale preview blocked';
 p:=jsonb_build_array(jsonb_build_object('order_sn','QA-FULL-'||b,'financials','{"original_cost_of_goods_sold":10,"commission_fee":1.67}'::jsonb));preview:=public.finance_import_order_finance(p,999999991,'MYR','admin1');assert preview->>'valid'='true' and preview->'rows'->0->>'nett' is null,'Incomplete detail stays unknown';perform public.finance_import_order_finance(p,999999991,'MYR','admin1',true,preview->>'hash');r:=finance.order_profit_row(b);assert r->>'nett' is null and r->>'finance_source'='excel','No false income from Excel';
 assert public.finance_import_order_finance(p,999999991,'USD','admin1')->>'valid'='false','Currency mismatch';assert public.finance_import_order_finance(p,999999990,'MYR','admin1')->>'valid'='false','Shop mismatch';
 assert not has_function_privilege('anon','public.finance_import_order_finance(jsonb,bigint,text,text,boolean,text)','execute') and not has_function_privilege('authenticated','public.finance_order_report(jsonb,boolean)','execute'),'Service-only grants';
end $$;
rollback;
