import type {FinanceReport} from './orderProfit';
export type ImportOrder={order_sn:string;financials:Record<string,unknown>};
const aliases:Record<string,string>={productsubtotal:'original_cost_of_goods_sold',sellerrebate:'seller_rebate',sellerdiscount:'seller_discount',shopeerebate:'shopee_discount',discountvoucheramountsponsoredbyseller:'voucher_from_seller',coincashbackvoucheramountsponsoredbyseller:'seller_coin_cash_back',discountvoucheramountsponsoredbyshopee:'voucher_from_shopee',shopeebundlediscount:'shopee_bundle_discount',sellerbundlediscount:'seller_bundle_discount',coincashbackvoucheramountsponsoredbyshopee:'shopee_coin_cash_back',creditcarddiscounttotal:'credit_card_promotion',totalamount:'total_amount',buyerpaidshippingfee:'buyer_paid_shipping_fee',shippingrebateestimate:'shopee_shipping_rebate',reverseshippingfee:'reverse_shipping_fee',transactionfee:'seller_transaction_fee',commissionfee:'commission_fee',servicefee:'service_fee',grandtotal:'buyer_total_amount',estimatedshippingfee:'estimated_shipping_fee',returnedquantity:'returned_quantity',escrowamount:'escrow_amount',releasedamount:'released_amount',adsescrowtopupfeeortechnicalsupportfee:'ads_escrow_top_up_fee_or_technical_support_fee',orderamscommissionfee:'order_ams_commission_fee',shippingfeesst:'shipping_fee_sst',actualshippingfee:'actual_shipping_fee',sellerreturnrefund:'seller_return_refund'};
const normalized=(v:string)=>v.toLowerCase().replace(/[^a-z0-9]/g,'');
function cell(v:unknown):unknown{if(v&&typeof v==='object'){const x=v as {result?:unknown;text?:string;richText?:{text:string}[]};if('result'in x)return x.result;if(x.text)return x.text;if(x.richText)return x.richText.map(t=>t.text).join('');}return v;}
function amount(v:unknown):number|null{const s=String(cell(v)??'').trim().replace(/^(MYR|RM)\s*/i,'').replaceAll(',','');if(!s)return null;const n=Number(/^\(.*\)$/.test(s)?'-'+s.slice(1,-1):s);if(!Number.isFinite(n)||Math.abs(n)>1e9)throw new Error(`Nilai tidak sah: ${s}`);return n;}
export async function parseFinanceExcel(file:File):Promise<ImportOrder[]>{
 if(file.size>10*1024*1024)throw new Error('Fail maksimum 10MB');if(!/\.xlsx$/i.test(file.name))throw new Error('Gunakan fail .xlsx Shopee');
 const Excel=(await import('exceljs')).default;const workbook=new Excel.Workbook();await workbook.xlsx.load(await file.arrayBuffer());const sheet=workbook.worksheets[0];if(!sheet)throw new Error('Worksheet tiada');
 const headers:Record<number,string>={};sheet.getRow(1).eachCell((v,i)=>{headers[i]=String(cell(v.value)??'').trim()});const orderCol=Number(Object.entries(headers).find(([,v])=>normalized(v)==='orderid')?.[0]);if(!orderCol)throw new Error('Header Order ID tidak dijumpai');
 const grouped=new Map<string,{financials:Record<string,unknown>;items:Record<string,unknown>[];goods:number|null;returns:number|null}>();
 sheet.eachRow((row,index)=>{if(index===1)return;const sn=String(cell(row.getCell(orderCol).value)??'').trim();if(!sn)return;if(!/^[A-Za-z0-9-]{5,40}$/.test(sn))throw new Error(`Order ID tidak sah pada baris ${index}`);let g=grouped.get(sn);if(!g){g={financials:{},items:[],goods:null,returns:null};grouped.set(sn,g)}const raw:Record<string,unknown>={};
 for(const [i,h]of Object.entries(headers)){const v=cell(row.getCell(Number(i)).value);if(v==null||String(v).trim()==='')continue;raw[h]=v;const k=aliases[normalized(h)];if(!k)continue;const n=amount(v);if(k==='original_cost_of_goods_sold'){if(n!=null)g.goods=(g.goods??0)+n;continue}if(k==='returned_quantity'){if(n!=null)g.returns=(g.returns??0)+n;continue}if(k in g.financials&&g.financials[k]!==n)throw new Error(`Order ${sn}: ${h} berbeza antara item. Semak fail sebelum import.`);g.financials[k]=n;}
 g.items.push(raw);});
 if(grouped.size>500)throw new Error('Maksimum 500 order setiap import; pecahkan fail kepada beberapa batch');if(!grouped.size)throw new Error('Tiada order dalam fail');
 return [...grouped].map(([order_sn,g])=>({order_sn,financials:{...g.financials,original_cost_of_goods_sold:g.goods,returned_quantity:g.returns,report_items:g.items}}));
}
export function downloadFinanceCsv(report:FinanceReport){
 const columns=['order_sn','status','currency','finance_source','income_state','nett','cost_total','profit','margin','courier','shop_id','shipping_net','return_shipping','refund_total','seller_promotion','fee_total','platform_ads','affiliate','reconciliation','reasons'];
 const csvCell=(v:unknown)=>{let s=Array.isArray(v)?v.join(' | '):String(v??'');if(/^[=+@\-]/.test(s)&&typeof v!=='number')s="'"+s;return '"'+s.replaceAll('"','""')+'"'};
 const rows=report.rows.map(r=>columns.map(k=>csvCell((r as unknown as Record<string,unknown>)[k]??(r.finance_metrics as unknown as Record<string,unknown>|undefined)?.[k])).join(','));
 const url=URL.createObjectURL(new Blob(['\ufeff'+[columns.join(','),...rows].join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='icetak-order-finance.csv';a.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000);
}
