// @ts-nocheck
import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
import { applyLearningRules, filterOrderEvidenceMessages } from '../_shared/ai-learning-engine.ts';
const db=createClient(Deno.env.get('SUPABASE_URL')||'',Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'',{auth:{persistSession:false}});
const BRIDGE='https://buivecgahhmrhlmfujgt.supabase.co/functions/v1/qrpay-ai-order-bridge';
const H={'content-type':'application/json','access-control-allow-origin':'*','access-control-allow-methods':'POST,OPTIONS','access-control-allow-headers':'content-type,x-qrpay-ai-token','cache-control':'no-store'},out=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H});
const t=(x:any)=>String(x??'').trim(),mt=(m:any)=>t(m.text_content||m.caption),at=(m:any)=>Date.parse(m.sent_at||m.created_at||'')||0,mins=(a:number,b:number)=>Math.abs(a-b)/60000,money=(x:any)=>Number(Number(x||0).toFixed(2));
const phone=(x:any)=>{let d=t(x).replace(/\D/g,'');if(!d)return'';if(d[0]==='0')d='60'+d.slice(1);else if(d[0]==='1')d='60'+d;else if(!d.startsWith('60'))d='60'+d;return d},wa=(x:any)=>x?`https://wa.me/${phone(x)}`:'';
const fn=(m:any)=>t(m.raw_payload?.data?.raw?.message?.document?.filename||m.raw_payload?.data?.raw?.message?.image?.filename||m.media_metadata?.file_name||m.media_metadata?.filename);
const exact=(s:string,a:number)=>[...t(s).replace(/,/g,' ').matchAll(/(?:rm\s*)?(\d{1,5}(?:\.\d{1,2})?)/gi)].some(m=>Math.abs(Number(m[1])-Number(a))<.011);
const paid=(s:string)=>/(dah|dh|sudah|done|already|telah|settle|paid).{0,24}(bayar|payment|transfer|pay)|done payment|dah bayar|dh bayar/i.test(t(s));
const payPrompt=(s:string)=>/qrpay|qr pay|bagi qr|bg qr|send qr|account|akaun|payment|bayar|total\s*(?:rm)?\s*\d/i.test(t(s));
const receipt=(m:any)=>{const s=(mt(m)+' '+fn(m)+' '+JSON.stringify(m.media_metadata||{})).toLowerCase();if(m.message_type==='document')return/m2u|cimb\s*octo|bimb.*receipt|receipt|resit|duitnow|payment|transfer|bank.*slip/.test(s);if(m.message_type==='image')return/receipt|resit|duitnow|payment|transfer|bayar|qrpay|qr pay/.test(s);return false};
const cols='id,conversation_id,direction,message_type,text_content,caption,sent_at,created_at,sender_phone,provider_message_id,media_url,media_metadata,raw_payload';
async function orderCall(token:string,body:any){const r=await fetch(BRIDGE,{method:'POST',headers:{'content-type':'application/json','x-qrpay-ai-token':token},body:JSON.stringify(body)}),j=await r.json().catch(()=>({}));if(!r.ok||j.ok===false)throw Error(j.error||`Bridge ${r.status}`);return j}
async function auth(req:Request){const k=req.headers.get('x-qrpay-ai-token')||'',q=await db.from('private_runtime_settings').select('setting_value').eq('setting_key','qrpay_ai_worker_token').maybeSingle();return!!k&&!q.error&&k===q.data?.setting_value}
async function activeSellerSnippets(){const q=await db.from('quick_snippets').select('id,shortcut,title,message').eq('active',true);if(q.error){console.error('seller snippet filter',q.error);return[]}return q.data||[]}
async function windowMsgs(ts:number){const s=new Date(ts-150*60000).toISOString(),e=new Date(ts+15*60000).toISOString(),[a,b]=await Promise.all([db.from('messages').select(cols).eq('channel','whatsapp').gte('sent_at',s).lte('sent_at',e),db.from('messages').select(cols).eq('channel','whatsapp').is('sent_at',null).gte('created_at',s).lte('created_at',e)]);if(a.error)throw a.error;if(b.error)throw b.error;const z=new Map();for(const m of [...(a.data||[]),...(b.data||[])])z.set(m.id,m);return[...z.values()].sort((p,q)=>at(p)-at(q))}
function score(ms:any[],amt:number,ts:number){let n=0,c=99999,why:any[]=[],hasExact=false;for(const m of ms){const d=mins(at(m),ts),v=mt(m);c=Math.min(c,d);if(m.direction==='inbound'&&receipt(m))n+=d<=15?320:d<=60?220:100;if(m.direction==='inbound'&&paid(v))n+=d<=20?45:28;if(m.direction==='outbound'&&exact(v,amt)){n+=260;hasExact=true}if(m.direction==='outbound'&&payPrompt(v))n+=8}if(ms.some(receipt))why.push('receipt_near_payment');if(ms.some(m=>paid(mt(m))))why.push('customer_payment_claim');if(hasExact)why.push('exact_amount_quote');n+=Math.max(0,22-c/8);why.push(`closest_message_${Math.round(c)}m`);return{n,why}}
async function best(job:any,snippets:any[]){const ts=Date.parse(job.payment_received_at),all=filterOrderEvidenceMessages(await windowMsgs(ts),snippets).messages,g:any={},excluded=new Set((Array.isArray(job?.evidence?.excluded_conversation_ids)?job.evidence.excluded_conversation_ids:[]).map(String));for(const m of all)(g[m.conversation_id]??=[]).push(m);const cs:any[]=Object.entries(g).filter(([id])=>!excluded.has(String(id))).map(([id,ms]:any)=>({id,ms,...score(ms,Number(job.amount),ts)})).sort((a,b)=>b.n-a.n).slice(0,5);for(const c of cs){const q=await db.from('conversations').select('customer_id').eq('id',c.id).maybeSingle(),cid=q.data?.customer_id;let name='WhatsApp Customer',p=phone(c.ms.find((m:any)=>m.sender_phone)?.sender_phone);if(cid){const[a,b]=await Promise.all([db.from('customers').select('display_name').eq('id',cid).maybeSingle(),db.from('customer_identities').select('normalized_phone,external_id').eq('customer_id',cid).eq('channel','whatsapp')]);name=t(a.data?.display_name)||name;p=phone(b.data?.find((i:any)=>i.normalized_phone)?.normalized_phone||b.data?.[0]?.external_id||p)}c.name=name;c.phone=p}if(cs[0])cs[0].why.push(`score_margin_${Math.round(cs[0].n-(cs[1]?.n||0))}`);return{top:cs[0]||null,alts:cs.slice(1).map(c=>({conversation_id:c.id,score:c.n,name:c.name,phone:c.phone})),excluded:[...excluded]}}
async function sessionMessages(id:string,opened:string,ts:number){const floor=new Date(Math.max(Date.parse(opened)||0,ts-45*86400000)).toISOString(),end=new Date(ts+15*60000).toISOString(),q=await db.from('messages').select(cols).eq('conversation_id',id).gt('created_at',floor).lte('created_at',end).order('created_at').limit(700);if(q.error)throw q.error;return q.data||[]}
function dealBlock(ms:any[],amt:number,ts:number){if(!ms.length)return[];let qi=-1,qgap=Infinity,ri=-1,rgap=Infinity;for(let i=0;i<ms.length;i++){const m=ms[i],gap=(ts-at(m))/60000,v=mt(m);if(gap>=0&&m.direction==='outbound'&&exact(v,amt)&&/total|jumlah|topper|edible|acrylic|akrilik|wafer|burn|rm|payment|bayar/i.test(v)&&gap<qgap){qi=i;qgap=gap}const d=mins(at(m),ts);if((receipt(m)||paid(v))&&d<rgap){ri=i;rgap=d}}const indexes=new Set<number>();if(qi>=0)for(let j=Math.max(0,qi-20);j<=Math.min(ms.length-1,qi+20);j++)indexes.add(j);if(ri>=0)for(let j=Math.max(0,ri-12);j<=Math.min(ms.length-1,ri+6);j++)indexes.add(j);if(!indexes.size)for(let j=Math.max(0,ms.length-60);j<ms.length;j++)indexes.add(j);return[...indexes].sort((a,b)=>a-b).map(i=>ms[i])}
const catRe:any={edible:/\bedible\b|\bei\b|print gambar|icing sheet/i,acrylic:/acrylic|akrilik|ayrlic|arylic|arcylic/i,wafer:/\bwafer\b/i,burnaway:/burn\s*away|burnaway/i,printed:/\btopper\b|glossy|printed topper|topper tema/i,mirror:/mirror gold artpaper|artpaper/i};
function cats(ms:any[]){const z=new Set<string>();for(const m of ms){const s=mt(m);for(const[k,re]of Object.entries(catRe))if((re as RegExp).test(s))z.add(k)}if(z.has('burnaway')){z.delete('edible');z.delete('wafer')}if(!z.size)z.add('printed');return[...z]}
function catMsgs(ms:any[],cat:string){const re=catRe[cat]||catRe.printed,idx=new Set<number>();for(let i=0;i<ms.length;i++)if(re.test(mt(ms[i])))for(let j=Math.max(0,i-3);j<=Math.min(ms.length-1,i+3);j++)idx.add(j);return[...idx].map(i=>ms[i])}
function explicitRm(line:string){const a=[...t(line).matchAll(/\brm\s*(\d{1,5}(?:\.\d{1,2})?)/gi)];return a.length?Number(a.at(-1)![1]):null}
function quotes(ms:any[]){const out:any={};for(const m of ms.filter(x=>x.direction==='outbound'))for(const raw of mt(m).split(/\n+/)){const line=raw.trim();if(!line||/^\s*(?:total|jumlah)\b/i.test(line))continue;for(const[cat,re]of Object.entries(catRe)){if(!(re as RegExp).test(line)||(cat==='printed'&&catRe.acrylic.test(line)))continue;let price:null|number=null,qty:null|number=null;const mult=line.match(/(?:rm\s*)?(\d+(?:\.\d+)?)\s*[x×]\s*(\d{1,2})\s*(?:pcs?|pc|keping|set|unit)?(?:\s+(\d+(?:\.\d+)?))?/i);if(mult){price=Number(mult[1]);qty=Number(mult[2])}if(price==null){const rm=explicitRm(line);if(rm!=null)price=rm}const q1=line.match(new RegExp(`(?:${(re as RegExp).source}).{0,24}?(\\d{1,2})\\s*(?:pcs?|pc|keping|set|unit)\\b`,'i'))||line.match(new RegExp(`\\b(\\d{1,2})\\s*(?:pcs?|pc|keping|set|unit)\\s*(?:x\\s*)?(?:${(re as RegExp).source})`,'i'));if(qty==null&&q1)qty=Number(q1[1]);if(price!=null&&price>0&&price<=500)out[cat]={...(out[cat]||{}),price};if(qty!=null&&qty>=1&&qty<=50)out[cat]={...(out[cat]||{}),qty}}}return out}
function qty(ms:any[],cat:string,h:any){if(h?.qty)return h.qty;const re=catRe[cat]||catRe.printed;for(const m of [...ms].reverse()){const v=mt(m),x=v.match(new RegExp(`(?:${re.source}).{0,28}?(\\d{1,2})\\s*(?:pcs?|pc|keping|set|unit|design)\\b`,'i'))||v.match(new RegExp(`\\b(\\d{1,2})\\s*(?:pcs?|pc|keping|set|unit|design)\\s*(?:x\\s*)?(?:${re.source})`,'i'));if(x){const n=Number(x[1]);if(n>=1&&n<=50&&!/\bA[4-7]\b/i.test(x[0]))return n}}return 1}
function size(ss:string[]){for(const r of [/\b(\d+(?:\.\d+)?\s*[x×]\s*\d+(?:\.\d+)?\s*(?:inch|inci|in)?)\b/i,/\b(\d+(?:\.\d+)?\s*(?:inch|inci|inches|in))\b/i,/(\d+(?:\.\d+)?)\s*\"/i,/\b(A[4-7])\b/i])for(let i=ss.length-1;i>=0;i--){const m=t(ss[i]).match(r);if(m)return m[1]}return''}
function validW(v:string){v=t(v);return!!v&&v.length<=160&&!/^(OK|YA|YE|YES|SAMA|BAIK|SALAM|BOLEH|CONFIRM|WAIT|OKAY)$/i.test(v)&&!/payment|alamat|address|total|spx|jnt|postcode|poskod|pickup|make it \d+\s*(?:inch|in)/i.test(v)}
function wording(ms:any[],loose=false){const a=ms.filter(m=>m.direction==='inbound').map(mt).filter(Boolean);for(let i=a.length-1;i>=0;i--){let v=t(a[i]),m=v.match(/^\s*(?:wording|tulisan|custom\s*name|nama|name|huruf)\s*[:=-]\s*(.+)$/i);if(m&&validW(m[1]))return t(m[1]);if(/^(happy|selamat|the wedding|birthday|congrat)/i.test(v)&&validW(v))return v}if(loose){for(let i=a.length-1;i>=1;i--)if(/\bname\b.*(?:line|2\s*lines|two\s*lines|make)/i.test(a[i])&&validW(a[i-1]))return t(a[i-1])}return''}
function delivery(ms:any[]){for(const m of [...ms].reverse()){const v=mt(m);if(/pickup|ambil|ambik|self collect/i.test(v))return{method:'pickup',fee:0};if(/\bspx\b/i.test(v))return{method:'spx',fee:explicitRm(v)??4.5};if(/\bj\s*&?\s*t\b|\bjnt\b/i.test(v))return{method:'jnt',fee:explicitRm(v)??5.9};if(/ninja/i.test(v))return{method:'ninja',fee:explicitRm(v)??6.9}}return{method:'unknown',fee:0}}
function dateNeed(ms:any[],ts:number){const s=ms.filter(m=>m.direction==='inbound').map(mt).join('\n');let z=[...s.matchAll(/\b(\d{1,2})[\/.\-](\d{1,2})(?:[\/.\-](\d{2,4}))?\b/g)].at(-1);if(z){let y=z[3]?Number(z[3]):new Date(ts).getFullYear();if(y<100)y+=2000;return`${y}-${String(z[2]).padStart(2,'0')}-${String(z[1]).padStart(2,'0')}`}const hb=[...s.matchAll(/\b(\d{1,2})\s*(?:hb|haribulan)\b/gi)].at(-1),local=new Date(ts+8*3600000);if(hb){let day=Number(hb[1]),mo=local.getUTCMonth()+1,y=local.getUTCFullYear();if(day<local.getUTCDate()-3)mo++;if(mo>12){mo=1;y++}return`${y}-${String(mo).padStart(2,'0')}-${String(day).padStart(2,'0')}`}if(/esok|tomorrow/i.test(s)){const d=new Date(ts+8*3600000);d.setUTCDate(d.getUTCDate()+1);return d.toISOString().slice(0,10)}return null}
function refs(ms:any[]){return ms.filter(m=>['image','document'].includes(m.message_type)).slice(-12).map(m=>({message_id:m.id,provider_message_id:m.provider_message_id,type:m.message_type,media_url:m.media_url||null,caption:mt(m)||null,file_name:fn(m)||null}))}
function makeItems(rel:any[],job:any,c:any){const qd=quotes(rel),r=refs(rel),all=rel.map(mt).filter(Boolean),newd=/new design|design baru|custom topper|tema|buat design/.test(rel.filter(m=>m.direction==='inbound').map(mt).join('\n').toLowerCase())&&!/design sama|repeat|tukar nama|change name|edit|template sama/.test(rel.filter(m=>m.direction==='inbound').map(mt).join('\n').toLowerCase()),fb:any={edible:'Edible Image',acrylic:'Acrylic Cake Topper',wafer:'Wafer Paper',burnaway:'Burn Away Combo',printed:newd?'New Design Cake Topper':'Cake Topper',mirror:'Mirror Gold Topper'};return cats(rel).map((cat,i)=>{const cm=catMsgs(rel,cat),ss=(cm.length?cm:rel).map(mt).filter(Boolean),w=wording(cm.length?cm:rel,false)||(cat==='printed'?wording(rel,true):''),jt=cat==='printed'?(newd?'topper_new_design_glossy':'topper_editing_glossy'):cat;return{k:cat,product_type:cat,title:fb[cat]||'Item',qty:qty(cm.length?cm:rel,cat,qd[cat]),price:money(qd[cat]?.price||0),size:cat==='printed'?(size(all)||size(ss)):size(ss),style:cat==='printed'?`${newd?'New Design':'Editing / Existing Design'} — Glossy`:'',wording:w,custom_text:w,review:'Need Review',review_required:true,customization:{ai_generated:true,ai_job_type:jt,ai_pending_confirmation:true,conversation_id:c.id,whatsapp_phone:c.phone,whatsapp_link:wa(c.phone),qrpay_transaction_id:job.transaction_id,qrpay_amount:Number(job.amount),match_score:Number(Math.min(.99,c.n/150).toFixed(3)),reference_message_ids:r.map(v=>v.message_id),reference_media:r,source:'whatsapp_qrpay_ai',set_hint:i+1}}})}
function payload(rel:any[],c:any,job:any,alts:any[],rules:any[],opened:string){
  const its=makeItems(rel,job,c),del=delivery(rel),dn=dateNeed(rel,Date.parse(job.payment_received_at)),p=phone(c.phone||rel.find(m=>m.sender_phone)?.sender_phone),sc=Number(Math.max(.35,Math.min(.99,c.n/150)).toFixed(3));
  const quote=rel.filter(m=>m.direction==='outbound'&&exact(mt(m),Number(job.amount))).at(-1),gap=quote?Math.round((Date.parse(job.payment_received_at)-at(quote))/60000):null;
  const draft=applyLearningRules({customer:{name:c.name||'WhatsApp Customer',phone:p,address_line1:'',postcode:'',city:'',state:''},items:its,delivery:del.method,delivery_fee:del.fee,date_need:dn,conversation_id:c.id,transaction_id:job.transaction_id,payment_received_at:job.payment_received_at,match_score:sc,match_reason:[...c.why,...(quote&&gap>120?['historical_exact_amount_quote']:[])].join(','),payment_amount:Number(job.amount),evidence:{conversation_id:c.id,order_session_opened_at:opened,session_boundary_enforced:true,alternatives:alts,messages:rel.slice(-80).map(m=>({id:m.id,direction:m.direction,type:m.message_type,at:m.sent_at||m.created_at,text:mt(m).slice(0,600)})),reference_media:refs(rel),whatsapp_link:wa(p),worker_version:'qrpay-ai-draft-v13-effective-learning',historical_recovery:quote&&gap>120?{used:true,quote_message_id:quote.id,quote_at:quote.sent_at||quote.created_at,gap_minutes:gap}:{used:false}}},rel,rules,{flow:'qrpay_payment',referenceTime:job.payment_received_at,promptInjected:false,customerIdentity:{name:c.name,phone:p}});
  const subtotal=money(draft.items.reduce((sum:any,item:any)=>sum+Number(item.price||0)*Math.max(1,Number(item.qty||1)),0)),total=money(subtotal+Number(draft.delivery_fee||0)),difference=money(total-Number(job.amount)),missing=[];
  if(!draft.date_need)missing.push('date_need');
  if(draft.delivery==='unknown')missing.push('shipping_method');
  if(draft.items.some((item:any)=>Number(item.price||0)<=0))missing.push('item_price');
  if(Math.abs(difference)>.01)missing.push('payment_reconciliation');
  draft.ai_missing=missing;
  draft.draft_total=total;
  draft.admin_remark=`AI DRAFT ONLY — current order session. QRPay RM${Number(job.amount).toFixed(2)}. ${missing.length?'Admin check: '+missing.join(', '):'Main details extracted.'}`;
  return draft;
}
async function run(j:any,k:string,rules:any[],snippets:any[]){const b=await best(j,snippets);if(!b.top||b.top.n<42){await orderCall(k,{action:'update_job',job_id:j.id,patch:{status:'unmatched',match_score:b.top?.n||0,match_reason:'no_strong_whatsapp_candidate',evidence:{alternatives:b.alts,excluded_conversation_ids:b.excluded||[]},locked_at:null,completed_at:new Date().toISOString()}});return{job_id:j.id,status:'unmatched'}}const c=b.top,ts=Date.parse(j.payment_received_at),ctx=await orderCall(k,{action:'order_session_context',conversation_id:c.id,phone:c.phone}),opened=t(ctx.opened_at)||new Date(ts-45*86400000).toISOString(),all=await sessionMessages(c.id,opened,ts),filtered=filterOrderEvidenceMessages(all,snippets),rel=dealBlock(filtered.messages,Number(j.amount),ts);if(!rel.length){await orderCall(k,{action:'update_job',job_id:j.id,patch:{status:'unmatched',match_reason:'no_messages_in_current_order_session',evidence:{conversation_id:c.id,session_boundary_at:ctx.boundary_at||opened,seller_messages_excluded:filtered.excluded.length},locked_at:null,completed_at:new Date().toISOString()}});return{job_id:j.id,status:'unmatched',reason:'no_messages_in_current_order_session'}}const p=payload(rel,c,j,b.alts,rules,opened);p.evidence={...p.evidence,order_session_id:ctx.session_id||null,session_boundary_at:ctx.boundary_at||opened,seller_template_filter:{total_messages:all.length,included_messages:filtered.messages.length,excluded_count:filtered.excluded.length,excluded:filtered.excluded}};await orderCall(k,{action:'update_job',job_id:j.id,patch:{status:'matched',matched_conversation_id:c.id,matched_phone:p.customer.phone,matched_customer_name:p.customer.name,match_score:p.match_score,match_reason:p.match_reason,extraction:p,evidence:p.evidence}});if(j.mode==='dry_run'){await orderCall(k,{action:'update_job',job_id:j.id,patch:{status:'dry_run_complete',locked_at:null,completed_at:new Date().toISOString()}});return{job_id:j.id,status:'dry_run_complete',excluded_seller_messages:filtered.excluded.length,payload:p}}const z=await orderCall(k,{action:'create_draft',job_id:j.id,payload:p});return{job_id:j.id,status:'draft_created',draft:z.result,conversation_id:c.id,order_session_id:z.result?.order_session_id||ctx.session_id||null,session_opened_at:opened,excluded_seller_messages:filtered.excluded.length}}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:H});if(req.method!=='POST')return out({ok:false,error:'POST required'},405);if(!await auth(req))return out({ok:false,error:'Unauthorized'},401);const k=req.headers.get('x-qrpay-ai-token')||'';let body:any={};try{body=await req.json()}catch{}try{const q=await orderCall(k,{action:'claim',batch_size:Math.max(1,Math.min(10,Number(body.batch_size||3)))}),[learning,snippets]=await Promise.all([orderCall(k,{action:'learning_context'}).catch(()=>({rules:[]})),activeSellerSnippets()]),rules=Array.isArray(learning.rules)?learning.rules:[],rs=[];for(const j of q.jobs||[])try{rs.push(await run(j,k,rules,snippets))}catch(e){const m=e instanceof Error?e.message:String(e),fin=Number(j.attempts||0)>=5;await orderCall(k,{action:'update_job',job_id:j.id,patch:{status:fin?'failed':'retry',next_attempt_at:new Date(Date.now()+(fin?86400000:300000)).toISOString(),locked_at:null,last_error:m.slice(0,2000),completed_at:fin?new Date().toISOString():null}});rs.push({job_id:j.id,status:fin?'failed':'retry',error:m})}return out({ok:true,worker:'qrpay-ai-draft-v14-session-isolation',mode:'draft_only',claimed:q.jobs?.length||0,active_learning_rules:rules.length,seller_snippets:snippets.length,results:rs})}catch(e){return out({ok:false,error:e instanceof Error?e.message:String(e)},500)}});
