import { randomUUID, createHash } from 'crypto';
import { db, router, json, error } from '@appdeploy/sdk';
import { shipmentRoutes } from './shipment-routes';
import { paymentRoutes } from './payment-routes';
import { notifySubscribers, realtimeSubscriptionRoutes } from './realtime-subscribers';
import { getProductionStatus, setProductionUrl, queueProduction } from './production-integration';

type InputItem={k:string;title:string;process:string;review?:string;size:string;style:string;customText?:string;price:number;qty:number};
type Customer={name:string;address_line1:string;city:string;postcode:string;state:string;phone:string;phone_masked:string;address_masked:string};
type CustomerRow={public_token:string;name:string;phone:string;created_at:number};
type OrderRow={order_id:string;public_token:string;customer_token:string;date_need:string;created_at:number;total:number;payment:string;delivery:string;delivery_name?:string;delivery_phone?:string;delivery_address?:string;delivery_city?:string;delivery_postcode?:string;delivery_state?:string;status:string;tab:string;tracking?:string;admin_status?:string;admin_remark?:string;production_approved?:boolean;customer_confirmed?:boolean;customer_confirm_token?:string;customer_confirmed_at?:number};
type ItemRow={order_token:string;k:string;title:string;qty:number;size:string;style:string;custom_text?:string;price:number;workflow:string;review_required:boolean;design_preview_url?:string};
type ComponentRow={order_token:string;item_id:string;component_type:string;label:string;workflow:string;review_required:boolean;review_status:string;preview_url?:string;clickup_task_id?:string;clickup_status?:string;last_synced_at?:number};
type LoginRow={token:string;customer_token:string;phone:string;expires_at:number;used_at?:number};
type AdminSession={token:string;username:string;expires_at:number};
type AdminPermission={username:string;permissions:string[]};
type AuditRow={order_db_id:string;order_id:string;action:string;actor:string;created_at:number};
const token=(prefix:string)=>prefix+'_'+randomUUID().replace(/-/g,'').slice(0,24);
function normalizeMalaysiaPhone(value:string){const digits=String(value||'').replace(/\D/g,'');const normalized=digits.startsWith('60')?digits:digits.startsWith('0')?'60'+digits.slice(1):digits.startsWith('1')?'60'+digits:'';return /^601\d{8,9}$/.test(normalized)?'+'+normalized:''}
const dateText=(v:number|string)=>new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Kuala_Lumpur',day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(v));
const hash=(username:string,password:string)=>createHash('sha256').update(`${username}|icetak|${password}`).digest('hex');
const ADMIN_HASHES:Record<string,string>={admin1:'f24c9d70bf705e12b01d142823ca8a6d1f9e757486151ab5226e3e6a262bb0de',admin2:'8fdff8a1d00401f26e14b945980b3e6f5868a899fb3ac2621795f4fa3bcd81b6',admin3:'48bd0e9d7f6a1413002e76d8908bd678810dcd54ebe67023ee9fe3b38c1e93c2'};
const ALL_PERMS=['view_orders','create_order','mark_paid','approve_cash','cancel_order','edit_order','approve_production','manage_permissions','open_whatsapp','export_data'];
const DEFAULT_PERMS:Record<string,string[]>={admin1:ALL_PERMS,admin2:['view_orders','create_order','mark_paid','approve_cash','edit_order','approve_production','open_whatsapp'],admin3:['view_orders','open_whatsapp']};
async function permissionsFor(username:string){if(username==='admin1')return ALL_PERMS;const {items}=await db.list<AdminPermission>('admin_permissions',{filter:{username}});return items[0]?.permissions||DEFAULT_PERMS[username]||[]}
async function requireAdmin(sessionToken:string,permission?:string){if(!sessionToken)return null;const {items}=await db.list<AdminSession>('admin_sessions',{filter:{token:sessionToken}});const session=items[0];if(!session||session.expires_at<Date.now())return null;const permissions=await permissionsFor(session.username);if(permission&&!permissions.includes(permission))return null;return {username:session.username,permissions}}
async function paymentWebhookConfigured(){const {items}=await db.list<{key:string;key_hash:string}>('integration_settings',{filter:{key:'payment_webhook'}});return Boolean(items[0]?.key_hash)}
async function uniqueOrderId(){for(let i=0;i<8;i++){const d=new Date(),yy=String(d.getFullYear()).slice(-2),mm=String(d.getMonth()+1).padStart(2,'0'),dd=String(d.getDate()).padStart(2,'0'),candidate=`IC${yy}${mm}${dd}-${Math.floor(1000+Math.random()*9000)}`;const {items}=await db.list<OrderRow>('orders',{filter:{order_id:candidate}});if(!items.length)return candidate}throw new Error('Unable to generate order id')}
async function customerFor(input:Customer,provided?:string){if(provided){const {items}=await db.list<CustomerRow>('customers',{filter:{public_token:provided}});if(items[0])return items[0]}const phone=normalizeMalaysiaPhone(input.phone);if(!phone)throw new Error('Invalid Malaysia phone number');const {items}=await db.list<CustomerRow>('customers',{filter:{phone}});if(items[0])return items[0];const legacy=phone.replace(/\D/g,'');const {items:legacyItems}=await db.list<CustomerRow>('customers',{filter:{phone:legacy}});if(legacyItems[0])return legacyItems[0];const public_token=token('c');const [id]=await db.add('customers',[{public_token,name:input.name,phone,created_at:Date.now()}]);if(!id)throw new Error('Failed to create customer');return {id,public_token,name:input.name,phone,created_at:Date.now()}}
function componentRecords(orderToken:string,itemId:string,item:InputItem){const review=item.review==='Need Review',base={order_token:orderToken,item_id:itemId,workflow:'Order Received',review_required:review,review_status:review?'pending':'not_required',preview_url:'',clickup_task_id:'',clickup_status:'',last_synced_at:0};if(item.k==='burnaway')return [{...base,component_type:'edible',label:'Edible Layer'},{...base,component_type:'wafer',label:'Wafer Layer'}];const labels:Record<string,string>={edible:'Edible Image',wafer:'Wafer Paper',printed:'Cake Topper',mirror:'Mirror Gold Topper',acrylic:'Acrylic Topper'};return [{...base,component_type:item.k,label:labels[item.k]||item.title}]}
async function shapeOrder(o:OrderRow&{id:string}){const {items}=await db.list<ItemRow>('order_items',{filter:{order_token:o.public_token}}),{items:components}=await db.list<ComponentRow>('production_components',{filter:{order_token:o.public_token}});const byItem=new Map<string,Array<ComponentRow&{id:string}>>();components.forEach(c=>{const list=byItem.get(c.item_id)||[];list.push(c);byItem.set(c.item_id,list)});const shapedItems=items.map(i=>{const linked=byItem.get(i.id)||[{id:i.id,order_token:o.public_token,item_id:i.id,component_type:i.k,label:i.title,workflow:i.workflow,review_required:i.review_required,review_status:i.workflow==='Approved'?'approved':i.review_required?'pending':'not_required',preview_url:i.design_preview_url||'',clickup_task_id:'',clickup_status:'',last_synced_at:0}];return {id:i.id,k:i.k,title:i.title,qty:i.qty,size:i.size,style:i.style,customText:i.custom_text,price:i.price,workflow:i.workflow,reviewRequired:i.review_required,previewUrl:i.design_preview_url||'',components:linked.map(c=>({id:c.id,type:c.component_type,label:c.label,workflow:c.workflow,reviewRequired:c.review_required,reviewStatus:c.review_status,previewUrl:c.preview_url||'',clickupTaskId:c.clickup_task_id||'',clickupStatus:c.clickup_status||'',lastSyncedAt:c.last_synced_at||0,legacy:c.id===i.id}))}});const allComponents=shapedItems.flatMap(i=>i.components),actionCount=allComponents.filter(c=>c.reviewRequired&&c.workflow==='Waiting Review').length;const deliverySummary=o.delivery==='Pickup'?'Pickup — Bandar Baru Pasir Puteh':[o.delivery_address,o.delivery_postcode,o.delivery_city,o.delivery_state].filter(Boolean).join(', ')||o.delivery;return {id:o.order_id,orderToken:o.public_token,tab:o.tab,dateNeed:dateText(o.date_need),dateNeedRaw:o.date_need,created:dateText(o.created_at),total:o.total,payment:o.payment,delivery:o.delivery,deliverySummary,deliveryName:o.delivery_name||'',deliveryPhone:o.delivery_phone||'',status:actionCount?'Action Required':o.status,actionCount,tracking:o.tracking,canCancel:o.payment==='Unpaid'&&!o.production_approved&&o.status!=='Cancelled',adminRemark:o.admin_remark||'',productionApproved:Boolean(o.production_approved),customerConfirmed:Boolean(o.customer_confirmed),items:shapedItems}}
const SUPABASE_PROJECT_REF='buivecgahhmrhlmfujgt';
const SUPABASE_PROJECT_URL='https://buivecgahhmrhlmfujgt.supabase.co';
async function checkSupabaseBridge(){try{const response=await fetch(`${SUPABASE_PROJECT_URL}/functions/v1/icetak-bridge`);return {configured:true,projectRef:SUPABASE_PROJECT_REF,bridge:'icetak-bridge',reachable:response.status<500,status:response.status}}catch{return {configured:true,projectRef:SUPABASE_PROJECT_REF,bridge:'icetak-bridge',reachable:false,status:0}}}
async function adminOrders(){const {items}=await db.list<OrderRow>('orders');const {items:customers}=await db.list<CustomerRow>('customers');const {items:audits}=await db.list<AuditRow>('admin_audit');const customerMap=new Map(customers.map(c=>[c.public_token,c]));const latestAudit=new Map<string,AuditRow>();audits.sort((a,b)=>b.created_at-a.created_at).forEach(a=>{if(!latestAudit.has(a.order_db_id))latestAudit.set(a.order_db_id,a)});return Promise.all(items.sort((a,b)=>b.created_at-a.created_at).map(async o=>{const customer=customerMap.get(o.customer_token),audit=latestAudit.get(o.id);const shaped=await shapeOrder(o);return {...shaped,dbId:o.id,customerToken:o.customer_token,customerName:customer?.name||'Customer',customerPhone:customer?.phone||'',adminStatus:o.admin_status||o.status,lastAction:audit?`${audit.action} by ${audit.actor} • ${dateText(audit.created_at)}`:''}}))}
export const handler=router({
 ...shipmentRoutes,
 ...paymentRoutes,
 ...realtimeSubscriptionRoutes,
 'GET /api/_healthcheck':[async()=>json({message:'Success'})],
 'GET /api/supabase/status':[async()=>json(await checkSupabaseBridge())],
 'GET /api/migration/appdeploy-counts':[async()=>{const tables=['customers','orders','order_items','production_components','payment_sessions','shipment_events','integration_settings','integration_outbox','notification_outbox','admin_sessions','admin_permissions','login_tokens','entity_subscriptions','unmatched_payment_transactions'];const counts:Record<string,number>={};for(const table of tables){try{const {items}=await db.list(table);counts[table]=items.length}catch{counts[table]=-1}}return json({ok:true,source:'appdeploy',counts})}],
 'POST /api/orders':[async({body})=>{const b=(body||{}) as {customer_token?:string;customer?:Customer;items?:InputItem[];date_need?:string;delivery?:string;payment?:string;total?:number;notify_whatsapp?:boolean};if(!b.customer||!b.items?.length||!b.date_need||!b.delivery||!b.payment||typeof b.total!=='number')return error('Missing order details',400);const c=await customerFor(b.customer,b.customer_token);const public_token=token('o'),order_id=await uniqueOrderId(),cashPickup=b.payment==='Cash Counter'&&b.delivery==='pickup',confirmToken=cashPickup?token('cf'):undefined,payment=cashPickup?'Cash at Counter':'Unpaid',tab=cashPickup?'progress':'to_pay',status=cashPickup?'Waiting Customer Confirmation':'Waiting Payment',admin_status=cashPickup?'Awaiting Customer Confirmation':'New Order';const [orderDbId]=await db.add('orders',[{order_id,public_token,customer_token:c.public_token,date_need:b.date_need,created_at:Date.now(),total:b.total,payment,delivery:b.delivery==='pickup'?'Pickup':String(b.delivery).toUpperCase(),delivery_name:b.customer.name,delivery_phone:c.phone,delivery_address:b.customer.address_line1||'',delivery_city:b.customer.city||'',delivery_postcode:b.customer.postcode||'',delivery_state:b.customer.state||'',status,tab,admin_status,customer_confirmed:!cashPickup,customer_confirm_token:confirmToken}]);if(!orderDbId)return error('Failed to create order',500);const ids=await db.add('order_items',b.items.map(i=>({order_token:public_token,k:i.k,title:i.title,qty:i.qty,size:i.size,style:i.style,custom_text:i.customText||'',price:i.price,workflow:'Order Received',review_required:i.review==='Need Review'})));if(ids.some(x=>!x))return error('Failed to create order items',500);const componentIds=await db.add('production_components',b.items.flatMap((i,n)=>componentRecords(public_token,String(ids[n]),i)));if(componentIds.some(x=>!x))return error('Failed to create production components',500);if(b.notify_whatsapp!==false)await db.add('notification_outbox',[{event_type:'order_created',channel:'whatsapp',phone:c.phone,customer_name:c.name,order_id,order_token:public_token,confirm_token:confirmToken||'',status:'pending',source:'customer',created_at:Date.now()}]);return json({success:true,order_id,order_token:public_token,customer_token:c.public_token,confirm_token:confirmToken,notify_whatsapp:b.notify_whatsapp!==false})}],
 'GET /api/customers/:token/profile':[async({params})=>{const {items:customers}=await db.list<CustomerRow>('customers',{filter:{public_token:params.token}});const c=customers[0];if(!c)return error('Customer not found',404);const {items:orders}=await db.list<OrderRow>('orders',{filter:{customer_token:params.token}});const latest=orders.sort((a,b)=>b.created_at-a.created_at).find(o=>o.delivery!=='Pickup'&&Boolean(o.delivery_address));const phone=normalizeMalaysiaPhone(c.phone)||c.phone,digits=String(phone).replace(/\D/g,'');const address_line1=latest?.delivery_address||'',city=latest?.delivery_city||'',postcode=latest?.delivery_postcode||'',state=latest?.delivery_state||'';return json({customer:{name:latest?.delivery_name||c.name,phone,phone_masked:`+${digits.slice(0,3)}***${digits.slice(-4)}`,address_line1,city,postcode,state,address_masked:address_line1?`${address_line1}, ${postcode} ${city}, ${state}`:''}})}],
 'GET /api/customers/:token/orders':[async({params})=>{const {items}=await db.list<OrderRow>('orders',{filter:{customer_token:params.token}});return json({orders:await Promise.all(items.sort((a,b)=>b.created_at-a.created_at).map(shapeOrder))})}],
 'GET /api/orders/:token':[async({params})=>{const {items}=await db.list<OrderRow>('orders',{filter:{public_token:params.token}});if(!items[0])return error('Order not found',404);return json({order:await shapeOrder(items[0])})}],
 'GET /api/order-confirmations/:token':[async({params})=>{const {items}=await db.list<OrderRow>('orders',{filter:{customer_confirm_token:params.token}});const order=items[0];if(!order)return error('Confirmation link not found',404);return json({order:await shapeOrder(order)})}],
 'POST /api/order-confirmations/:token':[async({params})=>{const {items}=await db.list<OrderRow>('orders',{filter:{customer_confirm_token:params.token}});const order=items[0];if(!order)return error('Confirmation link not found',404);if(order.customer_confirmed)return json({ok:true,already_confirmed:true,order_id:order.order_id});const [ok]=await db.update('orders',[{id:order.id,record:{...order,customer_confirmed:true,customer_confirmed_at:Date.now(),status:'Customer Confirmed',admin_status:'Customer Confirmed'}}]);if(!ok)return error('Confirmation failed',500);await db.add('admin_audit',[{order_db_id:order.id,order_id:order.order_id,action:'customer_confirmed',actor:'customer',created_at:Date.now()}]);return json({ok:true,order_id:order.order_id})}],
 'POST /api/orders/:token/items/:itemId/approve':[async({params})=>{const [item]=await db.get<ItemRow>('order_items',[params.itemId]);if(!item||item.order_token!==params.token)return error('Item not found',404);if(!item.review_required)return error('Review not required',400);if(!item.design_preview_url)return error('Design preview belum tersedia',409);if(item.workflow!=='Waiting Review')return error('Item belum menunggu approval',409);const [ok]=await db.update('order_items',[{id:params.itemId,record:{...item,workflow:'Approved'}}]);return ok?json({ok:true}):error('Approval failed',500)}],
 'POST /api/orders/:token/cancel':[async({params})=>{const {items}=await db.list<OrderRow>('orders',{filter:{public_token:params.token}});const order=items[0];if(!order)return error('Order not found',404);if(order.payment!=='Unpaid')return error('Paid order cannot be cancelled',409);if(order.production_approved)return error('Order already in production',409);if(order.status==='Cancelled')return json({ok:true,already_cancelled:true});const [ok]=await db.update('orders',[{id:order.id,record:{...order,status:'Cancelled',admin_status:'Cancelled by Customer',tab:'completed'}}]);if(!ok)return error('Cancel failed',500);await db.add('admin_audit',[{order_db_id:order.id,order_id:order.order_id,action:'customer_cancel',actor:'customer',created_at:Date.now()}]);return json({ok:true})}],
 'POST /api/orders/:token/components/:componentId/approve':[async({params})=>{const [component]=await db.get<ComponentRow>('production_components',[params.componentId]);if(!component||component.order_token!==params.token)return error('Component not found',404);if(!component.review_required)return error('Review not required',400);if(!component.preview_url)return error('Design preview belum tersedia',409);if(component.workflow!=='Waiting Review')return error('Component belum menunggu approval',409);const [ok]=await db.update('production_components',[{id:params.componentId,record:{...component,workflow:'Approved',review_status:'approved'}}]);return ok?json({ok:true}):error('Approval failed',500)}],
 'POST /api/login/request':[async({body})=>{const phone=normalizeMalaysiaPhone(String((body as {phone?:string})?.phone||''));if(!phone)return error('Nombor WhatsApp Malaysia tidak sah',400);const {items}=await db.list<CustomerRow>('customers',{filter:{phone}});let customer=items[0];if(!customer){const legacy=phone.replace(/\D/g,'');const {items:legacyItems}=await db.list<CustomerRow>('customers',{filter:{phone:legacy}});customer=legacyItems[0]}if(!customer)return error('Tiada order dijumpai untuk nombor ini',404);const loginToken=token('lg'),expires_at=Date.now()+15*60*1000;const [id]=await db.add('login_tokens',[{token:loginToken,customer_token:customer.public_token,phone,expires_at}]);if(!id)return error('Gagal jana login link',500);return json({login_token:loginToken,expires_in_minutes:15,phone})}],
 'POST /api/login/exchange':[async({body})=>{const loginToken=String((body as {login_token?:string})?.login_token||'');if(!loginToken)return error('Login token diperlukan',400);const {items}=await db.list<LoginRow>('login_tokens',{filter:{token:loginToken}});const row=items[0];if(!row)return error('Login link tidak sah',404);if(row.used_at)return error('Login link sudah digunakan',410);if(row.expires_at<Date.now())return error('Login link telah tamat tempoh',410);const [ok]=await db.update('login_tokens',[{id:row.id,record:{...row,used_at:Date.now()}}]);if(!ok)return error('Gagal sahkan login',500);return json({customer_token:row.customer_token})}],
 'POST /api/admin/login':[async({body})=>{const b=(body||{}) as {username?:string;password?:string};const username=String(b.username||'').toLowerCase(),password=String(b.password||'');if(!ADMIN_HASHES[username]||hash(username,password)!==ADMIN_HASHES[username])return error('Username atau password salah',401);const sessionToken=token('adm'),expires_at=Date.now()+12*60*60*1000;const [id]=await db.add('admin_sessions',[{token:sessionToken,username,expires_at}]);if(!id)return error('Login gagal',500);return json({session_token:sessionToken,username,permissions:await permissionsFor(username)})}],
 'POST /api/admin/dashboard':[async({body})=>{const sessionToken=String((body as {session_token?:string})?.session_token||''),admin=await requireAdmin(sessionToken,'view_orders');if(!admin)return error('Unauthorized',401);return json({admin:{...admin,paymentWebhookConfigured:await paymentWebhookConfigured(),productionIntegration:await getProductionStatus()},orders:await adminOrders(),admins:await Promise.all(['admin1','admin2','admin3'].map(async username=>({username,permissions:await permissionsFor(username)})))})}],
 'POST /api/admin/payment-webhook-key':[async({body})=>{const sessionToken=String((body as {session_token?:string})?.session_token||''),admin=await requireAdmin(sessionToken,'manage_permissions');if(!admin||admin.username!=='admin1')return error('Admin 1 sahaja boleh jana webhook key',403);const rawKey=`dcwh_${randomUUID().replaceAll('-','')}${randomUUID().replaceAll('-','')}`,key_hash=createHash('sha256').update(rawKey).digest('hex'),{items}=await db.list<{key:string;key_hash:string;updated_at:number}>('integration_settings',{filter:{key:'payment_webhook'}}),record={key:'payment_webhook',key_hash,updated_at:Date.now()};if(items[0])await db.update('integration_settings',[{id:items[0].id,record}]);else await db.add('integration_settings',[record]);await db.add('admin_audit',[{order_db_id:'integration',order_id:'PAYMENT-WEBHOOK',action:'regenerate_webhook_key',actor:admin.username,created_at:Date.now()}]);return json({ok:true,key:rawKey,warning:'Copy sekarang. Key ini tidak akan dipaparkan lagi.'})}],
 'POST /api/admin/orders':[async({body})=>{const b=(body||{}) as {session_token?:string;customer?:Customer;items?:InputItem[];date_need?:string;delivery?:string;payment?:string;admin_remark?:string};const admin=await requireAdmin(String(b.session_token||''),'create_order');if(!admin||!b.customer||!b.items?.length||!b.date_need||!b.delivery||!b.payment)return error('Invalid admin order',400);const c=await customerFor(b.customer),public_token=token('o'),order_id=await uniqueOrderId(),cashPickup=b.payment==='Cash Counter'&&b.delivery==='pickup',confirmToken=cashPickup?token('cf'):undefined,total=b.items.reduce((s,i)=>s+Math.max(1,Number(i.qty)||1)*Math.max(0,Number(i.price)||0),0),payment=cashPickup?'Cash at Counter':b.payment==='Paid'?'Paid':'Unpaid',tab=payment==='Unpaid'?'to_pay':'progress',status=cashPickup?'Waiting Customer Confirmation':payment==='Paid'?'Ready to Process':'Waiting Payment',admin_status=cashPickup?'Awaiting Customer Confirmation':payment==='Paid'?'Ready to Process':'New Order';const [orderDbId]=await db.add('orders',[{order_id,public_token,customer_token:c.public_token,date_need:b.date_need,created_at:Date.now(),total,payment,delivery:b.delivery==='pickup'?'Pickup':String(b.delivery).toUpperCase(),delivery_name:b.customer.name,delivery_phone:c.phone,delivery_address:b.customer.address_line1||'',delivery_city:b.customer.city||'',delivery_postcode:b.customer.postcode||'',delivery_state:b.customer.state||'',status,tab,admin_status,admin_remark:String(b.admin_remark||''),customer_confirmed:!cashPickup,customer_confirm_token:confirmToken,created_by:admin.username,source:'admin'}]);if(!orderDbId)return error('Failed to create order',500);const ids=await db.add('order_items',b.items.map(i=>({order_token:public_token,k:i.k,title:i.title,qty:Math.max(1,Number(i.qty)||1),size:i.size,style:i.style,custom_text:i.customText||'',price:Math.max(0,Number(i.price)||0),workflow:'Order Received',review_required:i.review==='Need Review'})));if(ids.some(x=>!x))return error('Failed to create order items',500);const componentIds=await db.add('production_components',b.items.flatMap((i,n)=>componentRecords(public_token,String(ids[n]),i)));if(componentIds.some(x=>!x))return error('Failed to create production components',500);await db.add('notification_outbox',[{event_type:'order_created',channel:'whatsapp',phone:c.phone,customer_name:c.name,order_id,order_token:public_token,confirm_token:confirmToken||'',status:'pending',source:'admin',created_by:admin.username,total,date_need:b.date_need,delivery:b.delivery,created_at:Date.now()}]);await db.add('admin_audit',[{order_db_id:orderDbId,order_id,action:'create_order',actor:admin.username,created_at:Date.now()}]);return json({success:true,order_id,order_token:public_token,customer_token:c.public_token,confirm_token:confirmToken,total})}],
 'POST /api/admin/order-action':[async({body})=>{const b=(body||{}) as {session_token?:string;order_db_id?:string;action?:string};const required=b.action==='mark_paid'?'mark_paid':b.action==='approve_cash'?'approve_cash':b.action==='cancel'?'cancel_order':b.action==='approve_production'?'approve_production':'';const admin=await requireAdmin(String(b.session_token||''),required);if(!admin||!b.order_db_id||!b.action)return error('Unauthorized',401);const [order]=await db.get<OrderRow>('orders',[b.order_db_id]);if(!order)return error('Order not found',404);let next={...order};if(b.action==='mark_paid'){next={...next,payment:'Paid',status:'Ready to Process',tab:'progress',admin_status:'Ready to Process'};const {items:sessions}=await db.list<Record<string,any>>('payment_sessions',{filter:{order_token:order.public_token}});const session=sessions.sort((a,b)=>Number(b.created_at||0)-Number(a.created_at||0))[0];if(session){const matchedAt=Date.now(),transactionId=session.transaction_id||`ADMIN-${matchedAt}`,updatedSession={...session,status:'matched',transaction_id:transactionId,matched_at:matchedAt};await db.update('payment_sessions',[{id:session.id,record:updatedSession}]);await notifySubscribers('payment',order.public_token,{paid:true,payment:{id:session.id,orderToken:session.order_token,orderId:session.order_id,baseAmount:session.base_amount,expectedAmount:session.expected_amount,discount:session.discount,expiresAt:session.expires_at,status:'matched',transactionId,receiptName:session.receipt_name||'',receiptUrl:'',submittedAt:session.submitted_at||0,matchedAt}})}await db.add('notification_outbox',[{event_type:'payment_received',channel:'whatsapp',phone:order.delivery_phone||'',customer_name:order.delivery_name||'',order_id:order.order_id,order_token:order.public_token,transaction_id:session?.transaction_id||'ADMIN-CONFIRMED',amount:session?.expected_amount||order.total,status:'pending',source:'admin',created_at:Date.now()}])}if(b.action==='approve_cash')next={...next,status:'Ready to Process',tab:'progress',admin_status:'Ready to Process'};if(b.action==='cancel')next={...next,status:'Cancelled',tab:'completed',admin_status:'Cancelled'};if(b.action==='approve_production'){if(order.payment==='Cash at Counter'&&!order.customer_confirmed)return error('Customer confirmation required',409);next={...next,production_approved:true,status:'In Production',tab:'progress',admin_status:'Approved for Production'}};const [ok]=await db.update('orders',[{id:b.order_db_id,record:next}]);if(!ok)return error('Update failed',500);await db.add('admin_audit',[{order_db_id:b.order_db_id,order_id:order.order_id,action:b.action,actor:admin.username,created_at:Date.now()}]);return json({ok:true})}],
 'POST /api/admin/order-update':[async({body})=>{const b=(body||{}) as {session_token?:string;order_db_id?:string;date_need?:string;admin_remark?:string;items?:Array<{id:string;qty:number;price:number;custom_text?:string;design_preview_url?:string}>};const admin=await requireAdmin(String(b.session_token||''),'edit_order');if(!admin||!b.order_db_id||!b.date_need||!Array.isArray(b.items)||!b.items.length)return error('Invalid order update',400);const [order]=await db.get<OrderRow>('orders',[b.order_db_id]);if(!order)return error('Order not found',404);const itemRecords=await db.get<ItemRow>('order_items',b.items.map(i=>i.id));const updates: Array<{id:string;record:Record<string,unknown>}>=[];let total=0;for(let n=0;n<b.items.length;n++){const input=b.items[n],current=itemRecords[n];if(!current||current.order_token!==order.public_token)return error('Invalid order item',400);const qty=Math.max(1,Math.floor(Number(input.qty)||1)),price=Math.max(0,Number(input.price)||0);total+=qty*price;updates.push({id:input.id,record:{...current,qty,price,custom_text:String(input.custom_text||''),design_preview_url:String(input.design_preview_url||'')}})}const itemOk=await db.update('order_items',updates);if(itemOk.some(ok=>!ok))return error('Item update failed',500);const [orderOk]=await db.update('orders',[{id:b.order_db_id,record:{...order,date_need:b.date_need,total,admin_remark:String(b.admin_remark||''),production_approved:false,admin_status:'Needs Approval'}}]);if(!orderOk)return error('Order update failed',500);await db.add('admin_audit',[{order_db_id:b.order_db_id,order_id:order.order_id,action:'edit_order',actor:admin.username,created_at:Date.now()}]);return json({ok:true,total})}],
 'POST /api/admin/permissions':[async({body})=>{const b=(body||{}) as {session_token?:string;username?:string;permissions?:string[]};const admin=await requireAdmin(String(b.session_token||''),'manage_permissions');if(!admin||admin.username!=='admin1')return error('Admin 1 sahaja boleh ubah permission',403);if(!b.username||b.username==='admin1'||!['admin2','admin3'].includes(b.username))return error('Admin tidak sah',400);const clean=(b.permissions||[]).filter(p=>ALL_PERMS.includes(p)&&!['manage_permissions','export_data'].includes(p));const {items}=await db.list<AdminPermission>('admin_permissions',{filter:{username:b.username}});if(items[0])await db.update('admin_permissions',[{id:items[0].id,record:{username:b.username,permissions:clean}}]);else await db.add('admin_permissions',[{username:b.username,permissions:clean}]);return json({ok:true,permissions:clean})}],
 'POST /api/admin/export':[async({body})=>{const sessionToken=String((body as {session_token?:string})?.session_token||''),admin=await requireAdmin(sessionToken,'export_data');if(!admin||admin.username!=='admin1')return error('Admin 1 sahaja boleh export data',403);const [customers,orders,orderItems,components,audit]=await Promise.all([db.list('customers'),db.list('orders'),db.list('order_items'),db.list('production_components'),db.list('admin_audit')]);return json({exported_at:new Date().toISOString(),customers:customers.items,orders:orders.items,order_items:orderItems.items,production_components:components.items,admin_audit:audit.items})}],
});