import { db, json, error, secrets } from '@appdeploy/sdk';

const LIST_ID='901604488980';
const SHOP_ID='188218638';
const CACHE_TABLE='catalog_products';
const META_TABLE='catalog_meta';
const GENERIC_IMAGE='https://icetak.myshopify.com/cdn/shop/products/15bace3254888672b80c9d166c4792e9_d2bf378c-423b-414b-be67-6b8455feed5a_360x.jpg';

type CatalogProduct={id:string;clickupTaskId:string;slug:string;title:string;displayTitle:string;parentSku:string;shopeeProductId:string;category:string;status:string;imageUrl:string;shopeeUrl:string;hasDimension:boolean;searchText:string;sourceUpdatedAt:number;source:string};
type MetaRecord={key:string;source:string;count:number;updatedAt:number;lastAttemptAt:number;lastError?:string};

const seed:CatalogProduct[]=[
 {id:'86cwqmjgc',clickupTaskId:'86cwqmjgc',slug:'spider-man-custom-name-cake-topper-86cwqmjgc',title:'[CUSTOM NAME] Happy Birthday Cake Topper Spider-Man Decoration Set Party Accessories Banner Hiasan Kek Design',displayTitle:'Spider-Man Custom Name Cake Topper',parentSku:'',shopeeProductId:'',category:'CUSTOM NAME - Topper',status:'NORMAL - active',imageUrl:GENERIC_IMAGE,shopeeUrl:'',hasDimension:false,searchText:'spiderman spider man spider-man custom name cake topper',sourceUpdatedAt:Date.now(),source:'fallback'},
 {id:'86cwqmmy4',clickupTaskId:'86cwqmmy4',slug:'spider-man-ready-stock-cake-topper-86cwqmmy4',title:'READY STOCK Happy Birthday Cake Topper Spider-Man Decoration Set Party Accessories Banner Hiasan Kek Design',displayTitle:'Spider-Man Ready Stock Cake Topper',parentSku:'',shopeeProductId:'',category:'Ready Stock - topper',status:'NORMAL - active',imageUrl:GENERIC_IMAGE,shopeeUrl:'',hasDimension:false,searchText:'spiderman spider man spider-man ready stock cake topper',sourceUpdatedAt:Date.now(),source:'fallback'},
 {id:'86cwqmmur',clickupTaskId:'86cwqmmur',slug:'spiderman-custom-name-cake-topper-86cwqmmur',title:'[CUSTOM NAME] Happy Birthday Cake Topper Spiderman Decoration Set Party Accessories Banner Hiasan Kek Design',displayTitle:'Spiderman Custom Name Cake Topper',parentSku:'',shopeeProductId:'',category:'CUSTOM NAME - Topper',status:'NORMAL - active',imageUrl:GENERIC_IMAGE,shopeeUrl:'',hasDimension:false,searchText:'spiderman spider man spider-man custom name cake topper',sourceUpdatedAt:Date.now(),source:'fallback'},
 {id:'86cwqmnzx',clickupTaskId:'86cwqmnzx',slug:'spiderman-cupcake-topper-86cwqmnzx',title:'Happy Birthday Cake Topper Cupcake Spiderman Decoration Set Party Accessories Hiasan Kek Design 1',displayTitle:'Spiderman Cupcake Topper',parentSku:'',shopeeProductId:'',category:'Ready Stock - topper',status:'NORMAL - active',imageUrl:GENERIC_IMAGE,shopeeUrl:'',hasDimension:false,searchText:'spiderman spider man spider-man cupcake topper',sourceUpdatedAt:Date.now(),source:'fallback'},
 {id:'86cwqmhpz',clickupTaskId:'86cwqmhpz',slug:'jnt-express-custom-name-cake-topper-cn0790',title:'[CUSTOM NAME] Happy Birthday Cake Topper J&T Express Decoration Set Party Accessories Banner Hiasan Kek Design',displayTitle:'J&T Express Custom Name Cake Topper',parentSku:'CN0790',shopeeProductId:'23912013802',category:'CUSTOM NAME - Topper',status:'NORMAL - active',imageUrl:'https://cf.shopee.com.my/file/sg-11134201-23010-sbuzbr8nrrlv94',shopeeUrl:'https://shopee.com.my/product/188218638/23912013802/',hasDimension:true,searchText:'j&t jnt express custom name cake topper cn0790 23912013802',sourceUpdatedAt:1772438653993,source:'fallback'}
];

function text(value:unknown){return value==null?'':String(value).trim()}
function normalize(value:string){return value.toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim()}
function compact(value:string){return normalize(value).replace(/\s+/g,'')}
function slugify(value:string){return normalize(value).replace(/\s+/g,'-').replace(/^-+|-+$/g,'').slice(0,150)}
function customField(task:any,name:string){return (Array.isArray(task.custom_fields)?task.custom_fields:[]).find((field:any)=>text(field.name).toLowerCase()===name.toLowerCase())}
function optionValue(field:any){if(!field||field.value==null)return '';const options=Array.isArray(field.type_config?.options)?field.type_config.options:[];const match=options.find((option:any)=>text(option.id)===text(field.value)||Number(option.orderindex)===Number(field.value));return text(match?.name||field.value)}
function shortTitle(title:string,category:string){let value=title.replace(/\[(?:CUSTOM NAME|CUSTOM GAMBAR|CUSTOM NAME\]\[CUSTOM GAMBAR)[^\]]*\]/gi,' ').replace(/\bREADY STOCK\b/gi,' ').replace(/\bHappy Birthday Cake Topper\b/gi,' ').replace(/\bDecoration Set Party Accessories(?: Banner)? Hiasan Kek(?: Design)?\b/gi,' ').replace(/\s+/g,' ').trim();if(!value)value=title;if(/custom name/i.test(category)&&!/custom name/i.test(value))value+=' Custom Name';if(!/topper|edible|wafer|acrylic/i.test(value))value+=' Cake Topper';return value.slice(0,90)}
function mapTask(task:any):CatalogProduct|null{const title=text(customField(task,'title product')?.value||task.name);if(!title)return null;const categoryField=customField(task,'categories ' )||customField(task,'categories');const statusField=customField(task,'status product');const category=optionValue(categoryField)||'Other';const sourceStatus=optionValue(statusField);if(sourceStatus&&!/normal|active/i.test(sourceStatus))return null;const parentSku=text(customField(task,'Parent SKU')?.value);const shopeeProductId=text(customField(task,'Product ID')?.value);const cover=text(customField(task,'Cover image')?.value);const link=text(customField(task,'link product')?.value)||(shopeeProductId?`https://shopee.com.my/product/${SHOP_ID}/${shopeeProductId}/`:'');const attachment=(Array.isArray(task.attachments)?task.attachments:[]).find((item:any)=>String(item.mimetype||'').startsWith('image/'));const image=text(attachment?.url||attachment?.thumbnail_large||cover)||GENERIC_IMAGE;const displayTitle=shortTitle(title,category);const taskId=text(task.id);const slug=slugify(`${displayTitle}-${parentSku||taskId}`);const updated=Number(task.date_updated||Date.now());const aliases=title.replace(/spider[-\s]?man/gi,'spiderman spider man spider-man');return {id:taskId,clickupTaskId:taskId,slug,title,displayTitle,parentSku,shopeeProductId,category,status:sourceStatus||'NORMAL - active',imageUrl:image,shopeeUrl:link,hasDimension:Boolean(customField(task,'ada demention')?.value),searchText:normalize([aliases,displayTitle,parentSku,shopeeProductId,category].join(' ')),sourceUpdatedAt:updated,source:'clickup'}}
async function listAll<T>(table:string){const all:Array<T&{id:string}>=[];let nextToken:string|undefined;do{const page=await db.list<T>(table,{limit:1000,nextToken});all.push(...page.items as Array<T&{id:string}>);nextToken=page.nextToken}while(nextToken);return all}
async function replaceCatalog(products:CatalogProduct[],source:string,lastError=''){const current=await listAll<CatalogProduct>(CACHE_TABLE);for(let i=0;i<current.length;i+=250)await db.delete(CACHE_TABLE,current.slice(i,i+250).map(item=>item.id));for(let i=0;i<products.length;i+=200){const ids=await db.add(CACHE_TABLE,products.slice(i,i+200));if(ids.some(id=>!id))throw new Error('catalog cache write failed')}const metas=await listAll<MetaRecord>(META_TABLE);if(metas.length)await db.delete(META_TABLE,metas.map(item=>item.id));await db.add(META_TABLE,[{key:'clickup',source,count:products.length,updatedAt:Date.now(),lastAttemptAt:Date.now(),lastError}]);return {ok:true,source,count:products.length}}
async function fetchClickUpProducts(){const names=await secrets.listSecretNames();if(!names.includes('CLICKUP_API_TOKEN'))throw new Error('CLICKUP_API_TOKEN is not configured');const token=await secrets.readSecret('CLICKUP_API_TOKEN');const tasks:any[]=[];for(let page=0;page<40;page++){const response=await fetch(`https://api.clickup.com/api/v2/list/${LIST_ID}/task?archived=false&include_closed=true&subtasks=true&page=${page}`,{headers:{Authorization:token}});if(!response.ok)throw new Error(`ClickUp API ${response.status}`);const payload=await response.json() as {tasks?:any[];last_page?:boolean};const batch=Array.isArray(payload.tasks)?payload.tasks:[];tasks.push(...batch);if(payload.last_page||batch.length<100)break}const mapped=tasks.map(mapTask).filter((item):item is CatalogProduct=>Boolean(item));const unique=new Map<string,CatalogProduct>();mapped.forEach(item=>unique.set(item.clickupTaskId,item));return Array.from(unique.values())}
export async function syncProductCatalog(){try{const products=await fetchClickUpProducts();if(!products.length)throw new Error('No active ClickUp products returned');return await replaceCatalog(products,'clickup')}catch(cause){const existing=await listAll<CatalogProduct>(CACHE_TABLE);const message=cause instanceof Error?cause.message:'catalog sync failed';if(existing.length)return {ok:false,source:'stale-cache',count:existing.length,error:message};return await replaceCatalog(seed,'fallback',message)}}
async function ensureCatalog(){const products=await listAll<CatalogProduct>(CACHE_TABLE);const metas=await listAll<MetaRecord>(META_TABLE);const meta:MetaRecord|undefined=metas[0];if(products.length)return {products,meta};await replaceCatalog(seed,'fallback');const fallbackMeta:MetaRecord={key:'clickup',source:'fallback',count:seed.length,updatedAt:Date.now(),lastAttemptAt:0,lastError:''};return {products:await listAll<CatalogProduct>(CACHE_TABLE),meta:fallbackMeta}}
function score(product:CatalogProduct,q:string){if(!q)return 1;const n=normalize(q),c=compact(q),title=normalize(product.displayTitle),all=normalize(product.searchText);let value=0;if(title===n)value+=100;if(title.startsWith(n))value+=50;if(title.includes(n))value+=30;if(all.includes(n))value+=20;if(compact(all).includes(c))value+=25;if(normalize(product.parentSku)===n||normalize(product.shopeeProductId)===n)value+=80;return value}

export const productCatalogRoutes={
 'GET /api/catalog/search':[async({query}:{query:Record<string,string>})=>{const {products,meta}=await ensureCatalog();const q=text(query.q);const page=Math.max(1,Number(query.page)||1);const limit=Math.min(48,Math.max(1,Number(query.limit)||24));const ranked=products.map(product=>({product,score:score(product,q)})).filter(item=>!q||item.score>0).sort((a,b)=>b.score-a.score||b.product.sourceUpdatedAt-a.product.sourceUpdatedAt);const start=(page-1)*limit;return json({ok:true,q,page,limit,total:ranked.length,items:ranked.slice(start,start+limit).map(item=>item.product),source:meta?.source||'cache',updatedAt:meta?.updatedAt||0})}],
 'GET /api/catalog/products/:slug':[async({params}:{params:Record<string,string>})=>{const {products}=await ensureCatalog();const product=products.find(item=>item.slug===params.slug);return product?json({ok:true,product}):error('Product not found',404)}],
 'GET /api/catalog/status':[async()=>{const {products,meta}=await ensureCatalog();return json({ok:true,count:products.length,source:meta?.source||'cache',updatedAt:meta?.updatedAt||0,lastError:meta?.lastError||''})}],
 'POST /api/catalog/sync':[async()=>{const metas=await listAll<MetaRecord>(META_TABLE);const lastAttempt=Number(metas[0]?.lastAttemptAt||0);if(lastAttempt&&Date.now()-lastAttempt<10*60*1000)return error('Catalogue sync was requested recently',429);return json(await syncProductCatalog())}]
};
