import { db, ws, json, error } from '@appdeploy/sdk';

type SubscriptionRecord={id:string;entity_type:string;entity_id:string;connection_id:string;created_at:number};
async function listSubscriptions(){const {items}=await db.list<SubscriptionRecord>('entity_subscriptions');return items}
export async function removeSubscriptionsByConnection(connectionId:string){const items=await listSubscriptions(),ids=items.filter(x=>x.connection_id===connectionId).map(x=>x.id);if(ids.length)await db.delete('entity_subscriptions',ids)}
export async function notifySubscribers(entityType:string,entityId:string,data:unknown){const items=await listSubscriptions(),targets=Array.from(new Set(items.filter(x=>x.entity_type===entityType&&x.entity_id===entityId).map(x=>x.connection_id)));if(targets.length)await ws.send(targets,{v:1,type:'entity.update',payload:{entity_type:entityType,entity_id:entityId,data}})}
export const realtimeSubscriptionRoutes={
 'POST /api/subscriptions':[async({body}:{body:unknown})=>{const b=(body||{}) as {entity_type?:string;entity_id?:string;connection_id?:string};if(!b.entity_type||!b.entity_id||!b.connection_id)return error('entity_type, entity_id and connection_id are required',400);const items=await listSubscriptions();if(!items.some(x=>x.entity_type===b.entity_type&&x.entity_id===b.entity_id&&x.connection_id===b.connection_id))await db.add('entity_subscriptions',[{entity_type:b.entity_type,entity_id:b.entity_id,connection_id:b.connection_id,created_at:Date.now()}]);return json({ok:true})}],
 'POST /api/subscriptions/remove':[async({body}:{body:unknown})=>{const b=(body||{}) as {entity_type?:string;entity_id?:string;connection_id?:string};if(!b.entity_type||!b.entity_id||!b.connection_id)return error('entity_type, entity_id and connection_id are required',400);const items=await listSubscriptions(),ids=items.filter(x=>x.entity_type===b.entity_type&&x.entity_id===b.entity_id&&x.connection_id===b.connection_id).map(x=>x.id);if(ids.length)await db.delete('entity_subscriptions',ids);return json({ok:true})}],
};
