import {useEffect,useRef,useState} from 'react';
import {detailRequest,detailDate,detailStage,type DetailData} from '../lib/orderDetails';
import './OrderDetailSession.css';
const rules=[['review','Perlu semak keperluan'],['standard','Standard / tiada customization'],['name','Nama'],['name_age','Nama + umur'],['wording','Wording'],['image','Gambar'],['image_wording','Gambar + wording']];
const labels:DetailData={name:'Nama',age:'Umur',wording:'Wording',image:'URL gambar dipilih'};
function local(v:unknown){if(!v)return '';const date=new Date(String(v));return Number.isNaN(date.getTime())?'':new Date(date.getTime()+8*3600000).toISOString().slice(0,16);}
const iso=(v:string)=>v?new Date(v+'+08:00').toISOString():null;
const safe=(v:unknown)=>/^https:\/\//i.test(String(v||''));
export function DetailSummary({data,onOpen}:{data?:DetailData;onOpen:()=>void}){
 return <div className="ods-summary"><span className={'ods-status '+(data?.status||'review')}>{data?.label||'Belum disemak'}</span>{data?<><small>{data.complete}/{data.total} item lengkap</small>{data.missing?.length?<small>{data.missing.join(', ')}</small>:null}{data.items?.map((i:DetailData)=>Object.values(i.values||{}).filter(Boolean).length?<small key={i.id}>{Object.entries(i.values).map(([k,v])=>`${labels[k]}: ${v}`).join(' · ')}</small>:null)}</>:null}<button type="button" onClick={onOpen}>Detail / session</button></div>;
}
export default function OrderDetailSession({rowKey,onClose,onSaved,onOpenChat}:{rowKey:string;onClose:()=>void;onSaved:()=>void;onOpenChat?:(id:string)=>void}){
 const [row,setRow]=useState<DetailData|null>(null),[form,setForm]=useState<DetailData>({items:{},bindings:[],deadline:''}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[notice,setNotice]=useState('');
 const retry=useRef<DetailData|null>(null),mounted=useRef(true),dirty=useRef(false);
 const load=async()=>{setLoading(true);setError('');try{const r=await detailRequest({action:'order_details',keys:[rowKey]});if(!mounted.current)return;const x=r.rows[0];if(!x)throw Error('Order tidak ditemui');x.can_manage=r.capabilities.can_manage;setRow(x);const d=x.detail_collection,s=x.state.data.detail_check||{};setForm({signature:d.signature,items:Object.fromEntries(d.items.map((i:DetailData)=>[i.id,{rule:i.rule,values:i.values,same_design:i.same_design}])),bindings:s.bindings||[],deadline:local(d.deadline)});retry.current=null;dirty.current=false;}catch(e){if(mounted.current)setError(e instanceof Error?e.message:String(e));}finally{if(mounted.current)setLoading(false);}};
 useEffect(()=>{mounted.current=true;void load();return()=>{mounted.current=false};},[rowKey]);
 useEffect(()=>{const listener=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!busy&&(!dirty.current||window.confirm('Buang perubahan yang belum disimpan?')))onClose();};window.addEventListener('keydown',listener);return()=>window.removeEventListener('keydown',listener);},[busy,onClose]);
 function change(fn:(f:DetailData)=>DetailData){dirty.current=true;retry.current=null;setForm(fn);}
 async function save(mark=false){if(!row)return;setBusy(true);setError('');const request=retry.current||{action:'order_detail_save',row_key:rowKey,expected_version:row.state.version,source_fingerprint:row.source_fingerprint,request_id:crypto.randomUUID(),detail_check:{...form,deadline:iso(form.deadline),mark_followup:mark}};retry.current=request;
  try{await detailRequest(request);retry.current=null;setNotice(mark?'Follow-up luar sistem direkodkan.':'Detail dan session disimpan.');onSaved();await load();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}
 }
 const d=row?.detail_collection,disabled=busy||!row?.can_manage||d?.locked;
 const message=row?`Hi, untuk order ${row.reference}, sila berikan ${d.missing?.join(', ')||'detail customization untuk item yang ditempah'}.${form.deadline?` Mohon beri sebelum ${detailDate(iso(form.deadline))}.`:''} Terima kasih.`:'';
 return <div className="ods-backdrop"><section className="ods-panel" role="dialog" aria-modal="true" aria-labelledby="ods-title"><header><div><h3 id="ods-title">Detail order · {row?.reference||'Memuatkan…'}</h3><small>Detail setiap item, bukti customer dan session order</small></div><button type="button" disabled={busy} aria-label="Tutup detail order" onClick={()=>{if(!dirty.current||window.confirm('Buang perubahan yang belum disimpan?'))onClose();}}>×</button></header>
 {loading?<p role="status">Menyemak order, chat dan ClickUp…</p>:null}{error?<p className="ods-error" role="alert">{error}</p>:null}{notice?<p role="status">{notice}</p>:null}
 {row&&d?<><div className="ods-links"><span className={'ods-status '+d.status}>{d.label} · {d.complete}/{d.total}</span><span>iCetak: {d.internal_order_id?'Linked':'Belum linked'}</span><span>ClickUp: {d.clickup_linked?'Linked':'Belum ada task'}</span><span>Session: {d.session_linked?'Linked':'Perlu padankan'}</span></div>
 {d.locked?<p className="ods-warning">Production sudah bermula atau order ditutup. Balasan baru perlu disemak melalui task asal.</p>:null}{d.warnings.map((w:string)=><p key={w} className="ods-warning">{w}</p>)}
 <div className="ods-scroll"><h4>Item & detail untuk design</h4>{d.items.map((i:DetailData,n:number)=><article className="ods-item" key={i.id}><strong>{n+1}. {i.quantity||1}× {i.title}</strong><small>{i.sku||'SKU belum tersedia'} · {i.size||''}</small><label>Detail diperlukan<select disabled={disabled||i.locked} value={form.items[i.id]?.rule||'review'} onChange={e=>change(f=>({...f,items:{...f.items,[i.id]:{...f.items[i.id],rule:e.target.value}}}))}>{rules.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><div className="ods-fields">{Object.entries(labels).map(([key,label])=><label key={key}>{String(label)}<input aria-label={String(label)} disabled={disabled||i.locked} value={form.items[i.id]?.values?.[key]||''} maxLength={2000} onChange={e=>change(f=>({...f,items:{...f.items,[i.id]:{...f.items[i.id],values:{...f.items[i.id].values,[key]:e.target.value}}}}))}/>{i.sources[key]?<small>{i.sources[key].source}</small>:null}{i.candidates[key]?.length?<small className="ods-warning">Nilai lain: {i.candidates[key].map((x:DetailData)=>x.value).join(' / ')}</small>:null}</label>)}</div>{Number(i.quantity)>1?<label className="ods-check"><input type="checkbox" disabled={disabled||i.locked} checked={!!form.items[i.id]?.same_design} onChange={e=>change(f=>({...f,items:{...f.items,[i.id]:{...f.items[i.id],same_design:e.target.checked}}}))}/> Semua unit item ini guna design/detail yang sama</label>:null}</article>)}
 {d.source_note?<div className="ods-note"><strong>Note to seller / nota order</strong><p>{d.source_note}</p></div>:null}
 <h4>Session chat untuk order ini</h4>{d.bindings.map((b:DetailData)=><div key={b.id} className="ods-session"><strong>{b.source==='admin_bound'?'Dipadankan admin':'Session Shopee sedia ada'}</strong><small>{detailDate(b.start_at)} → {b.end_at?detailDate(b.end_at):'Masih terbuka'} · {b.usable?'Boleh guna detail':'Perlu semakan padanan'}</small>{onOpenChat?<button type="button" onClick={()=>onOpenChat(b.id)}>Buka chat</button>:null}</div>)}
 <small>Tambah chat WhatsApp/Shopee customer yang sama jika detail diberi melalui channel lain. Pilih waktu mula supaya detail order lama tidak digunakan.</small>
 {row.detail_candidates.map((c:DetailData)=>{const binding=form.bindings.find((b:DetailData)=>b.conversation_id===c.id);return <div className="ods-bind" key={c.id}><label className="ods-check"><input type="checkbox" disabled={disabled||c.ambiguous} checked={!!binding} onChange={e=>change(f=>({...f,bindings:e.target.checked?[...f.bindings,{conversation_id:c.id,start_at:row.created_at||new Date().toISOString(),end_at:null}]:f.bindings.filter((b:DetailData)=>b.conversation_id!==c.id)}))}/>{c.channel} · {c.name}</label>{binding?<div className="ods-fields"><label>Mula (MYT)<input type="datetime-local" disabled={disabled} value={local(binding.start_at)} onChange={e=>change(f=>({...f,bindings:f.bindings.map((b:DetailData)=>b.conversation_id===c.id?{...b,start_at:iso(e.target.value)}:b)}))}/></label><label>Akhir (MYT, pilihan)<input type="datetime-local" disabled={disabled} value={local(binding.end_at)} onChange={e=>change(f=>({...f,bindings:f.bindings.map((b:DetailData)=>b.conversation_id===c.id?{...b,end_at:iso(e.target.value)}:b)}))}/></label></div>:null}</div>;})}
 {d.evidence.length?<><h4>Detail daripada balasan customer</h4>{d.evidence.map((e:DetailData)=><blockquote key={e.id}>{e.text}<small>{detailDate(e.at)}</small></blockquote>)}</>:null}
 {d.media.length?<><h4>Gambar dalam session · pilih untuk item</h4><div className="ods-media">{d.media.filter((m:DetailData)=>safe(m.url)).map((m:DetailData)=><a key={m.id} href={m.url} target="_blank" rel="noopener noreferrer"><img src={m.url} alt={m.caption||'Gambar customer'}/><small>{m.caption||detailDate(m.at)}</small></a>)}</div></>:null}
 <h4>Follow-up & deadline detail</h4><p>{detailStage[d.stage]}{d.followup.sent_at?` · Follow-up terakhir ${detailDate(d.followup.sent_at)} (ditanda manual)`:''}</p><label>Waktu akhir beri detail (MYT)<input type="datetime-local" disabled={busy||!row.can_manage} value={form.deadline} onChange={e=>change(f=>({...f,deadline:e.target.value}))}/></label><small>Tetapkan sebelum design/production dan pickup. Due platform {detailDate(row.platform_deadline)}.</small><div className="ods-note"><p>{message}</p><button type="button" onClick={async()=>{try{await navigator.clipboard.writeText(message);setNotice('Mesej disalin.');}catch{setError('Salinan gagal; pilih teks mesej untuk salin.');}}}>Salin permintaan detail</button><button type="button" disabled={busy||!row.can_manage||d.status==='complete'||d.locked} onClick={()=>void save(true)}>Saya sudah follow-up</button></div><small>API penghantaran Shopee belum disambungkan. Butang ini merekod tindakan manual.</small>
 <h4>ClickUp / production</h4>{row.production_tasks.map((t:DetailData)=><div className="ods-session" key={t.id}>{safe(t.url)?<a href={t.url} target="_blank" rel="noopener noreferrer">{t.title||t.id}</a>:<strong>{t.title||t.id}</strong>}<small>{t.status} · {t.review_status||'Tiada review'} · Sync {detailDate(t.source_updated_at)}</small><small>Customize Name: {t.detail?.customize_name||'Belum ada'} · Confirmed: {t.detail?.confirmed===true?'Ya':'Belum'}</small></div>)}</div>
 <footer><button type="button" disabled={busy} onClick={()=>void load()}>Semak semula</button><button type="button" className="ods-save" disabled={busy||!row.can_manage||d.locked} onClick={()=>void save()}>{busy?'Menyimpan…':retry.current?'Cuba simpan semula':'Simpan & semak detail'}</button></footer></>:null}</section></div>;
}
