import {useEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {extraCostLabels,materialCategories,profitDate,profitMoney,profitRequest,profitStateLabel} from '../lib/orderProfit';
import type {CostMode,ExtraCostKey,MaterialCategory,MaterialLine,OrderProfitRow} from '../lib/orderProfit';
import '../pages/OrderProfit.css';
type EditableLine=MaterialLine&{input:string};
type EditableExtra={input:string;mode:CostMode};
type Props={orderId:string;canManage:boolean;onClose:()=>void;onSaved?:(r:OrderProfitRow)=>void};
export default function OrderProfitDetail({orderId,canManage,onClose,onSaved}:Props){
  const [row,setRow]=useState<OrderProfitRow|null>(null),[lines,setLines]=useState<EditableLine[]>([]),[extras,setExtras]=useState<Record<ExtraCostKey,EditableExtra>|null>(null);
  const [minutes,setMinutes]=useState(''),[note,setNote]=useState(''),[reviewed,setReviewed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const dialog=useRef<HTMLDivElement>(null),closeRef=useRef(onClose);closeRef.current=onClose;
  const install=(next:OrderProfitRow)=>{setRow(next);setLines(next.material_lines.map(l=>({...l,input:l.amount==null?'':l.amount.toFixed(2)})));setExtras(Object.fromEntries(Object.entries(next.extra_costs).map(([k,v])=>[k,{input:v.amount.toFixed(2),mode:v.mode}])) as Record<ExtraCostKey,EditableExtra>);setMinutes(next.work_minutes==null?'':String(next.work_minutes));setNote(next.note);setReviewed(next.reviewed&&!next.detail_changed);};
  useEffect(()=>{let active=true;setRow(null);setError('');void profitRequest<OrderProfitRow>({action:'order_profit_detail',order_id:orderId}).then(r=>{if(active)install(r)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[orderId]);
  useEffect(()=>{
    const prev=document.activeElement as HTMLElement|null,overflow=document.body.style.overflow;document.body.style.overflow='hidden';dialog.current?.focus();
    const keydown=(e:KeyboardEvent)=>{if(e.key==='Escape')closeRef.current();if(e.key!=='Tab')return;const els=[...(dialog.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled)')||[])],first=els[0],last=els.at(-1);if(e.shiftKey&&(document.activeElement===first||document.activeElement===dialog.current)){e.preventDefault();last?.focus()}else if(!e.shiftKey&&(document.activeElement===last||document.activeElement===dialog.current)){e.preventDefault();first?.focus()}};
    document.addEventListener('keydown',keydown);return()=>{document.body.style.overflow=overflow;document.removeEventListener('keydown',keydown);prev?.focus()};
  },[]);
  const number=(v:string,nullable=false)=>{if(nullable&&v.trim()==='')return null;if(v.trim()===''||!Number.isFinite(Number(v))||Number(v)<0||Number(v)>1000000)throw new Error('Isi kos yang sah, minimum 0.');return Number(v)};
  const save=async()=>{if(!row||!extras)return;setBusy(true);setError('');setNotice('');try{
    const r=await profitRequest<OrderProfitRow>({action:'order_costs_save',order_id:orderId,version:row.cost_version,lines:lines.map(l=>({line_no:l.line_no,amount:number(l.input,true),category:l.category,mode:l.mode})),extras:Object.fromEntries(Object.entries(extras).map(([k,v])=>[k,{amount:number(v.input),mode:v.mode}])),work_minutes:number(minutes,true),reviewed,note});install(r);setNotice('Kos order disimpan.');onSaved?.(r);
  }catch(e){setError(e instanceof Error?e.message:'Kos gagal disimpan')}finally{setBusy(false)}};
  const updateLine=(i:number,patch:Partial<EditableLine>)=>{setReviewed(false);setNotice('');setLines(prev=>prev.map((l,j)=>i===j?{...l,...patch}:l))};
  const updateExtra=(k:ExtraCostKey,patch:Partial<EditableExtra>)=>{setReviewed(false);setNotice('');setExtras(prev=>prev?{...prev,[k]:{...prev[k],...patch}}:prev)};
  const allActual=lines.length>0&&lines.every(l=>l.mode==='actual'&&l.input.trim()!=='')&&extras&&Object.values(extras).every(v=>v.mode==='actual');
  const valid=lines.length>0&&lines.every(l=>l.input.trim()!==''&&Number.isFinite(Number(l.input)))&&extras&&Object.values(extras).every(v=>v.input.trim()!==''&&Number.isFinite(Number(v.input)));
  const costs=valid&&extras?lines.reduce((s,l)=>s+Number(l.input),0)+Object.values(extras).reduce((s,v)=>s+Number(v.input),0):null;
  const profit=row?.nett!=null&&costs!=null&&row.profit_state!=='lifecycle_review'?row.nett-costs:null;
  return createPortal(<div className="op-backdrop"><div className="op-dialog" role="dialog" aria-modal="true" aria-labelledby="op-detail-title" tabIndex={-1} ref={dialog}>
    <header className="op-dialog-head"><div><p className="op-eyebrow">FINANCE ORDER</p><h2 id="op-detail-title">{row?.order_sn||'Memuatkan order…'}</h2><p>{row?`@${row.buyer||'—'} · ${row.status.replaceAll('_',' ')} · ${profitDate(row.placed_at)}`:'Nett Shopee dan kos setiap order'}</p></div><button className="btn btn-outline" onClick={onClose} aria-label="Tutup detail finance">Tutup ×</button></header>
    <div className="op-dialog-body">{error&&<div className="op-alert error" role="alert">{error}</div>}{notice&&<div className="op-alert success" role="status">{notice}</div>}{!row&&!error&&<p className="op-empty">Memuatkan detail finance…</p>}
    {row&&<>
      <div className="op-detail-metrics"><div><span>Nett Shopee</span><strong>{profitMoney(row.nett,row.currency)}</strong><small>{row.income_state==='released'?`Dilepaskan ${profitDate(row.released_at)}`:row.income_state==='escrow'?'Escrow · belum release':'Data belum diterima'}</small></div><div><span>Kos dalam borang</span><strong>{profitMoney(costs,row.currency)}</strong><small>Bahan + semua kos tambahan</small></div><div><span>Baki selepas kos</span><strong className={profit!=null&&profit<0?'op-negative':'op-positive'}>{profitMoney(profit,row.currency)}</strong><small>Pratonton borang · sebelum overhead</small></div></div>
      <div className="op-explanation">Nett sudah mengambil kira potongan platform. Isi hanya kos tambahan yang belum dipotong Shopee. Baki ini ialah sumbangan order sebelum sewa, utiliti dan overhead perniagaan.</div>
      {row.detail_changed&&<div className="op-alert" role="alert">Item berubah selepas kos disimpan. Borang menunjukkan item terkini dengan anggaran asal; semak semua kos dan simpan semula.</div>}
      {row.profit_state==='lifecycle_review'&&<div className="op-alert">Order batal / refund perlu semakan. Untung belum dimuktamadkan.</div>}
      <details className="op-breakdown"><summary>Detail duit dan potongan Shopee</summary><dl>{[['Customer bayar',row.buyer_paid],['Nilai barang (asas margin)',row.goods_value],['Shipping dari Shopee',row.shipping_fee],['Commission',row.commission_fee],['Service fee',row.service_fee],['Transaction fee',row.transaction_fee],['Other fees',row.other_fees],['Escrow',row.escrow_amount],['Released',row.released_amount]].map(([label,value])=><div key={String(label)}><dt>{label}</dt><dd>{profitMoney(value as number|null,row.currency)}</dd></div>)}</dl><small>Finance terakhir diterima: {profitDate(row.enriched_at)}. Fees ini untuk rujukan; tidak ditolak sekali lagi.</small></details>
      <section className="op-section"><div className="op-section-head"><h3>Modal raw material</h3><span className="op-muted">Setting versi {row.settings_version} · kos bagi kuantiti penuh item</span></div>{!lines.length&&<div className="op-alert">Item belum diterima daripada Shopee. Kos dan untung belum boleh disahkan.</div>}
        <div className="op-material-lines">{lines.map((l,i)=><div className="op-material-line" key={l.line_no}><div className="op-item-copy"><b>{l.quantity}× {l.title||l.sku}</b><small>{l.parent_sku}{l.sku!==l.parent_sku?` · ${l.sku}`:''}{l.variation?` · ${l.variation}`:''}</small><small>Nilai barang {profitMoney(l.goods_value,row.currency)} · {l.basis==='sku_unit'?`${profitMoney(l.unit_cost,row.currency)} / unit`:l.rate!=null?`${l.rate}% anggaran asal`:'Kategori belum dipetakan'}</small></div>
          <label>Kategori<select aria-label={`Kategori item ${i+1}`} disabled={!canManage||busy} value={l.category||''} onChange={e=>updateLine(i,{category:(e.target.value||null) as MaterialCategory|null})}><option value="">Belum dipetakan</option>{Object.entries(materialCategories).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>
          <label>Kos bahan ({row.currency})<input aria-label={`Kos bahan item ${i+1}`} type="number" min="0" step="0.01" value={l.input} placeholder="Belum diketahui" disabled={!canManage||busy} onChange={e=>updateLine(i,{input:e.target.value,mode:'actual'})}/></label>
          <label>Jenis kos<select aria-label={`Jenis kos item ${i+1}`} value={l.mode} disabled={!canManage||busy} onChange={e=>updateLine(i,{mode:e.target.value as 'actual'|'estimated'})}><option value="estimated">Anggaran</option><option value="actual">Sebenar</option></select></label>
        </div>)}</div>
      </section>
      <section className="op-section"><h3>Kos tambahan order</h3><p className="op-muted">Nilai 0 bermaksud tiada kos direkod. Sahkan 0 sebagai sebenar selepas semakan. Ads agihan kekal anggaran.</p><div className="op-extras">{extras&&(Object.entries(extraCostLabels) as [ExtraCostKey,string][]).map(([k,label])=><div key={k}><label>{label}<input aria-label={label} type="number" min="0" step="0.01" value={extras[k].input} disabled={!canManage||busy} onChange={e=>updateExtra(k,{input:e.target.value})}/></label><label className="op-mode-label">Jenis<select aria-label={`Jenis ${label}`} value={extras[k].mode} disabled={!canManage||busy} onChange={e=>updateExtra(k,{mode:e.target.value as CostMode})}><option value="estimated">Anggaran</option><option value="actual">Sebenar</option><option value="allocated">Agihan / anggaran</option></select></label></div>)}</div></section>
      <section className="op-section op-notes"><label>Masa kerja (minit, pilihan)<input type="number" min="0" max="100000" step="0.1" value={minutes} disabled={!canManage||busy} onChange={e=>setMinutes(e.target.value)}/></label><label>Catatan kos<textarea maxLength={2000} rows={2} value={note} disabled={!canManage||busy} placeholder="Contoh: ads diagih ikut jualan bulan ini; affiliate sudah dipotong Shopee." onChange={e=>setNote(e.target.value)}/></label></section>
      <label className="op-review"><input type="checkbox" checked={reviewed} disabled={!canManage||busy||!allActual} onChange={e=>setReviewed(e.target.checked)}/><span>Saya telah semak semua kos order sebagai sebenar.<small>Aktif selepas semua kos bahan dan tambahan ditanda Sebenar. Untung sebenar juga memerlukan duit sudah release.</small></span></label>
    </>}</div><footer className="op-dialog-footer"><span className="op-muted">{row?`${profitStateLabel(row)} · kos versi ${row.cost_version} · ${row.cost_updated_at?profitDate(row.cost_updated_at):'Anggaran awal'}`:''}</span><button className="btn btn-primary" disabled={!canManage||busy||!row||!lines.length} onClick={()=>void save()}>{busy?'Menyimpan…':'Simpan kos order'}</button></footer>
  </div></div>,document.body);
}
