import {useRef,useState} from 'react';
import {profitMoney,profitRequest} from '../lib/orderProfit';
import type {FinanceOptions} from '../lib/orderProfit';
import {parseFinanceExcel} from '../lib/financeExcel';
import type {ImportOrder} from '../lib/financeExcel';
type Preview={hash:string;valid:boolean;committed:boolean;inserted:number;reference_only:number;duplicates:number;rows:{order_sn:string;state:string;nett:number|null}[]};
export default function OrderFinanceImport({options,onImported}:{options:FinanceOptions|null;onImported:()=>void}){
 const [orders,setOrders]=useState<ImportOrder[]>([]),[shop,setShop]=useState(''),[currency,setCurrency]=useState('MYR'),[preview,setPreview]=useState<Preview|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[filename,setFilename]=useState('');const gen=useRef(0);
 const invalidate=()=>{gen.current++;setPreview(null);setError('')};
 const fileChange=async(file:File|undefined)=>{invalidate();setOrders([]);if(!file)return;setFilename(file.name);setBusy(true);const token=gen.current;try{const rows=await parseFinanceExcel(file);if(token===gen.current)setOrders(rows)}catch(e){if(token===gen.current)setError((e as Error).message)}finally{if(token===gen.current)setBusy(false)}};
 const submit=async(commit:boolean)=>{const token=gen.current;setBusy(true);setError('');try{const p=await profitRequest<Preview>({action:'order_finance_import',orders,shop_id:shop,currency,commit,hash:preview?.hash});if(token===gen.current){setPreview(p);if(commit)onImported()}}catch(e){if(token===gen.current){setError((e as Error).message);setPreview(null)}}finally{if(token===gen.current)setBusy(false)}};
 return <details className="op-breakdown op-import"><summary>Import laporan Excel Shopee</summary><p>Satu order dengan banyak item digabung sekali. Fees berulang mesti sama. Excel disimpan sebagai sejarah rujukan jika API sudah ada. Laporan ini tidak membuktikan duit sudah release.</p><div className="op-filters"><label>Shop<select aria-label="Shop" disabled={busy} value={shop} onChange={e=>{invalidate();setShop(e.target.value)}}><option value="">Pilih shop</option>{options?.shops.map(s=><option key={`${s.shop_id}-${s.currency}`} value={s.shop_id}>{s.shop_id} · {s.currency} · {s.orders} order</option>)}</select></label><label>Currency<select aria-label="Currency" disabled={busy} value={currency} onChange={e=>{invalidate();setCurrency(e.target.value)}}>{[...new Set(['MYR',...(options?.shops.map(s=>s.currency)||[])])].map(c=><option key={c}>{c}</option>)}</select></label><label>Fail .xlsx<input disabled={busy} type="file" accept=".xlsx" onChange={e=>void fileChange(e.target.files?.[0])}/></label></div>
 {filename&&<p>{filename} · {orders.length} order</p>}{error&&<p role="alert" className="op-negative">{error}</p>}<div className="op-actions"><button className="btn btn-outline" disabled={busy||!orders.length||!shop} onClick={()=>void submit(false)}>{busy?'Memproses…':'Preview import'}</button>{preview&&!preview.committed&&<button className="btn btn-primary" disabled={busy||!preview.valid} onClick={()=>void submit(true)}>Sahkan import {orders.length} order</button>}</div>
 {preview&&<><p role="status">{preview.committed?`${preview.inserted} snapshot disimpan.`:preview.valid?'Preview sah. Semak angka sebelum sahkan.':'Ada baris tidak sah. Semak fail, shop dan currency.'} {preview.reference_only} rujukan sahaja · {preview.duplicates} duplicate</p><div className="op-table-wrap"><table className="op-table"><thead><tr><th>Order</th><th>Status import</th><th>Nett / anggaran</th></tr></thead><tbody>{preview.rows.map(r=><tr key={r.order_sn}><td>{r.order_sn}</td><td>{r.state}</td><td>{profitMoney(r.nett,currency)}</td></tr>)}</tbody></table></div></>}
 </details>;
}
