import {useState} from 'react';
import {financeReasonLabels,profitDate,profitMoney} from '../lib/orderProfit';
import type {OrderProfitRow} from '../lib/orderProfit';
const groups:Record<string,string>={goods:'Barang',discounts:'Diskaun & voucher',shipping:'Shipping',returns:'Return / refund',fees:'Fees & potongan',taxes:'Cukai',adjustments:'Pampasan / pelarasan',settlement:'Nett & escrow',buyer:'Bayaran pembeli (rujukan)',additional:'Medan tambahan'};
export default function OrderFinanceBreakdown({row}:{row:OrderProfitRow}){
 const [query,setQuery]=useState(''),[revision,setRevision]=useState<number|null>(null);const selected=row.finance_history?.find(h=>h.id===revision);const fields=Object.values(selected?.fields||row.finance_fields||{}),m=selected?.metrics||row.finance_metrics;
 const visible=fields.filter(f=>`${f.code} ${f.label} ${f.source_path}`.toLowerCase().includes(query.toLowerCase()));
 return <section className="op-section op-finance-full"><h3>Pecahan finance penuh</h3>{revision!=null&&<div className="op-alert">Melihat snapshot #{revision} · {profitDate(selected?.captured_at||null)} <button onClick={()=>setRevision(null)}>Kembali terkini</button></div>}<p className="op-muted">Sumber: {row.finance_source||'Belum diterima'} · {fields.length} medan · {profitDate(row.finance_updated_at||row.enriched_at)}. — bermaksud belum diterima; 0 ialah nilai sifar daripada sumber.</p>
 {m&&<><div className="op-finance-mini">{[['Baki shipping',m.shipping_net],['Return shipping',m.return_shipping],['Refund barang',m.refund_total],['Jumlah fees',m.fee_total],['Ads platform',m.platform_ads],['Affiliate AMS',m.affiliate]].map(([l,v])=><div key={String(l)}><span>{String(l)}</span><b>{profitMoney(v as number|null,row.currency)}</b></div>)}</div><div className="op-reasons">{m.reasons.map(r=><span key={r} className="op-badge">{financeReasonLabels[r]||r}</span>)}</div>
 <details className="op-breakdown"><summary>Semakan nett: {m.reconciliation==='matched'?'Sepadan':m.reconciliation==='report_estimate'?'Anggaran laporan':'Perlu semakan'}</summary><dl>{[['Nett sumber',m.provider_nett],['Nett daripada pecahan',m.reconstructed_nett],['Perbezaan',m.reconciliation_delta]].map(([l,v])=><div key={String(l)}><dt>{String(l)}</dt><dd>{profitMoney(v as number|null,row.currency)}</dd></div>)}</dl><p>Shipping menggunakan caj sebenar jika ada, kemudian anggaran. Shipping final dan credit card transaction ialah medan alternatif; ia tidak ditolak sekali lagi. Medan yang belum dipetakan kekal sebagai rujukan.</p>{m.issues.map((s,i)=><p className="op-negative" key={i}>{s}</p>)}</details></>}
 <label>Cari medan finance<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="shipping, voucher, reverse, tax…"/></label>
 {!fields.length?<p className="op-empty">Belum ada payload finance untuk order ini.</p>:Object.entries(groups).map(([group,label])=>{const list=visible.filter(f=>f.group===group);return list.length?<details className="op-breakdown" key={group} open={!!query||group==='shipping'||group==='returns'||group==='fees'}><summary>{label} · {list.length} medan</summary><dl>{list.map(f=><div key={f.code}><dt>{f.label}<small>{f.code} · {f.role==='seller'?'Dibiayai seller':f.role==='platform'?'Dibiayai platform / pihak luar':f.role==='alternative'?'Alternatif · tidak ditolak lagi':f.role==='unmapped'?'Belum dipetakan':f.role==='reference'?'Rujukan':f.role==='deduction'?'Potongan':'Bertanda mengikut sumber'}</small><small>{f.source_path}</small></dt><dd>{f.amount!=null?(f.code.match(/quantity|weight|tenure/)?String(f.amount):profitMoney(f.amount,row.currency)):f.value==null?'—':typeof f.value==='object'?<details><summary>Detail</summary><pre>{JSON.stringify(f.value,null,2)}</pre></details>:String(f.value)}</dd></div>)}</dl></details>:null})}
 {!!row.finance_history?.length&&<details className="op-breakdown"><summary>Sejarah finance · {row.finance_history.length} snapshot terkini</summary>{row.finance_history.map(h=><div key={h.id} className="op-history"><button className="op-detail-link" onClick={()=>setRevision(revision===h.id?null:h.id)}>{profitDate(h.captured_at)} · {h.source} · {profitMoney(h.metrics.provider_nett,row.currency)}</button>{revision===h.id&&<dl>{Object.entries(h.metrics).filter(([,v])=>typeof v==='number'||v===null).map(([k,v])=><div key={k}><dt>{k.replaceAll('_',' ')}</dt><dd>{k==='field_count'?String(v):profitMoney(v as number|null,row.currency)}</dd></div>)}</dl>}</div>)}</details>}
 </section>;
}
