import { useCallback, useEffect, useMemo, useState } from 'react';
import { supabase } from '../lib/supabase';
import { IconDownload, IconEdit, IconPhone, IconPlus, IconRefresh, IconSearch, IconStaff, IconX } from '../components/Icons';
import './Customers.css';

type CustomerRow = {
  id: string; name: string; sourceName: string; phone: string; email: string; status: string;
  stage: string; priority: string; owner: string; doNotContact: boolean; orderCount: number;
  lifetimeSpend: number; lastOrderAt: string | null; lastSeenAt: string | null; addressCount: number;
  openTasks: number; tags: string[]; channels: string[];
};
type ListResult = { ok: boolean; total: number; limit: number; offset: number; rows: CustomerRow[]; summary: { active: number; merged: number; withPhone: number; withEmail: number; openTasks: number } };
type Tag = { id: string; name: string; customerCount?: number };
type Address = { id: string; label: string; recipientName: string; phone: string; addressLine1: string; addressLine2: string; city: string; postcode: string; state: string; country: string; isDefault: boolean; isVerified: boolean; source: string; usageCount: number; lastUsedAt: string | null };
type Order = { kind: 'internal'|'marketplace'; id: string; dbId: string; orderToken?: string; source?: string; provider?: string; buyerUsername?: string; status: string; payment: string; total: number; delivery: string; dateNeed?: string|null; createdAt: string|null; tracking?: string };
type Note = { id: string; type: string; body: string; pinned: boolean; createdBy: string; createdAt: string; updatedAt: string };
type Task = { id: string; title: string; detail: string; dueAt: string|null; priority: string; status: string; assignedTo: string; createdBy: string; completedAt: string|null; createdAt: string };
type Identifier = { type: string; channel: string; value: string; scope: string; verified: boolean; source: string; lastSeenAt: string|null };
type Source = { system: string; table: string; recordId: string; lastSeenAt: string|null };
type Audit = { id: string; action: string; actor: string; before: Record<string,unknown>; after: Record<string,unknown>; metadata: Record<string,unknown>; createdAt: string };
type CustomerDetail = {
  ok: boolean;
  profile: { id:string; name:string; sourceName:string; adminNameOverride:string; phone:string; email:string; status:string; stage:string; priority:string; owner:string; doNotContact:boolean; firstSeenAt:string|null; lastSeenAt:string|null; createdAt:string|null; updatedAt:string|null };
  stats: { orderCount:number; internalOrders:number; marketplaceOrders:number; lifetimeSpend:number; internalSpend:number; marketplaceSpend:number; lastOrderAt:string|null; addressCount:number; openTasks:number };
  tags: Tag[]; addresses: Address[]; orders: Order[]; notes: Note[]; tasks: Task[]; identifiers: Identifier[]; sources: Source[];
  portalAccounts: Array<{id:string;name:string;phone:string;source:string;createdAt:string}>;
  marketplaceAccounts: Array<{id:string;provider:string;region:string;username:string;lastSeenAt:string|null}>;
  audit: Audit[]; duplicates: Array<{id:string;name:string;phone:string;email:string;status:string}>;
};
type Props = { permissions?: string[]; initialCustomer?: string; onOpenOrder: (orderNo:string)=>void };
type ProfileDraft = { name:string; phone:string; email:string; stage:string; priority:string; owner:string; doNotContact:boolean };
type AddressDraft = { id?:string; label:string; recipientName:string; phone:string; addressLine1:string; addressLine2:string; city:string; postcode:string; state:string; country:string; isDefault:boolean };
type TaskDraft = { id?:string; title:string; detail:string; dueAt:string; priority:string; status:string; assignedTo:string };

const money = (value:number) => `RM${Number(value||0).toLocaleString('en-MY',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const dateTime = (value?:string|null) => value ? new Date(value).toLocaleString('en-MY',{dateStyle:'medium',timeStyle:'short'}) : '—';
const shortDate = (value?:string|null) => value ? new Date(value).toLocaleDateString('en-MY',{day:'2-digit',month:'short',year:'numeric'}) : '—';
const digits = (value:string) => String(value||'').replace(/\D/g,'');
const stageLabel = (value:string) => ({lead:'Lead',customer:'Customer',vip:'VIP',inactive:'Inactive',blocked:'Blocked'}[value]||value);
const priorityLabel = (value:string) => ({low:'Low',normal:'Normal',high:'High',urgent:'Urgent'}[value]||value);

async function rpc<T>(name:string,args:Record<string,unknown> = {}) {
  const { data, error } = await supabase.rpc(name,args as never);
  if (error) throw error;
  return data as T;
}

function Modal({ title, children, onClose, wide=false }: {title:string;children:React.ReactNode;onClose:()=>void;wide?:boolean}) {
  return <div className="crm-modal-backdrop" onMouseDown={(event)=>{ if(event.target===event.currentTarget) onClose(); }}>
    <div className={`crm-modal ${wide?'wide':''}`}><div className="crm-modal-head"><h3>{title}</h3><button className="crm-icon-btn" onClick={onClose}><IconX size={18}/></button></div>{children}</div>
  </div>;
}

export default function Customers({ permissions = [], initialCustomer = '', onOpenOrder }: Props) {
  const canManage = permissions.includes('manage_customers') || permissions.includes('manage_admins');
  const canExport = permissions.includes('export_data');
  const [rows,setRows]=useState<CustomerRow[]>([]);
  const [summary,setSummary]=useState<ListResult['summary']>({active:0,merged:0,withPhone:0,withEmail:0,openTasks:0});
  const [total,setTotal]=useState(0); const [offset,setOffset]=useState(0); const limit=50;
  const [search,setSearch]=useState(''); const [status,setStatus]=useState('active'); const [stage,setStage]=useState(''); const [tag,setTag]=useState(''); const [sort,setSort]=useState('recent');
  const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [notice,setNotice]=useState('');
  const [selected,setSelected]=useState(initialCustomer || new URL(location.href).searchParams.get('customer') || '');
  const [detail,setDetail]=useState<CustomerDetail|null>(null); const [detailLoading,setDetailLoading]=useState(false);
  const [activeTab,setActiveTab]=useState('overview'); const [tags,setTags]=useState<Tag[]>([]); const [admins,setAdmins]=useState<Array<{username:string;display_name:string|null}>>([]);
  const [editProfile,setEditProfile]=useState(false); const [profileDraft,setProfileDraft]=useState<ProfileDraft|null>(null);
  const [addressDraft,setAddressDraft]=useState<AddressDraft|null>(null); const [taskDraft,setTaskDraft]=useState<TaskDraft|null>(null);
  const [noteBody,setNoteBody]=useState(''); const [noteType,setNoteType]=useState('note'); const [notePinned,setNotePinned]=useState(false);
  const [tagText,setTagText]=useState(''); const [mergeOpen,setMergeOpen]=useState(false); const [mergeSearch,setMergeSearch]=useState(''); const [mergeRows,setMergeRows]=useState<CustomerRow[]>([]); const [mergeTarget,setMergeTarget]=useState('');
  const [busy,setBusy]=useState('');

  const loadList=useCallback(async(nextOffset=0)=>{
    setLoading(true); setError('');
    try {
      const data=await rpc<ListResult>('icetak_admin_crm_customers',{p_search:search,p_status:status,p_stage:stage,p_tag:tag,p_limit:limit,p_offset:nextOffset,p_sort:sort});
      setRows(data.rows||[]); setSummary(data.summary||summary); setTotal(Number(data.total||0)); setOffset(nextOffset);
    } catch(err:any){ setError(err?.message||'Failed to load customers'); }
    finally { setLoading(false); }
  },[search,status,stage,tag,sort]);

  const loadDetail=useCallback(async(id:string)=>{
    if(!id){ setDetail(null); return; }
    setDetailLoading(true); setError('');
    try { const data=await rpc<CustomerDetail>('icetak_admin_crm_customer_detail',{p_customer_id:id}); setDetail(data); setTagText((data.tags||[]).map(t=>t.name).join(', ')); }
    catch(err:any){ setError(err?.message||'Failed to load customer'); }
    finally { setDetailLoading(false); }
  },[]);

  useEffect(()=>{ const t=window.setTimeout(()=>void loadList(0),220); return()=>window.clearTimeout(t); },[loadList]);
  useEffect(()=>{ void rpc<Tag[]>('icetak_admin_crm_tag_catalog').then(setTags).catch(()=>setTags([])); if(canManage){ void supabase.from('admin_users').select('username,display_name').eq('is_active',true).order('display_name').then(({data})=>setAdmins((data||[]) as any)); } },[canManage]);
  useEffect(()=>{ if(selected) void loadDetail(selected); },[selected,loadDetail]);
  useEffect(()=>{ if(!notice)return; const t=window.setTimeout(()=>setNotice(''),3200); return()=>window.clearTimeout(t); },[notice]);

  const chooseCustomer=(id:string)=>{ setSelected(id); setActiveTab('overview'); const url=new URL(location.href); url.searchParams.set('admin','v2'); url.searchParams.set('view','customers'); url.searchParams.set('customer',id); url.searchParams.delete('order'); history.replaceState({},'',url); };
  const closeDetail=()=>{ setSelected(''); setDetail(null); const url=new URL(location.href); url.searchParams.delete('customer'); history.replaceState({},'',url); };
  const refreshAll=async()=>{ await loadList(offset); if(selected) await loadDetail(selected); };
  const mutate=async(label:string,fn:()=>Promise<CustomerDetail>)=>{ setBusy(label); setError(''); try{ const next=await fn(); setDetail(next); setTagText((next.tags||[]).map(t=>t.name).join(', ')); setNotice('Saved successfully'); await loadList(offset); return next; }catch(err:any){ setError(err?.message||'Action failed'); throw err; }finally{ setBusy(''); } };

  const openProfileEditor=()=>{ if(!detail)return; setProfileDraft({name:detail.profile.name,phone:detail.profile.phone,email:detail.profile.email,stage:detail.profile.stage,priority:detail.profile.priority,owner:detail.profile.owner,doNotContact:detail.profile.doNotContact}); setEditProfile(true); };
  const saveProfile=async()=>{ if(!detail||!profileDraft)return; await mutate('profile',()=>rpc<CustomerDetail>('icetak_admin_crm_update_customer',{p_customer_id:detail.profile.id,p_payload:profileDraft})); setEditProfile(false); };
  const saveAddress=async()=>{ if(!detail||!addressDraft)return; await mutate('address',()=>rpc<CustomerDetail>('icetak_admin_crm_save_address',{p_customer_id:detail.profile.id,p_address_id:addressDraft.id||null,p_payload:addressDraft})); setAddressDraft(null); };
  const archiveAddress=async(id:string)=>{ if(!detail||!confirm('Archive alamat ini?'))return; await mutate('address',()=>rpc<CustomerDetail>('icetak_admin_crm_archive_address',{p_customer_id:detail.profile.id,p_address_id:id})); };
  const addNote=async()=>{ if(!detail||!noteBody.trim())return; await mutate('note',()=>rpc<CustomerDetail>('icetak_admin_crm_add_note',{p_customer_id:detail.profile.id,p_payload:{type:noteType,body:noteBody,pinned:notePinned}})); setNoteBody(''); setNotePinned(false); };
  const deleteNote=async(id:string)=>{ if(!detail||!confirm('Delete note ini?'))return; await mutate('note',()=>rpc<CustomerDetail>('icetak_admin_crm_delete_note',{p_customer_id:detail.profile.id,p_note_id:id})); };
  const saveTask=async()=>{ if(!detail||!taskDraft)return; await mutate('task',()=>rpc<CustomerDetail>('icetak_admin_crm_save_task',{p_customer_id:detail.profile.id,p_task_id:taskDraft.id||null,p_payload:taskDraft})); setTaskDraft(null); };
  const deleteTask=async(id:string)=>{ if(!detail||!confirm('Delete task ini?'))return; await mutate('task',()=>rpc<CustomerDetail>('icetak_admin_crm_delete_task',{p_customer_id:detail.profile.id,p_task_id:id})); };
  const saveTags=async()=>{ if(!detail)return; const values=tagText.split(',').map(v=>v.trim()).filter(Boolean); await mutate('tags',()=>rpc<CustomerDetail>('icetak_admin_crm_set_tags',{p_customer_id:detail.profile.id,p_tags:values})); void rpc<Tag[]>('icetak_admin_crm_tag_catalog').then(setTags).catch(()=>{}); };

  useEffect(()=>{ if(!mergeOpen){setMergeRows([]);return;} const t=window.setTimeout(async()=>{ try{ const data=await rpc<ListResult>('icetak_admin_crm_customers',{p_search:mergeSearch,p_status:'active',p_stage:'',p_tag:'',p_limit:20,p_offset:0,p_sort:'recent'}); setMergeRows((data.rows||[]).filter(row=>row.id!==selected)); }catch{setMergeRows([]);} },220); return()=>window.clearTimeout(t); },[mergeOpen,mergeSearch,selected]);
  const doMerge=async()=>{ if(!detail||!mergeTarget)return; const target=mergeRows.find(r=>r.id===mergeTarget); if(!target||!confirm(`Merge "${target.name}" INTO "${detail.profile.name}"?\n\nCustomer yang dipilih sekarang akan KEKAL. Tindakan ini tidak boleh dibatalkan dengan mudah.`))return; await mutate('merge',()=>rpc<CustomerDetail>('icetak_admin_crm_merge_customer',{p_keep:detail.profile.id,p_merge:mergeTarget,p_reason:'Admin V2 CRM manual merge'})); setMergeOpen(false); setMergeTarget(''); setMergeSearch(''); };

  const exportCsv=async()=>{
    if(!canExport)return; setBusy('export'); setError('');
    try{
      const all:CustomerRow[]=[]; let cursor=0; let count=0;
      do{ const data=await rpc<ListResult>('icetak_admin_crm_customers',{p_search:search,p_status:status,p_stage:stage,p_tag:tag,p_limit:100,p_offset:cursor,p_sort:sort}); all.push(...(data.rows||[])); count=Number(data.total||0); cursor+=100; }while(cursor<count && cursor<10000);
      const cols=['Name','Phone','Email','Status','Stage','Priority','Owner','Orders','Lifetime Spend','Last Order','Addresses','Open Tasks','Tags','Channels'];
      const esc=(v:unknown)=>`"${String(v??'').replaceAll('"','""')}"`;
      const csv=[cols.map(esc).join(','),...all.map(r=>[r.name,r.phone,r.email,r.status,r.stage,r.priority,r.owner,r.orderCount,r.lifetimeSpend,r.lastOrderAt||'',r.addressCount,r.openTasks,(r.tags||[]).join('|'),(r.channels||[]).join('|')].map(esc).join(','))].join('\n');
      const blob=new Blob([csv],{type:'text/csv;charset=utf-8'}); const href=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=href; a.download=`icetak-customers-${new Date().toISOString().slice(0,10)}.csv`; a.click(); URL.revokeObjectURL(href); setNotice(`${all.length} customers exported`);
    }catch(err:any){setError(err?.message||'Export failed');}finally{setBusy('');}
  };

  const filteredTags=useMemo(()=>tags.filter(t=>t.name),[tags]);
  const pageStart=total?offset+1:0; const pageEnd=Math.min(offset+limit,total);

  return <div className="crm-page fade-in">
    <div className="page-header"><div><h1 className="page-title">Customer CRM</h1><p className="page-subtitle">Enterprise customer 360° · internal orders + marketplace identity</p></div><div className="crm-head-actions">{canExport&&<button className="btn btn-outline" disabled={busy==='export'} onClick={()=>void exportCsv()}><IconDownload size={16}/>{busy==='export'?'Exporting…':'Export CSV'}</button>}<button className="btn btn-outline" onClick={()=>void refreshAll()}><IconRefresh size={16}/> Refresh</button></div></div>
    {notice&&<div className="crm-notice ok">{notice}</div>}{error&&<div className="crm-notice bad">{error}</div>}

    <div className="crm-kpis">
      <div><span>Active customers</span><strong>{summary.active.toLocaleString()}</strong></div><div><span>With phone</span><strong>{summary.withPhone.toLocaleString()}</strong></div><div><span>With email</span><strong>{summary.withEmail.toLocaleString()}</strong></div><div><span>Open follow-ups</span><strong>{summary.openTasks.toLocaleString()}</strong></div><div><span>Merged records</span><strong>{summary.merged.toLocaleString()}</strong></div>
    </div>

    <section className="crm-toolbar panel">
      <label className="crm-search"><IconSearch size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name, phone, email, Shopee username…"/></label>
      <select value={status} onChange={e=>setStatus(e.target.value)}><option value="active">Active only</option><option value="all">All records</option><option value="merged">Merged</option></select>
      <select value={stage} onChange={e=>setStage(e.target.value)}><option value="">All CRM stages</option><option value="lead">Lead</option><option value="customer">Customer</option><option value="vip">VIP</option><option value="inactive">Inactive</option><option value="blocked">Blocked</option></select>
      <select value={tag} onChange={e=>setTag(e.target.value)}><option value="">All tags</option>{filteredTags.map(t=><option key={t.id} value={t.name}>{t.name}{t.customerCount!=null?` (${t.customerCount})`:''}</option>)}</select>
      <select value={sort} onChange={e=>setSort(e.target.value)}><option value="recent">Recent activity</option><option value="spend">Highest spend</option><option value="orders">Most orders</option><option value="name">Name A–Z</option></select>
    </section>

    <div className={`crm-workspace ${selected?'has-detail':''}`}>
      <section className="panel crm-list-panel">
        <div className="panel-header"><div><div className="panel-title">Customers</div><div className="panel-subtitle">{pageStart.toLocaleString()}–{pageEnd.toLocaleString()} of {total.toLocaleString()}</div></div></div>
        {loading?<div className="loading"><span className="spinner"/></div>:rows.length===0?<div className="empty"><div className="empty-icon"><IconStaff size={22}/></div><div>No customers match this filter</div></div>:<div className="crm-customer-list">{rows.map(row=><button key={row.id} className={`crm-customer-row ${selected===row.id?'active':''}`} onClick={()=>chooseCustomer(row.id)}>
          <div className="crm-avatar">{(row.name||'?').slice(0,1).toUpperCase()}</div><div className="crm-row-main"><div className="crm-row-name">{row.name}{row.doNotContact&&<span className="crm-dnc">DNC</span>}</div><div className="crm-row-sub">{row.phone?`+${digits(row.phone)}`:'No phone'}{row.email?` · ${row.email}`:''}</div><div className="crm-row-tags"><span className={`crm-stage ${row.stage}`}>{stageLabel(row.stage)}</span>{(row.tags||[]).slice(0,3).map(value=><span key={value} className="crm-tag">{value}</span>)}</div></div><div className="crm-row-stats"><strong>{money(row.lifetimeSpend)}</strong><span>{row.orderCount} orders</span><small>{row.lastOrderAt?shortDate(row.lastOrderAt):'No order'}</small>{row.openTasks>0&&<b>{row.openTasks} follow-up</b>}</div>
        </button>)}</div>}
        <div className="crm-pagination"><button className="btn btn-outline" disabled={offset<=0||loading} onClick={()=>void loadList(Math.max(0,offset-limit))}>Previous</button><span>{pageStart}–{pageEnd} / {total}</span><button className="btn btn-outline" disabled={offset+limit>=total||loading} onClick={()=>void loadList(offset+limit)}>Next</button></div>
      </section>

      {selected&&<section className="panel crm-detail-panel">{detailLoading&&!detail?<div className="loading"><span className="spinner"/></div>:detail?<>
        <div className="crm-detail-hero"><button className="crm-mobile-close" onClick={closeDetail}><IconX size={18}/></button><div className="crm-avatar large">{detail.profile.name.slice(0,1).toUpperCase()}</div><div className="crm-hero-main"><div className="crm-hero-title"><h2>{detail.profile.name}</h2><span className={`crm-stage ${detail.profile.stage}`}>{stageLabel(detail.profile.stage)}</span>{detail.profile.doNotContact&&<span className="crm-dnc">Do Not Contact</span>}</div><div className="crm-hero-sub">{detail.profile.phone?`+${digits(detail.profile.phone)}`:'No phone'}{detail.profile.email?` · ${detail.profile.email}`:''}</div><div className="crm-hero-meta">{priorityLabel(detail.profile.priority)} priority{detail.profile.owner?` · Owner: ${detail.profile.owner}`:''} · Last seen {shortDate(detail.profile.lastSeenAt)}</div></div><div className="crm-hero-actions">{detail.profile.phone&&!detail.profile.doNotContact&&<a className="btn btn-outline" href={`tel:${digits(detail.profile.phone)}`}><IconPhone size={15}/> Call</a>}{canManage&&detail.profile.status==='active'&&<button className="btn btn-primary" onClick={openProfileEditor}><IconEdit size={15}/> Edit</button>}</div></div>
        <div className="crm-detail-kpis"><div><span>Lifetime</span><strong>{money(detail.stats.lifetimeSpend)}</strong></div><div><span>Orders</span><strong>{detail.stats.orderCount}</strong></div><div><span>Shopee / Market</span><strong>{detail.stats.marketplaceOrders}</strong></div><div><span>Addresses</span><strong>{detail.stats.addressCount}</strong></div><div><span>Follow-ups</span><strong>{detail.stats.openTasks}</strong></div></div>
        <div className="crm-tabs">{['overview','orders','addresses','activity','tasks','identity'].map(value=><button key={value} className={activeTab===value?'active':''} onClick={()=>setActiveTab(value)}>{value[0].toUpperCase()+value.slice(1)}</button>)}</div>

        <div className="crm-tab-body">
          {activeTab==='overview'&&<div className="crm-grid-two">
            <section className="crm-card"><div className="crm-card-head"><h3>Customer profile</h3>{canManage&&detail.profile.status==='active'&&<button className="crm-link" onClick={openProfileEditor}>Edit</button>}</div><dl className="crm-dl"><div><dt>Admin name</dt><dd>{detail.profile.adminNameOverride||'—'}</dd></div><div><dt>Source name</dt><dd>{detail.profile.sourceName||'—'}</dd></div><div><dt>Phone</dt><dd>{detail.profile.phone?`+${digits(detail.profile.phone)}`:'—'}</dd></div><div><dt>Email</dt><dd>{detail.profile.email||'—'}</dd></div><div><dt>CRM stage</dt><dd>{stageLabel(detail.profile.stage)}</dd></div><div><dt>Priority</dt><dd>{priorityLabel(detail.profile.priority)}</dd></div><div><dt>First seen</dt><dd>{dateTime(detail.profile.firstSeenAt)}</dd></div><div><dt>Last order</dt><dd>{dateTime(detail.stats.lastOrderAt)}</dd></div></dl></section>
            <section className="crm-card"><div className="crm-card-head"><h3>Tags</h3></div><div className="crm-tag-cloud">{detail.tags.length?detail.tags.map(t=><span key={t.id} className="crm-tag">{t.name}</span>):<span className="crm-muted">No tags yet</span>}</div>{canManage&&detail.profile.status==='active'&&<div className="crm-inline-edit"><input value={tagText} onChange={e=>setTagText(e.target.value)} placeholder="VIP, Repeat Buyer, Cake Shop"/><button className="btn btn-outline" disabled={busy==='tags'} onClick={()=>void saveTags()}>Save tags</button></div>}</section>
            <section className="crm-card crm-span-two"><div className="crm-card-head"><h3>Quick note</h3><span className="crm-muted">Internal CRM only</span></div>{canManage&&detail.profile.status==='active'?<><div className="crm-note-compose"><select value={noteType} onChange={e=>setNoteType(e.target.value)}><option value="note">Note</option><option value="call">Call</option><option value="whatsapp">WhatsApp</option><option value="email">Email</option><option value="meeting">Meeting</option><option value="issue">Issue</option></select><textarea value={noteBody} onChange={e=>setNoteBody(e.target.value)} placeholder="Add customer context, preference, issue or follow-up note…"/><label><input type="checkbox" checked={notePinned} onChange={e=>setNotePinned(e.target.checked)}/> Pin</label><button className="btn btn-primary" disabled={!noteBody.trim()||busy==='note'} onClick={()=>void addNote()}><IconPlus size={15}/> Add note</button></div><div className="crm-note-list">{detail.notes.slice(0,5).map(n=><article key={n.id} className={`crm-note ${n.pinned?'pinned':''}`}><div><b>{n.type.toUpperCase()}</b>{n.pinned&&<span>PINNED</span>}<small>{dateTime(n.createdAt)} · {n.createdBy||'admin'}</small></div><p>{n.body}</p>{canManage&&<button className="crm-link danger" onClick={()=>void deleteNote(n.id)}>Delete</button>}</article>)}</div></>:<div className="crm-note-list">{detail.notes.slice(0,5).map(n=><article key={n.id} className="crm-note"><div><b>{n.type.toUpperCase()}</b><small>{dateTime(n.createdAt)}</small></div><p>{n.body}</p></article>)}</div>}</section>
            {canManage&&detail.profile.status==='active'&&<section className="crm-card crm-span-two danger-zone"><div><h3>Duplicate management</h3><p>Merge duplicate master records without losing addresses, tags, notes, tasks, portal identity or marketplace identity.</p></div><button className="btn btn-outline" onClick={()=>setMergeOpen(true)}>Merge duplicate customer</button></section>}
          </div>}

          {activeTab==='orders'&&<div className="crm-order-list">{detail.orders.length===0?<div className="empty">No order history</div>:detail.orders.map((o,index)=><article key={`${o.kind}-${o.id}-${index}`} className="crm-order"><div><span className={`crm-order-source ${o.kind}`}>{o.kind==='marketplace'?(o.provider||'Marketplace'):'iCetak'}</span><strong>{o.id}</strong><small>{dateTime(o.createdAt)}{o.buyerUsername?` · @${o.buyerUsername}`:''}</small></div><div><b>{money(o.total)}</b><span>{o.payment||'—'}</span></div><div><b>{o.status||'—'}</b><span>{o.delivery||'—'}</span></div>{o.kind==='internal'?<button className="btn btn-outline" onClick={()=>onOpenOrder(o.id)}>Open order</button>:<span className="crm-muted">Marketplace record</span>}</article>)}</div>}

          {activeTab==='addresses'&&<div><div className="crm-section-actions"><div><h3>Address book</h3><p>{detail.addresses.length} active addresses</p></div>{canManage&&detail.profile.status==='active'&&<button className="btn btn-primary" onClick={()=>setAddressDraft({label:'Home',recipientName:detail.profile.name,phone:detail.profile.phone?`+${digits(detail.profile.phone)}`:'',addressLine1:'',addressLine2:'',city:'',postcode:'',state:'Kelantan',country:'Malaysia',isDefault:detail.addresses.length===0})}><IconPlus size={15}/> Add address</button>}</div><div className="crm-address-grid">{detail.addresses.map(a=><article key={a.id} className={`crm-address ${a.isDefault?'default':''}`}><div className="crm-card-head"><h3>{a.label||'Address'} {a.isDefault&&<span className="crm-default">DEFAULT</span>}</h3>{a.isVerified&&<span className="crm-verified">Verified</span>}</div><b>{a.recipientName||detail.profile.name}</b><p>{[a.addressLine1,a.addressLine2,`${a.postcode} ${a.city}`,a.state,a.country].filter(Boolean).join(', ')}</p><small>{a.phone||'No phone'} · used {a.usageCount||0}× · {a.source||'manual'}</small>{canManage&&detail.profile.status==='active'&&<div className="crm-address-actions"><button className="crm-link" onClick={()=>setAddressDraft({...a})}>Edit</button><button className="crm-link danger" onClick={()=>void archiveAddress(a.id)}>Archive</button></div>}</article>)}</div></div>}

          {activeTab==='activity'&&<div className="crm-grid-two"><section className="crm-card"><div className="crm-card-head"><h3>Notes & interactions</h3></div><div className="crm-note-list">{detail.notes.length?detail.notes.map(n=><article key={n.id} className={`crm-note ${n.pinned?'pinned':''}`}><div><b>{n.type.toUpperCase()}</b>{n.pinned&&<span>PINNED</span>}<small>{dateTime(n.createdAt)} · {n.createdBy||'admin'}</small></div><p>{n.body}</p>{canManage&&detail.profile.status==='active'&&<button className="crm-link danger" onClick={()=>void deleteNote(n.id)}>Delete</button>}</article>):<div className="crm-muted">No CRM notes</div>}</div></section><section className="crm-card"><div className="crm-card-head"><h3>Admin audit trail</h3></div><div className="crm-timeline">{detail.audit.length?detail.audit.map(a=><div key={a.id}><i/><div><b>{a.action.replaceAll('_',' ')}</b><span>{a.actor||'admin'} · {dateTime(a.createdAt)}</span></div></div>):<div className="crm-muted">No CRM changes yet</div>}</div></section></div>}

          {activeTab==='tasks'&&<div><div className="crm-section-actions"><div><h3>Follow-up tasks</h3><p>Customer-specific reminders and action queue</p></div>{canManage&&detail.profile.status==='active'&&<button className="btn btn-primary" onClick={()=>setTaskDraft({title:'',detail:'',dueAt:'',priority:'normal',status:'open',assignedTo:detail.profile.owner||''})}><IconPlus size={15}/> Add task</button>}</div><div className="crm-task-list">{detail.tasks.length===0?<div className="empty">No follow-up tasks</div>:detail.tasks.map(t=><article key={t.id} className={`crm-task ${t.status}`}><div><span className={`crm-priority ${t.priority}`}>{priorityLabel(t.priority)}</span><strong>{t.title}</strong><p>{t.detail||'No details'}</p><small>{t.dueAt?`Due ${dateTime(t.dueAt)}`:'No due date'}{t.assignedTo?` · ${t.assignedTo}`:''} · {t.status}</small></div>{canManage&&detail.profile.status==='active'&&<div><button className="crm-link" onClick={()=>setTaskDraft({id:t.id,title:t.title,detail:t.detail,dueAt:t.dueAt?new Date(t.dueAt).toISOString().slice(0,16):'',priority:t.priority,status:t.status,assignedTo:t.assignedTo})}>Edit</button><button className="crm-link danger" onClick={()=>void deleteTask(t.id)}>Delete</button></div>}</article>)}</div></div>}

          {activeTab==='identity'&&<div className="crm-grid-two"><section className="crm-card"><h3>Identifiers</h3><div className="crm-identity-list">{detail.identifiers.map((i,index)=><div key={`${i.type}-${i.scope}-${index}`}><div><b>{i.type}</b><span>{i.channel||i.source}</span></div><code>{i.value}</code><small>{i.scope}{i.verified?' · verified':''} · {dateTime(i.lastSeenAt)}</small></div>)}</div></section><section className="crm-card"><h3>Connected accounts</h3><div className="crm-identity-list">{detail.portalAccounts.map(a=><div key={a.id}><div><b>Customer Portal</b><span>{a.source}</span></div><code>{a.phone}</code><small>{a.name} · {dateTime(a.createdAt)}</small></div>)}{detail.marketplaceAccounts.map(a=><div key={a.id}><div><b>{a.provider}</b><span>{a.region}</span></div><code>@{a.username}</code><small>Last seen {dateTime(a.lastSeenAt)}</small></div>)}</div></section><section className="crm-card crm-span-two"><h3>Source records</h3><div className="crm-source-table">{detail.sources.map((s,index)=><div key={`${s.system}-${s.recordId}-${index}`}><b>{s.system}</b><span>{s.table}</span><code>{s.recordId}</code><small>{dateTime(s.lastSeenAt)}</small></div>)}</div></section></div>}
        </div>
      </>:null}</section>}
    </div>

    {editProfile&&profileDraft&&<Modal title="Edit customer profile" onClose={()=>setEditProfile(false)}><div className="crm-form-grid"><label className="span-two">Admin display name<input value={profileDraft.name} onChange={e=>setProfileDraft({...profileDraft,name:e.target.value})}/><small>Source name is preserved; this override is protected from imports.</small></label><label>Phone<input value={profileDraft.phone} onChange={e=>setProfileDraft({...profileDraft,phone:e.target.value})} placeholder="6012…"/><small>Changing phone updates the linked customer portal identity safely.</small></label><label>Email<input type="email" value={profileDraft.email} onChange={e=>setProfileDraft({...profileDraft,email:e.target.value})}/></label><label>CRM stage<select value={profileDraft.stage} onChange={e=>setProfileDraft({...profileDraft,stage:e.target.value})}><option value="lead">Lead</option><option value="customer">Customer</option><option value="vip">VIP</option><option value="inactive">Inactive</option><option value="blocked">Blocked</option></select></label><label>Priority<select value={profileDraft.priority} onChange={e=>setProfileDraft({...profileDraft,priority:e.target.value})}><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></select></label><label>Owner<select value={profileDraft.owner} onChange={e=>setProfileDraft({...profileDraft,owner:e.target.value})}><option value="">Unassigned</option>{admins.map(a=><option key={a.username} value={a.username}>{a.display_name||a.username}</option>)}</select></label><label className="crm-check"><input type="checkbox" checked={profileDraft.doNotContact} onChange={e=>setProfileDraft({...profileDraft,doNotContact:e.target.checked})}/> Do Not Contact</label></div><div className="crm-modal-actions"><button className="btn btn-outline" onClick={()=>setEditProfile(false)}>Cancel</button><button className="btn btn-primary" disabled={busy==='profile'} onClick={()=>void saveProfile()}>{busy==='profile'?'Saving…':'Save profile'}</button></div></Modal>}

    {addressDraft&&<Modal title={addressDraft.id?'Edit address':'Add address'} onClose={()=>setAddressDraft(null)}><div className="crm-form-grid"><label>Label<input value={addressDraft.label} onChange={e=>setAddressDraft({...addressDraft,label:e.target.value})}/></label><label>Recipient<input value={addressDraft.recipientName} onChange={e=>setAddressDraft({...addressDraft,recipientName:e.target.value})}/></label><label className="span-two">Phone<input value={addressDraft.phone} onChange={e=>setAddressDraft({...addressDraft,phone:e.target.value})}/></label><label className="span-two">Address line 1<textarea value={addressDraft.addressLine1} onChange={e=>setAddressDraft({...addressDraft,addressLine1:e.target.value})}/></label><label className="span-two">Address line 2<input value={addressDraft.addressLine2} onChange={e=>setAddressDraft({...addressDraft,addressLine2:e.target.value})}/></label><label>Postcode<input value={addressDraft.postcode} onChange={e=>setAddressDraft({...addressDraft,postcode:e.target.value})}/></label><label>City<input value={addressDraft.city} onChange={e=>setAddressDraft({...addressDraft,city:e.target.value})}/></label><label>State<input value={addressDraft.state} onChange={e=>setAddressDraft({...addressDraft,state:e.target.value})}/></label><label>Country<input value={addressDraft.country} onChange={e=>setAddressDraft({...addressDraft,country:e.target.value})}/></label><label className="crm-check span-two"><input type="checkbox" checked={addressDraft.isDefault} onChange={e=>setAddressDraft({...addressDraft,isDefault:e.target.checked})}/> Default address</label></div><div className="crm-modal-actions"><button className="btn btn-outline" onClick={()=>setAddressDraft(null)}>Cancel</button><button className="btn btn-primary" disabled={busy==='address'} onClick={()=>void saveAddress()}>{busy==='address'?'Saving…':'Save address'}</button></div></Modal>}

    {taskDraft&&<Modal title={taskDraft.id?'Edit follow-up':'New follow-up'} onClose={()=>setTaskDraft(null)}><div className="crm-form-grid"><label className="span-two">Title<input value={taskDraft.title} onChange={e=>setTaskDraft({...taskDraft,title:e.target.value})}/></label><label className="span-two">Details<textarea value={taskDraft.detail} onChange={e=>setTaskDraft({...taskDraft,detail:e.target.value})}/></label><label>Due<input type="datetime-local" value={taskDraft.dueAt} onChange={e=>setTaskDraft({...taskDraft,dueAt:e.target.value})}/></label><label>Priority<select value={taskDraft.priority} onChange={e=>setTaskDraft({...taskDraft,priority:e.target.value})}><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></select></label><label>Status<select value={taskDraft.status} onChange={e=>setTaskDraft({...taskDraft,status:e.target.value})}><option value="open">Open</option><option value="done">Done</option><option value="cancelled">Cancelled</option></select></label><label>Assigned to<select value={taskDraft.assignedTo} onChange={e=>setTaskDraft({...taskDraft,assignedTo:e.target.value})}><option value="">Unassigned</option>{admins.map(a=><option key={a.username} value={a.username}>{a.display_name||a.username}</option>)}</select></label></div><div className="crm-modal-actions"><button className="btn btn-outline" onClick={()=>setTaskDraft(null)}>Cancel</button><button className="btn btn-primary" disabled={busy==='task'||!taskDraft.title.trim()} onClick={()=>void saveTask()}>{busy==='task'?'Saving…':'Save task'}</button></div></Modal>}

    {mergeOpen&&detail&&<Modal title="Merge duplicate customer" wide onClose={()=>setMergeOpen(false)}><div className="crm-merge-warning"><b>Keep:</b> {detail.profile.name} · +{digits(detail.profile.phone)}<p>The selected duplicate will be merged into this customer. Orders, marketplace identity, addresses, notes, tasks and tags remain linked to the kept master record.</p></div><label className="crm-search modal-search"><IconSearch size={17}/><input autoFocus value={mergeSearch} onChange={e=>setMergeSearch(e.target.value)} placeholder="Search duplicate name / phone / Shopee username…"/></label><div className="crm-merge-list">{mergeRows.map(row=><label key={row.id} className={mergeTarget===row.id?'active':''}><input type="radio" name="mergeTarget" value={row.id} checked={mergeTarget===row.id} onChange={()=>setMergeTarget(row.id)}/><div><b>{row.name}</b><span>{row.phone?`+${digits(row.phone)}`:'No phone'} · {row.orderCount} orders · {money(row.lifetimeSpend)}</span></div></label>)}</div><div className="crm-modal-actions"><button className="btn btn-outline" onClick={()=>setMergeOpen(false)}>Cancel</button><button className="btn btn-primary" disabled={!mergeTarget||busy==='merge'} onClick={()=>void doMerge()}>{busy==='merge'?'Merging…':'Merge into current customer'}</button></div></Modal>}
  </div>;
}
