import { useCallback, useDeferredValue, useEffect, useMemo, useRef, useState } from 'react';
import { supabase } from '../lib/supabase';
import './CustomerFocus.css';
type Data=Record<string,any>;
type Column={key:string;label:string;width:number};
const columns:Column[]=[{key:'priority',label:'Prioriti',width:130},{key:'customer',label:'Customer / channel',width:170},{key:'reference',label:'Order / produk',width:210},{key:'action',label:'Tindakan seterusnya',width:240},{key:'payment',label:'Bayaran',width:130},{key:'details',label:'Detail order',width:200},{key:'chat',label:'Chat customer',width:260},{key:'focus_due',label:'Tarikh fokus',width:140},{key:'customer_needed',label:'Customer perlu',width:150},{key:'dispatch_by',label:'Janji pos / pickup',width:155},{key:'design_by',label:'Design perlu siap',width:155},{key:'platform_deadline',label:'Deadline platform',width:155},{key:'clickup_due',label:'Due ClickUp',width:155},{key:'clickup',label:'ClickUp / set',width:255},{key:'courier',label:'Penghantaran',width:220},{key:'note',label:'Nota / kemas kini',width:220},{key:'created_at',label:'Order / chat masuk',width:155}];
const filters=[['actionable','Fokus hari ini'],['all','Semua kerja aktif'],['paid','Dah bayar'],['details','Kurang detail'],['design','Perlu design'],['reply','Semak / balas chat'],['waiting','Menunggu'],['production','Production'],['shipping','Pos / pickup'],['draft','Draft baru'],['issue','Semak masalah'],['backlog','Rekod lama'],['done','Tindakan selesai']];
const date=(v:unknown)=>v&&Number.isFinite(Date.parse(String(v)))?new Date(String(v)).toLocaleString('ms-MY',{timeZone:'Asia/Kuala_Lumpur',day:'numeric',month:'short',year:'2-digit',hour:'2-digit',minute:'2-digit'}):'—';
const dayInput=(v:unknown)=>v&&Number.isFinite(Date.parse(String(v)))?new Date(String(v)).toLocaleDateString('en-CA',{timeZone:'Asia/Kuala_Lumpur'}):'';
const money=(v:unknown)=>v==null?'Jumlah belum tersedia':new Intl.NumberFormat('ms-MY',{style:'currency',currency:'MYR'}).format(Number(v));
function match(r:Data,f:string){if(f==='backlog')return r.history??r.backlog;if(r.history??r.backlog)return false;if(f==='all')return r.category!=='done';if(f==='actionable')return r.actionable;if(f==='details')return r.detail_status==='missing';if(f==='paid')return r.work.paid&&r.work.active&&!r.work.shipped&&!r.work.closed;if(f==='design')return ['design','review'].includes(r.category);if(f==='reply')return r.chat.reply&&r.chat.recent!==false;if(f==='waiting')return ['waiting','snoozed'].includes(r.category);if(f==='shipping')return ['ready','pickup'].includes(r.category);if(f==='issue')return ['issue','unknown'].includes(r.category);if(f==='done')return r.manual_work==='handled'||(r.kind==='chat'&&r.category==='done'&&r.state.data.work_state==='handled');return r.category===f;}
function value(r:Data,k:string):string|number|null {switch(k){case'priority':return r.priority;case'customer':return r.customer_name||'';case'payment':return r.work.paid?0:r.work.cod?1:2;case'details':return r.detail_status;case'chat':return r.chat.at?Date.parse(r.chat.at):null;case'clickup':return Math.min(...(r.production_tasks||[]).map((t:Data)=>Number(t.progress_stage??-1)),99);case'courier':return r.shipment_status||r.courier||'';case'note':return r.note||'';default:return ['focus_due','customer_needed','dispatch_by','design_by','platform_deadline','clickup_due','created_at'].includes(k)?r[k]?Date.parse(r[k]):null:r[k]||'';}}
const prefKey='icetak.customerFocus.list.v1';
const defaultColumns=['priority','customer','reference','action','focus_due','payment','details','clickup','chat','courier','customer_needed','dispatch_by','design_by','platform_deadline','clickup_due','note','created_at'];
const defaultSort=[{key:'priority',direction:1},{key:'focus_due',direction:1},{key:'created_at',direction:-1}];
function prefs(){try{const p=JSON.parse(localStorage.getItem(prefKey)||'{}');return {columns:Array.isArray(p.columns)?[...new Set(p.columns.filter((k:string)=>columns.some(c=>c.key===k)))].concat(p.columns.includes('customer')?[]:['customer']) as string[]:defaultColumns,sort:Array.isArray(p.sort)&&p.sort.length&&p.sort.every((s:Data)=>columns.some(c=>c.key===s.key)&&[1,-1].includes(s.direction))?p.sort:defaultSort};}catch{return {columns:defaultColumns,sort:defaultSort};}}
async function call(body:Data){let timer:ReturnType<typeof setTimeout>|undefined;try{const result=await Promise.race([supabase.functions.invoke('admin-ai-dashboard',{body}),new Promise<never>((_,reject)=>{timer=setTimeout(()=>reject(Error('Semakan mengambil terlalu lama. Cuba Muat semula.')),90000);})]);if(result.error)throw Error(result.error.message);if(!result.data?.ok)throw Error(result.data?.error||'Semakan gagal');return result.data;}finally{clearTimeout(timer);}}
function safeLink(v:unknown){try{const u=new URL(String(v));return u.protocol==='https:'?u.href:null;}catch{return null;}}
function whatsappPhone(v:unknown){let n=String(v||'').replace(/\D/g,'');if(n.startsWith('00'))n=n.slice(2);else if(n.startsWith('0'))n=`6${n}`;return /^[1-9]\d{7,14}$/.test(n)?n:null;}
function shopeeUsername(r:Data){return String(r.kind==='shopee'?r.chat_search||'':r.channel==='shopee'?r.chat.name||'':'').trim();}
function deliveryType(r:Data){if(r.kind==='chat')return null;const method=String(r.delivery_method||'').toLowerCase(),courier=String(r.courier||'').toLowerCase();if(/pick[\s_-]*up|walk[\s_-]*in|collect|counter/.test(`${method} ${courier}`))return 'pickup';if((method&&!['unknown','none','null'].includes(method))||courier||r.tracking)return 'post';return null;}
const focusIconPaths={copy:<><rect x="9" y="9" width="11" height="11" rx="2"/><path d="M15 9V5a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h4"/></>,app:<><rect x="6" y="2" width="12" height="20" rx="2"/><path d="M10 18h4"/></>,external:<><path d="M15 3h6v6M10 14 21 3"/><path d="M21 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h6"/></>,shopee:<><path d="M5 7h14l2 14H3L5 7Z"/><path d="M8 7V6a4 4 0 0 1 8 0v1M14 11h-3a2 2 0 0 0 0 4h2a2 2 0 0 1 0 4h-3"/></>,store:<><path d="M3 10V6l2-3h14l2 3v4M3 10a3 3 0 0 0 6 0 3 3 0 0 0 6 0 3 3 0 0 0 6 0M5 13v8h14v-8M9 21v-6h6v6"/></>,post:<><path d="M3 6h11v12H3zM14 10h4l3 4v4h-7"/><circle cx="7" cy="18" r="2"/><circle cx="18" cy="18" r="2"/></>,pickup:<><path d="M3 9 12 4l9 5-9 5-9-5ZM3 9v9l9 4 9-4V9M12 14v8M7 7l9 5"/></>,chat:<path d="M21 11a9 9 0 0 1-9 9 10 10 0 0 1-4-.9L3 21l1.9-5A10 10 0 0 1 3 11a9 9 0 0 1 18 0Z"/>};
function FocusIcon({name}:{name:keyof typeof focusIconPaths}){
 return <svg className="focus-icon" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{focusIconPaths[name]}</svg>;
}
export default function CustomerFocus({onOpenOrder,onOpenMarketplace,onOpenChat,onOpenDrafts}:{onOpenOrder:(reference:string)=>void;onOpenMarketplace:(reference:string)=>void;onOpenChat:(id:string)=>void;onOpenDrafts:(query:string)=>void}){
 const initial=useMemo(prefs,[]),[visibleCols,setVisibleCols]=useState<string[]>(initial.columns),[sort,setSort]=useState<Data[]>(initial.sort);
 const [data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [filter,setFilter]=useState('actionable'),[channel,setChannel]=useState('all'),[search,setSearch]=useState(''),[page,setPage]=useState(0),[colOpen,setColOpen]=useState(false),[auto,setAuto]=useState(true);
 const [editing,setEditing]=useState<Data|null>(null),[form,setForm]=useState<Data>({}),[saving,setSaving]=useState(false),[editError,setEditError]=useState('');
 const seq=useRef(0),editingRef=useRef(false),mounted=useRef(true),query=useDeferredValue(search.toLowerCase().trim());
 editingRef.current=!!editing||saving;
 useEffect(()=>{if(!editing)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[!!editing]);
 const load=useCallback(async()=>{const id=++seq.current;setLoading(true);setError('');try{const r=await call({action:'focus'});if(mounted.current&&id===seq.current){setData(r);}}catch(e){if(mounted.current&&id===seq.current)setError(e instanceof Error?e.message:String(e));}finally{if(mounted.current&&id===seq.current)setLoading(false);}},[]);
 useEffect(()=>{mounted.current=true;void load();return()=>{mounted.current=false;seq.current++;};},[load]);
 useEffect(()=>{if(!auto)return;const timer=setInterval(()=>{if(document.visibilityState==='visible'&&!editingRef.current&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName||''))void load();},60000);return()=>clearInterval(timer);},[auto,load]);
 useEffect(()=>{try{localStorage.setItem(prefKey,JSON.stringify({columns:visibleCols,sort}));}catch{/* List remains usable without storage. */}},[visibleCols,sort]);
 useEffect(()=>setPage(0),[filter,channel,query,sort]);
 const rows:Data[]=data?.rows||[];
 const counts=useMemo(()=>Object.fromEntries(filters.map(([key])=>[key,rows.filter(r=>match(r,key)).length])),[rows]);
 const selectedCols=visibleCols.map(k=>columns.find(c=>c.key===k)!).filter(Boolean);
 const selected=useMemo(()=>rows.filter(r=>match(r,filter)&&(channel==='all'||(r.kind==='shopee'?'shopee':r.channel||'whatsapp')===channel)&&(!query||[r.customer_name,r.phone,shopeeUsername(r),r.reference,r.action,r.note,r.missing_details,r.chat.preview,...(r.items||[]).map((i:Data)=>`${i.title} ${i.sku} ${i.wording}`)].join(' ').toLowerCase().includes(query))).sort((a,b)=>{for(const s of sort){const x=value(a,s.key),y=value(b,s.key);if(x==null&&y!=null)return 1;if(y==null&&x!=null)return -1;if(x===y)continue;const n=typeof x==='number'&&typeof y==='number'?x-y:String(x||'').localeCompare(String(y||''),'ms',{numeric:true});if(n)return n*s.direction;}return a.key.localeCompare(b.key);}),[rows,filter,channel,query,sort]);
 const safePage=Math.min(page,Math.max(0,Math.ceil(selected.length/50)-1)),shown=selected.slice(safePage*50,safePage*50+50);
 function setOrdering(k:string,multi=false){setSort(old=>{const existing=old.find(s=>s.key===k),next={key:k,direction:existing?.direction===1?-1:1};return multi?[...old.filter(s=>s.key!==k),next]:[next];});}
 function edit(r:Data){setEditing(r);setEditError('');setForm({...r.state.data,detail_status:r.detail_status,missing_details:r.missing_details,note:r.note,urgent:r.state.data.urgent===true,work_state:r.manual_work||'',customer_needed:dayInput(r.customer_needed),dispatch_by:dayInput(r.dispatch_by),design_by:dayInput(r.design_by),snoozed_until:dayInput(r.snoozed_until)});}
 async function save(){if(!editing)return;setSaving(true);setEditError('');try{const update={...form};for(const k of ['customer_needed','dispatch_by','design_by','snoozed_until'])update[k]=form[k]?`${form[k]}T${k==='design_by'?'12:00:00':k==='snoozed_until'?'08:30:00':'16:00:00'}+08:00`:null;await call({action:'focus_save',row_key:editing.key,expected_version:editing.state.version,source_fingerprint:editing.source_fingerprint,request_id:crypto.randomUUID(),data:update});setEditing(null);setNotice('Tindakan panel disimpan. Status order, bayaran dan ClickUp kekal mengikut sumber masing-masing.');await load();}catch(e){setEditError(e instanceof Error?e.message:String(e));}finally{setSaving(false);}}
 async function copyText(text:string,label:string){try{if(navigator.clipboard?.writeText)await navigator.clipboard.writeText(text);else{const el=document.createElement('textarea');el.value=text;el.style.position='fixed';el.style.opacity='0';document.body.appendChild(el);try{el.select();if(!document.execCommand('copy'))throw Error('Clipboard unavailable');}finally{el.remove();}}setNotice(`${label} disalin.`);}catch{setNotice(`Tak dapat salin ${label.toLowerCase()}. Cuba pilih dan salin teks.`);}}
 function copyButton(text:string,label:string){return <button type="button" className="focus-icon-button" title={`Salin ${label.toLowerCase()}: ${text}`} aria-label={`Salin ${label.toLowerCase()} ${text}`} onClick={()=>void copyText(text,label)}><FocusIcon name="copy"/></button>;}
 function exportCsv(){const fields=['customer_name','reference','priority_label','action','payment_label','detail_status','missing_details','focus_due','customer_needed','dispatch_by','design_by','platform_deadline','courier','shipment_status','tracking','note'];const esc=(v:unknown)=>{let t=String(v??'');if(/^[=+\-@\t\r]/.test(t))t="'"+t;return '"'+t.replaceAll('"','""')+'"';};const text='\uFEFF'+[fields.map(esc).join(','),...selected.map(r=>fields.map(k=>esc(r[k])).join(','))].join('\r\n');const url=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='fokus-customer.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function cell(r:Data,k:string){const tasks:Data[]=r.production_tasks||[];switch(k){
  case'priority':return <><span className={`focus-pill priority-${r.priority}`}>{r.priority_label}</span><small>{r.priority_reason}</small>{r.manual_expired?<small className="focus-warning">Status sumber berubah; tanda kerja lama tidak digunakan.</small>:null}</>;
  case'customer':{const shopee=r.kind==='shopee'||r.channel==='shopee',username=shopeeUsername(r),phone=whatsappPhone(r.phone),delivery=deliveryType(r);return <><strong>{r.customer_name||'Customer belum dipadankan'}</strong><div className="focus-badges"><span className={`focus-badge ${shopee?'focus-shopee':'focus-deco'}`} title={r.kind==='chat'?'Channel pertanyaan':r.kind==='draft'?'Draft iCetak / Deco':'Sumber order'}><FocusIcon name={shopee?'shopee':r.kind==='chat'?'chat':'store'}/>{shopee?'Shopee':r.kind==='chat'?'WhatsApp':r.kind==='draft'?'Draft Deco':'iCetak / Deco'}</span>{delivery?<span className={`focus-badge focus-${delivery}`} title={delivery==='pickup'?'Ambil sendiri / pickup':'Penghantaran melalui courier'}><FocusIcon name={delivery==='pickup'?'pickup':'post'}/>{delivery==='pickup'?'Pickup':'Pos'}</span>:null}</div>{username?<div className="focus-identity-line"><span className="focus-username" title="Username Shopee">@{username.replace(/^@/,'')}</span>{copyButton(username,'Username Shopee')}</div>:null}{r.phone?<div className="focus-identity-line"><span>{r.phone}</span>{copyButton(String(r.phone),'Nombor telefon')}</div>:null}{phone&&r.chat.identity_status!=='ambiguous'?<div className="focus-phone-actions"><a href={`whatsapp://send?phone=${phone}`} title={`Buka WhatsApp app: ${phone}`} aria-label={`WhatsApp app ${phone}`}><FocusIcon name="app"/>WA app</a><a href={`https://wa.me/${phone}`} target="_blank" rel="noopener noreferrer" title={`Buka wa.me: ${phone}`} aria-label={`WhatsApp wa.me ${phone}`}><FocusIcon name="external"/>wa.me</a></div>:null}{r.chat.identity_status==='ambiguous'?<small className="focus-warning">Identiti bertindih · semak CRM</small>:null}</>;}
  case'reference':return <><div className="focus-reference-line"><button className="focus-text-button" disabled={r.kind==='chat'} onClick={()=>r.kind==='draft'?onOpenDrafts(r.phone||r.customer_name):r.kind==='shopee'?onOpenMarketplace(r.reference):onOpenOrder(r.reference)}>{r.reference}</button>{r.kind!=='chat'&&r.reference&&!['Draft','Pertanyaan'].includes(r.reference)?copyButton(r.reference,'Order ID'):null}</div>{(r.items||[]).map((i:Data,n:number)=><small key={n}>{i.quantity||1}× {i.title}{i.size?` · ${i.size}`:''}{i.sku?` · ${i.sku}`:''}{i.wording?` · ${i.wording}`:''}</small>)}<small>{r.status}</small>{r.order_note?<small>Nota order: {r.order_note}</small>:null}{r.kind==='chat'&&r.chat.related_references?.length?<><small>Order rujukan · belum disahkan untuk chat ini:</small>{r.chat.related_references.map((ref:string)=><div key={ref} className="focus-identity-line"><span>{ref}</span>{copyButton(ref,'Order ID rujukan')}</div>)}</>:null}</>;
  case'action':return <><strong>{r.action}</strong><small>{r.reason}</small><div className="focus-row-actions">{r.chat.id?<button onClick={()=>onOpenChat(r.chat.id)}>Buka chat</button>:null}{r.kind!=='chat'?<button onClick={()=>r.kind==='draft'?onOpenDrafts(r.phone||r.customer_name):r.kind==='shopee'?onOpenMarketplace(r.reference):onOpenOrder(r.reference)}>Order</button>:null}<button disabled={!data?.capabilities?.can_manage||loading||!!error} onClick={()=>edit(r)}>Urus</button></div></>;
  case'payment':return <><span className={r.work.paid?'focus-paid':''}>{r.payment_label}</span><small>{r.kind==='chat'?'Order belum dipadankan':money(r.amount)}</small></>;
  case'details':return <><span>{r.detail_status==='complete'?'Detail disahkan lengkap':r.detail_status==='missing'?'Detail belum lengkap':'Perlu semak detail'}</span><small>{r.missing_details||'—'}</small></>;
  case'chat':return <><strong>{r.chat.state}</strong>{r.kind!=='chat'&&r.chat.id&&!r.chat.order_confirmed?<small>Chat customer · order untuk mesej ini belum disahkan</small>:null}<small className="focus-chat-preview">{r.chat.preview||'Tiada chat yang menyebut order ini dipadankan.'}</small><small>{date(r.chat.at)}</small></>;
  case'focus_due':return <><strong>{date(r.focus_due)}</strong><small>{r.due_source||'Tarikh kerja belum ditetapkan'}</small>{r.overdue?<small className="focus-warning">Lewat</small>:null}</>;
  case'clickup_due':case'customer_needed':case'dispatch_by':case'design_by':case'platform_deadline':return <>{k==='customer_needed'&&r[k]?new Date(r[k]).toLocaleDateString('ms-MY',{timeZone:'Asia/Kuala_Lumpur',day:'numeric',month:'short',year:'numeric'}):date(r[k])}<small>{k==='customer_needed'?'Tarikh perlu; bukan jaminan courier':k==='clickup_due'?'Set belum siap design':k==='platform_deadline'?'Daripada platform':k==='design_by'?'Target 12 tengah hari':'Target 4 petang'}</small></>;
  case'clickup':return tasks.length?<>{tasks.map(t=><div key={t.id} className="focus-task">{safeLink(t.url)?<a href={safeLink(t.url)!} target="_blank" rel="noreferrer">{(t.set_labels||[]).join(', ')||t.title||'Task'}</a>:<strong>{t.title||'Komponen'}</strong>}<small>{t.status||'Status belum diketahui'} · {t.review_status||'Tiada review'}</small><small>Due: {date(t.due_at)} · Perlu: {date(t.needed_at)}</small><small>Sync: {date(t.source_updated_at)}</small></div>)}</>:<span>Belum ada task dipadankan</span>;
  case'courier':return <><strong>{r.courier||r.delivery_method||'Belum ditetapkan'}</strong><small>{r.shipment_status||(r.logistics||[])[0]?.status||'Status courier belum tersedia'}</small>{r.tracking?<div className="focus-identity-line"><span>{r.tracking}</span>{copyButton(r.tracking,'Tracking')}</div>:<small>Tiada tracking</small>}</>;
  case'note':return <>{r.note||'—'}<small>Sumber: {date(r.source_updated_at)}</small>{r.state.updated_by?<small>Panel: {r.state.updated_by} · {date(r.state.updated_at)}</small>:null}</>;
  default:return date(r.created_at);
 }}
 return <section className="customer-focus">
  <div className="focus-heading"><div><h2>Fokus Customer</h2><p>Mulakan dengan Fokus hari ini. Kerja kemudian dan rekod lama ada filter sendiri.</p></div><div className="focus-controls"><label><input type="checkbox" checked={auto} onChange={e=>setAuto(e.target.checked)}/> Auto semak 60s</label><button disabled={loading||!!editing} onClick={()=>void load()}>{loading?'Sedang semak…':'Muat semula'}</button><button disabled={!data||loading} onClick={exportCsv}>Eksport CSV</button></div></div>
  {error?<div role="alert" className="focus-error">{error}{data?' · Data lama masih dipaparkan; tindakan simpan dijeda.':''}</div>:null}{notice?<div role="status" className="focus-notice">{notice}<button onClick={()=>setNotice('')} aria-label="Tutup notis">×</button></div>:null}
  <div className="focus-filters" role="group" aria-label="Filter Fokus Customer">{filters.map(([key,label])=><button key={key} aria-pressed={filter===key} onClick={()=>setFilter(key)}>{label} <b>{counts[key]||0}</b></button>)}</div>
  <div className="focus-toolbar"><input aria-label="Cari customer atau order" placeholder="Cari nama, telefon, order, SKU, wording atau mesej…" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Channel Fokus Customer" value={channel} onChange={e=>setChannel(e.target.value)}><option value="all">Semua channel</option><option value="shopee">Shopee</option><option value="whatsapp">WhatsApp / Deco</option></select><button aria-expanded={colOpen} onClick={()=>setColOpen(v=>!v)}>Kolum & susunan</button><button onClick={()=>{setSort(defaultSort);setVisibleCols(defaultColumns);}}>Reset paparan</button></div>
  {colOpen?<div className="focus-column-settings"><div><strong>Kolum dipaparkan</strong>{columns.map(c=><label key={c.key}><input type="checkbox" checked={visibleCols.includes(c.key)} disabled={c.key==='customer'} onChange={e=>setVisibleCols(old=>e.target.checked?[...old,c.key]:old.filter(k=>k!==c.key))}/>{c.label}</label>)}</div><div><strong>Susunan kolum</strong>{visibleCols.map((k,n)=><div key={k}>{columns.find(c=>c.key===k)?.label}<button aria-label={`Naik kolum ${k}`} disabled={n===0} onClick={()=>setVisibleCols(old=>{const a=[...old];[a[n-1],a[n]]=[a[n],a[n-1]];return a;})}>↑</button><button aria-label={`Turun kolum ${k}`} disabled={n===visibleCols.length-1} onClick={()=>setVisibleCols(old=>{const a=[...old];[a[n+1],a[n]]=[a[n],a[n+1]];return a;})}>↓</button></div>)}</div></div>:null}
  <div className="focus-sort"><span>Sort:</span>{sort.map((s,n)=><span key={s.key}>{n+1}. {columns.find(c=>c.key===s.key)?.label} {s.direction===1?'↑':'↓'}<button aria-label={`Buang sort ${s.key}`} disabled={sort.length===1} onClick={()=>setSort(old=>old.filter(v=>v.key!==s.key))}>×</button></span>)}<select aria-label="Tambah sort" value="" onChange={e=>{const key=e.target.value;if(key)setSort(old=>[...old.filter(s=>s.key!==key),{key,direction:1}]);}}><option value="">+ Kolum sort</option>{columns.map(c=><option key={c.key} value={c.key}>{c.label}</option>)}</select><small>Klik tajuk kolum untuk sort · Shift + klik untuk tambah sort.</small></div>
  <div className="focus-meta"><span>{selected.length} baris sepadan · {shown.length} dipaparkan</span><span>Disemak {date(data?.fetched_at)} MYT</span></div>
  {filter==='actionable'?<p className="focus-meta">Kerja aktif tanpa tarikh / perlu siap hari ini atau esok, detail order, chat masuk 24 jam dan aduan terkini. Order selesai tidak guna deadline pos lama.</p>:filter==='backlog'?<p className="focus-meta">Rekod lama untuk semakan sahaja. Dikeluarkan daripada fokus; status order asal tidak ditanda selesai.</p>:null}
  {data?.coverage?.truncated?<div className="focus-error">Liputan mencapai had bacaan. Senarai ini belum meliputi semua rekod.</div>:null}
  {loading&&!data?<div className="focus-loading">Menggabungkan order, bayaran, chat, ClickUp dan courier…</div>:<div className="focus-table-wrap"><table className="focus-table" style={{width:selectedCols.reduce((n,c)=>n+c.width,0)}}><colgroup>{selectedCols.map(c=><col key={c.key} style={{width:c.width}}/>)}</colgroup><thead><tr>{selectedCols.map(c=><th key={c.key} style={{minWidth:c.width}} className={c.key==='customer'?'focus-customer-col':''} aria-sort={sort[0]?.key===c.key?(sort[0].direction===1?'ascending':'descending'):'none'}><button onClick={e=>setOrdering(c.key,e.shiftKey)}>{c.label} {sort.some(s=>s.key===c.key)?`${sort.findIndex(s=>s.key===c.key)+1}${sort.find(s=>s.key===c.key)?.direction===1?'↑':'↓'}`:'↕'}</button></th>)}</tr></thead><tbody>{shown.map(r=><tr key={r.key} data-focus-key={r.key} className={r.priority===0?'focus-urgent-row':''}>{selectedCols.map(c=><td key={c.key} className={c.key==='customer'?'focus-customer-col':''}>{cell(r,c.key)}</td>)}</tr>)}{!shown.length?<tr><td colSpan={selectedCols.length} className="focus-empty">{data?'Tiada customer untuk filter ini.':'Data belum tersedia. Tekan Muat semula.'}</td></tr>:null}</tbody></table></div>}
  <div className="focus-pagination"><button disabled={safePage===0} onClick={()=>setPage(safePage-1)}>Sebelum</button><span>Halaman {safePage+1} / {Math.max(1,Math.ceil(selected.length/50))}</span><button disabled={(safePage+1)*50>=selected.length} onClick={()=>setPage(safePage+1)}>Seterusnya</button></div>
  {data?<details className="focus-coverage"><summary>Liputan & status sync</summary><p>{data.coverage.orders} order · {data.coverage.drafts||0} draft aktif · {data.coverage.chats} perbualan dibaca sebelum sort/filter. Chat menggunakan {data.coverage.chat_messages} mesej terkini; balasan luar sistem mungkin belum direkodkan. Fokus chat biasa ialah 24 jam; filter Semak / balas chat meliputi 7 hari. Chat lebih lama dan order tanpa kerja semasa diasingkan dalam Rekod lama.</p><p>ClickUp terakhir: {date(data.coverage.clickup?.latest_event_at)} · {data.coverage.clickup?.unlinked||0} task belum dipadankan. Sumber ikut webhook dan replay snapshot tersimpan; tarikh pada setiap task menunjukkan usia status.</p><p>Tanda kerja dalam panel tidak mengubah bayaran, status courier atau task ClickUp. Perubahan status sumber membatalkan tanda kerja lama. Tiada mesej dihantar apabila membuka chat, menyimpan atau menyalin.</p></details>:null}
  {editing?<div className="focus-modal-backdrop"><section role="dialog" aria-modal="true" aria-labelledby="focus-edit-title" className="focus-modal"><h3 id="focus-edit-title">Urus {editing.customer_name} · {editing.reference}</h3><p>Tetapkan tindakan dan tarikh untuk panel ini.</p><form onSubmit={e=>{e.preventDefault();void save();}}><label>Detail order<select value={form.detail_status} onChange={e=>setForm(f=>({...f,detail_status:e.target.value}))}><option value="unknown">Perlu semak</option><option value="missing">Belum lengkap</option><option value="complete">Disahkan lengkap</option></select></label><label>Detail yang masih kurang<input maxLength={2000} value={form.missing_details||''} onChange={e=>setForm(f=>({...f,missing_details:e.target.value}))} placeholder="Contoh: gambar dan wording"/></label><label>Tindakan / peringkat panel<select value={form.work_state} onChange={e=>setForm(f=>({...f,work_state:e.target.value}))}><option value="">Ikut status sumber</option><option value="waiting">Detail diminta / menunggu customer</option>{!['chat','draft'].includes(editing.kind)&&!['IN_CANCEL','UNKNOWN'].includes(editing.status)?<><option value="design_done">Design ditanda siap dalam panel</option><option value="production_done">Production ditanda siap dalam panel</option></>:null}<option value="handled">Tindakan saya selesai</option></select></label><label className="focus-inline"><input type="checkbox" checked={!!form.urgent} onChange={e=>setForm(f=>({...f,urgent:e.target.checked}))}/> Utamakan customer ini (urgent)</label><div className="focus-edit-dates">{[['customer_needed','Customer perlu'],['dispatch_by','Janji pos / pickup'],['design_by','Design perlu siap'],['snoozed_until','Tangguh hingga']].map(([key,label])=><label key={key}>{label}<input type="date" value={form[key]||''} onChange={e=>setForm(f=>({...f,[key]:e.target.value}))}/></label>)}</div><small>Waktu MYT: design 12:00, pos/pickup 16:00, sambung selepas tangguh 08:30. Deadline platform {date(editing.platform_deadline)} kekal daripada sumber.</small><label>Nota admin<textarea rows={3} maxLength={2000} value={form.note||''} onChange={e=>setForm(f=>({...f,note:e.target.value}))}/></label>{editError?<div role="alert" className="focus-error">{editError}</div>:null}<div className="focus-modal-actions"><button type="button" disabled={saving} onClick={()=>{if(JSON.stringify(form)!==JSON.stringify({...editing.state.data,detail_status:editing.detail_status,missing_details:editing.missing_details,note:editing.note,urgent:editing.state.data.urgent===true,work_state:editing.manual_work||'',customer_needed:dayInput(editing.customer_needed),dispatch_by:dayInput(editing.dispatch_by),design_by:dayInput(editing.design_by),snoozed_until:dayInput(editing.snoozed_until)})&&!window.confirm('Buang perubahan yang belum disimpan?'))return;setEditing(null);}}>Batal</button><button type="submit" disabled={saving}>{saving?'Menyimpan…':'Simpan tindakan'}</button></div></form></section></div>:null}
 </section>;
}
