import { useCallback, useEffect, useRef, useState } from 'react';
import { IconRefresh } from '../components/Icons';
import { supabase } from '../lib/supabase';
import { DraftMetrics, DraftGraphs, malaysiaToday, moveDraftPeriod, sourceLabel, outcomeLabel, type DraftReport, type DraftFilters } from './DraftAnalytics';
import './DraftOrders.css';

type Draft={
  id:string;status:string;source_type:string;customer_name:string|null;customer_phone:string|null;
  customer_bsuid:string|null;customer_username:string|null;conversation_id:string|null;
  draft_total:number|string;payment_status:string;payment_required:boolean;payment_mode:string;transaction_id:string|null;
  payment_amount:number|string|null;review_token:string;admin_approved_at:string|null;
  customer_confirmed_at:string|null;date_need:string|null;delivery:string|null;item_count:number;
  created_at:string;updated_at:string;payment_available:boolean|null;
  customer_link_sent_at?:string|null;converted_at?:string|null;cohort_at?:string;
  order_id?:string|null;order_no?:string|null;order_status?:string|null;order_payment_status?:string|null;
  outcome?:string;cancel_reason_label?:string|null;
  rejected_at?:string|null;rejected_by?:string|null;cancel_reason_code?:string|null;cancel_reason_detail?:string|null;
  cancel_source?:string|null;followup_count?:number;shopee_match?:{status:string;order_sn:string;reason?:string}|null;
};
type CancelReason={code:string;label:string;requires_detail:boolean};
type DraftData=DraftReport & {reasons?:CancelReason[];drafts:Draft[]};
type ApiResponse<T>={success:boolean;data?:T;error?:string};
type FlowDraft={delivery:string;payment_mode:string};
type ManualDraftForm={customer_name:string;customer_phone:string;date_need:string;delivery:string;payment_mode:string};
const money=(v:number|string|null)=>`RM ${Number(v||0).toFixed(2)}`;
const when=(v:string)=>new Date(v).toLocaleString('en-MY',{timeZone:'Asia/Kuala_Lumpur',dateStyle:'medium',timeStyle:'short'});
const defaultManual:ManualDraftForm={customer_name:'',customer_phone:'',date_need:'',delivery:'unknown',payment_mode:'prepaid'};
async function finance<T>(body:Record<string,unknown>){
  const {data,error}=await supabase.functions.invoke('finance-admin',{body});
  if(error)throw new Error(error.message);
  return data as ApiResponse<T>;
}
async function draftControl<T>(body:Record<string,unknown>){
  const {data,error}=await supabase.functions.invoke('admin-draft-control',{body});
  if(error)throw new Error(error.message);
  return data as ApiResponse<T>;
}
export default function DraftOrders({canManage=false,onOpenOrder,onCreateOrder,embedded=false,initialQuery=''}:{canManage?:boolean;onOpenOrder?:(orderNo:string)=>void;onCreateOrder?:()=>void;embedded?:boolean;initialQuery?:string}){
  const [data,setData]=useState<DraftData|null>(null);
  const [query,setQuery]=useState(initialQuery);
  const [filters,setFilters]=useState<DraftFilters>({period:'month',date:malaysiaToday(),date_basis:'created',state:'all',status:'all',source:'all',payment_mode:'all',delivery:'all',reason:'all',sort:'newest',offset:0});
  const [view,setView]=useState<'list'|'cards'|'graphs'>('list');const [expanded,setExpanded]=useState<string|null>(null);
  const requestId=useRef(0);
  const changeFilter=(patch:Partial<DraftFilters>)=>{requestId.current++;setLoading(true);setError('');setFilters(x=>({...x,...patch,offset:patch.offset??0}));setExpanded(null)};
  const [loading,setLoading]=useState(true);const [busy,setBusy]=useState<string|null>(null);
  const [error,setError]=useState('');const [links,setLinks]=useState<Record<string,string>>({});
  const [flows,setFlows]=useState<Record<string,FlowDraft>>({});
  const [manualDraft,setManualDraft]=useState<Draft|null>(null);const [manualMethod,setManualMethod]=useState('bank_transfer');const [manualReference,setManualReference]=useState('');
  const [createOpen,setCreateOpen]=useState(false);const [createForm,setCreateForm]=useState<ManualDraftForm>(defaultManual);
  const [cancelTarget,setCancelTarget]=useState<Draft|null>(null);const [cancelReason,setCancelReason]=useState('');const [cancelDetail,setCancelDetail]=useState('');
  const load=useCallback(async()=>{const current=++requestId.current;setLoading(true);setError('');try{
    const r=await finance<DraftData>({action:'draft_report',...filters,query});
    if(!r.success||!r.data)throw new Error(r.error||'Draft report failed');if(current===requestId.current){
      if(r.data.pagination.total>0&&r.data.pagination.offset>=r.data.pagination.total){setFilters(x=>({...x,offset:Math.floor((r.data!.pagination.total-1)/50)*50}));return}
      setData(r.data);
    }
  }catch(e){if(current===requestId.current)setError(e instanceof Error?e.message:'Draft report failed')}finally{if(current===requestId.current)setLoading(false)}},[query,filters]);
  useEffect(()=>{const t=window.setTimeout(()=>void load(),250);return()=>{window.clearTimeout(t);requestId.current++}},[load]);
  const edit=(d:Draft)=>window.open(`https://shop.decocake.my/qrpay-draft.html?token=${encodeURIComponent(d.review_token)}`,'_blank','noopener,noreferrer');
  const detach=async(d:Draft)=>{if(!d.transaction_id||!confirm(`Detach ${d.transaction_id} daripada draft ${d.customer_name||d.id}?\n\nPayment tidak dipadam dan akan kembali ke Needs Review.`))return;
    setBusy(d.id);setError('');try{const r=await finance({action:'draft_detach_payment',draft_id:d.id});if(!r.success)throw new Error(r.error||'Detach failed');await load()}catch(e){setError(e instanceof Error?e.message:'Detach failed')}finally{setBusy(null)}};
  const cancelDraft=async()=>{if(!cancelTarget||!cancelReason)return setError('Pilih sebab pembatalan.');const selected=(data?.reasons||[]).find(x=>x.code===cancelReason);if(selected?.requires_detail&&!cancelDetail.trim())return setError('Isi sebab lain-lain dahulu.');
    setBusy(cancelTarget.id);setError('');try{const r=await finance({action:'draft_cancel',review_token:cancelTarget.review_token,reason_code:cancelReason,reason_detail:cancelDetail.trim()||null});if(!r.success)throw new Error(r.error||'Cancel draft failed');setCancelTarget(null);setCancelReason('');setCancelDetail('');await load()}catch(e){setError(e instanceof Error?e.message:'Cancel draft failed')}finally{setBusy(null)}};
  const reopenDraft=async(d:Draft)=>{if(!confirm(`Buka semula draft ${d.customer_name||d.id}?`))return;setBusy(d.id);setError('');try{const r=await finance({action:'draft_reopen',draft_id:d.id});if(!r.success)throw new Error(r.error||'Reopen draft failed');await load()}catch(e){setError(e instanceof Error?e.message:'Reopen draft failed')}finally{setBusy(null)}};
  const manualPaid=async()=>{if(!manualDraft)return;if(!confirm(`Sahkan ${manualDraft.customer_name||manualDraft.id} sudah dibayar? Ini akan terus create order, tandakan Paid, masuk production dan hantar ke ClickUp.`))return;
    setBusy(manualDraft.id);setError('');try{const r=await finance({action:'draft_manual_paid',review_token:manualDraft.review_token,payment_method:manualMethod,reference:manualReference.trim()});if(!r.success)throw new Error(r.error||'Manual payment failed');setManualDraft(null);setManualReference('');await load()}catch(e){setError(e instanceof Error?e.message:'Manual payment failed')}finally{setBusy(null)}};
  const link=async(d:Draft,confirmed=false)=>{const tx=(links[d.id]||'').trim();if(!tx)return setError('Masukkan QRPay transaction ID dahulu.');
    if(!confirm(`Link ${tx} kepada draft ${d.customer_name||d.id} dan CREATE ORDER?`))return;
    setBusy(d.id);setError('');try{
      let r=await finance<{success?:boolean;requires_confirmation?:boolean;requires_mismatch_confirmation?:boolean;order_no?:string}>({action:'draft_link_payment',draft_id:d.id,transaction_id:tx,confirm_mismatch:confirmed});
      if(!r.success&&(r.data?.requires_confirmation||r.data?.requires_mismatch_confirmation)){
        if(confirm('Phone atau jumlah tidak sepadan. Teruskan dengan amaran?'))r=await finance<{success?:boolean;requires_confirmation?:boolean;requires_mismatch_confirmation?:boolean;order_no?:string}>({action:'draft_link_payment',draft_id:d.id,transaction_id:tx,confirm_mismatch:true});
      }
      if(!r.success)throw new Error(r.error||'Link payment failed');
      const orderNo=(r.data as {order_no?:string}|undefined)?.order_no; if(orderNo&&onOpenOrder)onOpenOrder(orderNo);else await load();
    }catch(e){setError(e instanceof Error?e.message:'Link payment failed')}finally{setBusy(null)}};
  const createManual=async()=>{if(createForm.payment_mode==='cash_counter'&&!['pickup','unknown'].includes(createForm.delivery))return setError('Cash at Counter hanya untuk Pickup.');
    setBusy('create');setError('');try{const r=await draftControl<Draft>({action:'create_manual',...createForm,date_need:createForm.date_need||null});if(!r.success||!r.data)throw new Error(r.error||'Create manual draft failed');setCreateOpen(false);setCreateForm(defaultManual);await load();edit(r.data)}catch(e){setError(e instanceof Error?e.message:'Create manual draft failed')}finally{setBusy(null)}};
  const setFlow=async(d:Draft)=>{const f=flows[d.id]||{delivery:d.delivery||'pickup',payment_mode:d.payment_mode||'prepaid'};if(f.payment_mode==='cash_counter'&&f.delivery!=='pickup')return setError('Cash at Counter hanya untuk Pickup.');
    setBusy(d.id);setError('');try{const r=await draftControl<Draft>({action:'set_flow',review_token:d.review_token,delivery:f.delivery,payment_mode:f.payment_mode});if(!r.success)throw new Error(r.error||'Update draft flow failed');await load()}catch(e){setError(e instanceof Error?e.message:'Update draft flow failed')}finally{setBusy(null)}};
  const flow=(d:Draft)=>flows[d.id]||{delivery:d.delivery&&d.delivery!=='unknown'?d.delivery:'pickup',payment_mode:d.payment_mode||'prepaid'};
  const renderCard=(d:Draft)=>{const f=flow(d);return <article className="draft-card" key={d.id}>
      <div className="draft-card-top"><div><span className="draft-status">{d.status.replaceAll('_',' ')}</span><h2>{d.customer_name||'Customer belum dikenal pasti'}</h2><div className="draft-contact-links">{d.customer_phone?<><a href={`tel:${d.customer_phone}`}>☎ {d.customer_phone}</a><a href={`https://wa.me/${d.customer_phone.replace(/\D/g,'')}`} target="_blank" rel="noreferrer">WhatsApp</a></>:d.customer_username?<a href={`https://wa.me/${encodeURIComponent(d.customer_username.replace(/^@+/,''))}`} target="_blank" rel="noreferrer">@{d.customer_username.replace(/^@+/,'')}</a>:<span>Phone tidak dikongsi</span>}{d.customer_bsuid&&<small title={d.customer_bsuid}>ID: {d.customer_bsuid}</small>}</div></div><strong>{money(d.draft_total)}</strong></div>
      <div className="draft-meta"><span>{d.source_type.replaceAll('_',' ')}</span><span>{d.item_count} item</span><span>{d.date_need||'Date belum pilih'}</span><span>{d.delivery&&d.delivery!=='unknown'?d.delivery:'Delivery belum pilih'}</span><span>{d.payment_mode==='cash_counter'?'Cash at Counter':'Prepaid'}</span><span>{when(d.updated_at)}</span></div>
      {d.status!=='rejected'&&d.shopee_match?.status==='needs_review'&&<div className="draft-cancelled-info"><b>Shopee order detected — semakan admin</b><span>Order ID: {d.shopee_match.order_sn}</span><small>{d.shopee_match.reason==='multiple_drafts'?'Ada beberapa draft untuk telefon sama. Pilih draft berkaitan untuk cancel.':'Padanan identiti perlu disemak.'} Follow-up dijeda.</small></div>}
      {d.order_id?<div className="draft-payment"><b>{outcomeLabel(d.outcome||'order_unpaid')} · {d.order_no||'Order linked'}</b><small>{d.order_status} · {d.order_payment_status}</small></div>:d.status==='rejected'?<div className="draft-cancelled-info"><b>{(data?.reasons||[]).find(x=>x.code===d.cancel_reason_code)?.label||d.cancel_reason_code||'Cancelled'}</b>{d.cancel_reason_detail&&<span>{d.cancel_reason_detail}</span>}<small>{d.cancel_source==='automation'?'Auto-cancel':'Dibatalkan oleh '+(d.rejected_by||'admin')} · {d.rejected_at?when(d.rejected_at):'-'} · {d.followup_count||0} follow-up</small></div>:<>
      {d.transaction_id?<div className="draft-payment wrong"><div><span>QRPay linked</span><b>{d.transaction_id} · {money(d.payment_amount)}</b></div><small>Pastikan payment memang milik customer ini.</small></div>:<div className="draft-payment"><span>{d.payment_mode==='cash_counter'?'Bayar di kaunter — production boleh approve sebelum bayaran.':'Belum ada payment linked'}</span></div>}
      {canManage&&!d.order_id&&d.source_type!=='qrpay_payment'&&!d.transaction_id&&<div className="draft-flow"><div><label>Delivery<select value={f.delivery} onChange={e=>setFlows(x=>({...x,[d.id]:{...f,delivery:e.target.value}}))}><option value="pickup">Pickup</option><option value="spx">SPX</option><option value="jnt">J&amp;T</option><option value="ninja">Ninja Van</option></select></label><label>Payment flow<select value={f.payment_mode} onChange={e=>setFlows(x=>({...x,[d.id]:{...f,payment_mode:e.target.value}}))}><option value="prepaid">Prepaid</option><option value="cash_counter">Cash at Counter</option></select></label></div><button className="btn btn-outline" disabled={busy===d.id} onClick={()=>void setFlow(d)}>{busy===d.id?'Updating…':'Apply Flow'}</button><small>Source asal kekal untuk audit. Flow delivery/payment boleh berubah tanpa trigger semula.</small></div>}
      </>}
      <div className="draft-actions"><button className="btn btn-outline" onClick={()=>edit(d)}>Open / Edit Draft</button>{d.order_id?onOpenOrder&&d.order_no&&<button className="btn btn-primary" onClick={()=>onOpenOrder(d.order_no!)}>Open Order {d.order_no}</button>:d.status==='rejected'?canManage&&<button className="btn btn-primary" disabled={busy===d.id} onClick={()=>void reopenDraft(d)}>Reopen Draft</button>:<>{canManage&&!d.transaction_id&&d.payment_mode!=='cash_counter'&&<button className="btn btn-outline" disabled={busy===d.id||Number(d.draft_total)<=0} onClick={()=>{setManualDraft(d);setManualMethod('bank_transfer');setManualReference('')}}>Manual Payment</button>}{canManage&&d.transaction_id&&<button className="btn btn-danger" disabled={busy===d.id} onClick={()=>void detach(d)}>Detach QRPay</button>}{canManage&&<button className="btn btn-danger" disabled={busy===d.id} onClick={()=>{setCancelTarget(d);setCancelReason('');setCancelDetail('')}}>Cancel Draft</button>}</>}</div>
      {!d.order_id&&d.status!=='rejected'&&canManage&&!d.transaction_id&&d.payment_mode!=='cash_counter'&&<div className="draft-link"><input value={links[d.id]||''} onChange={e=>setLinks(x=>({...x,[d.id]:e.target.value}))} placeholder="Contoh QR02086824"/><button className="btn btn-primary" disabled={busy===d.id||!(links[d.id]||'').trim()} onClick={()=>void link(d)}>Link Payment & Create Order</button><small>Edit dan Save Draft dahulu. Link akan terus create order + production + ClickUp.</small></div>}
    </article>};
  return <div className="draft-orders-page">
    {embedded?<div className="draft-embedded-actions">{canManage&&<button className="btn btn-primary" onClick={()=>onCreateOrder?onCreateOrder():(setCreateForm(defaultManual),setCreateOpen(true))}>+ Create Order</button>}<button className="btn btn-outline" onClick={()=>void load()} disabled={loading}><IconRefresh size={16}/> Refresh</button></div>:<div className="draft-orders-head"><div><h1>Draft Orders</h1><p>Draft boleh datang daripada trigger atau dibuat melalui Create Order. Semak flow, edit dan approve sebelum production.</p></div><div className="draft-head-actions">{canManage&&<button className="btn btn-primary" onClick={()=>onCreateOrder?onCreateOrder():(setCreateForm(defaultManual),setCreateOpen(true))}>+ Create Order</button>}<button className="btn btn-outline" onClick={()=>void load()} disabled={loading}><IconRefresh size={16}/> Refresh</button></div></div>}
    <div className="draft-report-toolbar"><div className="draft-view-switch" role="group" aria-label="Draft view">{(['list','cards','graphs'] as const).map(v=><button key={v} aria-pressed={view===v} onClick={()=>setView(v)}>{v==='list'?'List view':v==='graphs'?'Graf view':'Card view'}</button>)}</div><div className="draft-period-switch" role="group" aria-label="Analysis period">{(['day','week','month'] as const).map(p=><button key={p} aria-pressed={filters.period===p} onClick={()=>changeFilter({period:p})}>{p==='day'?'Day':p==='week'?'Week':'Month'}</button>)}</div></div>
    <div className="draft-period-controls"><button className="btn btn-outline" aria-label="Previous period" onClick={()=>changeFilter({date:moveDraftPeriod(filters.date,filters.period,-1)})}>‹</button><label>{filters.period==='month'?'Bulan':'Tarikh rujukan'}<input aria-label={filters.period==='month'?'Bulan':'Tarikh rujukan'} type={filters.period==='month'?'month':'date'} value={filters.period==='month'?filters.date.slice(0,7):filters.date} onChange={e=>{if(e.target.value)changeFilter({date:filters.period==='month'?e.target.value+'-01':e.target.value})}}/></label><button className="btn btn-outline" aria-label="Next period" onClick={()=>changeFilter({date:moveDraftPeriod(filters.date,filters.period,1)})}>›</button><button className="btn btn-outline" onClick={()=>changeFilter({date:malaysiaToday()})}>Semasa</button><label>Asas tarikh<select aria-label="Asas tarikh" value={filters.date_basis} onChange={e=>changeFilter({date_basis:e.target.value as DraftFilters['date_basis']})}><option value="created">Draft dibuat</option><option value="sent">Dihantar ke customer</option></select></label></div>
    <div className="draft-tools"><input aria-label="Cari draft" value={query} onChange={e=>{setQuery(e.target.value);changeFilter({})}} placeholder="Cari nama, phone, @username, order atau transaction…"/><select aria-label="Keputusan draft" value={filters.state} onChange={e=>changeFilter({state:e.target.value})}><option value="all">Semua keputusan</option><option value="active">Draft aktif</option><option value="sent">Sudah dihantar</option><option value="unsent">Belum dihantar</option><option value="closed">Closed sales</option><option value="cancelled">Cancelled</option><option value="pending">Dihantar · belum closed</option><option value="order_unpaid">Order belum bayar</option></select></div>
    <details className="draft-advanced-filters"><summary>Filter tambahan</summary><div><label>Sumber<select aria-label="Sumber" value={filters.source} onChange={e=>changeFilter({source:e.target.value})}><option value="all">Semua sumber</option>{data?.options.sources.map(x=><option key={x} value={x}>{sourceLabel(x)}</option>)}</select></label><label>Status draft<select aria-label="Status draft" value={filters.status} onChange={e=>changeFilter({status:e.target.value})}><option value="all">Semua status</option>{data?.options.statuses.map(x=><option key={x} value={x}>{x.replaceAll('_',' ')}</option>)}</select></label><label>Payment flow<select aria-label="Payment flow" value={filters.payment_mode} onChange={e=>changeFilter({payment_mode:e.target.value})}><option value="all">Semua flow</option><option value="prepaid">Prepaid</option><option value="cash_counter">Cash at Counter</option></select></label><label>Delivery<select aria-label="Delivery" value={filters.delivery} onChange={e=>changeFilter({delivery:e.target.value})}><option value="all">Semua delivery</option><option value="pickup">Pickup</option><option value="spx">SPX</option><option value="jnt">J&amp;T</option><option value="ninja">Ninja Van</option><option value="unknown">Belum dipilih</option></select></label><label>Sebab cancelled<select aria-label="Sebab cancelled" value={filters.reason} onChange={e=>changeFilter({reason:e.target.value})}><option value="all">Semua sebab</option>{data?.reasons?.map(r=><option key={r.code} value={r.code}>{r.label}</option>)}<option value="order_cancelled">Order converted dibatalkan</option><option value="unknown">Sebab tidak direkodkan</option></select></label><label>Susunan<select aria-label="Susunan" value={filters.sort} onChange={e=>changeFilter({sort:e.target.value})}><option value="newest">Tarikh terbaru</option><option value="oldest">Tarikh terdahulu</option><option value="name">Nama A–Z</option><option value="amount_desc">Jumlah tertinggi</option><option value="amount_asc">Jumlah terendah</option></select></label></div><button className="btn btn-outline" onClick={()=>{setQuery('');changeFilter({state:'all',status:'all',source:'all',payment_mode:'all',delivery:'all',reason:'all',sort:'newest'})}}>Reset filters</button></details>
    {!loading&&!error&&data&&<><p className="draft-report-note"><b>{data.period.from} hingga {data.period.to} · MYT</b> · {data.period.date_basis==='created'?'Draft dibuat dalam tempoh ini':'Draft dengan rekod hantar dalam tempoh ini'}. Keputusan terkini; closed sales memerlukan order paid yang tidak cancelled. Closed/cancelled/belum closed % menggunakan draft dihantar sebagai asas.</p><DraftMetrics report={data} state={filters.state} onState={state=>changeFilter({state})}/><p className="draft-report-note">{data.summary.cancelled_all} cancelled keseluruhan ({data.summary.cancelled_all-data.summary.cancelled} tanpa rekod hantar) · {data.summary.order_unpaid_all} order belum bayar. Klik tile atau bar sebab untuk tapis senarai.</p></>}
    {error&&<div className="draft-error">{error}</div>}
    {!loading&&!error&&data&&(view==='graphs'?<DraftGraphs report={data} onReason={reason=>{changeFilter({reason,state:'cancelled'});setView('list')}} onState={state=>{changeFilter({state});setView('list')}}/>:data.drafts.length===0?<div className="draft-empty">Tiada draft dalam filter ini. Cuba tempoh atau filter lain.</div>:view==='cards'?<div className="draft-grid">{data.drafts.map(renderCard)}</div>:<div className="draft-table-scroll"><table className="draft-report-table draft-list-table"><thead><tr><th>Customer</th><th>Tarikh</th><th>Sumber / flow</th><th>Keputusan</th><th>Jumlah</th><th>Order / sebab batal</th><th>Tindakan</th></tr></thead><tbody>{data.drafts.map(d=><DraftListRows key={d.id} draft={d} expanded={expanded===d.id} onExpand={()=>setExpanded(expanded===d.id?null:d.id)} onEdit={()=>edit(d)} onOrder={onOpenOrder} detail={expanded===d.id?renderCard(d):null}/>)}</tbody></table></div>)}
    {loading&&<div className="draft-empty" role="status">Loading draft report…</div>}
    {!loading&&!error&&data&&view!=='graphs'&&<div className="draft-pagination"><span>{data.pagination.total===0?'0':`${data.pagination.offset+1}–${Math.min(data.pagination.offset+data.drafts.length,data.pagination.total)}`} daripada {data.pagination.total} draft</span><div><button className="btn btn-outline" disabled={filters.offset===0} onClick={()=>changeFilter({offset:Math.max(0,filters.offset-50)})}>Previous</button><button className="btn btn-outline" disabled={filters.offset+50>=data.pagination.total} onClick={()=>changeFilter({offset:filters.offset+50})}>Next</button></div></div>}
    {createOpen&&<div className="draft-modal-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget&&busy!=='create')setCreateOpen(false)}}><section className="draft-modal" role="dialog" aria-modal="true" aria-labelledby="create-draft-title"><div className="draft-modal-head"><div><h2 id="create-draft-title">Create Manual Draft</h2><p>Buat draft terus dari Admin V2 tanpa WhatsApp trigger.</p></div><button className="draft-modal-close" aria-label="Close" disabled={busy==='create'} onClick={()=>setCreateOpen(false)}>×</button></div><div className="draft-modal-grid"><label>Customer name<input value={createForm.customer_name} onChange={e=>setCreateForm(x=>({...x,customer_name:e.target.value}))} maxLength={200} placeholder="Optional — boleh isi dalam editor"/></label><label>No. WhatsApp<input value={createForm.customer_phone} onChange={e=>setCreateForm(x=>({...x,customer_phone:e.target.value}))} maxLength={30} placeholder="6012..."/></label><label>Date<input type="date" value={createForm.date_need} onChange={e=>setCreateForm(x=>({...x,date_need:e.target.value}))}/></label><label>Delivery<select value={createForm.delivery} onChange={e=>setCreateForm(x=>({...x,delivery:e.target.value,payment_mode:x.payment_mode==='cash_counter'&&e.target.value!=='pickup'?'prepaid':x.payment_mode}))}><option value="unknown">Pilih kemudian</option><option value="pickup">Pickup</option><option value="spx">SPX</option><option value="jnt">J&amp;T</option><option value="ninja">Ninja Van</option></select></label><label>Payment flow<select value={createForm.payment_mode} onChange={e=>setCreateForm(x=>({...x,payment_mode:e.target.value,delivery:e.target.value==='cash_counter'&&x.delivery==='unknown'?'pickup':x.delivery}))}><option value="prepaid">Prepaid / customer pay online</option><option value="cash_counter">Cash at Counter</option></select></label></div><div className="draft-modal-warning"><b>Manual draft sahaja — belum create order.</b>Selepas create, editor draft akan dibuka. Lengkapkan item, harga dan kemudian pilih flow approval yang sesuai.</div><div className="draft-modal-actions"><button className="btn btn-outline" disabled={busy==='create'} onClick={()=>setCreateOpen(false)}>Cancel</button><button className="btn btn-primary" disabled={busy==='create'} onClick={()=>void createManual()}>{busy==='create'?'Creating…':'Create & Open Draft'}</button></div></section></div>}
    {manualDraft&&<div className="draft-modal-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)setManualDraft(null)}}><section className="draft-modal" role="dialog" aria-modal="true" aria-labelledby="manual-payment-title"><div className="draft-modal-head"><div><h2 id="manual-payment-title">Confirm Manual Payment</h2><p>{manualDraft.customer_name||'Customer'} · {money(manualDraft.draft_total)}</p></div><button className="draft-modal-close" aria-label="Close" disabled={busy===manualDraft.id} onClick={()=>setManualDraft(null)}>×</button></div><label>Payment method<select value={manualMethod} onChange={e=>setManualMethod(e.target.value)}><option value="bank_transfer">Bank Transfer</option><option value="card">Card</option><option value="qr_pay_manual">QR Pay (Manual)</option><option value="other">Cash / Other</option></select></label><label>Reference / remark (optional)<input value={manualReference} onChange={e=>setManualReference(e.target.value)} maxLength={180} placeholder="Contoh: cash counter / bank ref"/></label><div className="draft-modal-warning"><b>Selepas confirm:</b> order sebenar akan dicipta, status Paid, masuk production dan dihantar ke ClickUp.</div><div className="draft-modal-actions"><button className="btn btn-outline" disabled={busy===manualDraft.id} onClick={()=>setManualDraft(null)}>Back</button><button className="btn btn-primary" disabled={busy===manualDraft.id} onClick={()=>void manualPaid()}>{busy===manualDraft.id?'Processing…':'Confirm Paid & Create Order'}</button></div></section></div>}
    {cancelTarget&&<div className="draft-modal-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget&&busy!==cancelTarget.id)setCancelTarget(null)}}><section className="draft-modal" role="dialog" aria-modal="true" aria-labelledby="cancel-draft-title"><div className="draft-modal-head"><div><h2 id="cancel-draft-title">Cancel Draft</h2><p>{cancelTarget.customer_name||'Customer'} · {money(cancelTarget.draft_total)}</p></div><button className="draft-modal-close" aria-label="Close" disabled={busy===cancelTarget.id} onClick={()=>setCancelTarget(null)}>×</button></div><div className="cancel-reason-list">{(data?.reasons||[]).map(reason=><label className={cancelReason===reason.code?'selected':''} key={reason.code}><input type="radio" name="cancel-reason" value={reason.code} checked={cancelReason===reason.code} onChange={()=>{setCancelReason(reason.code);if(!reason.requires_detail)setCancelDetail('')}}/><span>{reason.label}</span></label>)}</div>{(data?.reasons||[]).find(x=>x.code===cancelReason)?.requires_detail&&<label>Nyatakan sebab<textarea rows={3} maxLength={500} value={cancelDetail} onChange={e=>setCancelDetail(e.target.value)} placeholder="Sebab pembatalan…"/></label>}<div className="draft-modal-warning"><b>Draft tidak akan dipadam.</b>Ia disimpan dalam senarai Cancelled untuk audit dan laporan.</div><div className="draft-modal-actions"><button className="btn btn-outline" disabled={busy===cancelTarget.id} onClick={()=>setCancelTarget(null)}>Back</button><button className="btn btn-danger" disabled={busy===cancelTarget.id||!cancelReason} onClick={()=>void cancelDraft()}>{busy===cancelTarget.id?'Cancelling…':'Confirm Cancel Draft'}</button></div></section></div>}
  </div>;
}



function DraftListRows({draft:d,expanded,onExpand,onEdit,onOrder,detail}:{draft:Draft;expanded:boolean;onExpand:()=>void;onEdit:()=>void;onOrder?:((orderNo:string)=>void);detail:React.ReactNode}){
  return <><tr><td><b>{d.customer_name||'Customer belum dikenal pasti'}</b><small>{d.customer_phone||d.customer_username||d.customer_bsuid||'Phone tidak dikongsi'}</small>{d.customer_phone&&<a href={`https://wa.me/${d.customer_phone.replace(/\D/g,'')}`} target="_blank" rel="noreferrer">WhatsApp</a>}</td><td><small>Dibuat {when(d.created_at)}</small><small>{d.customer_link_sent_at?'Dihantar '+when(d.customer_link_sent_at):'Belum dihantar'}</small></td><td>{sourceLabel(d.source_type)}<small>{d.payment_mode==='cash_counter'?'Cash at Counter':'Prepaid'} · {d.delivery||'unknown'}</small></td><td><span className={`draft-outcome-badge ${d.outcome}`}>{outcomeLabel(d.outcome||'active')}</span><small>{d.status.replaceAll('_',' ')}</small></td><td className="draft-amount-cell">{money(d.draft_total)}<small>{d.order_payment_status||d.payment_status}</small></td><td>{d.order_no&&onOrder?<button className="draft-order-link" onClick={()=>onOrder(d.order_no!)}>{d.order_no}</button>:d.order_no}{d.cancel_reason_label&&<small>{d.cancel_reason_label}</small>}{d.cancel_reason_detail&&<small>{d.cancel_reason_detail}</small>}{d.shopee_match?.order_sn&&<small>Shopee: {d.shopee_match.order_sn}</small>}</td><td><div className="draft-row-actions"><button className="btn btn-outline" onClick={onExpand} aria-expanded={expanded}>{expanded?'Tutup':'Details'}</button>{!d.order_id&&<button className="btn btn-outline" onClick={onEdit}>Open / Edit</button>}</div></td></tr>{expanded&&<tr className="draft-expanded-row"><td colSpan={7}>{detail}</td></tr>}</>;
}
