import { useCallback, useEffect, useState } from 'react';
import { IconRefresh } from '../components/Icons';
import { supabase } from '../lib/supabase';
import './DraftFollowUps.css';

type FollowupDraft={id:string;review_token:string;customer_name:string|null;customer_phone:string|null;draft_total:number|string;date_need:string|null;followup_enabled:boolean;followup_count:number;last_followup_at:string|null;next_followup_at:string|null;customer_link_sent_at:string;customer_responded_at:string|null;queue_status:string|null;queue_error:string|null;decision_mode:string|null;provider_message_id:string|null;status?:string|null;payment_status?:string|null;order_id?:string|null;cancelled_at?:string|null};
type QueueData={counts:{all:number;due:number;paused:number;failed:number;final:number};drafts:FollowupDraft[]};
type Settings={enabled:boolean;auto_cancel_enabled:boolean;max_followups:number;first_delay_hours:number;second_delay_hours:number;third_delay_hours:number;auto_cancel_delay_hours:number;template_ready:boolean;due_count:number};
type ApiResponse<T>={success:boolean;data?:T;error?:string};
const empty:QueueData={counts:{all:0,due:0,paused:0,failed:0,final:0},drafts:[]};
const money=(v:number|string)=>`RM ${Number(v||0).toFixed(2)}`;
const when=(v:string|null)=>v?new Date(v).toLocaleString('en-MY',{timeZone:'Asia/Kuala_Lumpur',dateStyle:'medium',timeStyle:'short'}):'—';
const phoneDigits=(v:string|null)=>String(v||'').replace(/\D/g,'');
const PhoneActions=({phone}:{phone:string|null})=>{const p=phoneDigits(phone);if(!p)return <span className="phone-actions muted">Phone tidak tersedia</span>;return <span className="phone-actions"><a className="phone-link" href={`whatsapp://send?phone=${p}`} title="Buka WhatsApp app" aria-label="Buka WhatsApp app">◉</a><a className="phone-link" href={`https://wa.me/${p}`} target="_blank" rel="noreferrer" title="Buka WhatsApp web" aria-label="Buka WhatsApp web">◉</a><a className="phone-text" href={`https://wa.me/${p}`} target="_blank" rel="noreferrer">{phone}</a></span>};
const stage=(d:FollowupDraft)=>{const s=`${d.status||''} ${d.payment_status||''}`.toLowerCase();if(d.cancelled_at||s.includes('cancel'))return 'cancelled';if(d.order_id||s.includes('paid')||s.includes('converted'))return 'won';return d.followup_count<=0?'draft':`followup${Math.min(d.followup_count,3)}`};
async function api<T>(body:Record<string,unknown>){const {data,error}=await supabase.functions.invoke('finance-admin',{body});if(error)throw new Error(error.message);return data as ApiResponse<T>}

export default function DraftFollowUps({canManage=false}:{canManage?:boolean}){
  const [data,setData]=useState<QueueData>(empty);const [settings,setSettings]=useState<Settings|null>(null);
  const [filter,setFilter]=useState('');const [query,setQuery]=useState('');const [loading,setLoading]=useState(true);const [busy,setBusy]=useState('');const [error,setError]=useState('');const [notice,setNotice]=useState('');const [showSettings,setShowSettings]=useState(false);
  const load=useCallback(async()=>{setLoading(true);setError('');try{const [q,s]=await Promise.all([api<QueueData>({action:'draft_followups',filter,query,limit:200}),api<Settings>({action:'draft_followup_settings'})]);if(!q.success||!q.data)throw new Error(q.error||'Follow-up list failed');if(!s.success||!s.data)throw new Error(s.error||'Settings failed');setData(q.data);setSettings(s.data)}catch(e){setError(e instanceof Error?e.message:'Load failed')}finally{setLoading(false)}},[filter,query]);
  useEffect(()=>{const t=window.setTimeout(()=>void load(),200);return()=>window.clearTimeout(t)},[load]);
  const action=async(d:FollowupDraft,followup_action:string)=>{setBusy(d.id);setError('');setNotice('');try{const r=await api({action:'draft_followup_action',draft_id:d.id,followup_action});if(!r.success)throw new Error(r.error||'Action failed');setNotice(followup_action==='send_now'?'Follow-up dimasukkan ke WhatsApp queue.':'Draft follow-up dikemas kini.');await load()}catch(e){setError(e instanceof Error?e.message:'Action failed')}finally{setBusy('')}};
  const saveSettings=async(next:Settings)=>{setBusy('settings');setError('');try{const r=await api<Settings>({action:'draft_followup_settings_save',settings:next});if(!r.success||!r.data)throw new Error(r.error||'Settings failed');setSettings(r.data);setNotice('Tetapan follow-up disimpan.');setShowSettings(false);await load()}catch(e){setError(e instanceof Error?e.message:'Settings failed')}finally{setBusy('')}};
  return <div className="followup-page">
    <div className="page-header"><div><div className="page-label">Draft</div><h1 className="page-title">Draft Follow-up</h1><p className="page-subtitle">Pantau prepaid draft yang sudah dihantar tetapi belum dibayar.</p></div><div className="followup-head-actions">{canManage&&<button className="btn btn-outline" onClick={()=>setShowSettings(true)}>Settings</button>}<button className="btn btn-outline" disabled={loading} onClick={()=>void load()}><IconRefresh size={16}/> Refresh</button></div></div>
    {settings&&<div className={`followup-system ${settings.enabled?'on':'off'}`}><b>Automation {settings.enabled?'ON':'OFF'}</b><span>{settings.template_ready?'Template Meta lengkap.':'Template Meta belum lengkap — automation kekal selamat jika OFF.'}</span><span>Auto-cancel {settings.auto_cancel_enabled?'ON':'OFF'}</span></div>}
    <div className="followup-stats">{([['', 'Semua',data.counts.all],['due','Due / Overdue',data.counts.due],['paused','Paused',data.counts.paused],['failed','Failed WhatsApp',data.counts.failed],['final','Final Follow-up',data.counts.final]] as const).map(([k,label,value])=><button key={k} className={filter===k?'active':''} onClick={()=>setFilter(k)}><span>{label}</span><b>{value||0}</b></button>)}</div>
    <div className="followup-search"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cari nama atau nombor telefon…"/></div>
    {notice&&<div className="followup-notice">{notice}</div>}{error&&<div className="draft-error">{error}</div>}
    {loading?<div className="draft-empty">Loading follow-up…</div>:data.drafts.length===0?<div className="draft-empty">Tiada draft dalam senarai ini.</div>:<div className="followup-kanban">{([['draft','1 · Draft'],['followup1','Follow-up 1'],['followup2','Follow-up 2'],['followup3','Follow-up 3'],['won','Won → Order'],['cancelled','Cancelled / Auto-cancel']] as const).map(([key,label])=><section className="kanban-column" key={key}><header><b>{label}</b><span>{data.drafts.filter(d=>stage(d)===key).length}</span></header><div className="kanban-cards">{data.drafts.filter(d=>stage(d)===key).map(d=><article className="followup-card" key={d.id}><div className="followup-card-top"><div><span className={`followup-badge ${d.followup_enabled?'active':'paused'}`}>{d.followup_enabled?`ACTIVE · ${Math.min(d.followup_count+1,3)}/3`:'PAUSED'}</span><h2>{d.customer_name||'Customer belum dikenal pasti'}</h2><PhoneActions phone={d.customer_phone}/></div><strong>{money(d.draft_total)}</strong></div><div className="followup-timeline"><div><span>Draft sent</span><b>{when(d.customer_link_sent_at)}</b></div><div><span>Next follow-up</span><b>{when(d.next_followup_at)}</b></div><div><span>WhatsApp</span><b>{d.queue_status||'Not queued'}{d.decision_mode?` · ${d.decision_mode}`:''}</b></div></div>{d.queue_error&&<div className="followup-error">{d.queue_error}</div>}<div className="followup-actions">{!['won','cancelled'].includes(key)&&<><button className="btn btn-primary" disabled={!canManage||busy===d.id} onClick={()=>void action(d,'send_now')}>Send Now</button>{d.followup_enabled?<button className="btn btn-outline" disabled={!canManage||busy===d.id} onClick={()=>void action(d,'pause')}>Pause</button>:<button className="btn btn-outline" disabled={!canManage||busy===d.id} onClick={()=>void action(d,'resume')}>Resume</button>}<button className="btn btn-outline" disabled={!canManage||busy===d.id} onClick={()=>void action(d,'responded')}>Customer Responded</button></>}<button className="btn btn-outline" onClick={()=>window.open(`https://shop.decocake.my/qrpay-draft.html?token=${encodeURIComponent(d.review_token)}`,'_blank','noopener,noreferrer')}>Open Draft</button></div></article>)}</div></section>)}</div>}
    {showSettings&&settings&&<SettingsModal value={settings} busy={busy==='settings'} onClose={()=>setShowSettings(false)} onSave={saveSettings}/>}
  </div>
}

function SettingsModal({value,busy,onClose,onSave}:{value:Settings;busy:boolean;onClose:()=>void;onSave:(v:Settings)=>Promise<void>}){const [form,setForm]=useState(value);return <div className="draft-modal-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)onClose()}}><section className="draft-modal" role="dialog" aria-modal="true"><div className="draft-modal-head"><div><h2>Draft Follow-up Settings</h2><p>Automation hanya patut ON selepas template Meta approved.</p></div><button className="draft-modal-close" disabled={busy} onClick={onClose}>×</button></div>{!form.template_ready&&<div className="draft-modal-warning"><b>Template belum lengkap</b>Map tiga template Draft Follow-up di WhatsApp Control Center dahulu.</div>}<div className="followup-setting-grid"><label><input type="checkbox" checked={form.enabled} onChange={e=>setForm({...form,enabled:e.target.checked})}/> Enable auto follow-up</label><label><input type="checkbox" checked={form.auto_cancel_enabled} onChange={e=>setForm({...form,auto_cancel_enabled:e.target.checked})}/> Auto-cancel selepas final reminder</label><label>Jumlah follow-up<select value={form.max_followups} onChange={e=>setForm({...form,max_followups:Number(e.target.value)})}><option value="1">1</option><option value="2">2</option><option value="3">3</option></select></label><label>Reminder pertama (jam)<input type="number" min="1" max="720" value={form.first_delay_hours} onChange={e=>setForm({...form,first_delay_hours:Number(e.target.value)})}/></label><label>Jarak reminder kedua (jam)<input type="number" min="1" max="720" value={form.second_delay_hours} onChange={e=>setForm({...form,second_delay_hours:Number(e.target.value)})}/></label><label>Jarak reminder ketiga (jam)<input type="number" min="1" max="720" value={form.third_delay_hours} onChange={e=>setForm({...form,third_delay_hours:Number(e.target.value)})}/></label><label>Auto-cancel selepas final (jam)<input type="number" min="1" max="720" value={form.auto_cancel_delay_hours} onChange={e=>setForm({...form,auto_cancel_delay_hours:Number(e.target.value)})}/></label></div><div className="draft-modal-actions"><button className="btn btn-outline" disabled={busy} onClick={onClose}>Back</button><button className="btn btn-primary" disabled={busy||form.enabled&&!form.template_ready} title={form.enabled&&!form.template_ready?'Template Meta belum lengkap':''} onClick={()=>void onSave(form)}>{busy?'Saving…':'Save Settings'}</button></div></section></div>}
