import {useEffect,useState} from 'react';
import {materialCategories,profitDate,profitRequest} from '../lib/orderProfit';
import type {MaterialCategory,MaterialSettings} from '../lib/orderProfit';
import './OrderProfit.css';
type SkuRow={sku:string;category:MaterialCategory;input:string};
export default function MaterialCostSettings({canManage}:{canManage:boolean}){
  const [settings,setSettings]=useState<MaterialSettings|null>(null),[rates,setRates]=useState<Record<MaterialCategory,string>>({topper:'',edible:'',wafer:'',acrylic:''}),[skus,setSkus]=useState<SkuRow[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const install=(s:MaterialSettings)=>{setSettings(s);setRates(Object.fromEntries(Object.entries(s.rates).map(([k,v])=>[k,String(v)])) as Record<MaterialCategory,string>);setSkus(Object.entries(s.sku_costs).map(([sku,v])=>({sku,category:v.category,input:String(v.unit_cost)})))};
  useEffect(()=>{let active=true;void profitRequest<MaterialSettings>({action:'material_cost_settings'}).then(s=>{if(active)install(s)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[]);
  const save=async()=>{if(!settings)return;setBusy(true);setError('');setNotice('');try{
    const parsed=Object.fromEntries(Object.entries(rates).map(([k,v])=>{if(v.trim()===''||!Number.isFinite(Number(v))||Number(v)<0||Number(v)>100)throw new Error('Setiap peratus mestilah antara 0 hingga 100.');return [k,Number(v)]}));const skuCosts:MaterialSettings['sku_costs']={};
    for(const s of skus){const key=s.sku.trim().toLowerCase();if(!key||s.input.trim()===''||!Number.isFinite(Number(s.input))||Number(s.input)<0||Number(s.input)>1000000)throw new Error('Isi SKU dan kos RM seunit yang sah.');if(skuCosts[key])throw new Error(`SKU berulang: ${s.sku}`);skuCosts[key]={category:s.category,unit_cost:Number(s.input)}}
    install(await profitRequest<MaterialSettings>({action:'material_cost_settings_save',version:settings.version,rates:parsed,sku_costs:skuCosts}));setNotice('Setting modal disimpan untuk order baharu. Anggaran order lama kekal.');
  }catch(e){setError(e instanceof Error?e.message:'Setting gagal disimpan')}finally{setBusy(false)}};
  return <div className="panel op-settings" id="material-cost-settings"><div className="panel-header"><div><div className="panel-title">Modal Bahan</div><div className="panel-subtitle">Setting berasingan untuk anggaran raw material setiap order.</div></div>{settings&&<span className="op-badge estimated">Versi {settings.version}</span>}</div><div className="op-settings-body">
    {error&&<div className="op-alert error" role="alert">{error}</div>}{notice&&<div className="op-alert success" role="status">{notice}</div>}{!settings?<p>Memuatkan setting modal…</p>:<>
      <p className="op-explanation">Ubah peratus selepas kira semula bahan. Anggaran = nilai barang × peratus kategori, tanpa shipping. Order lama menggunakan versi ketika order mula diterima; kos sebenar boleh diisi dalam detail order.</p>
      <div className="op-rate-grid">{(Object.entries(materialCategories) as [MaterialCategory,string][]).map(([k,label])=><label key={k}>{label}<div className="op-percent"><input aria-label={`Peratus modal ${label}`} type="number" min="0" max="100" step="0.01" value={rates[k]} disabled={!canManage||busy} onChange={e=>{setNotice('');setRates(prev=>({...prev,[k]:e.target.value}))}}/><span>%</span></div><small>Raw material sahaja</small></label>)}</div>
      <div className="op-section-head"><div><h3>Kos bahan mengikut SKU</h3><p className="op-muted">Pilihan: RM seunit mengatasi peratus. Kekal anggaran sehingga kos order disemak.</p></div>{canManage&&<button className="btn btn-outline btn-sm" disabled={busy} onClick={()=>{setNotice('');setSkus(prev=>[...prev,{sku:'',category:'topper',input:''}])}}>+ Tambah SKU</button>}</div><p className="op-muted">Gunakan SKU tepat. Untuk variation yang berkongsi SKU, gunakan <code>SKU parent::SKU variation</code> supaya kos tidak tersalah produk.</p>
      {!skus.length&&<div className="op-empty op-sku-empty">Belum ada kos SKU. Empat peratus di atas digunakan sebagai anggaran.</div>}
      {skus.map((s,i)=><div className="op-sku-row" key={i}><label>SKU<input aria-label={`SKU ${i+1}`} value={s.sku} disabled={!canManage||busy} placeholder="CN0546" onChange={e=>{setNotice('');setSkus(prev=>prev.map((v,j)=>i===j?{...v,sku:e.target.value}:v))}}/></label><label>Kategori<select aria-label={`Kategori SKU ${i+1}`} value={s.category} disabled={!canManage||busy} onChange={e=>setSkus(prev=>prev.map((v,j)=>i===j?{...v,category:e.target.value as MaterialCategory}:v))}>{Object.entries(materialCategories).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>RM / unit<input aria-label={`Kos unit SKU ${i+1}`} type="number" min="0" step="0.01" value={s.input} disabled={!canManage||busy} onChange={e=>setSkus(prev=>prev.map((v,j)=>i===j?{...v,input:e.target.value}:v))}/></label>{canManage&&<button className="btn btn-ghost btn-sm" disabled={busy} aria-label={`Buang SKU ${i+1}`} onClick={()=>{setNotice('');setSkus(prev=>prev.filter((_,j)=>j!==i))}}>Buang</button>}</div>)}
      <div className="op-setting-footer"><span className="op-muted">{settings.version===1?'Kadar awal daripada anggaran kau.':`Dikemas kini ${profitDate(settings.effective_at)}`}</span><button className="btn btn-primary" disabled={!canManage||busy} onClick={()=>void save()}>{busy?'Menyimpan…':'Simpan setting modal'}</button></div>
    </>}</div></div>;
}
