import {useEffect,useRef,useState} from 'react';
import MoneyBreakdown from '../components/MoneyBreakdown';
import OrderProfitDetail from '../components/OrderProfitDetail';
import {malaysiaDate,materialCategories,profitDate,profitMoney,profitRequest,profitStateLabel} from '../lib/orderProfit';
import type {FinanceReport,FinanceOptions} from '../lib/orderProfit';
import {financeReasonLabels} from '../lib/orderProfit';
import {downloadFinanceCsv} from '../lib/financeExcel';
import OrderFinanceImport from '../components/OrderFinanceImport';
import './OrderProfit.css';
export default function OrderProfit({canManage,onOpenSettings}:{canManage:boolean;onOpenSettings?:()=>void}){
  const today=malaysiaDate();const [from,setFrom]=useState(`${today.slice(0,7)}-01`),[to,setTo]=useState(today),[query,setQuery]=useState(''),[category,setCategory]=useState(''),[state,setState]=useState(''),[status,setStatus]=useState('all'),[sort,setSort]=useState('newest'),[offset,setOffset]=useState(0),[refresh,setRefresh]=useState(0),[data,setData]=useState<FinanceReport|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[selected,setSelected]=useState<string|null>(null);
  const [courier,setCourier]=useState(''),[source,setSource]=useState(''),[reason,setReason]=useState(''),[incomeState,setIncomeState]=useState(''),[currency,setCurrency]=useState('MYR'),[shop,setShop]=useState(''),[sku,setSku]=useState(''),[metric,setMetric]=useState('profit'),[min,setMin]=useState(''),[max,setMax]=useState(''),[dateBasis,setDateBasis]=useState('placed'),[options,setOptions]=useState<FinanceOptions|null>(null),[exporting,setExporting]=useState(false);
  useEffect(()=>{let active=true;void profitRequest<FinanceOptions>({action:'order_finance_options'}).then(v=>{if(active)setOptions(v)}).catch(()=>{});return()=>{active=false}},[]);
  const filters={from,to,query,category,state,status,sort,offset,courier,source,reason,income_state:incomeState,currency,shop_id:shop,sku,metric,min,max,date_basis:dateBasis};
  const exportCsv=async()=>{setExporting(true);setError('');try{const report=await profitRequest<FinanceReport>({action:'order_finance_export',...filters});if(report.truncated)throw new Error('Pilihan melebihi 5,000 order. Kecilkan julat sebelum export.');downloadFinanceCsv(report)}catch(e){setError((e as Error).message)}finally{setExporting(false)}};
  const generation=useRef(0);
  useEffect(()=>{const g=++generation.current;setLoading(true);setError('');const timer=window.setTimeout(()=>{void profitRequest<FinanceReport>({action:'order_finance_report',...filters}).then(next=>{if(g===generation.current)setData(next)}).catch(e=>{if(g===generation.current){setData(null);setError(e.message)}}).finally(()=>{if(g===generation.current)setLoading(false)});},220);return()=>{generation.current++;window.clearTimeout(timer)}},[from,to,query,category,state,status,sort,offset,refresh,courier,source,reason,incomeState,currency,shop,sku,metric,min,max,dateBasis]);
  const filter=(setter:(v:string)=>void,v:string)=>{setter(v);setOffset(0)},s=data?.summary;
  return <div className="op-page"><div className="op-title"><div><h2>Untung setiap order</h2><p>Berapa duit masuk, berapa modal keluar, dan baki untuk perniagaan.</p></div><div className="op-actions"><button className="btn btn-outline" disabled={exporting||loading} onClick={()=>void exportCsv()}>{exporting?'Export…':'Export CSV'}</button>{onOpenSettings&&<button className="btn btn-outline" onClick={onOpenSettings}>Setting Modal Bahan</button>}<button className="btn btn-outline" onClick={()=>setRefresh(v=>v+1)}>Refresh</button></div></div>
    <div className="op-filters"><label>Dari<input type="date" value={from} onChange={e=>filter(setFrom,e.target.value)}/></label><label>Hingga<input type="date" value={to} onChange={e=>filter(setTo,e.target.value)}/></label><label className="op-query">Order / buyer / SKU<input value={query} onChange={e=>filter(setQuery,e.target.value)} placeholder="Cari order atau produk…"/></label><label>Kategori<select aria-label="Kategori" value={category} onChange={e=>filter(setCategory,e.target.value)}><option value="">Semua kategori</option>{Object.entries(materialCategories).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Data untung<select aria-label="Data untung" value={state} onChange={e=>filter(setState,e.target.value)}><option value="">Semua data</option><option value="actual">Sebenar</option><option value="estimated">Anggaran</option><option value="incomplete">Belum lengkap</option><option value="loss">Rugi</option></select></label><label>Status order<select aria-label="Status order" value={status} onChange={e=>filter(setStatus,e.target.value)}><option value="active">Order aktif / selesai</option><option value="COMPLETED">Completed</option><option value="READY_TO_SHIP">Ready to ship</option><option value="SHIPPED">Shipped</option><option value="CANCELLED">Cancelled</option><option value="all">Semua termasuk batal</option></select></label><label>Susunan<select aria-label="Susunan" value={sort} onChange={e=>filter(setSort,e.target.value)}><option value="newest">Terbaharu</option><option value="profit_asc">Untung terendah</option><option value="margin_asc">Margin terendah</option><option value="shipping_asc">Shipping paling rugi</option><option value="fees_desc">Fees tertinggi</option><option value="returns_desc">Return shipping tertinggi</option></select></label></div>
    <details className="op-breakdown"><summary>Filter finance terperinci</summary><div className="op-filters">
<label>Asas tarikh<select aria-label="Asas tarikh" value={dateBasis} onChange={e=>filter(setDateBasis,e.target.value)}><option value="placed">Order dibuat</option><option value="finance">Finance diterima</option><option value="released">Duit dilepaskan</option></select></label>
<label>Currency<select aria-label="Currency" value={currency} onChange={e=>filter(setCurrency,e.target.value)}>{[...new Set(['MYR',...(options?.shops.map(s=>s.currency)||[])])].map(c=><option key={c}>{c}</option>)}</select></label>
<label>Shop<select aria-label="Shop" value={shop} onChange={e=>filter(setShop,e.target.value)}><option value="">Semua shop</option>{options?.shops.filter(s=>s.currency===currency).map(s=><option key={s.shop_id} value={s.shop_id}>{s.shop_id}</option>)}</select></label>
<label>Courier<select aria-label="Courier" value={courier} onChange={e=>filter(setCourier,e.target.value)}><option value="">Semua courier</option>{options?.couriers.map(c=><option key={c}>{c}</option>)}</select></label>
<label>SKU tepat<input value={sku} onChange={e=>filter(setSku,e.target.value)} placeholder="CN0546"/></label>
<label>Sumber finance<select aria-label="Sumber finance" value={source} onChange={e=>filter(setSource,e.target.value)}><option value="">Semua</option><option value="webhook">Webhook API</option><option value="excel">Excel</option><option value="missing">Belum diterima</option></select></label>
<label>Status duit<select aria-label="Status duit" value={incomeState} onChange={e=>filter(setIncomeState,e.target.value)}><option value="">Semua</option><option value="released">Sudah release</option><option value="escrow">Escrow</option><option value="report_estimate">Anggaran Excel</option><option value="missing">Belum diterima</option></select></label>
<label>Punca / potongan<select aria-label="Punca / potongan" value={reason} onChange={e=>filter(setReason,e.target.value)}><option value="">Semua</option>{Object.entries(financeReasonLabels).map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label>
<label>Nilai untuk tapis<select aria-label="Nilai untuk tapis" value={metric} onChange={e=>filter(setMetric,e.target.value)}>{Object.entries({profit:'Untung',nett:'Nett',margin:'Margin %',cost_total:'Modal + kos',shipping_net:'Baki shipping',return_shipping:'Return shipping',refund_total:'Refund',seller_promotion:'Promo seller',fee_total:'Fees',platform_ads:'Ads platform',affiliate:'Affiliate AMS'}).map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label>
<label>Minimum<input type="number" step="0.01" value={min} onChange={e=>filter(setMin,e.target.value)}/></label><label>Maksimum<input type="number" step="0.01" value={max} onChange={e=>filter(setMax,e.target.value)}/></label>
</div></details>
{canManage&&<OrderFinanceImport options={options} onImported={()=>setRefresh(v=>v+1)}/>}
    {error&&<div className="op-alert error" role="alert">{error}</div>}
    <div className="op-metrics" aria-busy={loading}>{[['Duit sudah release',s?profitMoney(s.released_nett,currency):'—','Nett Shopee diterima ke wallet','', 'released'],['Escrow belum release',s?profitMoney(s.escrow_nett,currency):'—','Masih anggaran penerimaan','amber','escrow'],['Untung sebenar',s?.actual_orders?profitMoney(s.actual_profit,currency):'—',s?`${s.actual_orders} order · kos sebenar disemak`:'Memuatkan…','green','actual'],['Untung anggaran',s?.estimated_orders?profitMoney(s.estimated_profit,currency):'—',s?`${s.estimated_orders} order · sebelum overhead`:'Memuatkan…','','estimated']].map(([label,v,detail,cls,key])=><div className={`op-metric ${cls}`} key={label}><span>{label}</span><strong>{loading?'…':v}</strong><small>{detail}</small>{!loading&&<MoneyBreakdown data={data?.breakdowns?.[key as keyof NonNullable<FinanceReport['breakdowns']>]} currency={currency} incomeOnly={key==='released'||key==='escrow'}/>}</div>)}</div>
    <div className="op-explanation">Untung order = nett Shopee − bahan − kos tambahan. Margin dibandingkan dengan nilai barang, tanpa shipping. Semua jumlah mengikut currency yang dipilih; P&amp;L perniagaan kekal di tab P&amp;L.</div>
    {s&&!loading&&<div className="op-attention"><span><b>{s.orders}</b> order dalam pilihan</span><button onClick={()=>filter(setState,'incomplete')}><b>{s.incomplete_orders}</b> belum lengkap</button><button onClick={()=>filter(setState,'loss')}><b>{s.loss_orders}</b> rugi</button><button onClick={()=>filter(setSort,'margin_asc')}><b>{s.low_margin_orders}</b> margin bawah 20%</button></div>}
    {s&&!loading&&<div className="op-finance-mini"><div><span>Order ada finance</span><b>{s.finance_orders??0} / {s.orders}</b></div>{[['Shipping rugi',s.shipping_loss],['Return shipping',s.return_shipping],['Refund',s.refunds],['Fees',s.fees],['Ads platform',s.platform_ads],['Affiliate',s.affiliate]].map(([l,v])=><div key={String(l)}><span>{String(l)}</span><b>{profitMoney(v as number|null,currency)}</b></div>)}<div><span>Pecahan perlu semak</span><b>{s.reconciliation_issues??0}</b></div></div>}
{!loading&&data&&<div className="op-charts"><section><h3>Untung mengikut hari</h3><p className="op-muted">Klik hari untuk lihat order. Jumlah hanya order dengan untung diketahui.</p><div className="op-bars">{data.trend?.map(t=><button key={t.day} onClick={()=>{setFrom(t.day);setTo(t.day);setOffset(0)}}><span>{t.day.slice(5)}</span><i className={t.profit!=null&&t.profit<0?'loss':''} style={{width:`${Math.max(2,Math.abs(t.profit||0)/Math.max(1,...data.trend.map(d=>Math.abs(d.profit||0)))*100)}%`}}/><b>{profitMoney(t.profit,currency)}</b><small>{t.known_orders}/{t.orders} diketahui</small></button>)}</div></section><section><h3>Untung mengikut courier</h3><p className="op-muted">Klik courier untuk lihat order dan shipping.</p><div className="op-bars">{data.groups?.map(g=><button key={g.name} onClick={()=>filter(setCourier,g.name==='Tidak diketahui'?'':g.name)}><span>{g.name}</span><i className={g.profit!=null&&g.profit<0?'loss':''} style={{width:`${Math.max(2,Math.abs(g.profit||0)/Math.max(1,...data.groups.map(d=>Math.abs(d.profit||0)))*100)}%`}}/><b>{profitMoney(g.profit,currency)}</b><small>{g.known_orders}/{g.orders} diketahui</small></button>)}</div></section></div>}
    <div className="op-table-wrap"><table className="op-table"><thead><tr><th>Order / produk</th><th>Customer bayar</th><th>Nett Shopee</th><th>Modal + kos</th><th>Untung / margin</th><th>Potongan / semakan</th></tr></thead><tbody>{loading?<tr><td colSpan={6} className="op-empty">Memuatkan untung order…</td></tr>:!data?.rows.length?<tr><td colSpan={6} className="op-empty">{error?'Data tidak dapat dimuatkan. Cuba Refresh.':'Tiada order dalam pilihan ini.'}</td></tr>:data.rows.map(r=><tr key={r.order_id}>
      <td><button className="op-order-link" onClick={()=>setSelected(r.order_id)}>{r.order_sn}</button><small>@{r.buyer||'—'} · {profitDate(r.placed_at)}</small><small className="op-skus">{r.material_lines.slice(0,2).map(l=>`${l.quantity}× ${l.parent_sku||l.sku||l.title}`).join(' · ')}{r.material_lines.length>2?' …':''}</small></td>
      <td><b>{profitMoney(r.buyer_paid,r.currency)}</b><small>{r.status.replaceAll('_',' ')}</small></td><td><b>{profitMoney(r.nett,r.currency)}</b><small>{r.income_state==='released'?'Sudah release':r.income_state==='escrow'?'Escrow · belum release':r.income_state==='report_estimate'?'Anggaran laporan':'Menunggu data'}</small></td>
      <td><b>{profitMoney(r.cost_total,r.currency)}</b><small>{r.cost_state==='actual'?'Kos sebenar':r.cost_state==='missing'?'Bahan belum lengkap':r.detail_changed?'Semak item berubah':'Kos anggaran'}</small></td><td><b className={r.profit!=null&&r.profit<0?'op-negative':'op-positive'}>{profitMoney(r.profit,r.currency)}</b><small>{r.margin==null?'Margin belum diketahui':`${r.margin.toFixed(1)}% margin`}{r.profit_per_hour!=null?` · ${profitMoney(r.profit_per_hour)} / jam`:''}</small></td>
      <td><small>{r.finance_metrics?.reasons.map(k=>financeReasonLabels[k]||k).join(' · ')||'—'}</small><span className={`op-badge ${r.profit_state}`}>{profitStateLabel(r)}</span><button className="op-detail-link" onClick={()=>setSelected(r.order_id)}>Detail kos →</button></td>
    </tr>)}</tbody></table></div><div className="op-pager"><span>{data?.total?offset+1:0}–{Math.min(offset+50,data?.total||0)} daripada {data?.total||0} order</span><div><button className="btn btn-outline btn-sm" disabled={loading||offset===0} onClick={()=>setOffset(v=>Math.max(0,v-50))}>Sebelumnya</button><button className="btn btn-outline btn-sm" disabled={loading||offset+50>=(data?.total||0)} onClick={()=>setOffset(v=>v+50)}>Seterusnya</button></div></div>
    {selected&&<OrderProfitDetail key={selected} orderId={selected} canManage={canManage} onClose={()=>setSelected(null)} onSaved={()=>setRefresh(v=>v+1)}/>}
  </div>;
}
