import {useEffect,useRef,useState} from 'react';
import OrderProfitDetail from '../components/OrderProfitDetail';
import {malaysiaDate,materialCategories,profitDate,profitMoney,profitRequest,profitStateLabel} from '../lib/orderProfit';
import type {ProfitList} from '../lib/orderProfit';
import './OrderProfit.css';
export default function OrderProfit({canManage,onOpenSettings}:{canManage:boolean;onOpenSettings?:()=>void}){
  const today=malaysiaDate();const [from,setFrom]=useState(`${today.slice(0,7)}-01`),[to,setTo]=useState(today),[query,setQuery]=useState(''),[category,setCategory]=useState(''),[state,setState]=useState(''),[status,setStatus]=useState('active'),[sort,setSort]=useState('newest'),[offset,setOffset]=useState(0),[refresh,setRefresh]=useState(0),[data,setData]=useState<ProfitList|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[selected,setSelected]=useState<string|null>(null);
  const generation=useRef(0);
  useEffect(()=>{const g=++generation.current;setLoading(true);setError('');const timer=window.setTimeout(()=>{void profitRequest<ProfitList>({action:'order_profit_list',from,to,query,category,state,status,sort,offset}).then(next=>{if(g===generation.current)setData(next)}).catch(e=>{if(g===generation.current){setData(null);setError(e.message)}}).finally(()=>{if(g===generation.current)setLoading(false)});},220);return()=>{generation.current++;window.clearTimeout(timer)}},[from,to,query,category,state,status,sort,offset,refresh]);
  const filter=(setter:(v:string)=>void,v:string)=>{setter(v);setOffset(0)},s=data?.summary;
  return <div className="op-page"><div className="op-title"><div><h2>Untung setiap order</h2><p>Berapa duit masuk, berapa modal keluar, dan baki untuk perniagaan.</p></div><div className="op-actions">{onOpenSettings&&<button className="btn btn-outline" onClick={onOpenSettings}>Setting Modal Bahan</button>}<button className="btn btn-outline" onClick={()=>setRefresh(v=>v+1)}>Refresh</button></div></div>
    <div className="op-filters"><label>Dari<input type="date" value={from} onChange={e=>filter(setFrom,e.target.value)}/></label><label>Hingga<input type="date" value={to} onChange={e=>filter(setTo,e.target.value)}/></label><label className="op-query">Order / buyer / SKU<input value={query} onChange={e=>filter(setQuery,e.target.value)} placeholder="Cari order atau produk…"/></label><label>Kategori<select value={category} onChange={e=>filter(setCategory,e.target.value)}><option value="">Semua kategori</option>{Object.entries(materialCategories).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Data untung<select value={state} onChange={e=>filter(setState,e.target.value)}><option value="">Semua data</option><option value="actual">Sebenar</option><option value="estimated">Anggaran</option><option value="incomplete">Belum lengkap</option><option value="loss">Rugi</option></select></label><label>Status order<select value={status} onChange={e=>filter(setStatus,e.target.value)}><option value="active">Order aktif / selesai</option><option value="COMPLETED">Completed</option><option value="READY_TO_SHIP">Ready to ship</option><option value="SHIPPED">Shipped</option><option value="CANCELLED">Cancelled</option><option value="all">Semua termasuk batal</option></select></label><label>Susunan<select value={sort} onChange={e=>filter(setSort,e.target.value)}><option value="newest">Terbaharu</option><option value="profit_asc">Untung terendah</option><option value="margin_asc">Margin terendah</option></select></label></div>
    {error&&<div className="op-alert error" role="alert">{error}</div>}
    <div className="op-metrics" aria-busy={loading}>{[['Duit sudah release',s?profitMoney(s.released_nett):'—','Nett Shopee diterima ke wallet',''],['Escrow belum release',s?profitMoney(s.escrow_nett):'—','Masih anggaran penerimaan','amber'],['Untung sebenar',s?.actual_orders?profitMoney(s.actual_profit):'—',s?`${s.actual_orders} order · kos sebenar disemak`:'Memuatkan…','green'],['Untung anggaran',s?.estimated_orders?profitMoney(s.estimated_profit):'—',s?`${s.estimated_orders} order · sebelum overhead`:'Memuatkan…','']].map(([label,v,detail,cls])=><div className={`op-metric ${cls}`} key={label}><span>{label}</span><strong>{loading?'…':v}</strong><small>{detail}</small></div>)}</div>
    <div className="op-explanation">Untung order = nett Shopee − bahan − kos tambahan. Margin dibandingkan dengan nilai barang, tanpa shipping. Semua jumlah di sini dalam MYR; P&amp;L perniagaan kekal di tab P&amp;L.</div>
    {s&&!loading&&<div className="op-attention"><span><b>{s.orders}</b> order dalam pilihan</span><button onClick={()=>filter(setState,'incomplete')}><b>{s.incomplete_orders}</b> belum lengkap</button><button onClick={()=>filter(setState,'loss')}><b>{s.loss_orders}</b> rugi</button><button onClick={()=>filter(setSort,'margin_asc')}><b>{s.low_margin_orders}</b> margin bawah 20%</button></div>}
    <div className="op-table-wrap"><table className="op-table"><thead><tr><th>Order / produk</th><th>Customer bayar</th><th>Nett Shopee</th><th>Modal + kos</th><th>Untung / margin</th><th>Semakan</th></tr></thead><tbody>{loading?<tr><td colSpan={6} className="op-empty">Memuatkan untung order…</td></tr>:!data?.rows.length?<tr><td colSpan={6} className="op-empty">{error?'Data tidak dapat dimuatkan. Cuba Refresh.':'Tiada order dalam pilihan ini.'}</td></tr>:data.rows.map(r=><tr key={r.order_id}>
      <td><button className="op-order-link" onClick={()=>setSelected(r.order_id)}>{r.order_sn}</button><small>@{r.buyer||'—'} · {profitDate(r.placed_at)}</small><small className="op-skus">{r.material_lines.slice(0,2).map(l=>`${l.quantity}× ${l.parent_sku||l.sku||l.title}`).join(' · ')}{r.material_lines.length>2?' …':''}</small></td>
      <td><b>{profitMoney(r.buyer_paid,r.currency)}</b><small>{r.status.replaceAll('_',' ')}</small></td><td><b>{profitMoney(r.nett,r.currency)}</b><small>{r.income_state==='released'?'Sudah release':r.income_state==='escrow'?'Escrow · belum release':'Menunggu data'}</small></td>
      <td><b>{profitMoney(r.cost_total,r.currency)}</b><small>{r.cost_state==='actual'?'Kos sebenar':r.cost_state==='missing'?'Bahan belum lengkap':r.detail_changed?'Semak item berubah':'Kos anggaran'}</small></td><td><b className={r.profit!=null&&r.profit<0?'op-negative':'op-positive'}>{profitMoney(r.profit,r.currency)}</b><small>{r.margin==null?'Margin belum diketahui':`${r.margin.toFixed(1)}% margin`}{r.profit_per_hour!=null?` · ${profitMoney(r.profit_per_hour)} / jam`:''}</small></td>
      <td><span className={`op-badge ${r.profit_state}`}>{profitStateLabel(r)}</span><button className="op-detail-link" onClick={()=>setSelected(r.order_id)}>Detail kos →</button></td>
    </tr>)}</tbody></table></div><div className="op-pager"><span>{data?.total?offset+1:0}–{Math.min(offset+50,data?.total||0)} daripada {data?.total||0} order</span><div><button className="btn btn-outline btn-sm" disabled={loading||offset===0} onClick={()=>setOffset(v=>Math.max(0,v-50))}>Sebelumnya</button><button className="btn btn-outline btn-sm" disabled={loading||offset+50>=(data?.total||0)} onClick={()=>setOffset(v=>v+50)}>Seterusnya</button></div></div>
    {selected&&<OrderProfitDetail key={selected} orderId={selected} canManage={canManage} onClose={()=>setSelected(null)} onSaved={()=>setRefresh(v=>v+1)}/>}
  </div>;
}
