import {useEffect,useMemo,useState} from 'react';
import {malaysiaDate,profitMoney,profitRequest} from '../lib/orderProfit';
import {skuRange} from './SalesSku';
import OrderProfitDetail from '../components/OrderProfitDetail';
import './SalesChannel.css';

type Channel='shopee'|'deco';
type Stat={channel:Channel;orders:number;sales_orders:number;sales:number|null;known_sales:number;sales_share:number|null;known_sales_share:number|null;missing_sales:number;basis_review_orders:number;average_order:number|null;known_average_order:number|null;growth:number|null;profit:number|null;known_profit:number|null;actual_profit:number|null;estimated_profit:number|null;missing_profit:number;margin:number|null;received:number|null;missing_received:number;known_pending:number|null;missing_pending:number;known_nett:number|null;known_fees:number|null;missing_fees:number;known_refund:number|null;missing_refund:number;known_return_shipping:number|null;known_shipping_loss:number|null;shipping:number|null;discount:number|null;cancelled:number;cancel_rate:number|null;refund_orders:number;loss_orders:number;customers:number;repeat_customers:number;repeat_orders:number;repeat_rate:number|null;unknown_customers:number;avg_fulfillment_days:number|null;timed_orders:number;pending_over_7_days:number};
type Order={order_id:string;channel:Channel;day:string;reference:string;status:string;included:boolean;sales:number|null;refund:number|null;received:number|null;pending:number|null;nett:number|null;profit:number|null;profit_state:string;payment_evidence:string;basis_review:boolean;repeat_customer:boolean};
type Trend={day:string;channel:Channel;sales:number|null;profit:number|null;orders:number};
type Report={channels:Stat[];summary:{sales:number|null;known_sales:number;orders:number;missing_sales:number;basis_review_orders:number;foreign_orders:number};coverage:{channel:Channel;first_day:string|null;last_day:string|null;orders:number}[];bucket:string;trend:Trend[];rows:Order[];total:number;products:{channel:Channel;sku:string;title:string;units:number;orders:number;sales:number|null;profit:number|null}[];pending_aging:{channel:Channel;age:string;orders:number;known_amount:number|null;missing:number}[]};
const names:Record<Channel,string>={shopee:'Shopee',deco:'Deco sendiri'};
const colors:Record<Channel,string>={shopee:'#ed7a42',deco:'#4276dc'};
const periods=[['day','1 hari'],['week','1 minggu'],['month','1 bulan'],['quarter','3 bulan'],['half','6 bulan'],['year','1 tahun'],['all','Keseluruhan'],['custom','Tarikh sendiri']];
const pct=(n:number|null)=>n==null?'—':`${n.toLocaleString('en-MY',{maximumFractionDigits:2})}%`;
const cell=(v:unknown)=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"';
const evidence=(v:string)=>({released:'Release disahkan',escrow:'Escrow anggaran',report_estimate:'Nett anggaran Excel',missing:'Finance belum lengkap',transaction:'Transaksi direkodkan',paid_status_only:'Status paid; amaun transaksi belum ada',unpaid:'Belum bayar'}[v]||v);
function Amount({value,missing=0,known=false}:{value:number|null;missing?:number;known?:boolean}){return <><b>{profitMoney(value)}</b>{(known||missing>0)&&<small>{missing>0?`${missing} order belum lengkap`:'Jumlah diketahui'}</small>}</>}
export default function SalesChannel({canManage=false,onOpenOrder}:{canManage?:boolean;onOpenOrder?:(reference:string)=>void}){
 const today=malaysiaDate();
 const [period,setPeriod]=useState('month'),[range,setRange]=useState(()=>skuRange('month',today)),[channel,setChannel]=useState('all'),[kind,setKind]=useState('all'),[query,setQuery]=useState(''),[search,setSearch]=useState(''),[page,setPage]=useState(0),[metric,setMetric]=useState<'sales'|'orders'|'profit'>('sales'),[refresh,setRefresh]=useState(0),[report,setReport]=useState<Report|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[exporting,setExporting]=useState(false),[order,setOrder]=useState<string|null>(null);
 useEffect(()=>{const id=setTimeout(()=>{setSearch(query);setPage(0)},350);return()=>clearTimeout(id)},[query]);
 useEffect(()=>{let active=true;setBusy(true);setError('');setReport(null);
  if(!range.to||(range.from&&range.from>range.to)||range.to>today){setError('Semak tarikh: julat mesti berakhir selewat-lewatnya hari ini.');setBusy(false);return;}
  profitRequest<Report>({action:'sales_channel_report',from:range.from||null,to:range.to,channel,kind,query:search,offset:page*50}).then(v=>{if(active)setReport(v)}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setBusy(false)});return()=>{active=false};
 },[range.from,range.to,channel,kind,search,page,refresh,today]);
 const setFilter=(c:string,k='all')=>{setChannel(c);setKind(k);setPage(0)};
 async function exportCsv(){setExporting(true);setError('');try{const r=await profitRequest<Report>({action:'sales_channel_report',from:range.from||null,to:range.to,channel,kind,query:search,offset:0,limit:5000});if(r.total>5000)throw new Error('Lebih 5,000 order. Kecilkan tarikh atau filter sebelum eksport.');const text=[['Channel','Order','Tarikh MYT','Status','Dikira sales','Sales barang MYR sebelum refund','Refund diketahui MYR','Diterima diketahui MYR','Pending diketahui MYR','Nett MYR','Untung MYR','Keadaan untung','Bukti bayaran','Asas perlu semak'],...r.rows.map(o=>[names[o.channel],o.reference,o.day,o.status,o.included?'Ya':'Tidak',o.sales,o.refund,o.received,o.pending,o.nett,o.profit,o.profit_state,evidence(o.payment_evidence),o.basis_review?'Ya':'Tidak'])].map(r=>r.map(cell).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\uFEFF'+text],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`sales-channel-${range.from||'all'}-${range.to}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){setError((e as Error).message)}finally{setExporting(false)}}
 const days=useMemo(()=>[...new Set(report?.trend.map(t=>t.day)||[])],[report]);
 const series=useMemo(()=>Object.fromEntries((['shopee','deco'] as Channel[]).map(c=>[c,new Map((report?.trend||[]).filter(t=>t.channel===c).map(t=>[t.day,t[metric]]))])) as Record<Channel,Map<string,number|null>>,[report,metric]);
 const values=Object.values(series).flatMap(m=>[...m.values()]).filter((v):v is number=>v!=null),low=Math.min(0,...values),high=Math.max(1,...values);
 const x=(i:number)=>50+i/Math.max(1,days.length-1)*730,y=(v:number)=>190-(v-low)/(high-low)*165;
 const open=(o:Order)=>o.channel==='shopee'?setOrder(o.order_id):onOpenOrder?.(o.reference);
 return <section className="channel-page">
  <header className="channel-heading"><div><h2>Sales Channel</h2><p>Shopee vs Deco sendiri • MYR • tarikh order, waktu Malaysia</p></div><div><button disabled={busy} onClick={()=>setRefresh(v=>v+1)}>Muat semula</button><button disabled={exporting||!report?.total} onClick={()=>void exportCsv()}>{exporting?'Mengeksport…':'Eksport order CSV'}</button></div></header>
  <div className="channel-periods">{periods.map(([key,label])=><button key={key} aria-pressed={period===key} onClick={()=>{setPeriod(key);setPage(0);if(key!=='custom')setRange(skuRange(key,today))}}>{label}</button>)}</div>
  <div className="channel-filters"><label>Dari<input type="date" value={range.from} max={range.to} onChange={e=>{setPeriod('custom');setPage(0);setRange({...range,from:e.target.value})}}/></label><label>Hingga<input type="date" value={range.to} max={today} onChange={e=>{setPeriod('custom');setPage(0);setRange({...range,to:e.target.value})}}/></label></div>
  {error&&<p role="alert" className="channel-error">{error} <button onClick={()=>setRefresh(v=>v+1)}>Cuba semula</button></p>}{busy&&<p role="status">Memuatkan laporan kedua-dua channel…</p>}
  {report&&<>
   <div className="channel-total"><span>Sales barang sebelum refund</span><strong>{profitMoney(report.summary.sales??report.summary.known_sales)}</strong><span>{report.summary.orders.toLocaleString('en-MY')} order jualan{report.summary.missing_sales>0?` • jumlah diketahui; ${report.summary.missing_sales} order tiada nilai`:''}</span></div>
   {(report.summary.missing_sales>0||report.summary.basis_review_orders>0)&&<p className="channel-warning">Percentage berdasarkan sales diketahui. {report.summary.missing_sales} order tiada nilai barang; {report.summary.basis_review_orders} order perlu semak asas diskaun. Ini belum jumlah muktamad selepas refund.</p>}
   <div className="channel-share" aria-label="Pecahan percentage sales">{report.channels.map(c=><button key={c.channel} style={{flex:Math.max(.04,(c.known_sales_share||0)/100),background:colors[c.channel]}} onClick={()=>setFilter(c.channel)}>{names[c.channel]} {pct(c.sales_share??c.known_sales_share)}</button>)}</div>
   <div className="channel-cards">{report.channels.map(c=><article key={c.channel} style={{borderTopColor:colors[c.channel]}}><header><h3>{names[c.channel]}</h3><span>{pct(c.sales_share??c.known_sales_share)} sales</span></header><button className="channel-sales" onClick={()=>setFilter(c.channel)}><Amount value={c.sales??c.known_sales} missing={c.missing_sales}/></button><div className="channel-card-grid"><div><span>Order jualan</span><b>{c.sales_orders}</b></div><div><span>Purata order</span><Amount value={c.average_order??c.known_average_order} missing={c.missing_sales}/></div><div><span>Perubahan sales</span><b>{pct(c.growth)}</b><small>Tempoh sebelumnya, sama bilangan hari</small></div><div><span>Untung penuh / margin</span><Amount value={c.profit} missing={c.missing_profit}/><small>{pct(c.margin)} • sebelum overhead</small></div></div><footer><button onClick={()=>setFilter(c.channel,'pending')}>Semak pending</button><button onClick={()=>setFilter(c.channel,'incomplete')}>Data belum lengkap</button></footer></article>)}</div>
   <div className="channel-panel"><header className="channel-heading"><h3>Trend kedua-dua channel</h3><label>Metrik graf<select value={metric} onChange={e=>setMetric(e.target.value as typeof metric)}><option value="sales">Sales barang</option><option value="orders">Order jualan</option><option value="profit">Untung penuh</option></select></label></header><p className="channel-note">{report.bucket==='month'?'Bulanan':'Harian'} • ruang terputus bermaksud nilai belum lengkap.</p><svg className="channel-trend" viewBox="0 0 800 220" role="img" aria-label="Trend Shopee dan Deco sendiri"><line x1="50" x2="780" y1={y(0)} y2={y(0)} stroke="#d2dbe7"/><text x="0" y="24">{metric==='orders'?high.toFixed(0):profitMoney(high)}</text><text x="0" y="195">{metric==='orders'?low.toFixed(0):profitMoney(low)}</text>{(['shopee','deco'] as Channel[]).flatMap(c=>days.map((d,i)=>{const v=series[c].get(d);const previous=series[c].get(days[i-1]);return v==null?null:<g key={c+d}><title>{d} • {names[c]}: {metric==='orders'?v:profitMoney(v)}</title>{i>0&&previous!=null&&<line x1={x(i-1)} x2={x(i)} y1={y(previous)} y2={y(v)} stroke={colors[c]} strokeWidth="2.5"/>}<circle cx={x(i)} cy={y(v)} r="3" fill={colors[c]}/></g>}))}</svg><div className="channel-heading"><small>{days[0]}</small><small>{days.at(-1)}</small></div><div className="channel-legend">{report.channels.map(c=><span key={c.channel}><i style={{background:colors[c.channel]}}/>{names[c.channel]}</span>)}</div><details><summary>Lihat angka trend</summary><div className="channel-table"><table><thead><tr><th>Tarikh</th><th>Shopee</th><th>Deco sendiri</th></tr></thead><tbody>{days.map(d=><tr key={d}><td>{d}</td>{(['shopee','deco'] as Channel[]).map(c=><td key={c}>{metric==='orders'?(series[c].get(d)??'—'):profitMoney(series[c].get(d))}</td>)}</tr>)}</tbody></table></div></details></div>
   <div className="channel-panel channel-table"><h3>Finance, customer & operasi</h3><table><thead><tr><th>Metrik</th>{report.channels.map(c=><th key={c.channel}>{names[c.channel]}</th>)}</tr></thead><tbody>
    {([
     ['Duit diterima diketahui',(c:Stat)=><Amount value={c.received} missing={c.missing_received} known/>],
     ['Pending diketahui',(c:Stat)=><button onClick={()=>setFilter(c.channel,'pending')}><Amount value={c.known_pending} missing={c.missing_pending} known/></button>],
     ['Nett Shopee diketahui',(c:Stat)=><Amount value={c.known_nett} known/>],
     ['Untung sebenar diketahui',(c:Stat)=><Amount value={c.actual_profit} known/>],
     ['Untung anggaran diketahui',(c:Stat)=><Amount value={c.estimated_profit} known/>],
     ['Platform fees diketahui',(c:Stat)=><Amount value={c.known_fees} missing={c.missing_fees} known/>],
     ['Shipping dibayar customer',(c:Stat)=><Amount value={c.shipping}/>],
     ['Diskaun order direkodkan',(c:Stat)=><Amount value={c.discount}/>],
     ['Refund diketahui',(c:Stat)=><Amount value={c.known_refund} missing={c.missing_refund} known/>],
     ['Return / reverse shipping diketahui',(c:Stat)=><Amount value={c.known_return_shipping} known/>],
     ['Shipping rugi diketahui',(c:Stat)=><Amount value={c.known_shipping_loss} known/>],
     ['Order rugi diketahui',(c:Stat)=><button onClick={()=>setFilter(c.channel,'loss')}>{c.loss_orders} order</button>],
     ['Cancel / kadar',(c:Stat)=><button onClick={()=>setFilter(c.channel,'cancelled')}>{c.cancelled} order • {pct(c.cancel_rate)}</button>],
     ['Customer dikenal pasti',(c:Stat)=><>{c.customers}<small>{c.unknown_customers} order tanpa identiti</small></>],
     ['Customer repeat / kadar',(c:Stat)=><button onClick={()=>setFilter(c.channel,'repeat')}>{c.repeat_customers} customer • {pct(c.repeat_rate)}<small>{c.repeat_orders} order repeat dalam data tersedia</small></button>],
     ['Purata order → shipped / collected',(c:Stat)=><>{c.avg_fulfillment_days==null?'—':`${c.avg_fulfillment_days} hari`}<small>{c.timed_orders} order ada timestamp</small></>],
    ] as [string,(c:Stat)=>React.ReactNode][]).map(([label,render])=><tr key={label}><td>{label}</td>{report.channels.map(c=><td key={c.channel}>{render(c)}</td>)}</tr>)}
   </tbody></table><p className="channel-note">Duit diterima dan pending ialah keadaan semasa bagi order dalam tempoh dipilih. Pending Shopee = nett yang belum ada bukti release; termasuk anggaran lama, bukan pengesahan hutang Shopee. Pending Deco = baki belum bayar termasuk partial payment. Nilai — belum tersedia, bukan sifar.</p></div>
   <div className="channel-panel"><h3>Umur order pending</h3><div className="channel-aging">{report.pending_aging.map(a=><button key={a.channel+a.age} onClick={()=>setFilter(a.channel,'pending')}><span>{names[a.channel]} • {a.age}</span><b>{profitMoney(a.known_amount)}</b><small>{a.orders} order{a.missing?` • ${a.missing} amaun belum ada`:''}</small></button>)}</div><p className="channel-note">Umur mengikut tarikh order; ini bukan tarikh akhir bayaran atau tarikh release dijanjikan.</p></div>
   <div className="channel-products">{report.channels.map(c=><div className="channel-panel channel-table" key={c.channel}><h3>Top 10 produk • {names[c.channel]}</h3><table><thead><tr><th>SKU / Produk</th><th>Unit</th><th>Sales agihan</th><th>Untung agihan</th></tr></thead><tbody>{report.products.filter(p=>p.channel===c.channel).map(p=><tr key={p.sku}><td><b>{p.sku}</b><small>{p.title}</small></td><td>{p.units}</td><td>{profitMoney(p.sales)}</td><td>{profitMoney(p.profit)}</td></tr>)}</tbody></table>{!report.products.some(p=>p.channel===c.channel)&&<p>Tiada item dalam tempoh ini.</p>}<p className="channel-note">Sales/untung diagihkan mengikut nilai item. Deco guna kod katalog atau kategori apabila SKU belum ada. Agihan bukan kos SKU sebenar.</p></div>)}</div>
   <div className="channel-panel"><h3>Order penyumbang kepada laporan</h3><div className="channel-filters"><label>Channel order<select value={channel} onChange={e=>setFilter(e.target.value,kind)}><option value="all">Kedua-dua channel</option><option value="shopee">Shopee</option><option value="deco">Deco sendiri</option></select></label><label>Jenis order<select value={kind} onChange={e=>setFilter(channel,e.target.value)}><option value="all">Semua</option><option value="pending">Pending</option><option value="loss">Untung negatif</option><option value="cancelled">Cancelled / in cancel</option><option value="incomplete">Belum lengkap</option><option value="repeat">Customer repeat</option></select></label><label>Cari order<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Order ID"/></label></div><p className="channel-note">Filter di sini menapis senarai order. Graf dan jumlah di atas kekal membandingkan kedua-dua channel.</p><div className="channel-table"><table><thead><tr><th>Order / Channel</th><th>Tarikh / Status</th><th>Sales barang</th><th>Diterima</th><th>Pending</th><th>Untung</th><th>Bukti</th></tr></thead><tbody>{report.rows.map(o=><tr key={o.channel+o.order_id}><td><button onClick={()=>open(o)}>{o.reference}</button><small>{names[o.channel]}{o.repeat_customer?' • Repeat':''}</small></td><td>{o.day}<small>{o.status}{!o.included?' • Sales dikecualikan':''}</small></td><td>{profitMoney(o.sales)}{o.basis_review&&<small>Asas perlu semak</small>}</td><td>{profitMoney(o.received)}</td><td>{profitMoney(o.pending)}</td><td>{profitMoney(o.profit)}<small>{o.profit_state==='actual'?'Sebenar':o.profit_state==='estimated'?'Anggaran':'Belum lengkap'}</small></td><td>{evidence(o.payment_evidence)}</td></tr>)}</tbody></table></div>{!report.rows.length&&<p>Tiada order untuk filter ini.</p>}<div className="channel-heading"><button disabled={!page} onClick={()=>setPage(v=>v-1)}>Sebelum</button><span>{report.total} order • halaman {page+1}/{Math.max(1,Math.ceil(report.total/50))}</span><button disabled={(page+1)*50>=report.total} onClick={()=>setPage(v=>v+1)}>Seterusnya</button></div></div>
   <details className="channel-panel"><summary>Definisi & liputan data</summary><ul><li>Sales barang = harga jualan barang selepas diskaun seller yang dikenal pasti, tidak termasuk shipping, sebelum refund dan platform fees. Deco menggunakan jumlah akhir order tolak delivery fee; Shopee menggunakan subtotal item tolak voucher/coins seller yang berasingan. Diskaun dalam harga tidak ditolak dua kali.</li><li>Order Deco sebenar termasuk order cash counter belum dibayar. Draft tidak dikira. Shopee unpaid/unknown dan order cancelled/in cancel tidak masuk sales. Rekod cancelled masih boleh disemak.</li><li>Order Shopee kekal channel Shopee walaupun customer chat WhatsApp. Order dalaman yang dipautkan melalui ID atau Order SN tepat tidak dikira dua kali. Deco sendiri merangkumi Shop, WhatsApp dan order kaunter/dalaman; pecahan subchannel tidak diteka.</li><li>Untung ialah contribution order sebelum overhead. Modal Deco belum mempunyai model lengkap; untung/margin Deco kekal —. Anggaran nett Shopee tidak menjadi release sebenar.</li><li>Refund yang belum mempunyai amaun jelas tidak dianggap sifar. Laporan ini sebelum refund; ia bukan net sales selepas refund atau P&L rasmi. Fees dan shipping yang sudah masuk nett tidak ditolak kali kedua.</li><li>Repeat customer berdasarkan identiti yang direkodkan dan sejarah tersedia dalam channel yang sama. Tiada padanan customer merentas channel secara tekaan.</li><li>Perubahan sales membandingkan tempoh sebelumnya dengan panjang hari yang sama, bukan bulan kalendar penuh. Kekurangan sejarah boleh menjejaskan perbandingan.</li>{report.coverage.map(c=><li key={c.channel}>{names[c.channel]}: data tersedia {c.first_day||'—'} → {c.last_day||'—'} • {c.orders} order. Ini tidak membuktikan sejarah lengkap.</li>)}<li>{report.summary.foreign_orders} order mata wang asing dalam tempoh diasingkan daripada MYR.</li></ul></details>
  </>}
  {order&&<OrderProfitDetail orderId={order} canManage={canManage} onClose={()=>setOrder(null)} onSaved={()=>setRefresh(v=>v+1)}/>}
 </section>;
}
