import {useEffect,useMemo,useState} from 'react';
import {profitRequest,profitMoney,malaysiaDate,type FinanceOptions} from '../lib/orderProfit';
import OrderProfitDetail from '../components/OrderProfitDetail';
import './SalesSku.css';
type Metric='net_units'|'sales'|'orders'|'profit';
type Row={sku_key:string;sku:string;title:string;variations:number;units:number;returned:number;net_units:number;orders:number;sales:number|null;profit:number|null;missing_profit_orders:number};
type Trend={day:string;units:number;sales:number|null;orders:number;profit:number|null};
type Report={rows:Row[];truncated:boolean;summary:{sales:number|null;net_units:number;returned:number;orders:number;sku_count:number};coverage:{first_day:string;last_day:string;bucket:string};trend:Trend[];orders:{order_id:string;order_sn:string;day:string;units:number;sales:number|null;profit:number|null}[];order_count:number};
const labels:Record<Metric,string>={net_units:'Unit bersih',sales:'Sales barang',orders:'Bilangan order',profit:'Untung agihan (anggaran)'};
const periods=[['day','1 hari'],['week','1 minggu'],['month','1 bulan'],['quarter','3 bulan'],['half','6 bulan'],['year','1 tahun'],['all','Keseluruhan'],['custom','Tarikh sendiri']];
export function skuRange(period:string,today:string){const start=new Date(today+'T00:00:00Z');if(period==='all')return {from:'',to:today};if(period==='week')start.setUTCDate(start.getUTCDate()-6);else if(period!=='day'){const months=({month:1,quarter:3,half:6,year:12} as Record<string,number>)[period]||1;const day=start.getUTCDate();start.setUTCDate(1);start.setUTCMonth(start.getUTCMonth()-months);start.setUTCDate(Math.min(day,new Date(Date.UTC(start.getUTCFullYear(),start.getUTCMonth()+1,0)).getUTCDate()));start.setUTCDate(start.getUTCDate()+1);}return {from:start.toISOString().slice(0,10),to:today};}
const csvCell=(v:unknown)=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"';
export default function SalesSku({canManage=false}:{canManage?:boolean}){
 const today=malaysiaDate();const [period,setPeriod]=useState('month'),[range,setRange]=useState(()=>skuRange('month',today)),[currency,setCurrency]=useState('MYR'),[shop,setShop]=useState(''),[options,setOptions]=useState<FinanceOptions>(),[metric,setMetric]=useState<Metric>('net_units'),[query,setQuery]=useState(''),[ascending,setAscending]=useState(false),[page,setPage]=useState(0),[selected,setSelected]=useState<Row|null>(null),[order,setOrder]=useState<string|null>(null),[report,setReport]=useState<Report|null>(null),[detail,setDetail]=useState<Report|null>(null),[error,setError]=useState(''),[detailError,setDetailError]=useState(''),[busy,setBusy]=useState(false),[refresh,setRefresh]=useState(0);
 useEffect(()=>{let active=true;profitRequest<FinanceOptions>({action:'order_finance_options'}).then(v=>{if(active)setOptions(v)}).catch(()=>{});return()=>{active=false}},[]);
 useEffect(()=>{let active=true;setBusy(true);setError('');setReport(null);setSelected(null);if(!range.to||(range.from&&range.from>range.to)||range.to>today){setError('Semak julat tarikh. Tarikh akhir mesti sehingga hari ini.');setBusy(false);return;}
 profitRequest<Report>({action:'sales_sku_report',from:range.from||null,to:range.to,currency,shop_id:shop||null}).then(v=>{if(active)setReport(v)}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setBusy(false)});return()=>{active=false}},[range.from,range.to,currency,shop,refresh,today]);
 useEffect(()=>{let active=true;setDetail(null);setDetailError('');if(selected)profitRequest<Report>({action:'sales_sku_report',from:range.from||null,to:range.to,currency,shop_id:shop||null,sku_key:selected.sku_key}).then(v=>{if(active)setDetail(v)}).catch(e=>{if(active)setDetailError(e.message)});return()=>{active=false}},[selected,range.from,range.to,currency,shop,refresh]);
 useEffect(()=>setPage(0),[query,metric,ascending,report]);
 const rows=useMemo(()=>[...(report?.rows||[])].filter(r=>(r.sku+' '+r.title).toLowerCase().includes(query.toLowerCase())).sort((a,b)=>a[metric]==null?b[metric]==null?0:1:b[metric]==null?-1:(ascending?1:-1)*(Number(a[metric])-Number(b[metric]))||a.sku.localeCompare(b.sku)),[report,query,metric,ascending]);
 const chart=rows.filter(r=>r[metric]!=null).slice(0,10),max=Math.max(1,...chart.map(r=>Math.abs(Number(r[metric]))));const value=(v:number|null|undefined)=>metric==='sales'||metric==='profit'?profitMoney(v,currency):v==null?'—':v.toLocaleString('en-MY');
 function exportCsv(){const data=[['SKU','Nama produk','Unit','Return','Unit bersih','Order','Sales '+currency,'Untung agihan '+currency],...rows.map(r=>[r.sku,r.title,r.units,r.returned,r.net_units,r.orders,r.sales,r.profit])].map(r=>r.map(csvCell).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\uFEFF'+data],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`sales-sku-${range.from||'all'}-${range.to}-${currency}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 const trend=selected?(detail?.trend||[]):(report?.trend||[]);const vals=trend.map(t=>metric==='net_units'?t.units:t[metric]);const lo=Math.min(0,...vals.filter((v):v is number=>v!=null)),hi=Math.max(1,...vals.filter((v):v is number=>v!=null));
 const x=(i:number)=>10+i/Math.max(1,trend.length-1)*780,y=(v:number)=>160-(v-lo)/(hi-lo)*140;
 return <section className="sku-page"><header className="sku-heading"><div><h2>Sales SKU</h2><p>SKU paling laku mengikut tarikh order • waktu Malaysia</p></div><div><button onClick={()=>setRefresh(v=>v+1)} disabled={busy}>Muat semula</button> <button onClick={exportCsv} disabled={!rows.length}>Eksport CSV</button></div></header>
 <div className="sku-periods">{periods.map(([key,label])=><button key={key} aria-pressed={period===key} onClick={()=>{setPeriod(key);if(key!=='custom')setRange(skuRange(key,today))}}>{label}</button>)}</div>
 <div className="sku-filters"><label>Dari<input type="date" value={range.from} max={range.to} onChange={e=>{setPeriod('custom');setRange({...range,from:e.target.value})}}/></label><label>Hingga<input type="date" value={range.to} max={today} onChange={e=>{setPeriod('custom');setRange({...range,to:e.target.value})}}/></label><label>Mata wang<select value={currency} onChange={e=>{setCurrency(e.target.value);setShop('')}}>{[...new Set(['MYR',...(options?.shops||[]).map(s=>s.currency)])].map(c=><option key={c}>{c}</option>)}</select></label><label>Kedai<select value={shop} onChange={e=>setShop(e.target.value)}><option value="">Semua kedai</option>{options?.shops.filter(s=>s.currency===currency).map(s=><option key={s.shop_id} value={s.shop_id}>{s.shop_id}</option>)}</select></label></div>
 {error&&<p role="alert" className="sku-error">{error}</p>}{busy&&<p role="status">Memuatkan sales SKU…</p>}
 {report&&<><div className="sku-kpis">{[['Sales barang',profitMoney(report.summary.sales,currency)],['Unit bersih',report.summary.net_units],['Order',report.summary.orders],['SKU',report.summary.sku_count]].map(([k,v])=><div key={k}><span>{k}</span><strong>{v}</strong></div>)}</div>
 <p className="sku-note">Data tersedia: {report.coverage.first_day||'—'} hingga {report.coverage.last_day||'—'}. {report.summary.returned} unit return ditolak daripada unit bersih. Sales ialah subtotal barang sebelum potongan platform; order batal dan belum bayar dikecualikan.</p>
 <div className="sku-filters"><label>Cari SKU / produk<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cari SKU atau nama produk"/></label><label>Susun mengikut<select value={metric} onChange={e=>setMetric(e.target.value as Metric)}>{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Arah<select value={ascending?'asc':'desc'} onChange={e=>setAscending(e.target.value==='asc')}><option value="desc">Tertinggi dahulu</option><option value="asc">Terendah dahulu</option></select></label></div>
 <div className="sku-panel"><h3>Ranking 10 SKU • {labels[metric]}</h3>{!rows.length?<p>Tiada SKU untuk pilihan ini.</p>:<div className="sku-bars">{chart.map(r=><button key={r.sku_key} onClick={()=>setSelected(r)} aria-label={`Butiran ${r.sku}`}><span className="sku-bar-name" title={r.title}>{r.sku}<small>{r.title}</small></span><span className="sku-bar-track"><span style={{width:`${Math.abs(Number(r[metric]))/max*100}%`,background:Number(r[metric])<0?'#d35454':undefined}}/></span><b>{value(r[metric])}</b></button>)}</div>}{rows.some(r=>r[metric]==null)&&<p className="sku-note">SKU dengan nilai belum lengkap tidak dipaparkan dalam graf.</p>}</div>
 <div className="sku-panel sku-table-wrap"><table><thead><tr><th>SKU / Produk</th><th>Unit</th><th>Return</th><th>Unit bersih</th><th>Order</th><th>Sales barang</th><th>Untung agihan</th></tr></thead><tbody>{rows.slice(page*50,page*50+50).map(r=><tr key={r.sku_key}><td><button onClick={()=>setSelected(r)}>{r.sku}</button><small>{r.title}{r.variations>1?` • ${r.variations} variasi`:''}</small></td><td>{r.units}</td><td>{r.returned}</td><td>{r.net_units}</td><td>{r.orders}</td><td>{profitMoney(r.sales,currency)}</td><td>{profitMoney(r.profit,currency)}{r.missing_profit_orders>0&&<small>{r.missing_profit_orders} order belum lengkap</small>}</td></tr>)}</tbody></table></div><div className="sku-pagination"><button disabled={!page} onClick={()=>setPage(v=>v-1)}>Sebelum</button><span>{rows.length} SKU • Halaman {page+1}/{Math.max(1,Math.ceil(rows.length/50))}</span><button disabled={(page+1)*50>=rows.length} onClick={()=>setPage(v=>v+1)}>Seterusnya</button></div>
 {report.truncated&&<p role="alert">Had 5,000 SKU dicapai. Kecilkan julat tarikh atau kedai.</p>}
 <div className="sku-panel"><header className="sku-heading"><h3>{selected?`Trend ${selected.sku}`:'Trend semua SKU'}</h3>{selected&&<button onClick={()=>setSelected(null)}>Semua SKU</button>}</header>{detailError&&<p role="alert">{detailError}</p>}{selected&&!detail&&!detailError?<p role="status">Memuatkan butiran SKU…</p>:<><p>{labels[metric]} • {report.coverage.bucket==='month'?'bulanan':'harian'}</p><svg className="sku-trend" viewBox="0 0 800 180" role="img" aria-label={`Trend ${labels[metric]}`}><line x1="10" x2="790" y1={y(0)} y2={y(0)} stroke="#ccd3dc"/>{vals.map((v,i)=>v==null?null:<g key={i}><title>{trend[i].day}: {value(v)}</title>{i>0&&vals[i-1]!=null&&<line x1={x(i-1)} y1={y(Number(vals[i-1]))} x2={x(i)} y2={y(v)} stroke="#4975dc" strokeWidth="2"/>}<circle cx={x(i)} cy={y(v)} r="3" fill="#4975dc"/></g>)}</svg><div className="sku-heading"><small>{trend[0]?.day}</small><small>{trend.at(-1)?.day}</small></div><details><summary>Nilai trend mengikut tarikh</summary><div className="sku-table-wrap"><table><thead><tr><th>Tarikh</th><th>{labels[metric]}</th></tr></thead><tbody>{trend.map((t,i)=><tr key={t.day}><td>{t.day}</td><td>{value(vals[i])}</td></tr>)}</tbody></table></div></details></>}
 {selected&&detail&&<><h3>Order untuk {selected.sku}</h3><div className="sku-table-wrap"><table><thead><tr><th>Order</th><th>Tarikh</th><th>Unit bersih</th><th>Sales barang</th><th>Untung agihan</th></tr></thead><tbody>{detail.orders.map(o=><tr key={o.order_id}><td><button onClick={()=>setOrder(o.order_id)}>{o.order_sn}</button></td><td>{o.day}</td><td>{o.units}</td><td>{profitMoney(o.sales,currency)}</td><td>{profitMoney(o.profit,currency)}</td></tr>)}</tbody></table></div>{detail.order_count>500&&<p>500 order terbaru daripada {detail.order_count}. Kecilkan julat tarikh untuk melihat selebihnya.</p>}</>}
 </div><p className="sku-note">Untung SKU ialah anggaran agihan untung order mengikut nisbah sales barang. Nilai — bermaksud finance atau modal belum lengkap; ia tidak dianggap sifar. Tempoh panjang hanya merangkumi data yang sudah masuk DB.</p></>}
 {order&&<OrderProfitDetail orderId={order} canManage={canManage} onClose={()=>setOrder(null)} onSaved={()=>setRefresh(v=>v+1)}/>}
 </section>
}
