// @ts-nocheck
import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const db=createClient(Deno.env.get('SUPABASE_URL')||'',Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'',{auth:{persistSession:false}});
const H={'content-type':'application/json','access-control-allow-origin':'*'};
const out=(x,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H});
const t=v=>v==null?'':String(v).trim();
const BSUID_RE=/^[A-Z]{2}\.\d+$/i;
const bsuid=v=>BSUID_RE.test(t(v))?t(v).toUpperCase():'';
const digits=v=>{const raw=t(v);if(!raw||BSUID_RE.test(raw))return'';let d=raw.replace(/\D/g,'');if(!d)return'';if(d[0]=='0')d='60'+d.slice(1);else if(d[0]=='1')d='60'+d;return/^601\d{8,9}$/.test(d)?d:''};
async function auth(r){const k=r.headers.get('x-qrpay-ai-token')||'',q=await db.from('private_runtime_settings').select('setting_value').eq('setting_key','qrpay_ai_worker_token').maybeSingle();return!!k&&!q.error&&k===q.data?.setting_value}
async function waSetting(key){const q=await db.from('whatsapp_settings').select('secret_value,text_value,value').eq('key',key).maybeSingle();return t(q.data?.secret_value)||t(q.data?.text_value)||t(q.data?.value?.url)}
const allowed=new Set(['status','matched_conversation_id','matched_phone','matched_bsuid','matched_username','matched_customer_master_id','matched_customer_name','match_score','match_reason','extraction','evidence','locked_at','completed_at','updated_at','next_attempt_at','last_error']);
function title(k,x){const s=(t(k)+' '+t(x)).toLowerCase();if(/acrylic|akrilik/.test(s))return'Acrylic Cake Topper';if(/edible/.test(s))return'Edible Image';if(/wafer/.test(s))return'Wafer Paper';if(/burn/.test(s))return'Burn Away Combo';return'Cake Topper'}
function inferDate(p){if(p.date_need)return p.date_need;const a=p?.evidence?.messages||[],s=a.filter(x=>x.direction==='inbound').map(x=>t(x.text)).join('\n').toLowerCase(),now=new Date();let m=[...s.matchAll(/\b(\d{1,2})\s*(?:hb|haribulan)\b/g)].at(-1);if(m){let d=Number(m[1]),mo=now.getUTCMonth()+1,y=now.getUTCFullYear();if(d<now.getUTCDate()-3)mo++;if(mo>12){mo=1;y++}return`${y}-${String(mo).padStart(2,'0')}-${String(d).padStart(2,'0')}`}const months={jan:1,januari:1,feb:2,februari:2,mac:3,mar:3,april:4,apr:4,mei:5,may:5,jun:6,julai:7,july:7,ogos:8,aug:8,august:8,sep:9,september:9,okt:10,oct:10,nov:11,dis:12,dec:12};m=[...s.matchAll(/\b(\d{1,2})\s+(jan|januari|feb|februari|mac|mar|april|apr|mei|may|jun|julai|july|ogos|aug|august|sep|september|okt|oct|nov|dis|dec)\b/g)].at(-1);if(m)return`${now.getUTCFullYear()}-${String(months[m[2]]).padStart(2,'0')}-${String(Number(m[1])).padStart(2,'0')}`;return null}
function canon(p){p=structuredClone(p||{});p.customer=p.customer||{};p.customer.phone=digits(p.customer.phone)||'';p.date_need=inferDate(p);if(Array.isArray(p.items))p.items=p.items.map(x=>({...x,title:title(x?.k,x?.title)}));const items=p.items||[],critical=[];if(!p.customer.phone)critical.push('customer');if(!items.length)critical.push('product');if(items.some(x=>!x.qty))critical.push('qty');if(items.some(x=>!t(x.size)&&['edible','acrylic'].includes(t(x.k))))critical.push('variation');const detail=Math.max(.45,Math.min(.97,1-critical.length*.18-(p.date_need?0:.05)));p.ai_missing=[...new Set([...(p.date_need?[]:['date']),...critical])];p.ai_confidence={customer:Number(p.match_score||0),payment:.98,order_detail:Number(detail.toFixed(2))};if(items.length)for(const x of items)x.customization={...(x.customization||{}),ai_confidence:p.ai_confidence,ai_missing:p.ai_missing};return p}
function canDraft(p){return/^601\d{8,9}$/.test(digits(p?.customer?.phone))&&Array.isArray(p?.items)&&p.items.length>0}
function release(p){const c=p.ai_confidence||{};return c.customer>=.90&&c.payment>=.90&&c.order_detail>=.90&&!p.ai_missing.some(x=>['customer','product','qty','variation'].includes(x))}
async function unifiedIdentity(conversationId){if(!conversationId)return{};const url=await waSetting('unified_inbox_24h_url');if(!url)return{};try{const res=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({conversation_id:conversationId})}),data=await res.json().catch(()=>({}));if(!res.ok||data.ok===false)return{};return{matched_phone:digits(data.phone)||null,matched_bsuid:bsuid(data.bsuid)||null,matched_username:t(data.username)||null,matched_customer_master_id:t(data.customer_master_id)||null,whatsapp_link:t(data.whatsapp_link)||null}}catch{return{}}}
async function ensureReview(job,p,identity){const sourceKey=`qrpay:${t(job.transaction_id)||job.id}`;const existing=await db.from('admin_order_reviews').select('id').eq('source_type','qrpay').eq('source_key',sourceKey).is('completed_at',null).limit(1).maybeSingle();if(existing.data?.id){await db.from('admin_order_reviews').update({candidate_phone:identity.matched_phone||null,candidate_bsuid:identity.matched_bsuid||null,candidate_username:identity.matched_username||null,candidate_name:job.matched_customer_name||p.customer?.name||null,match_score:job.match_score||p.match_score||null,extraction:p,evidence:{...(p.evidence||{}),whatsapp_identity:identity},updated_at:new Date().toISOString()}).eq('id',existing.data.id);return existing.data.id}const q=await db.from('admin_order_reviews').insert({source_type:'qrpay',source_key:sourceKey,qrpay_job_id:job.id,transaction_id:job.transaction_id,amount:job.amount,candidate_phone:identity.matched_phone||null,candidate_bsuid:identity.matched_bsuid||null,candidate_username:identity.matched_username||null,candidate_name:job.matched_customer_name||p.customer?.name||null,match_score:job.match_score||p.match_score||null,extraction:p,evidence:{...(p.evidence||{}),whatsapp_identity:identity},status:'pending_admin'}).select('id').single();if(q.error)throw q.error;return q.data.id}
async function create(job,p,token){const{data,error}=await db.rpc('icetak_auto_create_qrpay_order',{p_job_id:job.id,p_payload:p,p_internal_token:token});if(error)throw error;const oid=t(data?.order_db_id);if(oid){const auto=release(p);await db.from('orders').update({production_approved:auto,admin_status:auto?'Ready to Process':'AI Draft — Check Needed',status:auto?'Ready to Process':'AI Draft — Check Needed',tab:'progress',admin_remark:(t(p.admin_remark)+'\nAI CONFIDENCE: customer '+Math.round(p.ai_confidence.customer*100)+'% | order '+Math.round(p.ai_confidence.order_detail*100)+'% | payment 98%\nMissing: '+(p.ai_missing.join(', ')||'None')).slice(0,3000),updated_at:new Date().toISOString()}).eq('id',oid);if(auto)await db.rpc('enqueue_clickup_production_order',{p_order_id:oid});await db.from('admin_order_notification_queue').update({event_type:auto?'ai_order_created':'ai_order_draft_created',status:'pending',scheduled_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('order_id',oid);await db.rpc('icetak_kick_admin_order_notification',{p_order_id:oid})}return data}

Deno.serve(async r=>{if(r.method==='OPTIONS')return new Response('ok',{headers:H});if(r.method!=='POST')return out({error:'POST required'},405);if(!await auth(r))return out({error:'Unauthorized'},401);const token=r.headers.get('x-qrpay-ai-token')||'',b=await r.json().catch(()=>({}));try{
if(b.action==='claim'){const{data,error}=await db.rpc('claim_qrpay_ai_jobs',{p_limit:Math.max(1,Math.min(10,Number(b.batch_size||3)))});if(error)throw error;return out({ok:true,jobs:data||[]})}
if(b.action==='update_job'){const current=await db.from('qrpay_ai_jobs').select('*').eq('id',b.job_id).maybeSingle();if(current.error)throw current.error;const patch={};for(const[k,v]of Object.entries(b.patch||{}))if(allowed.has(k))patch[k]=k==='extraction'?canon(v):v;if('matched_phone'in patch)patch.matched_phone=digits(patch.matched_phone)||null;const conversationId=t(patch.matched_conversation_id||current.data?.matched_conversation_id);if(conversationId){const identity=await unifiedIdentity(conversationId);if(identity.matched_phone&&!patch.matched_phone)patch.matched_phone=identity.matched_phone;if(identity.matched_bsuid)patch.matched_bsuid=identity.matched_bsuid;if(identity.matched_username)patch.matched_username=identity.matched_username;if(identity.matched_customer_master_id)patch.matched_customer_master_id=identity.matched_customer_master_id;if(patch.extraction){patch.extraction.whatsapp_identity={bsuid:identity.matched_bsuid||null,username:identity.matched_username||null,phone:identity.matched_phone||null,customer_master_id:identity.matched_customer_master_id||null,whatsapp_link:identity.whatsapp_link||null}}if(patch.evidence)patch.evidence={...patch.evidence,whatsapp_identity:identity}}
if(patch.status==='order_created'&&current.data?.status==='needs_review'&&!current.data?.order_id){patch.status='needs_review';patch.completed_at=null;patch.last_error=current.data?.last_error||'Real customer phone required before order creation'}patch.updated_at=new Date().toISOString();const{data,error}=await db.from('qrpay_ai_jobs').update(patch).eq('id',b.job_id).select('*').maybeSingle();if(error)throw error;return out({ok:true,job:data})}
if(b.action==='create_order'){const{data:job,error}=await db.from('qrpay_ai_jobs').select('*').eq('id',b.job_id).single();if(error)throw error;const p=canon(b.payload),identity=await unifiedIdentity(job.matched_conversation_id);p.whatsapp_identity={bsuid:identity.matched_bsuid||job.matched_bsuid||null,username:identity.matched_username||job.matched_username||null,phone:identity.matched_phone||digits(job.matched_phone)||null,customer_master_id:identity.matched_customer_master_id||job.matched_customer_master_id||null,whatsapp_link:identity.whatsapp_link||null};if(!p.customer.phone&&p.whatsapp_identity.phone)p.customer.phone=p.whatsapp_identity.phone;if(!canDraft(p)){const reviewId=await ensureReview(job,p,identity);await db.from('qrpay_ai_jobs').update({status:'needs_review',matched_phone:identity.matched_phone||null,matched_bsuid:identity.matched_bsuid||job.matched_bsuid||null,matched_username:identity.matched_username||job.matched_username||null,matched_customer_master_id:identity.matched_customer_master_id||job.matched_customer_master_id||null,extraction:p,evidence:{...(p.evidence||{}),whatsapp_identity:identity,admin_review_id:reviewId},locked_at:null,updated_at:new Date().toISOString(),last_error:'Real customer phone required before order creation'}).eq('id',job.id);return out({ok:true,result:{success:true,draft_not_created:true,needs_review:true,admin_review_id:reviewId,reason:'real_phone_required',whatsapp_identity:p.whatsapp_identity}})}return out({ok:true,result:await create(job,p,token)})}
return out({error:'Unsupported action'},400)}catch(e){console.error(e);return out({ok:false,error:e instanceof Error?e.message:String(e)},500)}});