// @ts-nocheck
import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const U=Deno.env.get('SUPABASE_URL')||'',K=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';
const db=createClient(U,K,{auth:{persistSession:false}});
const H={'content-type':'application/json','access-control-allow-origin':'*','access-control-allow-methods':'POST,OPTIONS','access-control-allow-headers':'content-type,x-qrpay-ai-token','cache-control':'no-store'};
const out=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H});
const text=(v:any)=>v==null?'':String(v).trim();
const digits=(v:any)=>{let d=text(v).replace(/\D/g,'');if(!d)return'';if(d.startsWith('0'))d='6'+d;else if(d.startsWith('1'))d='60'+d;return /^601\d{8,9}$/.test(d)?d:''};
async function workerToken(){const q=await db.from('private_runtime_settings').select('setting_value').eq('setting_key','qrpay_ai_worker_token').maybeSingle();return text(q.data?.setting_value)}
async function auth(req:Request){const e=await workerToken();return!!e&&req.headers.get('x-qrpay-ai-token')===e}
async function waSetting(key:string){const q=await db.from('whatsapp_settings').select('secret_value,text_value,value').eq('key',key).maybeSingle();return text(q.data?.secret_value)||text(q.data?.text_value)||text(q.data?.value?.url)}
async function identity(conversationId:string){if(!conversationId)return{};const url=await waSetting('unified_inbox_24h_url');if(!url)return{};try{const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({conversation_id:conversationId})}),j=await r.json().catch(()=>({}));if(!r.ok||j.ok===false)return{};return{phone:digits(j.phone)||null,bsuid:text(j.bsuid)||null,username:text(j.username)||null,customer_master_id:text(j.customer_master_id)||null,whatsapp_link:text(j.whatsapp_link)||null}}catch{return{}}}
function canon(raw:any){const p=structuredClone(raw||{});p.customer=p.customer||{};p.customer.phone=digits(p.customer.phone)||'';p.delivery=text(p.delivery||'unknown').toLowerCase();p.delivery_fee=Math.max(0,Number(p.delivery_fee||0));p.items=Array.isArray(p.items)?p.items.map((x:any,i:number)=>{let k=text(x?.k||x?.product_type||x?.title).toLowerCase();if(/acrylic|akrilik/.test(k))k='acrylic';else if(/edible/.test(k))k='edible';else if(/wafer/.test(k))k='wafer';else if(/burn/.test(k))k='burnaway';else if(/mirror/.test(k))k='mirror';else k='printed';const w=text(x?.wording||x?.custom_text);return{...x,k,product_type:k,title:text(x?.title)||({printed:'Cake Topper',edible:'Edible Image',acrylic:'Acrylic Cake Topper',wafer:'Wafer Paper',burnaway:'Burn Away Combo',mirror:'Mirror Gold Topper'} as any)[k],qty:Math.max(1,Number(x?.qty||1)),price:Math.max(0,Number(x?.price||0)),size:text(x?.size),style:text(x?.style),wording:w,custom_text:w,review:x?.review||'Need Review',review_required:true,customization:{...(x?.customization||{}),ai_pending_confirmation:true,set_hint:x?.customization?.set_hint||i+1}}}):[];return p}
async function notify(draftId:string,token:string){try{const r=await fetch(`${U}/functions/v1/admin-review-link-dispatch`,{method:'POST',headers:{'content-type':'application/json','x-admin-order-token':token},body:JSON.stringify({action:'send_draft_link',draft_id:draftId})}),j=await r.json().catch(()=>({}));return r.ok&&j.ok!==false?{sent:true,...(j.result||{})}:{sent:false,error:j.error||`HTTP ${r.status}`}}catch(e){return{sent:false,error:String(e)}}}
async function createGeneric(b:any,token:string){const p=canon(b.payload||{}),conversationId=text(b.conversation_id||p.conversation_id||p?.evidence?.conversation_id),id=await identity(conversationId);if(!p.customer.phone)p.customer.phone=id.phone||digits(b.phone)||'';if(!p.customer.name)p.customer.name=text(b.customer_name)||'WhatsApp Customer';p.whatsapp_identity=id;p.evidence={...(p.evidence||{}),conversation_id:conversationId,whatsapp_identity:id,bridge_version:'unified-draft-bridge-v1'};const q=await db.rpc('icetak_create_generic_order_draft',{p_source_type:text(b.source_type)||'chat_trigger',p_conversation_id:conversationId||null,p_customer_phone:p.customer.phone||null,p_customer_name:p.customer.name||null,p_payload:p,p_request_key:text(b.request_key)||null,p_cutoff_at:b.cutoff_at||new Date().toISOString(),p_trigger_message_id:b.trigger_message_id||null,p_payment_mode:text(b.payment_mode)||'prepaid',p_actor:text(b.actor)||'draft-trigger'});if(q.error)throw q.error;const draftId=q.data?.id||q.data?.draft_id;return{...q.data,notification:draftId?await notify(draftId,token):{sent:false,reason:'no_draft_id'}}}
async function createQr(job:any,payload:any,token:string){const p=canon(payload),id=await identity(text(job.matched_conversation_id||p.conversation_id));if(!p.customer.phone)p.customer.phone=id.phone||digits(job.matched_phone)||'';p.whatsapp_identity=id;p.evidence={...(p.evidence||{}),whatsapp_identity:id,bridge_version:'qrpay-draft-bridge-v1'};const q=await db.rpc('icetak_create_or_update_qrpay_draft',{p_job_id:job.id,p_payload:p,p_internal_token:token});if(q.error)throw q.error;return{...q.data,notification:q.data?.draft_id?await notify(q.data.draft_id,token):{sent:false,reason:'no_draft_id'}}}
const allowed=new Set(['status','matched_conversation_id','matched_phone','matched_bsuid','matched_username','matched_customer_master_id','matched_customer_name','match_score','match_reason','extraction','evidence','locked_at','completed_at','updated_at','next_attempt_at','last_error']);
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:H});if(req.method!=='POST')return out({ok:false,error:'POST required'},405);if(!await auth(req))return out({ok:false,error:'Unauthorized'},401);const token=req.headers.get('x-qrpay-ai-token')||'',b=await req.json().catch(()=>({}));try{
 if(b.action==='claim'){const q=await db.rpc('claim_qrpay_ai_jobs',{p_limit:Math.max(1,Math.min(10,Number(b.batch_size||3)))});if(q.error)throw q.error;return out({ok:true,jobs:q.data||[]})}
 if(b.action==='learning_context'){const q=await db.rpc('icetak_qrpay_active_learning_context');if(q.error)throw q.error;return out({ok:true,rules:q.data||[]})}
 if(b.action==='order_session_context'){const q=await db.rpc('icetak_order_session_boundary',{p_conversation_id:b.conversation_id||null,p_customer_phone:digits(b.phone)||null});if(q.error)throw q.error;return out({ok:true,opened_at:q.data})}
 if(b.action==='update_job'){const patch:any={};for(const[k,v]of Object.entries(b.patch||{}))if(allowed.has(k))patch[k]=k==='extraction'?canon(v):v;if('matched_phone'in patch)patch.matched_phone=digits(patch.matched_phone)||null;patch.updated_at=new Date().toISOString();const q=await db.from('qrpay_ai_jobs').update(patch).eq('id',b.job_id).select('*').maybeSingle();if(q.error)throw q.error;return out({ok:true,job:q.data})}
 if(b.action==='create_draft'||b.action==='create_order'){const q=await db.from('qrpay_ai_jobs').select('*').eq('id',b.job_id).single();if(q.error)throw q.error;return out({ok:true,mode:'draft_only',legacy_action_redirected:b.action==='create_order',result:await createQr(q.data,b.payload,token)})}
 if(b.action==='create_generic_draft')return out({ok:true,mode:'draft_only',result:await createGeneric(b,token)});
 if(b.action==='create_pickup_order'){const p=canon(b.payload||{}),requestKey=text(b.request_key)||`pickup:${Date.now()}`,result=await createGeneric({...b,payload:p,source_type:'pickup_trigger',payment_mode:'cash_counter',request_key:requestKey,conversation_id:p.conversation_id||p?.evidence?.conversation_id,actor:'pickup-ai-trigger'},token);await db.from('pickup_ai_requests').upsert({request_key:requestKey,conversation_id:text(p.conversation_id)||null,phone:digits(p.customer?.phone)||null,status:'draft_created',request_payload:p,extraction:p,evidence:{...(p.evidence||{}),draft_id:result.id||result.draft_id||null},updated_at:new Date().toISOString()},{onConflict:'request_key'}).catch(()=>null);return out({ok:true,mode:'draft_only',legacy_action_redirected:true,result})}
 return out({ok:false,error:'Unsupported action'},400)
}catch(e){console.error('qrpay-ai-order-bridge',e);return out({ok:false,error:e instanceof Error?e.message:String(e)},500)}});