// @ts-nocheck
import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const U=Deno.env.get('SUPABASE_URL')||'',K=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'',db=createClient(U,K,{auth:{persistSession:false}});
const H={'content-type':'application/json','cache-control':'no-store'},out=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H}),t=(v:any)=>String(v??'').trim(),digits=(v:any)=>t(v).replace(/\D/g,'');
async function pset(k:string){const q=await db.from('private_runtime_settings').select('setting_value').eq('setting_key',k).maybeSingle();return t(q.data?.setting_value)}async function wset(k:string){const q=await db.from('whatsapp_settings').select('text_value,secret_value').eq('key',k).maybeSingle();return t(q.data?.secret_value||q.data?.text_value)}async function auth(req:Request){const x=req.headers.get('x-admin-order-token')||'';return!!x&&x===await pset('qrpay_ai_worker_token')}async function adminPhone(){return await wset('admin_order_notify_phone')||'60129554732'}async function publicBase(){return (await wset('customer_app_base_url')||'https://shop.decocake.my').replace(/\/$/,'')}
async function provider(to:string,text:string){const base=await wset('base_url')||'https://officialapi.wasapflow.com/bridge/v1',partner=await wset('partner_key'),waba=await wset('waba_id');if(!partner||!waba)throw Error('WasapFlow credentials incomplete');const r=await fetch(`${base}/messages/send`,{method:'POST',headers:{'content-type':'application/json','x-partner-key':partner,'x-waba-id':waba},body:JSON.stringify({to:digits(to),text,preview_url:false})}),j=await r.json().catch(()=>({}));if(!r.ok||j.success===false)throw Error(j?.error?.message||j?.message||`HTTP ${r.status}`);return j}
function method(v:any){const s=t(v).toLowerCase();return s==='pickup'?'Pickup':s==='spx'?'SPX':s==='jnt'?'J&T':s==='ninja'?'Ninja Van':s||'Not set'}function items(xs:any[]){return xs.map((x:any,i:number)=>`${i+1}. ${x.title||x.product_type||x.k||'Item'} x${Number(x.qty||1)} | RM${Number(x.price||0).toFixed(2)}${x.size?` | ${x.size}`:''}${x.wording?`\n   ${String(x.wording).replace(/\n/g,' / ')}`:''}`).join('\n')}function totals(p:any){const xs=Array.isArray(p?.items)?p.items:[],sub=xs.reduce((s:number,x:any)=>s+Number(x.price||0)*Math.max(1,Number(x.qty||1)),0),ship=Number(p?.delivery_fee||0);return{sub,ship,total:sub+ship}}
function customerContactLines(d:any,p:any){const identity=p?.whatsapp_identity||p?.evidence?.whatsapp_identity||{},phone=digits(d?.customer_phone||p?.customer?.phone||identity.phone),username=t(identity.username||p?.customer?.username).replace(/^@+/,''),bsuid=t(identity.bsuid||identity.user_id||p?.evidence?.whatsapp_identity?.bsuid),lines:string[]=[];if(phone)lines.push(`Phone: ${phone}`,`WhatsApp: https://wa.me/${phone}`);else if(username)lines.push(`WhatsApp: https://wa.me/${encodeURIComponent(username)}`);if(username)lines.push(`Username: @${username}`);if(bsuid)lines.push(`User ID: ${bsuid}`);return lines}
async function sendDraft(id:string){const q=await db.from('qrpay_order_drafts').select('*').eq('id',id).maybeSingle();if(q.error)throw q.error;const d=q.data;if(!d)throw Error('draft_not_found');if(!/^qrd_[a-f0-9]{32}$/i.test(t(d.review_token)))throw Error('draft_review_token_invalid');const link=`${await publicBase()}/qrpay-draft.html?token=${encodeURIComponent(d.review_token)}`,p=(d.status==='confirmed'?(d.confirmed_draft||d.working_draft):d.working_draft)||{},tt=totals(p),line=items(Array.isArray(p.items)?p.items:[]),source=t(d.source_type||'qrpay_payment'),paid=source==='qrpay_payment',cash=['cash_counter','cash_at_counter'].includes(t(d.payment_mode)),title=d.status==='confirmed'?'✅ ORDER CONFIRMED — ADMIN RECORD':source==='pickup_trigger'?'🟡 PICKUP AI DRAFT — ADMIN CHECK':source==='chat_trigger'?'🟡 CHAT ORDER DRAFT — ADMIN CHECK':'🟡 QRPay AI DRAFT — ADMIN CHECK';let payLine=paid?`Payment Received: RM${Number(d.payment_amount||0).toFixed(2)}`:cash?'Payment: Cash at Counter':'Payment: Awaiting customer confirmation / web payment';const msg=[title,`Ref: ${d.transaction_id||d.request_key||String(d.id).slice(0,8)}`,`Customer: ${d.customer_name||'-'}`,...customerContactLines(d,p),`Source: ${source}`,`Date Need: ${p.date_need||'-'}`,'','ORDER',line||'Item belum cukup','',`Shipping: ${method(p.delivery)} | RM${tt.ship.toFixed(2)}`,`Item Subtotal: RM${tt.sub.toFixed(2)}`,`TOTAL: RM${tt.total.toFixed(2)}`,payLine,...(paid?[`Difference: ${(tt.total-Number(d.payment_amount||0))>=0?'+':''}RM${(tt.total-Number(d.payment_amount||0)).toFixed(2)}`]:[]),'',d.status==='confirmed'?'Buka record (read-only):':'Buka draft untuk edit / add / remove item / shipping / Date Need:',link,'',d.status==='confirmed'?'🔒 Sudah Confirm.':'⚠️ Draft sahaja. Belum create Order / ClickUp.'].join('\n');const sent=await provider(await adminPhone(),msg),now=new Date().toISOString();await db.from('qrpay_order_drafts').update({admin_link_sent_at:now,updated_at:now}).eq('id',d.id);return{sent:true,draft_id:d.id,status:d.status,public_link:link,message_id:sent?.message_id||sent?.id||null}}
Deno.serve(async req=>{if(req.method!=='POST')return out({ok:false,error:'POST required'},405);if(!await auth(req))return out({ok:false,error:'Unauthorized'},401);try{const b=await req.json().catch(()=>({}));if(b.action==='send_draft_link'&&b.draft_id)return out({ok:true,result:await sendDraft(String(b.draft_id))});return out({ok:true,count:0,results:[]})}catch(e){return out({ok:false,error:e instanceof Error?e.message:String(e)},500)}});
