// @ts-nocheck
import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const U=Deno.env.get('SUPABASE_URL')||'',K=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'',db=createClient(U,K,{auth:{persistSession:false}});
const H={'content-type':'application/json; charset=utf-8','access-control-allow-origin':'*','access-control-allow-methods':'POST,OPTIONS','access-control-allow-headers':'content-type','cache-control':'no-store'};
const out=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H}),t=(v:any)=>String(v??'').trim();
async function load(token:string){const q=await db.from('qrpay_order_drafts').select('*').eq('review_token',token).maybeSingle();if(q.error)throw q.error;if(!q.data)throw Error('draft_not_found');return q.data}
async function customerWebEnabled(){const q=await db.from('private_runtime_settings').select('setting_value').eq('setting_key','draft_customer_web_enabled').maybeSingle();return ['1','true','yes','on'].includes(t(q.data?.setting_value).toLowerCase())}
function ignored(path:string){return/^(total|draft_total|payment_amount|transaction_id|payment_received_at|evidence|match_score|match_reason|admin_remark|whatsapp_identity|ai_confidence|ai_missing)(\.|$)/.test(path)||/(^|\.)customization\.(ai_generated|ai_pending_confirmation|match_score|match_reason|qrpay_|reference_|conversation_id|whatsapp_)/.test(path)}
function diff(ai:any,h:any,path=''){const rows:any[]=[];if(ignored(path))return rows;const aa=Array.isArray(ai),ha=Array.isArray(h);if(aa||ha){if(!(aa&&ha)){rows.push({field_path:path||'root',correction_type:'changed',ai_value:ai??null,human_value:h??null});return rows}if(ai.length!==h.length)rows.push({field_path:path?`${path}.length`:'length',correction_type:h.length>ai.length?'item_added':'item_removed',ai_value:ai.length,human_value:h.length});for(let i=0;i<Math.max(ai.length,h.length);i++)rows.push(...diff(ai[i],h[i],path?`${path}.${i}`:String(i)));return rows}const ao=ai&&typeof ai==='object',ho=h&&typeof h==='object';if(ao||ho){if(!(ao&&ho)){rows.push({field_path:path||'root',correction_type:'changed',ai_value:ai??null,human_value:h??null});return rows}for(const k of new Set([...Object.keys(ai),...Object.keys(h)]))rows.push(...diff(ai[k],h[k],path?`${path}.${k}`:k));return rows}if(JSON.stringify(ai)!==JSON.stringify(h))rows.push({field_path:path||'root',correction_type:ai===undefined?'added':h===undefined?'removed':'changed',ai_value:ai??null,human_value:h??null});return rows}
function strategy(path:string,type:string){if(path==='items.length'||type==='item_added'||type==='item_removed'||/^items\.\d+\.(k|product_type|title)$/.test(path))return['preserve_distinct_products','product','Keep distinct products','Keep separate product blocks distinct.'];if(/^items\.\d+\.price$/.test(path))return['price_from_latest_explicit_seller_quote','price','Use seller price','Prefer latest explicit seller unit price.'];if(/^items\.\d+\.qty$/.test(path))return['qty_from_nearest_explicit_item_count','quantity','Use explicit quantity','Bind qty to nearest product-specific count.'];if(/^items\.\d+\.(wording|custom_text)$/.test(path))return['wording_from_explicit_label','wording','Use explicit wording','Prefer wording/name labels and nearest customer text.'];if(/^items\.\d+\.(size|style)$/.test(path))return['variation_from_nearest_item_context','variation','Bind variation','Bind size/style to nearest item.'];if(/^delivery($|\.)|^delivery_fee$/.test(path))return['shipping_from_latest_explicit_quote','shipping','Use shipping quote','Prefer latest explicit shipping decision/fee.'];if(path==='date_need')return['date_from_latest_customer_need','date','Use latest date','Prefer latest required date evidence.'];if(/^customer\./.test(path))return['customer_identity_from_strong_payment_context','customer','Customer identity','Use current session identity evidence.'];return['human_override_requires_evidence','other','Human correction','Retain human correction as evidence.']}
function learn(ai:any,h:any,evidence:any){const corrections=diff(ai||{},h||{}).filter(x=>x.field_path&&x.field_path!=='root').map(x=>{const[s]=strategy(x.field_path,x.correction_type);return{...x,strategy_key:s,signature:`draft-v1:${s}`,evidence:{conversation_id:evidence?.conversation_id||null,reference_message_ids:evidence?.messages?.map((m:any)=>m.id).filter(Boolean).slice(-80)||[]}}}),seen=new Set(),candidates=[];for(const c of corrections){if(seen.has(c.signature))continue;seen.add(c.signature);const[s,g,title,lesson]=strategy(c.field_path,c.correction_type);candidates.push({signature:c.signature,strategy_key:s,field_group:g,title,lesson,field_path:c.field_path,ai_value:c.ai_value,human_value:c.human_value})}return{corrections,candidates}}
async function wset(k:string){const q=await db.from('whatsapp_settings').select('text_value,secret_value').eq('key',k).maybeSingle();return t(q.data?.secret_value||q.data?.text_value)}
async function send(to:string,text:string){const base=await wset('base_url')||'https://officialapi.wasapflow.com/bridge/v1',partner=await wset('partner_key'),waba=await wset('waba_id');if(!partner||!waba)throw Error('WasapFlow credentials incomplete');const r=await fetch(`${base}/messages/send`,{method:'POST',headers:{'content-type':'application/json','x-partner-key':partner,'x-waba-id':waba},body:JSON.stringify({to:String(to).replace(/\D/g,''),text,preview_url:false})}),j=await r.json().catch(()=>({}));if(!r.ok||j.success===false)throw Error(j?.error?.message||j?.message||`HTTP ${r.status}`);return j}
async function sendCustomer(d:any){const p=d.working_draft||{},items=Array.isArray(p.items)?p.items:[],link=`https://icetak.bolt.host/order-review.html?token=${encodeURIComponent(d.customer_review_token)}`,lines=items.map((x:any,i:number)=>`${i+1}. ${x.title||x.product_type||'Item'} x${Number(x.qty||1)} | RM${Number(x.price||0).toFixed(2)}${x.size?` | ${x.size}`:''}${x.wording?`\n   ${String(x.wording).replace(/\n/g,' / ')}`:''}`).join('\n'),msg=['🧾 DecoCake.my — SEMAK ORDER',`Hi ${d.customer_name||'Customer'},`,'','Sila semak order sebelum confirm'+(d.payment_required?' dan buat payment.':'.'),' ',lines,'',`Shipping: ${p.delivery||'-'} | RM${Number(p.delivery_fee||0).toFixed(2)}`,`TOTAL: RM${Number(d.draft_total||0).toFixed(2)}`,`Date Need: ${p.date_need||'-'}`,'','Buka link:',link,'','Jika detail salah, tekan Request Correction dalam page.'].join('\n');const sent=await send(d.customer_phone,msg);await db.from('qrpay_order_drafts').update({customer_link_sent_at:new Date().toISOString(),customer_status:'ready',updated_at:new Date().toISOString()}).eq('id',d.id);await db.from('qrpay_order_draft_events').insert({draft_id:d.id,event_type:'customer_link_sent',actor:'admin-link',metadata:{message_id:sent?.message_id||sent?.id||null}});return{sent:true,link,message_id:sent?.message_id||sent?.id||null}}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:H});if(req.method!=='POST')return out({ok:false,error:'POST required'},405);try{const b=await req.json().catch(()=>({})),token=t(b.token);if(!/^qrd_[a-f0-9]{32}$/i.test(token))return out({ok:false,error:'Invalid draft token'},401);let d=await load(token);if(b.action==='save'){const q=await db.rpc('icetak_save_qrpay_order_draft',{p_review_token:token,p_payload:b.payload||{},p_actor:'admin-link'});if(q.error)throw q.error;return out({ok:true,draft:q.data})}
 if(b.action==='approve_customer'){if(!await customerWebEnabled())return out({ok:false,error:'Customer review web belum published. Draft disimpan tetapi customer link belum dibenarkan.'},503);const lc=learn(d.ai_draft,b.payload||{},d.evidence||{}),q=await db.rpc('icetak_admin_approve_draft_for_customer',{p_review_token:token,p_payload:b.payload||{},p_actor:'admin-link'});if(q.error)throw q.error;d=q.data;const l=await db.rpc('icetak_record_generic_draft_learning',{p_draft_id:d.id,p_corrections:lc.corrections,p_learning_candidates:lc.candidates,p_actor:'admin-link'});if(l.error)throw l.error;const sent=await sendCustomer(d);return out({ok:true,draft:d,customer:sent,corrections:lc.corrections,candidates:lc.candidates})}
 if(b.action==='resend_customer'){if(!await customerWebEnabled())return out({ok:false,error:'Customer review web belum published. Resend customer link disabled.'},503);if(!d.admin_approved_at)throw Error('Approve draft first');return out({ok:true,customer:await sendCustomer(d)})}
 if(b.action==='confirm'){if(d.status==='confirmed')return out({ok:true,duplicate:true,order_id:d.order_no});if(d.source_type==='qrpay_payment'){const lc=learn(d.ai_draft,b.payload||{},d.evidence||{}),q=await db.rpc('icetak_confirm_qrpay_order_draft',{p_review_token:token,p_payload:b.payload||{},p_corrections:lc.corrections,p_learning_candidates:lc.candidates,p_actor:'admin-link'});if(q.error)throw q.error;return out({ok:true,result:q.data})}if(d.payment_mode==='cash_counter'||d.payment_mode==='cash_at_counter'){const lc=learn(d.ai_draft,b.payload||{},d.evidence||{}),a=await db.rpc('icetak_admin_approve_draft_for_customer',{p_review_token:token,p_payload:b.payload||{},p_actor:'admin-link'});if(a.error)throw a.error;d=a.data;const l=await db.rpc('icetak_record_generic_draft_learning',{p_draft_id:d.id,p_corrections:lc.corrections,p_learning_candidates:lc.candidates,p_actor:'admin-link'});if(l.error)throw l.error;const c=await db.rpc('icetak_customer_confirm_draft',{p_customer_token:d.customer_review_token,p_customer:{},p_actor:'admin-proxy'});if(c.error)throw c.error;return out({ok:true,result:c.data,corrections:lc.corrections})}return out({ok:false,error:'Prepaid chat draft must use Approve & Send Customer'},409)}
 if(b.action==='reject'){const q=await db.rpc('icetak_reject_qrpay_order_draft',{p_review_token:token,p_actor:'admin-link',p_reason:t(b.reason)});if(q.error)throw q.error;return out({ok:true,result:q.data})}
 if(b.action==='rematch'){const q=await db.rpc('icetak_mark_qrpay_draft_needs_rematch',{p_review_token:token,p_actor:'admin-link'});if(q.error)throw q.error;return out({ok:true,result:q.data})}
 if(b.action==='rule'){const q=await db.rpc('icetak_set_qrpay_learning_rule_status',{p_rule_id:b.rule_id,p_status:b.status,p_actor:'admin-link'});if(q.error)throw q.error;return out({ok:true,rule:q.data})}
 return out({ok:false,error:'Unsupported action'},400)}catch(e){console.error('qrpay-draft-review',e);return out({ok:false,error:e instanceof Error?e.message:String(e)},500)}});
