// @ts-nocheck
import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const U=Deno.env.get('SUPABASE_URL')||'',K=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'',db=createClient(U,K,{auth:{persistSession:false}});
const H={'content-type':'application/json; charset=utf-8','access-control-allow-origin':'*','access-control-allow-methods':'POST,OPTIONS','access-control-allow-headers':'content-type','cache-control':'no-store'};
const out=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H}),t=(v:any)=>String(v??'').trim();
const PRODUCTS:any={
 edible:{label:'Edible Image',shortLabel:'Edible',process:['Pre-order','Urgent'],sizes:['3 inch','3.5 inch','4 inch','4.5 inch','5 inch','5.5 inch','6 inch','6.5 inch','7 inch','7.5 inch','A6','A5','A4','Cupcake'],styles:['Round / Bulat','Square / Petak','Love Shape / Hati','Full Landscape','Full Portrait','Custom'],defaultSize:'3 inch',defaultStyle:'Round / Bulat',defaultReview:'No Review'},
 burnaway:{label:'Burn Away Combo',shortLabel:'Burn Away',process:['Pre-order','Urgent'],sizes:['3 inch','4 inch','5 inch','5.5 inch','6 inch','6.5 inch','7 inch','7.5 inch','Custom A5','Custom A4'],styles:['Round / Bulat','Square / Petak','Love Shape / Hati'],defaultSize:'5 inch',defaultStyle:'Round / Bulat',defaultReview:'No Review'},
 wafer:{label:'Wafer Paper Only',shortLabel:'Wafer',process:['Pre-order','Urgent'],sizes:['3 inch','3.5 inch','4 inch','4.5 inch','5 inch','5.5 inch','6 inch','6.5 inch','7 inch','7.5 inch','8 inch'],styles:['Round / Bulat','Square / Petak','Love Shape / Hati'],defaultSize:'3 inch',defaultStyle:'Round / Bulat',defaultReview:'No Review'},
 printed:{label:'Cake Topper',shortLabel:'Topper',process:['Pre-order'],sizes:['1 pc'],styles:['Custom Name','Happy Birthday'],defaultSize:'1 pc',defaultStyle:'Happy Birthday',defaultReview:'Need Review'},
 mirror:{label:'Mirror Gold Artpaper',shortLabel:'Mirror Gold',process:['Pre-order','Urgent'],sizes:['A7 Mini','A6 Standard','A5 Large'],styles:['Gold'],defaultSize:'A7 Mini',defaultStyle:'Gold',defaultReview:'No Review'},
 acrylic:{label:'Acrylic Cake Topper',shortLabel:'Acrylic',process:['Pre-order','Urgent'],sizes:['A7 Mini','A6 Standard','A5 Large'],styles:['Gold','Silver','Black','Rose Gold','Clear / Transparent','Dark Blue','Light Blue','Red','Yellow','Pink','Gold Glitter','Silver Glitter','Lilac / Light Purple','Mirror Blue','Bronze','Green','Orange','White'],defaultSize:'A7 Mini',defaultStyle:'Gold',defaultReview:'No Review'}
};
const DELIVERY:any={pickup:0,spx:4.5,jnt:5.9,ninja:6.9};
function kind(v:any){let k=t(v).toLowerCase();if(['topper','cake_topper'].includes(k))k='printed';return PRODUCTS[k]?k:'edible'}
function styles(k:string,size:string){if(k==='edible'&&['4 inch','4.5 inch','5 inch','5.5 inch'].includes(size))return['Round / Bulat','Square / Petak','Love Shape / Hati','Custom'];return PRODUCTS[k].styles}
function sizeNorm(k:string,v:any){const cfg=PRODUCTS[k],raw=t(v);if(cfg.sizes.includes(raw))return raw;if(['mirror','acrylic'].includes(k)){const u=raw.toUpperCase();if(u==='A7')return'A7 Mini';if(u==='A6')return'A6 Standard';if(u==='A5')return'A5 Large'}if(k==='printed')return'1 pc';const m=raw.match(/(\d+(?:\.\d+)?)\s*(?:inch|in|inci|\")?/i);if(m){const x=`${Number(m[1])} inch`;if(cfg.sizes.includes(x))return x}const up=raw.toUpperCase();const exact=cfg.sizes.find((x:string)=>x.toUpperCase()===up);return exact||cfg.defaultSize}
function styleNorm(k:string,size:string,v:any){const list=styles(k,size),raw=t(v);if(list.includes(raw))return raw;const l=raw.toLowerCase();if(/round|bulat/.test(l)&&list.includes('Round / Bulat'))return'Round / Bulat';if(/square|petak/.test(l)&&list.includes('Square / Petak'))return'Square / Petak';if(/love|hati|heart/.test(l)&&list.includes('Love Shape / Hati'))return'Love Shape / Hati';if(/landscape/.test(l)&&list.includes('Full Landscape'))return'Full Landscape';if(/portrait/.test(l)&&list.includes('Full Portrait'))return'Full Portrait';const exact=list.find((x:string)=>x.toLowerCase()===l);return exact||list[0]||PRODUCTS[k].defaultStyle}
function price(k:string,proc:string,size:string,style:string,review:string){if(k==='printed')return 10;if(k==='mirror')return proc==='Urgent'?18:15;if(k==='acrylic'){if(proc==='Urgent')return size==='A7 Mini'?15:size==='A6 Standard'?25:40;return size==='A7 Mini'?12:size==='A6 Standard'?20:35}if(k==='burnaway'){if(size.includes('A4'))return 36;if(size.includes('A5'))return 18;const n=parseFloat(size)||0;return n>=6?30:n>=5?18:12}if(k==='wafer'){const base=(parseFloat(size)||0)<=6?6:12;return base+(proc==='Urgent'&&review==='Need Review'?2:0)}let base;if(size==='A4'||size==='Cupcake')base=24;else if(size==='A5')base=12;else if(size==='A6')base=6;else{const n=parseFloat(size)||0;base=style==='Square / Petak'&&size==='4 inch'?12:n>=6?24:n>=4.5?12:6}if(proc==='Urgent'&&review==='Need Review')return base===6?7:base===12?14:base===24?28:base;return base}
function normItem(x:any){const k=kind(x?.k||x?.kind||x?.product_type||x?.productType),cfg=PRODUCTS[k];let proc=t(x?.process);if(!cfg.process.includes(proc))proc=/urgent/i.test(proc)?'Urgent':cfg.process[0];let review=t(x?.review);if(!['No Review','Need Review'].includes(review))review=x?.review_required||x?.reviewRequired?'Need Review':cfg.defaultReview;const sz=sizeNorm(k,x?.size),sty=styleNorm(k,sz,x?.style);const wording=t(x?.customText||x?.custom_text||x?.wording),ref=t(x?.referenceUrl||x?.reference_url||x?.customization?.reference_url||x?.product_snapshot?.image_url),custom={...(x?.customization||{}),admin_process:proc},snap={...(x?.product_snapshot||{}),quick_arrange_kind:k};if(ref){custom.reference_url=ref;snap.image_url=ref}const isCustom=Boolean(x?.is_custom_item||custom.manual_custom_item);return{...x,k,kind:k,product_type:k,title:isCustom&&t(x?.title)?t(x.title):cfg.label,is_custom_item:isCustom,process:proc,review,review_required:review==='Need Review',size:sz,style:sty,qty:Math.max(1,Number(x?.qty||1)),price:price(k,proc,sz,sty,review),wording,customText:wording,custom_text:wording,referenceUrl:ref,customization:custom,product_snapshot:snap}}
function normPayload(p:any){const delivery=t(p?.delivery||'unknown').toLowerCase(),items=(Array.isArray(p?.items)?p.items:[]).map(normItem);return{...(p||{}),items,delivery,delivery_fee:Object.prototype.hasOwnProperty.call(DELIVERY,delivery)?DELIVERY[delivery]:Number(p?.delivery_fee||0)}}
async function load(token:string){const q=await db.from('qrpay_order_drafts').select('*').eq('review_token',token).maybeSingle();if(q.error)throw q.error;if(!q.data)throw Error('draft_not_found');return q.data}
async function customerWebEnabled(){const q=await db.from('private_runtime_settings').select('setting_value').eq('setting_key','draft_customer_web_enabled').maybeSingle();return ['1','true','yes','on'].includes(t(q.data?.setting_value).toLowerCase())}
function ignored(path:string){return/^(total|draft_total|payment_amount|transaction_id|payment_received_at|evidence|match_score|match_reason|admin_remark|whatsapp_identity|ai_confidence|ai_missing)(\.|$)/.test(path)||/(^|\.)customization\.(ai_generated|ai_pending_confirmation|match_score|match_reason|qrpay_|reference_|conversation_id|whatsapp_)/.test(path)}
function diff(ai:any,h:any,path=''){const rows:any[]=[];if(ignored(path))return rows;const aa=Array.isArray(ai),ha=Array.isArray(h);if(aa||ha){if(!(aa&&ha)){rows.push({field_path:path||'root',correction_type:'changed',ai_value:ai??null,human_value:h??null});return rows}if(ai.length!==h.length)rows.push({field_path:path?`${path}.length`:'length',correction_type:h.length>ai.length?'item_added':'item_removed',ai_value:ai.length,human_value:h.length});for(let i=0;i<Math.max(ai.length,h.length);i++)rows.push(...diff(ai[i],h[i],path?`${path}.${i}`:String(i)));return rows}const ao=ai&&typeof ai==='object',ho=h&&typeof h==='object';if(ao||ho){if(!(ao&&ho)){rows.push({field_path:path||'root',correction_type:'changed',ai_value:ai??null,human_value:h??null});return rows}for(const k of new Set([...Object.keys(ai),...Object.keys(h)]))rows.push(...diff(ai[k],h[k],path?`${path}.${k}`:k));return rows}if(JSON.stringify(ai)!==JSON.stringify(h))rows.push({field_path:path||'root',correction_type:ai===undefined?'added':h===undefined?'removed':'changed',ai_value:ai??null,human_value:h??null});return rows}
function strategy(path:string,type:string){if(path==='items.length'||type==='item_added'||type==='item_removed'||/^items\.\d+\.(k|kind|product_type|title)$/.test(path))return['preserve_distinct_products','product','Keep distinct products','Keep separate product blocks distinct.'];if(/^items\.\d+\.price$/.test(path))return['price_from_quick_order_variation','price','Use Quick Order variation price','Price is determined by the same Quick Order V1 variation matrix.'];if(/^items\.\d+\.qty$/.test(path))return['qty_from_nearest_explicit_item_count','quantity','Use explicit quantity','Bind qty to nearest product-specific count.'];if(/^items\.\d+\.(wording|customText|custom_text)$/.test(path))return['wording_from_explicit_label','wording','Use explicit wording','Prefer wording/name labels and nearest customer text.'];if(/^items\.\d+\.(size|style|process|review)$/.test(path))return['variation_from_nearest_item_context','variation','Bind Quick Order variation','Bind process/review/size/style to nearest item and Quick Order options.'];if(/^items\.\d+\.(referenceUrl|reference_url)$/.test(path))return['reference_from_latest_media','reference','Use latest reference','Prefer the latest item-specific reference image or URL.'];if(/^delivery($|\.)|^delivery_fee$/.test(path))return['shipping_from_quick_order_delivery','shipping','Use Quick Order shipping','Use the same Quick Order courier and fee matrix.'];if(path==='date_need')return['date_from_latest_customer_need','date','Use latest date','Prefer latest required date evidence.'];if(/^customer\./.test(path))return['customer_identity_from_strong_payment_context','customer','Customer identity','Use current session identity evidence.'];return['human_override_requires_evidence','other','Human correction','Retain human correction as evidence.']}
function learn(ai:any,h:any,evidence:any){const corrections=diff(ai||{},h||{}).filter(x=>x.field_path&&x.field_path!=='root').map(x=>{const[s]=strategy(x.field_path,x.correction_type);return{...x,strategy_key:s,signature:`draft-v1:${s}`,evidence:{conversation_id:evidence?.conversation_id||null,reference_message_ids:evidence?.messages?.map((m:any)=>m.id).filter(Boolean).slice(-80)||[]}}}),seen=new Set(),candidates=[];for(const c of corrections){if(seen.has(c.signature))continue;seen.add(c.signature);const[s,g,title,lesson]=strategy(c.field_path,c.correction_type);candidates.push({signature:c.signature,strategy_key:s,field_group:g,title,lesson,field_path:c.field_path,ai_value:c.ai_value,human_value:c.human_value})}return{corrections,candidates}}
function learningForDraft(d:any,payload:any){return d?.source_type==='admin_manual'||d?.evidence?.manual_order?{corrections:[],candidates:[]}:learn(d?.ai_draft,payload,d?.evidence||{})}
async function wset(k:string){const q=await db.from('whatsapp_settings').select('text_value,secret_value').eq('key',k).maybeSingle();return t(q.data?.secret_value||q.data?.text_value)}
async function publicBase(){return (await wset('customer_app_base_url')||'https://shop.decocake.my').replace(/\/$/,'')}
async function send(identity:any,text:string){
  const base=await wset('base_url')||'https://officialapi.wasapflow.com/bridge/v1',partner=await wset('partner_key'),waba=await wset('waba_id');
  if(!partner||!waba)throw Error('WasapFlow credentials incomplete');
  const phone=String(identity?.phone||'').replace(/\D/g,''),bsuid=t(identity?.bsuid||identity?.user_id);
  if(!phone&&!bsuid)throw Error('Customer has no WhatsApp phone or user ID');
  const recipient=phone?{to:phone}:{user_id:bsuid};
  const r=await fetch(`${base}/messages/send`,{method:'POST',headers:{'content-type':'application/json','x-partner-key':partner,'x-waba-id':waba},body:JSON.stringify({...recipient,text,preview_url:false})}),j=await r.json().catch(()=>({}));
  if(!r.ok||j.success===false)throw Error(j?.error?.message||j?.message||`HTTP ${r.status}`);
  return{...j,recipient_type:phone?'phone':'bsuid',recipient_bsuid:bsuid||null}
}
async function sendCustomer(d:any){const p=d.working_draft||{},items=Array.isArray(p.items)?p.items:[],link=`${await publicBase()}/order-review.html?token=${encodeURIComponent(d.customer_review_token)}`,lines=items.map((x:any,i:number)=>`${i+1}. ${x.title||x.product_type||'Item'} x${Number(x.qty||1)} | RM${Number(x.price||0).toFixed(2)}${x.process?` | ${x.process}`:''}${x.size?` | ${x.size}`:''}${x.style?` | ${x.style}`:''}${x.wording?`\n   ${String(x.wording).replace(/\n/g,' / ')}`:''}`).join('\n'),msg=['🧾 DecoCake.my — SEMAK ORDER',`Hi ${d.customer_name||'Customer'},`,'','Sila semak order sebelum confirm'+(d.payment_required?' dan buat payment.':'.'),' ',lines,'',`Shipping: ${p.delivery||'-'} | RM${Number(p.delivery_fee||0).toFixed(2)}`,`TOTAL: RM${Number(d.draft_total||0).toFixed(2)}`,`Date Need: ${p.date_need||'-'}`,'','Buka link:',link,'','Jika detail salah, tekan Request Correction dalam page.'].join('\n');const identity=p.whatsapp_identity||d.evidence?.whatsapp_identity||{},bsuid=t(identity.bsuid),target={phone:bsuid?identity.phone:d.customer_phone,bsuid};const sent=await send(target,msg);await db.from('qrpay_order_drafts').update({customer_link_sent_at:new Date().toISOString(),customer_status:'ready',updated_at:new Date().toISOString()}).eq('id',d.id);await db.from('qrpay_order_draft_events').insert({draft_id:d.id,event_type:'customer_link_sent',actor:'admin-link',metadata:{message_id:sent?.message_id||sent?.id||null,recipient_type:sent?.recipient_type||null,recipient_bsuid:sent?.recipient_bsuid||null}});return{sent:true,link,message_id:sent?.message_id||sent?.id||null}}
async function sendConfirmedPickupOrder(draft:any){
 const refreshed=await db.from('qrpay_order_drafts').select('id,order_id,order_no,customer_name,customer_phone,working_draft,evidence,customer_link_sent_at').eq('id',draft.id).maybeSingle();
 if(refreshed.error)throw refreshed.error;
 const d=refreshed.data;
 if(!d?.order_id)throw Error('Pickup order belum berjaya dicipta');
 const existing=await db.from('qrpay_order_draft_events').select('metadata').eq('draft_id',d.id).eq('event_type','pickup_order_link_sent').order('created_at',{ascending:false}).limit(1).maybeSingle();
 if(existing.error)throw existing.error;
 if(existing.data)return{sent:true,duplicate:true,message_id:existing.data.metadata?.message_id||null};
 const order=await db.from('orders').select('id,order_no,public_token,total,payment_status,payment').eq('id',d.order_id).maybeSingle();
 if(order.error)throw order.error;
 if(!order.data?.public_token)throw Error('Customer order link tidak dijumpai');
 const optIn=await db.from('orders').update({whatsapp_opt_in:true,updated_at:new Date().toISOString()}).eq('id',d.order_id);
 if(optIn.error)throw optIn.error;
 const payload=d.working_draft||{},items=Array.isArray(payload.items)?payload.items:[];
 const itemLines=items.map((item:any,index:number)=>{const qty=Math.max(1,Number(item.qty||1)),price=Number(item.seller_deal_price??item.price??0),variation=[item.size,item.style].filter(Boolean).join(', ');return`${index+1}. ${item.title||item.product_type||'Item'}${variation?` (${variation})`:''} ×${qty} | RM${(price*qty).toFixed(2)}`}).join('\n');
 const queue=await db.rpc('icetak_enqueue_whatsapp_event',{p_event_type:'pickup_order_confirmed',p_order_id:d.order_id,p_extra:{items_summary:itemLines,payment_status:'UNPAID',delivery_method:'Pickup'},p_suffix:'draft_review',p_scheduled_at:new Date().toISOString()});
 if(queue.error)throw queue.error;
 let queueId=queue.data;
 if(!queueId){const previous=await db.from('notification_queue').select('id,status,provider_message_id,last_error').eq('idempotency_key',`pickup_order_confirmed:${d.order_id}:draft_review`).maybeSingle();if(previous.error)throw previous.error;if(!previous.data)throw Error('Pickup notification rule disabled atau customer tiada WhatsApp identity');if(previous.data.status==='sent')queueId=previous.data.id;else if(previous.data.status==='failed'||previous.data.status==='cancelled')throw Error(previous.data.last_error||'Pickup WhatsApp notification gagal');else queueId=previous.data.id}
 const response=await fetch(`${U}/functions/v1/whatsapp-dispatch`,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${K}`},body:JSON.stringify({queue_id:queueId,limit:1})});
 const dispatched=await response.json().catch(()=>({}));
 if(!response.ok||dispatched.ok===false)throw Error(dispatched.error||`WhatsApp dispatch HTTP ${response.status}`);
 const row=(dispatched.results||[]).find((result:any)=>result.id===queueId),sentRow=await db.from('notification_queue').select('status,provider_message_id,last_error').eq('id',queueId).maybeSingle();
 if(sentRow.error)throw sentRow.error;
 if(sentRow.data?.status!=='sent')throw Error(row?.reason||sentRow.data?.last_error||'Pickup WhatsApp belum berjaya dihantar');
 const messageId=sentRow.data.provider_message_id||row?.message_id||null,link=`${await publicBase()}/?order=${encodeURIComponent(order.data.public_token)}`,paymentLink=`${link}&page=payment`;
 const mark=await db.from('qrpay_order_drafts').update({customer_link_sent_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',d.id);
 if(mark.error)throw mark.error;
 const event=await db.from('qrpay_order_draft_events').insert({draft_id:d.id,event_type:'pickup_order_link_sent',actor:'admin-link',metadata:{message_id:messageId,queue_id:queueId,event_type:'pickup_order_confirmed'}});
 if(event.error)throw event.error;
 return{sent:true,link,payment_link:paymentLink,message_id:messageId,queue_id:queueId}
}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:H});if(req.method!=='POST')return out({ok:false,error:'POST required'},405);try{const b=await req.json().catch(()=>({})),token=t(b.token);if(!/^qrd_[a-f0-9]{32}$/i.test(token))return out({ok:false,error:'Invalid draft token'},401);let d=await load(token);const payload=normPayload(b.payload||{});
 if(b.action==='save'){const q=await db.rpc('icetak_save_qrpay_order_draft',{p_review_token:token,p_payload:payload,p_actor:'admin-link'});if(q.error)throw q.error;return out({ok:true,draft:q.data,contract:'quick-order-v1'})}
 if(b.action==='approve_customer'){if(!await customerWebEnabled())return out({ok:false,error:'Customer review web belum published. Draft disimpan tetapi customer link belum dibenarkan.'},503);const lc=learningForDraft(d,payload),approvalPayload={...payload,notify_whatsapp:b.whatsapp_opt_in!==false},q=await db.rpc('icetak_admin_approve_draft_for_customer',{p_review_token:token,p_payload:approvalPayload,p_actor:'admin-link'});if(q.error)throw q.error;d=q.data;const l=await db.rpc('icetak_record_generic_draft_learning',{p_draft_id:d.id,p_corrections:lc.corrections,p_learning_candidates:lc.candidates,p_actor:'admin-link'});if(l.error)throw l.error;const sent=await sendCustomer(d);return out({ok:true,draft:d,customer:sent,whatsapp_opt_in:approvalPayload.notify_whatsapp,corrections:lc.corrections,candidates:lc.candidates,contract:'quick-order-v1'})}
 if(b.action==='resend_customer'){if(!await customerWebEnabled())return out({ok:false,error:'Customer review web belum published. Resend customer link disabled.'},503);if(!d.admin_approved_at)throw Error('Approve draft first');return out({ok:true,customer:await sendCustomer(d)})}
 if(b.action==='confirm'||b.action==='confirm_send_customer'){const shouldSend=b.action==='confirm_send_customer',wantsWhatsApp=shouldSend&&b.whatsapp_opt_in!==false;if(d.status==='confirmed'){if(!shouldSend)return out({ok:true,duplicate:true,order_id:d.order_no});if(!['cash_counter','cash_at_counter'].includes(d.payment_mode))return out({ok:false,error:'Customer pickup link hanya untuk Cash at Counter'},409);if(!wantsWhatsApp)return out({ok:true,duplicate:true,order_id:d.order_no,customer:{sent:false,skipped:true,whatsapp_opt_in:false}});return out({ok:true,duplicate:true,order_id:d.order_no,customer:await sendConfirmedPickupOrder(d)})}if(d.source_type==='qrpay_payment'){if(shouldSend)return out({ok:false,error:'Customer pickup link hanya untuk Cash at Counter'},409);const lc=learningForDraft(d,payload),q=await db.rpc('icetak_confirm_qrpay_order_draft',{p_review_token:token,p_payload:payload,p_corrections:lc.corrections,p_learning_candidates:lc.candidates,p_actor:'admin-link'});if(q.error)throw q.error;return out({ok:true,result:q.data,contract:'quick-order-v1'})}if(d.payment_mode==='cash_counter'||d.payment_mode==='cash_at_counter'){const lc=learningForDraft(d,payload),a=await db.rpc('icetak_admin_approve_draft_for_customer',{p_review_token:token,p_payload:payload,p_actor:'admin-link'});if(a.error)throw a.error;d=a.data;const l=await db.rpc('icetak_record_generic_draft_learning',{p_draft_id:d.id,p_corrections:lc.corrections,p_learning_candidates:lc.candidates,p_actor:'admin-link'});if(l.error)throw l.error;const c=await db.rpc('icetak_customer_confirm_draft',{p_customer_token:d.customer_review_token,p_customer:{},p_actor:'admin-proxy'});if(c.error)throw c.error;const optIn=await db.from('orders').update({whatsapp_opt_in:wantsWhatsApp,updated_at:new Date().toISOString()}).eq('id',d.order_id);if(optIn.error)throw optIn.error;const customer=wantsWhatsApp?await sendConfirmedPickupOrder(d):{sent:false,skipped:true,whatsapp_opt_in:false};return out({ok:true,result:c.data,customer,corrections:lc.corrections,contract:'quick-order-v1'})}return out({ok:false,error:'Prepaid chat draft must use Approve & Send Customer'},409)}
 if(b.action==='reject'){const q=await db.rpc('icetak_reject_qrpay_order_draft',{p_review_token:token,p_actor:'admin-link',p_reason:t(b.reason)});if(q.error)throw q.error;return out({ok:true,result:q.data})}
 if(b.action==='rematch'){const q=await db.rpc('icetak_mark_qrpay_draft_needs_rematch',{p_review_token:token,p_actor:'admin-link'});if(q.error)throw q.error;return out({ok:true,result:q.data})}
 if(b.action==='rule'){const q=await db.rpc('icetak_set_qrpay_learning_rule_status',{p_rule_id:b.rule_id,p_status:b.status,p_actor:'admin-link'});if(q.error)throw q.error;return out({ok:true,rule:q.data})}
 return out({ok:false,error:'Unsupported action'},400)}catch(e){console.error('qrpay-draft-review',e);return out({ok:false,error:e instanceof Error?e.message:String(e)},500)}});
