// @ts-nocheck
import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const db = createClient(Deno.env.get('SUPABASE_URL') || '', Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') || '', { auth: { persistSession: false } });
const BRIDGE = 'https://buivecgahhmrhlmfujgt.supabase.co/functions/v1/qrpay-ai-order-bridge';
const H = { 'content-type':'application/json', 'access-control-allow-origin':'*', 'access-control-allow-methods':'POST,OPTIONS', 'access-control-allow-headers':'content-type,x-qrpay-ai-token', 'cache-control':'no-store' };
const out = (x,s=200) => new Response(JSON.stringify(x), { status:s, headers:H });
const t = x => x == null ? '' : String(x).trim();
const mt = m => t(m.text_content || m.caption);
const at = m => Date.parse(m.sent_at || m.created_at || '') || 0;
const mins = (a,b) => Math.abs(a-b)/60000;
const money = x => Number(Number(x || 0).toFixed(2));
const fn = m => t(m.raw_payload?.data?.raw?.message?.document?.filename || m.raw_payload?.data?.raw?.message?.image?.filename || m.media_metadata?.file_name || m.media_metadata?.filename);
const phone = x => { let d=t(x).replace(/\D/g,''); if(!d)return ''; if(d[0]==='0')d='60'+d.slice(1); else if(d[0]==='1')d='60'+d; else if(!d.startsWith('60'))d='60'+d; return d; };
const wa = x => x ? `https://wa.me/${phone(x)}` : '';
const exact = (s,a) => [...t(s).replace(/,/g,' ').matchAll(/(?:rm\s*)?(\d{1,5}(?:\.\d{1,2})?)/gi)].some(m => Math.abs(Number(m[1])-Number(a)) < .011);
const paid = s => /(dah|dh|sudah|done|already|telah|settle|paid).{0,24}(bayar|payment|transfer|pay)|done payment|dah bayar|dh bayar/i.test(t(s));
const payPrompt = s => /qrpay|qr pay|bagi qr|bg qr|send qr|nom(?:bor)? acc|akaun|account|payment|bayar|total\s*(?:rm)?\s*\d/i.test(t(s));
const receipt = m => { const s=(mt(m)+' '+fn(m)+' '+JSON.stringify(m.media_metadata||{})).toLowerCase(); if(m.message_type==='document') return /m2u|cimb\s*octo|bimb.*receipt|receipt|resit|duitnow|payment|transfer|bank.*slip/.test(s); if(m.message_type==='image') return /receipt|resit|duitnow|payment|transfer|bayar|qrpay|qr pay/.test(s); return false; };
const cols = 'id,conversation_id,direction,message_type,text_content,caption,sent_at,created_at,sender_phone,provider_message_id,media_url,media_metadata,raw_payload';

async function orderCall(token, body){ const r=await fetch(BRIDGE,{method:'POST',headers:{'content-type':'application/json','x-qrpay-ai-token':token},body:JSON.stringify(body)}); const j=await r.json().catch(()=>({error:'Invalid bridge response'})); if(!r.ok || j.ok===false) throw Error(j.error || `Bridge HTTP ${r.status}`); return j; }
async function auth(req){ const k=req.headers.get('x-qrpay-ai-token')||''; const r=await db.from('private_runtime_settings').select('setting_value').eq('setting_key','qrpay_ai_worker_token').maybeSingle(); return !!k && !r.error && k===r.data?.setting_value; }
async function windowMsgs(ts){ const s=new Date(ts-150*60000).toISOString(), e=new Date(ts+15*60000).toISOString(); const [a,b]=await Promise.all([db.from('messages').select(cols).eq('channel','whatsapp').gte('sent_at',s).lte('sent_at',e),db.from('messages').select(cols).eq('channel','whatsapp').is('sent_at',null).gte('created_at',s).lte('created_at',e)]); if(a.error)throw a.error;if(b.error)throw b.error;const z=new Map();for(const m of [...(a.data||[]),...(b.data||[])])z.set(m.id,m);return[...z.values()].sort((p,q)=>at(p)-at(q)); }
async function recentContext(id,ts){ const s=new Date(ts-36*3600000).toISOString(),e=new Date(ts+15*60000).toISOString();const r=await db.from('messages').select(cols).eq('conversation_id',id).gte('created_at',s).lte('created_at',e).order('created_at').limit(180);if(r.error)throw r.error;return r.data||[]; }
async function historicalDeal(id,ts,amount){ const s=new Date(ts-45*86400000).toISOString(),e=new Date(ts+15*60000).toISOString();const r=await db.from('messages').select(cols).eq('conversation_id',id).gte('created_at',s).lte('created_at',e).order('created_at').limit(700);if(r.error)throw r.error;const ms=r.data||[];let best=-1,bestGap=Infinity;for(let i=0;i<ms.length;i++){const m=ms[i],v=mt(m),gap=(ts-at(m))/60000;if(m.direction!=='outbound'||gap<0||gap>45*1440||!exact(v,amount))continue;if(!/total|jumlah|topper|edible|acrylic|akrilik|wafer|burn|rm|payment|bayar/i.test(v))continue;if(gap<bestGap){best=i;bestGap=gap;}}if(best<0)return null;return{block:ms.slice(Math.max(0,best-18),Math.min(ms.length,best+18)),quote:ms[best],gap_minutes:Math.round(bestGap)}; }
function score(ms,amt,ts){let n=0,c=99999,why=[],hasExact=false;for(const m of ms){const d=mins(at(m),ts),v=mt(m);c=Math.min(c,d);if(m.direction==='inbound'&&receipt(m))n+=d<=15?320:d<=60?220:100;if(m.direction==='inbound'&&paid(v))n+=d<=20?45:28;if(m.direction==='outbound'&&exact(v,amt)){n+=260;hasExact=true;}if(m.direction==='outbound'&&payPrompt(v))n+=8;}if(ms.some(receipt))why.push('receipt_near_payment');if(ms.some(m=>paid(mt(m))))why.push('customer_payment_claim');if(hasExact)why.push('exact_amount_quote');n+=Math.max(0,22-c/8);why.push(`closest_message_${Math.round(c)}m`);return{n,why,hasExact};}
async function best(job){const ts=Date.parse(job.payment_received_at),all=await windowMsgs(ts),g={},excluded=new Set((Array.isArray(job?.evidence?.excluded_conversation_ids)?job.evidence.excluded_conversation_ids:[]).map(String));for(const m of all)(g[m.conversation_id]??=[]).push(m);const cs=Object.entries(g).filter(([id])=>!excluded.has(String(id))).map(([id,ms])=>({id,ms,...score(ms,Number(job.amount),ts)})).sort((a,b)=>b.n-a.n).slice(0,5);for(const c of cs){const q=await db.from('conversations').select('customer_id').eq('id',c.id).maybeSingle(),cid=q.data?.customer_id;let name='WhatsApp Customer',p=phone(c.ms.find(m=>m.sender_phone)?.sender_phone);if(cid){const[a,b]=await Promise.all([db.from('customers').select('display_name').eq('id',cid).maybeSingle(),db.from('customer_identities').select('normalized_phone,external_id').eq('customer_id',cid).eq('channel','whatsapp')]);name=t(a.data?.display_name)||name;p=phone(b.data?.find(i=>i.normalized_phone)?.normalized_phone||b.data?.[0]?.external_id||p);}c.name=name;c.phone=p;}if(cs[0])cs[0].why.push(`score_margin_${Math.round(cs[0].n-(cs[1]?.n||0))}`);return{top:cs[0]||null,alts:cs.slice(1).map(c=>({conversation_id:c.id,score:c.n,name:c.name,phone:c.phone})),excluded_conversation_ids:[...excluded]};}

const autoNoise=s=>/HARGA ACRYLIC|RUJUKAN SAIZ MAKSIMUM|Menerima order:|save for order:|Terima kasih hubungi DecoCake/i.test(t(s));
function anchor(ms,amt,ts){let idx=ms.length-1,d=Infinity;for(let i=0;i<ms.length;i++){const v=mt(ms[i]);if(receipt(ms[i])||paid(v)||(ms[i].direction==='outbound'&&exact(v,amt))){const x=mins(at(ms[i]),ts);if(x<d){idx=i;d=x;}}}return idx;}
function around(ms,amt,ts){const a=anchor(ms,amt,ts);return ms.slice(Math.max(0,a-24),Math.min(ms.length,a+6)).filter(m=>!autoNoise(mt(m)));}
function dedupe(ms){const z=new Map();for(const m of ms)z.set(m.id,m);return[...z.values()].sort((a,b)=>at(a)-at(b));}
const catRe={edible:/\bedible\b|\bei\b|print gambar|icing sheet/i,acrylic:/acrylic|akrilik|ayrlic|arylic|arcylic/i,wafer:/\bwafer\b/i,burnaway:/burn\s*away|burnaway/i,printed:/\btopper\b|glossy|printed topper|topper tema/i,mirror:/mirror gold artpaper|artpaper/i};
function relevant(ms,job,recovered){return(recovered?ms:around(ms,Number(job.amount),Date.parse(job.payment_received_at))).filter(m=>!autoNoise(mt(m)));}
function categories(rel){const z=new Set();for(const m of rel){const s=mt(m);if(!s)continue;for(const[k,re]of Object.entries(catRe))if(re.test(s))z.add(k);}if(z.has('burnaway')){z.delete('edible');z.delete('wafer');}if(!z.size)z.add('printed');return[...z];}
function categoryMessages(ms,cat){const re=catRe[cat]||catRe.printed,idx=new Set();for(let i=0;i<ms.length;i++)if(re.test(mt(ms[i])))for(let j=Math.max(0,i-3);j<=Math.min(ms.length-1,i+3);j++)idx.add(j);return[...idx].map(i=>ms[i]).filter(m=>!autoNoise(mt(m)));}
function explicitRm(line){const a=[...t(line).matchAll(/\brm\s*(\d{1,5}(?:\.\d{1,2})?)/gi)];return a.length?Number(a.at(-1)[1]):null;}
function quoteData(ms){const out={};for(const m of ms.filter(x=>x.direction==='outbound'))for(const raw of mt(m).split(/\n+/)){const line=raw.trim();if(!line||autoNoise(line)||/^\s*(?:total|jumlah)\b/i.test(line))continue;for(const[cat,re]of Object.entries(catRe)){if(!re.test(line)||(cat==='printed'&&catRe.acrylic.test(line)))continue;let price=null,qty=null;const mult=line.match(/(?:rm\s*)?(\d+(?:\.\d+)?)\s*[x×]\s*(\d{1,2})\s*(?:pcs?|pc|keping|set|unit)?(?:\s+(\d+(?:\.\d+)?))?/i);if(mult){price=Number(mult[1]);qty=Number(mult[2]);}if(price==null){const rm=explicitRm(line);if(rm!=null)price=rm;}const q1=line.match(new RegExp(`(?:${re.source}).{0,24}?(\\d{1,2})\\s*(?:pcs?|pc|keping|set|unit)\\b`,'i'))||line.match(new RegExp(`\\b(\\d{1,2})\\s*(?:pcs?|pc|keping|set|unit)\\s*(?:x\\s*)?(?:${re.source})`,'i'));if(qty==null&&q1)qty=Number(q1[1]);if(price!=null&&price>0&&price<=500)out[cat]={...(out[cat]||{}),price};if(qty!=null&&qty>=1&&qty<=50)out[cat]={...(out[cat]||{}),qty};}}return out;}
function qty(ms,cat,hint){if(hint?.qty)return hint.qty;const re=catRe[cat]||catRe.printed;for(const m of [...ms].reverse()){const v=mt(m);if(!v)continue;let x=v.match(new RegExp(`(?:${re.source}).{0,28}?(?:qty\\s*[:=-]?\\s*)?(\\d{1,2})\\s*(?:pcs?|pc|keping|set|unit|design)\\b`,'i'))||v.match(new RegExp(`\\b(?:qty\\s*[:=-]?\\s*)?(\\d{1,2})\\s*(?:pcs?|pc|keping|set|unit|design)\\s*(?:x\\s*)?(?:${re.source})`,'i'));if(x){const n=Number(x[1]);if(n>=1&&n<=50&&!/\bA[4-7]\b/i.test(x[0]))return n;}}return 1;}
function size(ss){const ps=[/\b(\d+(?:\.\d+)?\s*[x×]\s*\d+(?:\.\d+)?\s*(?:inch|inci|in)?)\b/i,/\b(\d+(?:\.\d+)?\s*(?:inch|inci|inches|in))\b/i,/(\d+(?:\.\d+)?)\s*\"/i,/\b(A[4-7])\b/i];for(const r of ps)for(let i=ss.length-1;i>=0;i--){const m=t(ss[i]).match(r);if(m)return m[1];}return'';}
function style(ss){const colors=['rose gold','silver mirror','gold mirror','silver','gold','black','white','clear','pink','blue','red','green','orange','yellow','purple','lilac'];let c='',sh='';for(let i=ss.length-1;i>=0;i--){const v=t(ss[i]).toLowerCase();if(!c)c=colors.find(x=>v.includes(x))||'';if(!sh){if(/bulat|circle|round/.test(v))sh='Round / Bulat';else if(/petak|square/.test(v))sh='Square / Petak';else if(/hati|love shape/.test(v))sh='Love Shape / Hati';}if(c&&sh)break;}return[c&&c.replace(/\b\w/g,x=>x.toUpperCase()),sh].filter(Boolean).join(' — ');}
function validW(v){v=t(v);return!!v&&v.length<=160&&!/^(OK|YA|YE|YES|SAMA|BAIK|SALAM|BOLEH|CONFIRM|WAIT|OKAY)$/i.test(v)&&!/payment|alamat|address|total|spx|jnt|postcode|poskod|pickup|proses|kirim|bagi total|make it \d+\s*(?:inch|in)/i.test(v);}
function explicitWording(v){for(const line of t(v).split(/\n+/)){const m=line.match(/^\s*(?:wording|tulisan|custom\s*name|nama|huruf)\s*[:=-]\s*(.+?)\s*$/i);if(m&&validW(m[1]))return m[1].trim();}return'';}
function wording(ms,loose=false){const inbound=ms.filter(m=>m.direction==='inbound'),a=inbound.map(mt).filter(Boolean);for(const m of [...inbound].reverse()){const w=explicitWording(mt(m));if(w)return w;}for(let i=a.length-1;i>=0;i--){let v=t(a[i]);if(/^(wording|tulisan|custom\s*name|nama|huruf)\s*[:=-]?/i.test(v)){v=v.replace(/^(wording|tulisan|custom\s*name|nama|huruf)\s*[:=-]?/i,'').trim();if(validW(v))return v;if(a[i+1]&&validW(a[i+1]))return t(a[i+1]);}if(/^(happy|selamat|the wedding|mubarak|congrat|welcome|birthday)/i.test(v)&&validW(v))return v;}if(loose){for(let i=a.length-1;i>=1;i--){if(/\bname\b.*(?:line|2\s*lines|two\s*lines|make)/i.test(a[i])&&validW(a[i-1]))return t(a[i-1]);}for(let i=a.length-2;i>=0;i--){if(/^(?:name|nama)\b/i.test(a[i+1])&&validW(a[i]))return t(a[i]);}}return'';}
function shortTitle(ms,cat,fallback){const re=catRe[cat]||catRe.printed;for(const m of [...ms].reverse()){if(m.direction!=='inbound')continue;let v=mt(m);if(!re.test(v)||autoNoise(v))continue;v=v.replace(/\brm\s*\d+(?:\.\d+)?/ig,' ').replace(/\b(?:nak|mahu|mau|buat|order|oder|topper|cake topper|edible image|edible|acrylic|akrilik|wafer paper|wafer|burn away|glossy|paper|size|saiz|qty|pcs?|set)\b/ig,' ').replace(/\bA[4-7]\b/ig,' ').replace(/\b\d+(?:\.\d+)?\s*(?:inch|inci|in)?\b/ig,' ').replace(/\s+/g,' ').trim().replace(/^[-,:]+|[-,:]+$/g,'').trim();if(v.length>=2&&v.length<=60)return v.replace(/\b\w/g,x=>x.toUpperCase());}return fallback;}
function delivery(ms){const rel=ms.filter(m=>!autoNoise(mt(m)));for(const m of [...rel].reverse()){const v=mt(m);if(/pickup|ambil|ambik|self collect/i.test(v))return{method:'pickup',fee:0,evidence:m.id};if(/\bspx\b/i.test(v))return{method:'spx',fee:explicitRm(v)??4.5,evidence:m.id};if(/\bj\s*&?\s*t\b|\bjnt\b/i.test(v))return{method:'jnt',fee:explicitRm(v)??5.9,evidence:m.id};if(/ninja/i.test(v))return{method:'ninja',fee:explicitRm(v)??6.9,evidence:m.id};}return{method:'unknown',fee:0,evidence:null};}
function dateNeed(ms,ts){const s=ms.filter(m=>m.direction==='inbound').map(mt).join('\n');let z=[...s.matchAll(/(?:guna|pakai|need|before|sebelum|pickup|ambil|ambik|dapat|sampai)?[^\n]{0,18}\b(\d{1,2})[\/.\-](\d{1,2})(?:[\/.\-](\d{2,4}))?\b/gi)].at(-1);if(z){let y=z[3]?Number(z[3]):new Date(ts).getFullYear();if(y<100)y+=2000;return`${y}-${String(z[2]).padStart(2,'0')}-${String(z[1]).padStart(2,'0')}`;}const hb=[...s.matchAll(/\b(\d{1,2})\s*(?:hb|haribulan)\b/gi)].at(-1),local=new Date(ts+8*3600000);if(hb){let day=Number(hb[1]),mo=local.getUTCMonth()+1,y=local.getUTCFullYear();if(day<local.getUTCDate()-3)mo++;if(mo>12){mo=1;y++;}return`${y}-${String(mo).padStart(2,'0')}-${String(day).padStart(2,'0')}`;}const b=new Date(Date.UTC(local.getUTCFullYear(),local.getUTCMonth(),local.getUTCDate()));if(/esok|tomorrow/i.test(s)){b.setUTCDate(b.getUTCDate()+1);return b.toISOString().slice(0,10);}return null;}
function refs(ms){return ms.filter(m=>['image','document'].includes(m.message_type)).slice(-12).map(m=>({message_id:m.id,provider_message_id:m.provider_message_id,type:m.message_type,media_url:m.media_url||null,caption:mt(m)||null,file_name:fn(m)||null}));}
function makeItems(rel,job,c){const cs=categories(rel),quotes=quoteData(rel),r=refs(rel),allStrings=rel.map(mt).filter(Boolean),recentInbound=rel.filter(m=>m.direction==='inbound').map(mt).join('\n').toLowerCase(),newd=/new design|design baru|custom topper|tema|buat design/.test(recentInbound)&&!/design sama|repeat|tukar nama|change name|edit|template sama/.test(recentInbound),fallback={edible:'Edible Image',acrylic:'Acrylic Cake Topper',wafer:'Wafer Paper',burnaway:'Burn Away Combo',printed:newd?'New Design Cake Topper':'Cake Topper',mirror:'Mirror Gold Topper'};return cs.map((cat,i)=>{const cm=categoryMessages(rel,cat),ss=(cm.length?cm:rel).map(mt).filter(Boolean),q=qty(cm.length?cm:rel,cat,quotes[cat]),w=wording(cm.length?cm:rel,false)||(cat==='printed'?wording(rel,true):''),sz=cat==='printed'?(size(allStrings)||size(ss)):size(ss),title=shortTitle(cm.length?cm:rel,cat,fallback[cat]||'Cake Topper'),jt=cat==='printed'?(newd?'topper_new_design_glossy':'topper_editing_glossy'):cat,price=money(quotes[cat]?.price||0);return{k:cat,product_type:cat,title,qty:q,price,size:sz,style:cat==='printed'?`${newd?'New Design':'Editing / Existing Design'} — Glossy`:style(ss),wording:w,custom_text:w,review:'Need Review',review_required:true,customization:{ai_generated:true,ai_job_type:jt,ai_pending_confirmation:true,conversation_id:c.id,whatsapp_phone:c.phone,whatsapp_link:wa(c.phone),qrpay_transaction_id:job.transaction_id,qrpay_amount:Number(job.amount),qrpay_received_at:job.payment_received_at,match_score:Number(Math.min(.99,c.n/150).toFixed(3)),match_reason:c.why,reference_message_ids:r.map(v=>v.message_id),reference_media:r,source:'whatsapp_qrpay_ai',set_hint:i+1},product_snapshot:{source:'whatsapp_qrpay_ai',image_url:r.find(v=>v.type==='image'&&v.media_url)?.media_url||null,ai_job_type:jt,reference_message_ids:r.map(v=>v.message_id)}};});}
function buildPayload(ms,c,job,alts,rules,recovery=null){const recovered=!!recovery,rel=relevant(ms,job,recovered),its=makeItems(rel,job,c),del=delivery(rel),dn=dateNeed(rel,Date.parse(job.payment_received_at)),ins=rel.filter(m=>m.direction==='inbound').map(mt).filter(Boolean),ad=[...ins].reverse().find(v=>/\b\d{5}\b/.test(v)&&v.length>18)||'',pc=ad.match(/\b(\d{5})\b/)?.[1]||'',p=phone(c.phone||rel.find(m=>m.sender_phone)?.sender_phone),sc=Number(Math.max(.35,Math.min(.99,c.n/150)).toFixed(3));const itemSubtotal=money(its.reduce((s,x)=>s+Number(x.price||0)*Math.max(1,Number(x.qty||1)),0)),draftTotal=money(itemSubtotal+Number(del.fee||0)),diff=money(draftTotal-Number(job.amount||0)),missing=[];if(!dn)missing.push('date_need');if(del.method==='unknown')missing.push('shipping_method');if(!its.some(x=>x.wording||x.product_snapshot?.image_url))missing.push('wording_or_reference');if(!ad&&del.method!=='pickup'&&del.method!=='unknown')missing.push('delivery_address');if(its.some(x=>Number(x.price||0)<=0))missing.push('item_price');if(Math.abs(diff)>.01)missing.push('payment_reconciliation');const sum=its.map((x,i)=>`${i+1}. ${x.title} x${x.qty} | RM${Number(x.price||0).toFixed(2)}${x.size?' | '+x.size:''}${x.wording?' | '+x.wording.replace(/\n/g,' / '):''}`).join('\n');const remark=['AI DRAFT ONLY — belum create Order / ClickUp.',`QRPay: RM${Number(job.amount).toFixed(2)} | ${job.transaction_id}`,`AI customer match: ${Math.round(sc*100)}% | ${c.why.join(', ')}`,recovery?`Historical quote recovered: ${Math.round(recovery.gap_minutes/1440*10)/10} day(s) before payment.`:'',missing.length?`Admin check: ${missing.join(', ')}`:'Detail utama extracted; admin tetap wajib confirm.',sum].filter(Boolean).join('\n');return{customer:{name:c.name||'WhatsApp Customer',phone:p,address_line1:ad,postcode:pc,city:'',state:''},items:its,delivery:del.method,delivery_fee:del.fee,date_need:dn,admin_remark:remark,conversation_id:c.id,transaction_id:job.transaction_id,payment_received_at:job.payment_received_at,match_score:sc,match_reason:[...c.why,...(recovery?['historical_exact_amount_quote']:[])].join(','),ai_missing:missing,draft_total:draftTotal,payment_amount:Number(job.amount),evidence:{conversation_id:c.id,alternatives:alts,messages:rel.slice(-60).map(m=>({id:m.id,direction:m.direction,type:m.message_type,at:m.sent_at||m.created_at,text:mt(m).slice(0,600)})),receipt_message_ids:rel.filter(receipt).map(m=>m.id),reference_media:refs(rel),whatsapp_link:wa(p),worker_version:'qrpay-ai-draft-v11-historical-recovery-r2',excluded_conversation_ids:Array.isArray(job?.evidence?.excluded_conversation_ids)?job.evidence.excluded_conversation_ids:[],active_learning_rules:rules.map(x=>({id:x.id,strategy_key:x.strategy_key,occurrence_count:x.occurrence_count,title:x.title})),historical_recovery:recovery?{used:true,quote_message_id:recovery.quote?.id||null,quote_at:recovery.quote?.sent_at||recovery.quote?.created_at||null,gap_minutes:recovery.gap_minutes}:{used:false}}};}
function needsRecovery(p,amount){const total=money((p.items||[]).reduce((s,x)=>s+Number(x.price||0)*Math.max(1,Number(x.qty||1)),0)+Number(p.delivery_fee||0));return(p.items||[]).some(x=>Number(x.price||0)<=0)||Math.abs(total-Number(amount||0))>.01;}
async function run(j,k,rules){const b=await best(j);if(!b.top||b.top.n<42){await orderCall(k,{action:'update_job',job_id:j.id,patch:{status:'unmatched',match_score:b.top?.n||0,match_reason:'no_strong_whatsapp_candidate',evidence:{alternatives:b.alts,excluded_conversation_ids:b.excluded_conversation_ids||[]},locked_at:null,completed_at:new Date().toISOString()}});return{job_id:j.id,status:'unmatched'};}const c=b.top,ts=Date.parse(j.payment_received_at),recent=await recentContext(c.id,ts);let ms=recent,recovery=null,p=buildPayload(ms,c,j,b.alts,rules,null);if(needsRecovery(p,j.amount)){recovery=await historicalDeal(c.id,ts,Number(j.amount));if(recovery){ms=dedupe([...recovery.block,...recent]);p=buildPayload(ms,c,j,b.alts,rules,recovery);}}await orderCall(k,{action:'update_job',job_id:j.id,patch:{status:'matched',matched_conversation_id:c.id,matched_phone:p.customer.phone,matched_customer_name:p.customer.name,match_score:p.match_score,match_reason:p.match_reason,extraction:p,evidence:p.evidence}});if(j.mode==='dry_run'){await orderCall(k,{action:'update_job',job_id:j.id,patch:{status:'dry_run_complete',locked_at:null,completed_at:new Date().toISOString()}});return{job_id:j.id,status:'dry_run_complete',payload:p};}const z=await orderCall(k,{action:'create_draft',job_id:j.id,payload:p});return{job_id:j.id,status:'draft_created',draft:z.result,matched_phone:p.customer.phone,conversation_id:c.id,recovered_history:!!recovery};}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:H});if(req.method!=='POST')return out({ok:false,error:'POST required'},405);if(!await auth(req))return out({ok:false,error:'Unauthorized'},401);const k=req.headers.get('x-qrpay-ai-token')||'';let body={};try{body=await req.json()}catch{}try{const q=await orderCall(k,{action:'claim',batch_size:Math.max(1,Math.min(10,Number(body.batch_size||3)))}),learning=await orderCall(k,{action:'learning_context'}).catch(()=>({rules:[]})),rules=Array.isArray(learning.rules)?learning.rules:[],rs=[];for(const j of q.jobs||[])try{rs.push(await run(j,k,rules));}catch(e){const m=e instanceof Error?e.message:String(e),fin=Number(j.attempts||0)>=5;await orderCall(k,{action:'update_job',job_id:j.id,patch:{status:fin?'failed':'retry',next_attempt_at:new Date(Date.now()+(fin?86400000:300000)).toISOString(),locked_at:null,last_error:m.slice(0,2000),completed_at:fin?new Date().toISOString():null}});rs.push({job_id:j.id,status:fin?'failed':'retry',error:m});}return out({ok:true,worker:'qrpay-ai-draft-v11-historical-recovery-r2',mode:'draft_only',active_learning_rules:rules.length,claimed:q.jobs?.length||0,results:rs});}catch(e){console.error('qrpay-ai-order-worker',e);return out({ok:false,error:e instanceof Error?e.message:String(e)},500);}});
