// @ts-nocheck
import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const U=Deno.env.get('SUPABASE_URL')||'';
const K=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';
const db=createClient(U,K,{auth:{persistSession:false}});
const H={'content-type':'application/json','access-control-allow-origin':'*','access-control-allow-methods':'POST,OPTIONS','access-control-allow-headers':'content-type,x-admin-order-token','cache-control':'no-store'};
const out=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H});
const txt=(v:any)=>v==null?'':String(v).trim();
const digits=(v:any)=>{let d=txt(v).replace(/\D/g,'');if(!d)return'';if(d.startsWith('0'))d='60'+d.slice(1);else if(d.startsWith('1'))d='60'+d;else if(!d.startsWith('60'))d='60'+d;return d};
const wa=(v:any)=>digits(v)?`https://wa.me/${digits(v)}`:'';

async function secret(key:string){const {data}=await db.from('private_runtime_settings').select('setting_value').eq('setting_key',key).maybeSingle();return txt(data?.setting_value)}
async function setting(key:string){const {data}=await db.from('whatsapp_settings').select('text_value,secret_value').eq('key',key).maybeSingle();return txt(data?.secret_value||data?.text_value)}
async function auth(req:Request){const k=req.headers.get('x-admin-order-token')||'';return !!k&&k===await secret('qrpay_ai_worker_token')}
async function provider(path:string,payload:any){const base=await setting('base_url')||'https://officialapi.wasapflow.com/bridge/v1',partner=await setting('partner_key'),waba=await setting('waba_id');if(!partner||!waba)throw Error('WasapFlow credentials incomplete');const r=await fetch(`${base}${path}`,{method:'POST',headers:{'content-type':'application/json','x-partner-key':partner,'x-waba-id':waba},body:JSON.stringify(payload)});const j=await r.json().catch(()=>({}));if(!r.ok||j.success===false)throw Error(j?.error?.message||j?.message||`WasapFlow ${r.status}`);return j}
async function sendText(to:string,text:string){return provider('/messages/send',{to:digits(to),text,preview_url:true})}
async function sendButtons(to:string,text:string,buttons:any[]){try{return await provider('/messages/interactive',{to:digits(to),type:'button',body:{text},action:{buttons:buttons.slice(0,3).map((b:any)=>({type:'reply',reply:{id:b.id,title:b.title.slice(0,20)}}))}})}catch(e){await sendText(to,text+'\n\nBalas dengan detail order jika perlu.');return {fallback:true,error:String(e)}}}

function itemSummary(p:any){const a=Array.isArray(p?.items)?p.items:[];return a.length?a.map((x:any,i:number)=>`${i+1}. ${txt(x.title||x.k||'Item')} x${Number(x.qty||1)}${txt(x.size)?` | ${txt(x.size)}`:''}${txt(x.wording)?` | ${txt(x.wording).replace(/\n/g,' / ')}`:''}`).join('\n'):'- detail item belum cukup -'}
async function reviewMessage(r:any){const p=r.extraction||{},phone=digits(r.candidate_phone||p?.customer?.phone),name=txt(r.candidate_name||p?.customer?.name)||'Belum dikenal pasti',score=r.match_score==null?'':`${Math.round(Number(r.match_score)*100)}%`,missing=[];if(!phone)missing.push('phone');if(!p.date_need)missing.push('date');if(!Array.isArray(p.items)||!p.items.length)missing.push('order detail');const lines=[r.source_type==='qrpay'?'⚠️ QRPay perlu semakan':'⚠️ Pickup order perlu semakan',r.amount!=null?`RM: ${Number(r.amount).toFixed(2)}`:'',r.transaction_id?`Tx: ${r.transaction_id}`:'',`Customer: ${name}`,phone?`Phone: ${phone}`:'Phone: belum jumpa',phone?`WhatsApp: ${wa(phone)}`:'',score?`Confidence: ${score}`:'',p.delivery?`Delivery: ${String(p.delivery).toUpperCase()}`:'',p.date_need?`Date: ${p.date_need}`:'Date: belum ada','',itemSummary(p),missing.length?`\nBelum lengkap: ${missing.join(', ')}`:''].filter(Boolean);return lines.join('\n')}
async function notifyReview(r:any){const text=await reviewMessage(r);await sendButtons(r.admin_phone||'60129554732',text,[{id:`aor:approve:${r.review_token}`,title:'Approve & Create'},{id:`aor:detail:${r.review_token}`,title:'Bagi Detail'},{id:`aor:reject:${r.review_token}`,title:'Reject'}]);await db.from('admin_order_reviews').update({last_notified_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',r.id)}

function parseDate(v:string){const s=v.toLowerCase().trim();const iso=s.match(/\b(20\d{2})-(\d{1,2})-(\d{1,2})\b/);if(iso)return `${iso[1]}-${iso[2].padStart(2,'0')}-${iso[3].padStart(2,'0')}`;const dmy=s.match(/\b(\d{1,2})[\/.\-](\d{1,2})(?:[\/.\-](\d{2,4}))?\b/);if(dmy){let y=dmy[3]?Number(dmy[3]):new Date().getFullYear();if(y<100)y+=2000;return `${y}-${dmy[2].padStart(2,'0')}-${dmy[1].padStart(2,'0')}`};const months:any={jan:1,januari:1,feb:2,februari:2,mac:3,mar:3,april:4,apr:4,mei:5,may:5,jun:6,june:6,julai:7,july:7,ogos:8,aug:8,august:8,sep:9,september:9,okt:10,oktober:10,oct:10,nov:11,november:11,dis:12,disember:12,dec:12};const m=s.match(/\b(\d{1,2})\s+([a-z]+)(?:\s+(20\d{2}))?/i);if(m&&months[m[2]])return `${m[3]||new Date().getFullYear()}-${String(months[m[2]]).padStart(2,'0')}-${m[1].padStart(2,'0')}`;return null}
function kind(v:string){const s=v.toLowerCase();if(/acrylic|akrilik/.test(s))return'acrylic';if(/wafer/.test(s))return'wafer';if(/burn/.test(s))return'burnaway';if(/edible|\bei\b/.test(s))return'edible';return'printed'}
function mergeDetail(r:any,body:string){const p=structuredClone(r.extraction||{});p.customer=p.customer||{};p.items=Array.isArray(p.items)?p.items:[];let order='';let qty=1;let rm:any=null;let size='';let wording='';let note='';let name='';let address='';let delivery='';let date:any=null;let phone='';for(const raw of body.split(/\n+/)){const line=raw.trim();if(!line)continue;const m=line.match(/^([^:]+):\s*(.*)$/);if(m){const k=m[1].trim().toLowerCase(),v=m[2].trim();if(/^(order|produk|product)$/.test(k))order=v;else if(/^(qty|quantity|kuantiti)$/.test(k))qty=Math.max(1,Number(v.replace(/\D/g,''))||1);else if(/^(rm|price|harga|total)$/.test(k))rm=Number((v.match(/\d+(?:\.\d{1,2})?/)||[])[0]);else if(/^(delivery|courier|penghantaran)$/.test(k))delivery=v.toLowerCase();else if(/^(date|tarikh|need date)$/.test(k))date=parseDate(v);else if(/^(note|remark|catatan)$/.test(k))note=v;else if(/^(phone|no phone|no|telefon|nombor)$/.test(k))phone=digits(v);else if(/^(name|nama|customer)$/.test(k))name=v;else if(/^(wording|tulisan)$/.test(k))wording=v;else if(/^(size|saiz)$/.test(k))size=v;else if(/^(address|alamat)$/.test(k))address=v;continue}const pd=digits(line);if(/^601\d{8,9}$/.test(pd))phone=pd}
if(phone)p.customer.phone=phone;if(name)p.customer.name=name;if(address)p.customer.address_line1=address;if(delivery)p.delivery=/pickup|ambil|self/.test(delivery)?'pickup':/j.?t|jnt/.test(delivery)?'jnt':/spx/.test(delivery)?'spx':delivery;if(date)p.date_need=date;if(note)p.admin_remark=[txt(p.admin_remark),note].filter(Boolean).join('\n');if(order){const k=kind(order),amount=r.amount!=null?Number(r.amount):Number.isFinite(rm)?rm:0,fee=Number(p.delivery_fee||0),price=Math.max(0,amount-fee)/qty;p.items=[{k,title:k==='edible'?'Edible Image':k==='acrylic'?'Acrylic Cake Topper':k==='wafer'?'Wafer Paper':k==='burnaway'?'Burn Away Combo':'Cake Topper',qty,price:Number(price.toFixed(2)),size,wording,custom_text:wording,review:'Need Review',review_required:true,customization:{ai_generated:true,ai_pending_confirmation:true,source:'admin_whatsapp_detail'},product_snapshot:{source:'admin_whatsapp_detail'}}]}
return {payload:p,providedRm:rm}}
function validForCreate(r:any,p:any){const phone=digits(p?.customer?.phone||r.candidate_phone);return /^601\d{8,9}$/.test(phone)&&!!p.date_need&&Array.isArray(p.items)&&p.items.length>0}

async function createFromReview(r:any){const p=structuredClone(r.extraction||{});p.customer=p.customer||{};if(!p.customer.phone&&r.candidate_phone)p.customer.phone=digits(r.candidate_phone);if(!p.customer.name&&r.candidate_name)p.customer.name=r.candidate_name;if(!validForCreate(r,p))throw Error('Detail belum lengkap: perlu phone, Order/Qty dan Date');const token=await secret('qrpay_ai_worker_token');let result:any;if(r.source_type==='qrpay'){const {data,error}=await db.rpc('icetak_auto_create_qrpay_order',{p_job_id:r.qrpay_job_id,p_payload:p,p_internal_token:token});if(error)throw error;result=data}else if(r.source_type==='pickup_ai'){const {data,error}=await db.rpc('icetak_auto_create_pickup_ai_order',{p_request_key:r.source_key,p_payload:p,p_internal_token:token});if(error)throw error;result=data}else throw Error('Unsupported review source');const oid=txt(result?.order_db_id);await db.from('admin_order_reviews').update({status:'created',order_id:oid||null,order_no:txt(result?.order_id),approved_at:new Date().toISOString(),completed_at:new Date().toISOString(),updated_at:new Date().toISOString(),last_error:null}).eq('id',r.id);return result}

async function handleIncoming(phone:string,text:string,buttonId:string){const admin=digits(await setting('admin_order_notify_phone')||'60129554732');if(digits(phone)!==admin)return {ignored:true};let token='',action='';const m=txt(buttonId).match(/^aor:(approve|detail|reject):(.+)$/);if(m){action=m[1];token=m[2]}let q:any;if(token){const {data}=await db.from('admin_order_reviews').select('*').eq('review_token',token).maybeSingle();q=data}else{const {data}=await db.from('admin_order_reviews').select('*').eq('admin_phone',admin).in('status',['awaiting_admin_detail','pending_admin']).order('updated_at',{ascending:false}).limit(1).maybeSingle();q=data}if(!q)return {ignored:true,reason:'no_pending_review'};
if(action==='reject'){await db.from('admin_order_reviews').update({status:'rejected',rejected_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',q.id);await sendText(admin,`❌ Review ${q.transaction_id||q.source_key} dibatalkan.`);return {ok:true,status:'rejected'}}
if(action==='detail'){await db.from('admin_order_reviews').update({status:'awaiting_admin_detail',updated_at:new Date().toISOString()}).eq('id',q.id);await sendText(admin,`Hantar detail untuk ${q.transaction_id||q.source_key} dalam format biasa:\nOrder: edible\nQty: 1\nDelivery: spx\nDate: 8 ogos\nNote: ...\nPhone: 01...\n\nAddress optional. RM/payment/phone tak perlu ulang jika sistem dah ada.`);return {ok:true,status:'awaiting_admin_detail'}}
if(action==='approve'){try{const result=await createFromReview(q);await sendText(admin,`✅ Approved. Order ${result?.order_id||''} sedang tunggu ClickUp siap. Notification lengkap akan dihantar selepas semua task siap.`);return {ok:true,status:'created',result}}catch(e){await db.from('admin_order_reviews').update({status:'awaiting_admin_detail',last_error:String(e),updated_at:new Date().toISOString()}).eq('id',q.id);await sendText(admin,`⚠️ Belum boleh create: ${e instanceof Error?e.message:String(e)}\nTekan/Balas detail order.`);return {ok:false,error:String(e)}}}
if(txt(text)){const {payload,providedRm}=mergeDetail(q,text);if(Number.isFinite(providedRm)&&q.amount!=null&&Math.abs(Number(providedRm)-Number(q.amount))>0.009){await sendText(admin,`⚠️ RM tak sama. QRPay sebenar RM${Number(q.amount).toFixed(2)}, tetapi detail diberi RM${Number(providedRm).toFixed(2)}. Saya tak create dulu.`);return {ok:false,error:'amount_mismatch'}}await db.from('admin_order_reviews').update({extraction:payload,candidate_phone:digits(payload?.customer?.phone||q.candidate_phone)||null,candidate_name:txt(payload?.customer?.name||q.candidate_name)||null,status:'pending_admin',updated_at:new Date().toISOString(),last_error:null}).eq('id',q.id);const {data:r2}=await db.from('admin_order_reviews').select('*').eq('id',q.id).single();await notifyReview(r2);return {ok:true,status:'pending_admin'}}return {ignored:true}}

async function finalNotification(queueId:string){const {data:q,error}=await db.from('admin_order_notification_queue').select('*').eq('id',queueId).single();if(error)throw error;const {data:o,error:oe}=await db.from('orders').select('*').eq('id',q.order_id).single();if(oe)throw oe;const {data:components}=await db.from('production_components').select('id,label,clickup_task_id,clickup_status,order_item_id').eq('order_id',o.id).order('created_at');if((components||[]).some((x:any)=>!x.clickup_task_id)){await db.from('admin_order_notification_queue').update({status:'pending',locked_at:null,scheduled_at:new Date(Date.now()+60000).toISOString(),updated_at:new Date().toISOString()}).eq('id',q.id);return {waiting:true}}
const {data:items}=await db.from('order_items').select('id,title,qty,price,size,wording,custom_text').eq('order_id',o.id).order('created_at');const {data:tasks}=await db.from('clickup_tasks').select('clickup_task_id,url,component_id').eq('order_id',o.id);const {data:pay}=await db.from('payment_transactions').select('transaction_id,amount,provider,paid_at').eq('order_id',o.id).order('paid_at',{ascending:false}).limit(1).maybeSingle();const phone=digits(o.delivery_phone),orderLink=`https://icetak.bolt.host/?admin=1&order=${encodeURIComponent(o.public_token)}`,taskLinks=(tasks||[]).map((t:any)=>t.url||`https://app.clickup.com/t/${t.clickup_task_id}`).filter(Boolean);const title=q.event_type==='qrpay_matched_existing'?'✅ QRPay matched existing order':'✅ Order auto-created & ClickUp siap';const msg=[title,`Order: ${o.order_no||o.order_id}`,`Customer: ${o.delivery_name||'Customer'}`,`Phone: ${phone}`,phone?`WhatsApp: ${wa(phone)}`:'',`RM: ${Number(pay?.amount??o.total??0).toFixed(2)}`,pay?.transaction_id?`Tx: ${pay.transaction_id}`:'',`Delivery: ${String(o.delivery_method||o.delivery||'').toUpperCase()}`,`Date: ${o.date_need||'-'}`,`Payment: ${o.payment||o.payment_status||'-'}`,'',(items||[]).map((x:any,i:number)=>`${i+1}. ${x.title} x${x.qty}${x.size?` | ${x.size}`:''}${txt(x.wording||x.custom_text)?` | ${txt(x.wording||x.custom_text).replace(/\n/g,' / ')}`:''}`).join('\n'),'',`Open Order: ${orderLink}`,taskLinks.length?`ClickUp: ${taskLinks.join('\n')}`:''].filter(Boolean).join('\n');const admin=await setting('admin_order_notify_phone')||'60129554732';const sent=await sendText(admin,msg);await db.from('admin_order_notification_queue').update({status:'sent',provider_message_id:sent?.message_id||sent?.id||null,sent_at:new Date().toISOString(),locked_at:null,last_error:null,updated_at:new Date().toISOString()}).eq('id',q.id);return {sent:true}}

Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:H});if(req.method!=='POST')return out({ok:false,error:'POST required'},405);if(!await auth(req))return out({ok:false,error:'Unauthorized'},401);const b=await req.json().catch(()=>({}));try{if(b.action==='create_review'){const row={source_type:b.source_type,source_key:txt(b.source_key),qrpay_job_id:b.qrpay_job_id||null,transaction_id:txt(b.transaction_id)||null,amount:b.amount??null,candidate_phone:digits(b.candidate_phone)||null,candidate_name:txt(b.candidate_name)||null,match_score:b.match_score??null,extraction:b.extraction||{},evidence:b.evidence||{},status:'pending_admin',admin_phone:digits(await setting('admin_order_notify_phone')||'60129554732'),updated_at:new Date().toISOString()};const {data,error}=await db.from('admin_order_reviews').upsert(row,{onConflict:'source_type,source_key'}).select('*').single();if(error)throw error;await notifyReview(data);return out({ok:true,review:data})}if(b.action==='incoming')return out({ok:true,result:await handleIncoming(b.phone,b.text,b.button_id)});if(b.action==='send_final_notification')return out({ok:true,result:await finalNotification(b.queue_id)});return out({ok:false,error:'unsupported action'},400)}catch(e){console.error('admin-order-control',e);if(b.queue_id)await db.from('admin_order_notification_queue').update({status:'retry',locked_at:null,last_error:String(e).slice(0,2000),scheduled_at:new Date(Date.now()+300000).toISOString(),updated_at:new Date().toISOString()}).eq('id',b.queue_id).catch(()=>{});return out({ok:false,error:e instanceof Error?e.message:String(e)},500)}});
