import { useEffect, useState } from 'react';
type Data=Record<string,any>;
type Props={row:Data;examples:Data[];response:string;intent:string;canManage:boolean;canTrain:boolean;busy:boolean;call:(body:Data)=>Promise<Data>;onSave:(data:Data)=>Promise<void>;onUse:(text:string)=>void;onDirty:(dirty:boolean)=>void};
const verdicts:Record<string,string>={accepted:'Cadangan sesuai',corrected:'Perlu pembetulan',rejected:'Cadangan tidak sesuai'};
export default function AiTraining({row,examples,response,intent,canManage,canTrain,busy,call,onSave,onUse,onDirty}:Props){
 const [verdict,setVerdict]=useState('corrected'),[lesson,setLesson]=useState(''),[reusable,setReusable]=useState(''),[library,setLibrary]=useState<Data[]>([]),[error,setError]=useState(''),[saving,setSaving]=useState(false);
 useEffect(()=>{let live=true;setLibrary([]);void call({action:'training_list',channel:row.channel,intent:intent||row.analysis.intent}).then(d=>{if(live)setLibrary(d.examples||[]);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[row.id,intent,row.analysis.intent,examples]);
 const save=async(data:Data)=>{setSaving(true);setError('');try{await onSave(data);if(!data.training_id){setLesson('');setReusable('');onDirty(false);}}catch(e){setError((e as Error).message);}finally{setSaving(false);}};
 return <section className="ai-training"><h3>Latihan & pembetulan AI</h3><p className="ai-muted">Simpan penilaian untuk semakan kualiti. Model belum dilatih semula; hanya SOP diluluskan boleh dipilih secara manual.</p>
 {error&&<p className="ai-error" role="alert">{error}</p>}
 <div className="ai-training-counts"><span>{examples.length} rekod chat ini</span><span>{examples.filter(e=>e.state==='approved').length} SOP diluluskan</span></div>
 <label htmlFor="ai-verdict">Penilaian cadangan</label><select id="ai-verdict" disabled={!canManage||busy||saving} value={verdict} onChange={e=>{setVerdict(e.target.value);onDirty(true);}}>{Object.entries(verdicts).map(([key,label])=><option value={key} key={key}>{label}</option>)}</select>
 <p className="ai-muted">Balasan dinilai: teks dalam “Edit sebelum membalas”. Kategori: {intent||row.analysis.intent}.</p>
 <label htmlFor="ai-lesson">Apa yang AI perlu belajar?</label><textarea id="ai-lesson" value={lesson} maxLength={2000} rows={3} placeholder="Contoh: Auto-reply umum belum menjawab soalan saiz pelanggan." disabled={!canManage||busy||saving} onChange={e=>{setLesson(e.target.value);onDirty(true);}}/>
 <label htmlFor="ai-reusable">Contoh SOP umum (pilihan)</label><textarea id="ai-reusable" value={reusable} maxLength={4000} rows={3} placeholder="Tulis balasan umum tanpa nama, telefon, order ID atau fakta bayaran pelanggan ini." disabled={!canManage||busy||saving} onChange={e=>{setReusable(e.target.value);onDirty(true);}}/>
 <button className="ai-wide" disabled={!canManage||busy||saving||lesson.trim().length<3||(verdict!=='rejected'&&!response.trim())} onClick={()=>void save({training_action:'capture',verdict,lesson,reusable_response:reusable})}>{saving?'Menyimpan…':'Simpan contoh latihan'}</button>
 <details><summary>Rekod latihan chat ini ({examples.length})</summary>{examples.map(e=><article className="ai-training-example" key={e.id}><div><strong>{verdicts[e.verdict]}</strong><span>{e.state}</span></div><p>{e.lesson}</p><details><summary>Cadangan asal & pembetulan</summary><p>Asal: {e.original_response||'—'}</p><p>Pembetulan: {e.corrected_response||'—'}</p></details>{e.reusable_response&&<p className="ai-sop-example">SOP umum: {e.reusable_response}</p>}<small>{e.created_by} · {new Date(e.created_at).toLocaleDateString('ms-MY')} · v{e.version}</small>{canTrain&&<div className="ai-button-row">{e.state!=='approved'&&e.reusable_response&&<button disabled={busy||saving} onClick={()=>void save({training_action:'approve',training_id:e.id,training_version:e.version})}>Luluskan SOP umum</button>}{e.state!=='rejected'&&<button disabled={busy||saving} onClick={()=>void save({training_action:'reject',training_id:e.id,training_version:e.version})}>{e.state==='approved'?'Nyahaktif SOP':'Tolak contoh'}</button>}</div>}</article>)}{!examples.length&&<p className="ai-muted">Belum ada contoh disimpan untuk chat ini.</p>}</details>
 <details><summary>SOP diluluskan · {library.length}</summary><p className="ai-muted">Padanan channel dan kategori sahaja. Semak kesesuaian sebelum gunakan; tiada fakta pelanggan lain dimasukkan automatik.</p>{library.map(e=><article className="ai-training-example" key={e.id}><p>{e.lesson}</p><p className="ai-sop-example">{e.reusable_response}</p><button disabled={!canManage||busy||saving} onClick={()=>onUse(e.reusable_response)}>Gunakan sebagai draf</button></article>)}</details>
 </section>;
}
