import { useRef, useState } from 'react';
type Data=Record<string,any>;
type Props={row:Data;disabled:boolean;canManage:boolean;canCreate:boolean;canViewDrafts:boolean;onBind:(id:string,kind:string)=>Promise<void>;onCreate:()=>void;onDrafts:()=>void;onReply:()=>void;onResolve:()=>void};
export default function CaseSummary({row,disabled,canManage,canCreate,canViewDrafts,onBind,onCreate,onDrafts,onReply,onResolve}:Props){
 const ctx=row.context||{},info=row.analysis.case||{};
 const bindingPanel=useRef<HTMLDetailsElement>(null);
 const needsOrder=['shipping','payment','complaint'].includes(row.analysis.intent)||/shopee|order/i.test(info.request||'');
 const orders=[...(ctx.orders||[]).map((o:Data)=>({...o,kind:'icetak',reference:o.order_no})),...(ctx.marketplace_orders||[]).map((o:Data)=>({...o,kind:'shopee',reference:o.order_sn}))];
 const [choice,setChoice]=useState(info.order?`${info.order.kind}:${info.order.id}`:''),[confirm,setConfirm]=useState(false),[error,setError]=useState('');
 const save=async()=>{const order=orders.find(o=>`${o.kind}:${o.id}`===choice);setError('');try{await onBind(order?.id||'',order?.kind||'');setConfirm(false);}catch(e){setError((e as Error).message);}};
 const order=info.order;
 const orderUrl=order?.kind==='icetak'?`?admin=v2&order=${encodeURIComponent(order.reference)}`:order?`?admin=v2&view=marketplace-orders&marketplace_q=${encodeURIComponent(order.reference)}`:null;
 return <section className="ai-case-summary" aria-label="Ringkasan kes"><div className="ai-section-title"><h3>2 · Tindakan sekarang</h3><span className="ai-confidence">{info.binding_current?'Order disahkan':'Semak order'}</span></div><p className="ai-case-request">{info.request||row.analysis.summary}</p>
 <div className="ai-next-action"><strong>{info.title||'Semak kehendak pelanggan'}</strong><p>{info.next||'Baca mesej terkini dan semak balasan.'}</p>
 {row.analysis.acknowledgement&&!row.analysis.workflow?.decision?<button className="ai-primary ai-wide" disabled={disabled||!canManage} onClick={onResolve}>Semak & tandakan selesai</button>:row.analysis.workflow?.target==='draft'&&canViewDrafts?<button className="ai-primary ai-wide" disabled={disabled} onClick={onDrafts}>Semak draft & follow-up →</button>:orderUrl?<a className="ai-button ai-primary ai-wide" href={orderUrl} target="_blank" rel="noopener noreferrer">Semak order disahkan ↗</a>:needsOrder&&orders.length?<button className="ai-primary ai-wide" disabled={disabled} onClick={()=>{if(bindingPanel.current){bindingPanel.current.open=true;bindingPanel.current.scrollIntoView({block:'nearest'});}}}>Semak order berkaitan ({orders.length}) →</button>:info.active_draft_count&&canViewDrafts?<button className="ai-primary ai-wide" disabled={disabled} onClick={onDrafts}>Semak draft pelanggan ({info.active_draft_count}) →</button>:<button className="ai-primary ai-wide" disabled={disabled} onClick={onReply}>Semak cadangan balasan ↓</button>}
 </div><dl><dt>Sudah diketahui</dt><dd>{info.facts?.length?<ul>{info.facts.map((f:string)=><li key={f}>{f}</li>)}</ul>:'Belum ada fakta order disahkan untuk kes ini.'}</dd><dt>Masih perlu semakan</dt><dd>{info.missing?.length?<ul>{info.missing.map((f:string)=><li key={f}>{f}</li>)}</ul>:'Semak kesesuaian balasan sebelum hantar.'}</dd></dl>
 <details ref={bindingPanel}><summary>{info.binding_current?'Tukar / buang padanan order':'Sahkan order yang dibincangkan'}</summary><p className="ai-muted">Padanan untuk mesej dan session semasa. Mesej pelanggan baharu memerlukan semakan semula. Status order tidak berubah.</p><label htmlFor="ai-case-order">Order pelanggan</label><select id="ai-case-order" value={choice} disabled={disabled||!canManage||ctx.identity_status==='ambiguous'} onChange={e=>{setChoice(e.target.value);setConfirm(false);}}><option value="">Tiada order / buang padanan</option>{orders.map(o=><option key={`${o.kind}:${o.id}`} value={`${o.kind}:${o.id}`}>{o.reference} · {o.current_status||o.status} · {o.kind}</option>)}</select><button className="ai-wide" disabled={disabled||!canManage||ctx.identity_status==='ambiguous'} onClick={()=>setConfirm(true)}>Semak padanan</button>{confirm&&<div className="ai-case-confirm"><p>Sahkan {orders.find(o=>`${o.kind}:${o.id}`===choice)?.reference||'tiada order'} untuk pertanyaan semasa?</p><div className="ai-button-row"><button disabled={disabled} onClick={()=>setConfirm(false)}>Batal</button><button disabled={disabled} onClick={()=>void save()}>Sahkan padanan</button></div></div>}{error&&<p role="alert" className="ai-error">{error}</p>}</details>
 <details><summary>Pilihan lain · draft / order baharu</summary><div className="ai-case-actions">{orderUrl&&<a className="ai-button" href={orderUrl} target="_blank" rel="noopener noreferrer">Buka order, bayaran & tracking ↗</a>}{canViewDrafts&&<button disabled={disabled} onClick={onDrafts}>Semak draft pelanggan{info.active_draft_count?` (${info.active_draft_count})`:''}</button>}{canCreate&&<button disabled={disabled||ctx.identity_status==='ambiguous'||!ctx.phone} onClick={onCreate}>Sediakan draft baharu →</button>}</div><small className="ai-muted">Composer menerima nama dan telefon sahaja. Semak draft sedia ada dahulu; tiada order atau bayaran dibuat automatik.</small></details>
 </section>;
}
