import { useEffect, useRef, useState } from 'react';
import { supabase } from '../../lib/supabase';
import './KnowledgeTab.css';
type Data=Record<string,any>;
const blank=()=>({title:'',answer:'',category:'Umum',keywords:'',aliases:'',source:'',review_note:'',product_scope:'',channels:['whatsapp','shopee']});
export async function knowledgeApi(body:Data){
 const {data,error}=await supabase.functions.invoke('admin-ai-knowledge',{body});
 if(error){let message=error.message;try{message=(await error.context?.json())?.error||message;}catch{}throw Error(message);}
 if(!data?.ok)throw Error(data?.error||'Permintaan gagal');return data;
}
export default function KnowledgeTab({api=knowledgeApi,onDirtyChange=()=>{},onBusyChange=()=>{}}:{api?:(body:Data)=>Promise<Data>;onDirtyChange?:(dirty:boolean)=>void;onBusyChange?:(busy:boolean)=>void}){
 const [rows,setRows]=useState<Data[]>([]),[styles,setStyles]=useState<Data[]>([]),[canManage,setCanManage]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);
 const [error,setError]=useState(''),[notice,setNotice]=useState(''),[search,setSearch]=useState(''),[query,setQuery]=useState(''),[status,setStatus]=useState(''),[offset,setOffset]=useState(0),[more,setMore]=useState(false);
 const [selected,setSelected]=useState<Data|null>(null),[form,setForm]=useState<Data>(blank),[dirty,setDirty]=useState(false),[events,setEvents]=useState<Data[]>([]);
 const [question,setQuestion]=useState(''),[context,setContext]=useState(''),[channel,setChannel]=useState('whatsapp'),[test,setTest]=useState<Data|null>(null),[testing,setTesting]=useState(false);
 const seq=useRef(0),testSeq=useRef(0),editor=useRef<HTMLDivElement>(null),articleList=useRef<HTMLDivElement>(null);
 useEffect(()=>{onDirtyChange(dirty);},[dirty,onDirtyChange]);
 useEffect(()=>{onBusyChange(busy);},[busy,onBusyChange]);
 useEffect(()=>{if(!dirty)return;const fn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',fn);return()=>window.removeEventListener('beforeunload',fn);},[dirty]);
 const load=async(append=false)=>{const request=++seq.current;setLoading(true);setError('');try{const d=await api({action:'list',search:query,status,offset:append?offset:0});if(request!==seq.current)return;setRows(old=>append?[...old,...d.rows]:d.rows);if(!append&&articleList.current)articleList.current.scrollTop=0;setStyles(d.styles);setCanManage(d.can_manage);setMore(d.has_more);setOffset((append?offset:0)+d.rows.length);}catch(e){if(request===seq.current)setError((e as Error).message);}finally{if(request===seq.current)setLoading(false);}};
 useEffect(()=>{void load();return()=>{seq.current++;};},[query,status]);
 const discard=()=>!dirty||window.confirm('Draf belum disimpan. Tinggalkan perubahan?');
 const choose=(row:Data|null)=>{if(busy||!discard())return;setSelected(row);setForm(row?structuredClone(row.draft):blank());setDirty(false);setNotice('');setEvents([]);setError('');if(window.innerWidth<900)setTimeout(()=>editor.current?.scrollIntoView({behavior:'smooth',block:'start'}),0);};
 const change=(key:string,value:unknown)=>{setForm(old=>({...old,[key]:value}));setDirty(true);};
 const save=async(action:string)=>{if(busy)return;setBusy(true);setError('');setNotice('');try{const d=await api({action,id:selected?.id,version:selected?.version,draft:form});setSelected(d.row);setForm(structuredClone(d.row.draft));setDirty(false);setNotice(action==='publish'?'Diterbitkan — tersedia untuk suggestion Inbox.':action==='unpublish'?'Artikel ditarik daripada suggestion.':'Draf disimpan. Terbitkan untuk digunakan oleh AI.');await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const history=async()=>{if(!selected)return;setBusy(true);try{setEvents((await api({action:'history',id:selected.id})).events);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const style=async(s:Data,reset=false)=>{if(reset&&!window.confirm('Padam gaya yang dipelajari untuk saluran ini? Knowledge kekal tersedia.'))return;setBusy(true);setError('');try{await api({action:reset?'reset_style':'style',channel:s.channel,enabled:!s.enabled});await load();setNotice(reset?'Gaya kembali kepada bahasa formal standard.':'Tetapan pembelajaran dikemas kini.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const runTest=async()=>{const request=++testSeq.current;setTesting(true);setError('');setTest(null);try{const result=await api({action:'test',text:question,context,channel});if(request===testSeq.current)setTest(result);}catch(e){if(request===testSeq.current)setError((e as Error).message);}finally{if(request===testSeq.current)setTesting(false);}};
 return <section className="kb-home" aria-label="Knowledge AI">
  <header className="kb-heading"><div><span className="kb-eyebrow">RUJUKAN BALASAN</span><h1>Knowledge</h1><p>FAQ, maklumat produk dan gaya bahasa untuk AI Dashboard & Unified Inbox.</p></div><span className="kb-live">● Linked ke suggestion</span></header>
  {error&&<div className="kb-error" role="alert">{error}</div>}{notice&&<div className="kb-notice" role="status">{notice}</div>}
  <div className="kb-layout"><aside className="kb-library">
   <div className="kb-library-head"><h2>Artikel</h2>{canManage&&<button onClick={()=>choose(null)} disabled={busy}>+ Artikel baharu</button>}</div>
   <form className="kb-filters" onSubmit={e=>{e.preventDefault();setQuery(search);}}><input aria-label="Cari artikel" placeholder="Cari FAQ atau produk…" value={search} onChange={e=>setSearch(e.target.value)}/><button disabled={loading}>Cari</button><select aria-label="Status artikel" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Semua status</option><option value="published">Diterbitkan</option><option value="draft">Draf</option></select></form>
   <div ref={articleList} className="kb-articles" aria-busy={loading}>{rows.map(row=><button key={row.id} className={`kb-article ${selected?.id===row.id?'selected':''}`} onClick={()=>choose(row)} disabled={busy}><span><small>{row.draft.category}</small><b>{row.draft.title}</b><span className="kb-excerpt">{row.draft.answer}</span></span><em className={row.published?'published':''}>{row.published?`Live v${row.published_version}`:'Draf'}{row.published&&JSON.stringify(row.draft)!==JSON.stringify(row.published)?' · ada perubahan':''}</em></button>)}</div>
   {loading&&<p role="status">Memuatkan artikel…</p>}{!loading&&!rows.length&&<p>Tiada artikel untuk carian ini.</p>}{more&&<button className="kb-more" disabled={loading} onClick={()=>load(true)}>Muat lagi</button>}
  </aside><div className="kb-editor" ref={editor}>
   <div className="kb-editor-heading"><div><h2>{selected?'Sunting artikel':'Artikel baharu'}</h2><p>{selected?`Draf v${selected.version} · ${selected.updated_by}`:'Simpan sebagai draf, kemudian terbitkan.'}</p></div>{dirty&&<span className="kb-unsaved">Belum disimpan</span>}</div>
   <fieldset disabled={!canManage||busy}><label>Tajuk / soalan<input value={form.title} maxLength={200} onChange={e=>change('title',e.target.value)}/></label><div className="kb-field-row"><label>Kategori<input value={form.category} maxLength={100} onChange={e=>change('category',e.target.value)}/></label><label>Produk berkaitan<input value={form.product_scope} maxLength={300} placeholder="Contoh: edible, icing" onChange={e=>change('product_scope',e.target.value)}/></label></div>
   <label>Jawapan rasmi<textarea rows={7} value={form.answer} maxLength={4000} onChange={e=>change('answer',e.target.value)}/></label>
   <div className="kb-field-row"><label>Kata kunci<input value={form.keywords} maxLength={1200} placeholder="bahan, material, boleh makan" onChange={e=>change('keywords',e.target.value)}/></label><label>Sumber rujukan<input value={form.source} maxLength={1000} placeholder="Katalog produk / SOP pemilik" onChange={e=>change('source',e.target.value)}/></label></div>
   <details><summary>Padanan soalan & nota semakan</summary><label>Soalan alternatif · satu setiap baris<textarea rows={3} value={form.aliases} maxLength={2000} onChange={e=>change('aliases',e.target.value)}/></label><label>Nota yang perlu diselesaikan sebelum terbit<textarea rows={3} value={form.review_note} maxLength={2000} onChange={e=>change('review_note',e.target.value)}/></label></details>
   <div className="kb-channels">{['whatsapp','shopee'].map(c=><label key={c}><input type="checkbox" checked={form.channels.includes(c)} onChange={e=>change('channels',e.target.checked?[...form.channels,c]:form.channels.filter((v:string)=>v!==c))}/>{c==='whatsapp'?'WhatsApp':'Shopee'}</label>)}</div>
   <div className="kb-actions"><button className="kb-primary" disabled={!dirty||!form.title||!form.answer||!form.source} onClick={()=>save('save')}>Simpan draf</button><button disabled={!selected||dirty||!!form.review_note} onClick={()=>save('publish')}>Terbitkan</button>{selected?.published&&<button disabled={dirty} onClick={()=>save('unpublish')}>Tarik penerbitan</button>}</div></fieldset>
   {!canManage&&!loading&&<p className="kb-hint">Akses baca sahaja. Owner boleh mengurus Knowledge.</p>}
   <p className="kb-hint">AI menggunakan versi diterbitkan. Status order dan bayaran sentiasa dirujuk daripada rekod order sebenar.</p>
   {selected&&<><button disabled={busy} onClick={history}>Lihat sejarah versi</button>{events.length>0&&<ul className="kb-history">{events.map(e=><li key={e.id}><b>v{e.version} · {e.action}</b> — {e.actor}<small>{new Date(e.created_at).toLocaleString('ms-MY',{timeZone:'Asia/Kuala_Lumpur'})}</small><details><summary>Kandungan versi</summary><p>{e.snapshot.draft?.answer}</p></details></li>)}</ul>}</>}
  </div></div>
  <div className="kb-bottom"><section className="kb-panel"><h2>Pembelajaran gaya</h2><p>Belajar selepas balasan admin berjaya dihantar. Balasan yang disalin tanpa perubahan dan mesej automatik tidak dijadikan latihan.</p>{styles.map(s=><div className="kb-style" key={s.channel}><div><b>{s.channel==='whatsapp'?'WhatsApp':'Shopee'}</b><small>{s.samples} balasan dipelajari · gaya v{s.version}</small><span>{Object.values(s.preferences||{}).filter(v=>v!=='none').join(' · ')||'Bahasa formal standard'}</span></div><button aria-pressed={s.enabled} disabled={!canManage||busy} onClick={()=>style(s)}>{s.enabled?'Aktif':'Dimatikan'}</button><button disabled={!canManage||busy} onClick={()=>style(s,true)}>Reset</button></div>)}<p className="kb-hint">Corak gaya digunakan selepas 3 contoh sepadan. Harga, stok dan polisi tidak diubah daripada chat. Ayat FAQ yang mengekalkan fakta boleh dipelajari sebagai variasi.</p><button disabled={busy||loading} onClick={()=>load()}>Muat semula statistik</button></section>
  <section className="kb-panel"><h2>Uji suggestion</h2><label>Soalan pelanggan<textarea rows={3} maxLength={1000} value={question} onChange={e=>{setQuestion(e.target.value);setTest(null);testSeq.current++;}} placeholder="Edible image boleh makan ke?"/></label><label>Konteks produk · jika perlu<input value={context} maxLength={1000} onChange={e=>{setContext(e.target.value);setTest(null);testSeq.current++;}} placeholder="Contoh: pelanggan bertanya tentang edible"/></label><div className="kb-actions"><select aria-label="Saluran ujian" value={channel} onChange={e=>{setChannel(e.target.value);setTest(null);testSeq.current++;}}><option value="whatsapp">WhatsApp</option><option value="shopee">Shopee</option></select><button className="kb-primary" onClick={runTest} disabled={!question.trim()||testing}>{testing?'Menyemak…':'Uji soalan'}</button></div>{test&&<div className="kb-test" role="status"><p>{test.text||'Tiada padanan yang cukup jelas. AI akan guna SOP dan konteks order dalam Inbox.'}</p>{test.sources?.map((s:Data)=><small key={s.id}>Rujukan: {s.title} · v{s.version}<br/>{s.source}</small>)}<small>{test.note}</small></div>}</section></div>
 </section>;
}
