import { useCallback, useEffect, useRef, useState } from 'react';
import OrderProgress from './OrderProgress';
type Data = Record<string,any>;
const labels:Record<string,string>={all:'Semua kerja order',due:'Deadline hari ini / lewat',review:'Review artwork',design:'Design',production:'Printing / production',ready:'Packing / pos',pickup:'Pickup',payment:'Bayaran',unknown:'Semak status',issue:'Masalah courier'};
const date=(v:unknown)=>v?new Date(String(v)).toLocaleString('ms-MY',{timeZone:'Asia/Kuala_Lumpur',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}):'—';
export default function OrderWorkQueue({call,onOpenOrder,onFindChat,paused=false}:{call:(b:Data)=>Promise<Data>;onOpenOrder:(ref:string)=>void;onFindChat:(channel:string,search:string)=>void;paused?:boolean}){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[filter,setFilter]=useState('all'),[count,setCount]=useState(4),[copied,setCopied]=useState('');
 const seq=useRef(0),pausedRef=useRef(paused);pausedRef.current=paused;
 const load=useCallback(async()=>{const id=++seq.current;setLoading(true);try{const next=await call({action:'work'});if(id!==seq.current)return;setData(next);setError('');}catch(e){if(id===seq.current)setError((e as Error).message);}finally{if(id===seq.current)setLoading(false);}},[call]);
 useEffect(()=>{void load();const timer=window.setInterval(()=>{if(!pausedRef.current&&!document.hidden)void load();},60000);return()=>{seq.current++;window.clearInterval(timer);};},[load]);
 const rows:Data[]=data?.rows||[];
 const matches=(o:Data,k:string)=>k==='all'||(k==='due'?o.work.due:o.work.key===k);
 const visible=rows.filter(o=>matches(o,filter));
 return <section className="ai-global-work" aria-label="Kerja order seluruh sistem"><div className="ai-orders-title"><div><h2>Kerja order seluruh sistem</h2><p>Keutamaan daripada order, ClickUp, bayaran dan shipment — walaupun customer tiada chat baharu.</p></div><button disabled={loading||paused} onClick={()=>void load()}>{loading?'Menyemak…':'↻ Semak status order'}</button></div>
 {error&&<p role="alert" className="ai-error">Semakan order gagal: {error}. {data?'Data sebelumnya dikekalkan.':'Tiada status dianggap selesai.'}</p>}
 <div className="ai-order-tabs" role="group" aria-label="Tapis kerja order">{Object.entries(labels).filter(([k])=>k==='all'||rows.some(o=>matches(o,k))).map(([k,label])=><button key={k} aria-pressed={filter===k} onClick={()=>{setFilter(k);setCount(4);}}>{label} <b>{rows.filter(o=>matches(o,k)).length}</b></button>)}</div>
 {data&&<p className="ai-muted">{data.has_more?'Liputan terhad kepada 2,000 order sumber; jumlah ini belum menyeluruh.':`${data.active_total} order masih ada kerja · dikira sebelum paparan ditapis.`} Disemak {date(data.checked_at)}.<br/>Webhook ClickUp terakhir {date(data.sync?.latest_event_at)} · {data.sync?.unlinked||0} task belum dipadankan / bercanggah. Snapshot lama perlu disemak di ClickUp jika status diragui.</p>}
 <div className="ai-global-work-grid">{visible.slice(0,count).map(o=><article className={`ai-order-tile ${o.work.due?'ai-order-due':''}`} key={`${o.kind}:${o.id}`}><div className="ai-order-tile-heading"><strong>{o.work.due?'⚡ Deadline hari ini / lewat':labels[o.work.key]}</strong><span className={`ai-channel ${o.kind}`}>{o.kind==='shopee'?'Shopee':'iCetak'}</span></div><h3>{o.reference}</h3><p>{o.customer_name||'Pelanggan'} · {o.status}<br/>{o.deadline&&<small>Deadline: {date(o.deadline)}</small>}</p><OrderProgress work={o.work} compact/><small className="ai-block">Sumber order dikemas kini {date(o.source_updated_at)}</small><div className="ai-button-row">{o.kind==='icetak'?<button disabled={paused} onClick={()=>onOpenOrder(o.reference)}>Buka order ↗</button>:<a className="ai-button" href={`?admin=v2&view=marketplace-orders&marketplace_q=${encodeURIComponent(o.reference)}`} target="_blank" rel="noopener noreferrer">Buka order ↗</a>}<button disabled={paused||!o.chat_search} onClick={()=>onFindChat(o.kind==='shopee'?'shopee':'whatsapp',o.chat_search)}>Cari chat</button><button onClick={async()=>{try{await navigator.clipboard.writeText(o.reference);setCopied(o.reference);}catch{setCopied('Gagal salin');}}}>Salin ID</button></div></article>)}</div>
 {!loading&&!error&&!visible.length&&<p className="ai-muted">Tiada kerja dalam kategori ini. Pertanyaan customer masih boleh muncul dalam senarai chat di bawah.</p>}
 {visible.length>count&&<button onClick={()=>setCount(n=>n+16)}>Tunjuk lagi ({visible.length-count})</button>}{copied&&<small role="status">{copied==='Gagal salin'?copied:`Disalin: ${copied}`}</small>}
 </section>;
}
