from pathlib import Path

path = Path('icetak-admin/src/pages/Orders.tsx')
s = path.read_text()

old = "type PickupAutoSettings = { auto_send_enabled?: boolean; delay_minutes?: number; provider_name?: string; provider_ready?: boolean; template_name?: string; auto_send_activated_at?: string | null; pending?: number; sent?: number; failed?: number };\n"
new = old + "type CustomerProfile = { customer_id?: string | null; customer_master_id?: string | null; name?: string; phone?: string; locked?: boolean; admin_name_override?: string | null; admin_name_updated_at?: string | null; admin_name_updated_by?: string | null; master_display_name?: string | null; source?: string | null };\n"
assert old in s
s = s.replace(old, new, 1)

old = "  const [deliveryMethod, setDeliveryMethod] = useState<'pickup' | 'spx' | 'jnt'>('spx');\n  const [deliveryFee, setDeliveryFee] = useState(0);\n"
new = old + "  const [customerProfile, setCustomerProfile] = useState<CustomerProfile | null>(null);\n  const [customerProfileLoading, setCustomerProfileLoading] = useState(false);\n  const [customerProfileEditing, setCustomerProfileEditing] = useState(false);\n  const [customerProfileName, setCustomerProfileName] = useState('');\n  const [customerProfileSaving, setCustomerProfileSaving] = useState(false);\n"
assert old in s
s = s.replace(old, new, 1)

old = "  const canEdit = permissions.includes('edit_order'); const canVerify = permissions.includes('verify_payments'); const canApprove = permissions.includes('approve_production');\n"
new = "  const canEdit = permissions.includes('edit_order'); const canVerify = permissions.includes('verify_payments'); const canApprove = permissions.includes('approve_production');\n  const loadCustomerProfile = useCallback(async () => {\n    if (!order?.dbId) { setCustomerProfile(null); return; }\n    setCustomerProfileLoading(true);\n    const { data, error } = await supabase.rpc('icetak_admin_customer_profile', { p_order_db_id: order.dbId });\n    setCustomerProfileLoading(false);\n    if (error) { setLocalError(error.message); return; }\n    const profile = (data || null) as CustomerProfile | null;\n    setCustomerProfile(profile);\n    setCustomerProfileName(String(profile?.name || order.customerName || ''));\n  }, [order?.dbId, order?.customerName]);\n  useEffect(() => { void loadCustomerProfile(); setCustomerProfileEditing(false); }, [loadCustomerProfile]);\n  const saveCustomerProfile = async () => {\n    if (!order || !customerProfileName.trim()) return;\n    setCustomerProfileSaving(true); setLocalError(null);\n    const { data, error } = await supabase.rpc('icetak_admin_customer_profile_update', { p_order_db_id: order.dbId, p_display_name: customerProfileName.trim(), p_clear_override: false });\n    setCustomerProfileSaving(false);\n    if (error) { setLocalError(error.message); return; }\n    setCustomerProfile((data || null) as CustomerProfile | null); setCustomerProfileEditing(false); await onReload();\n  };\n  const clearCustomerProfileLock = async () => {\n    if (!order || !window.confirm('Buang Admin Preferred Name? Order akan datang boleh guna nama WhatsApp semula.')) return;\n    setCustomerProfileSaving(true); setLocalError(null);\n    const { data, error } = await supabase.rpc('icetak_admin_customer_profile_update', { p_order_db_id: order.dbId, p_display_name: '', p_clear_override: true });\n    setCustomerProfileSaving(false);\n    if (error) { setLocalError(error.message); return; }\n    setCustomerProfile((data || null) as CustomerProfile | null); setCustomerProfileEditing(false); await onReload();\n  };\n"
assert old in s
s = s.replace(old, new, 1)

old = '<DrawerCard title="Customer"><KV k="Name" v={order.customerName || \'—\'} /><KV k="Phone" v={order.customerPhone ? <a className="erp-inline-link" href={`https://wa.me/${digits(order.customerPhone)}`} target="_blank" rel="noreferrer">{order.customerPhone}</a> : \'—\'} /><KV k="Created" v={formatDateTime(order.createdAt)} /><KV k="Updated" v={formatDateTime(order.updatedAt)} /></DrawerCard>'
new = '''<DrawerCard title="Customer"><KV k="Name" v={order.customerName || '—'} /><KV k="Phone" v={order.customerPhone ? <a className="erp-inline-link" href={`https://wa.me/${digits(order.customerPhone)}`} target="_blank" rel="noreferrer">{order.customerPhone}</a> : '—'} />{customerProfile?.locked && <div style={{ margin: '8px 0' }}><span className="erp-status-pill success">ADMIN NAME LOCKED</span></div>}{customerProfileLoading ? <p className="cell-sub">Loading customer profile…</p> : customerProfileEditing ? <div style={{ marginTop: 10 }}><FilterField label="Preferred Customer Name"><input autoFocus maxLength={200} disabled={customerProfileSaving} value={customerProfileName} onChange={(e) => setCustomerProfileName(e.target.value)} /></FilterField><p className="cell-sub">Nama ini jadi nama utama customer. WhatsApp display name tak boleh overwrite selepas disimpan.</p><div className="erp-card-actions"><button className="btn btn-primary btn-sm" disabled={customerProfileSaving || !customerProfileName.trim()} onClick={() => void saveCustomerProfile()}>{customerProfileSaving ? 'Saving…' : 'Save Preferred Name'}</button><button className="btn btn-outline btn-sm" disabled={customerProfileSaving} onClick={() => { setCustomerProfileEditing(false); setCustomerProfileName(String(customerProfile?.name || order.customerName || '')); }}>Cancel</button></div></div> : <div className="erp-card-actions" style={{ marginTop: 8 }}>{canEdit && <button className="btn btn-outline btn-sm" onClick={() => { setCustomerProfileName(String(customerProfile?.name || order.customerName || '')); setCustomerProfileEditing(true); }}>Edit Profile</button>}{canEdit && customerProfile?.locked && <button className="btn btn-ghost btn-sm" disabled={customerProfileSaving} onClick={() => void clearCustomerProfileLock()}>Use WhatsApp Name Again</button>}</div>}{customerProfile?.locked && <p className="cell-sub">Preferred name disimpan oleh {customerProfile.admin_name_updated_by || 'admin'}{customerProfile.admin_name_updated_at ? ` · ${formatDateTime(customerProfile.admin_name_updated_at)}` : ''}. Future AI orders akan guna nama ini.</p>}<KV k="Created" v={formatDateTime(order.createdAt)} /><KV k="Updated" v={formatDateTime(order.updatedAt)} /></DrawerCard>'''
assert old in s
s = s.replace(old, new, 1)

path.write_text(s)
print('patched', path)
