from pathlib import Path

path = Path('icetak-admin/src/pages/Orders.tsx')
s = path.read_text()

old = "  const [dateNeed, setDateNeed] = useState(''); const [remark, setRemark] = useState(''); const [items, setItems] = useState<OrderItem[]>([]); const [saving, setSaving] = useState(false); const [localError, setLocalError] = useState<string | null>(null);\n  useEffect(() => { if (!order) return; setDateNeed(String(order.dateNeed || '').slice(0, 10)); setRemark(order.adminRemark || ''); setItems((detail?.items || []).map((i) => ({ ...i, qty: Number(i.qty || 1), price: Number(i.price || 0), customText: i.customText || '', previewUrl: i.previewUrl || '' }))); }, [detail, order]);\n  const canEdit = permissions.includes('edit_order'); const canVerify = permissions.includes('verify_payments'); const canApprove = permissions.includes('approve_production');\n  const save = async () => {\n    if (!order) return; setSaving(true); setLocalError(null);\n    const { error } = await supabase.rpc('icetak_admin_order_update', { p_payload: { order_db_id: order.dbId, date_need: dateNeed, admin_remark: remark, items: items.map((i) => ({ id: i.id, qty: i.qty, price: i.price, custom_text: i.customText, design_preview_url: i.previewUrl })) } });\n    setSaving(false); if (error) { setLocalError(error.message); return; } await onReload();\n  };"
new = "  const [dateNeed, setDateNeed] = useState(''); const [remark, setRemark] = useState(''); const [items, setItems] = useState<OrderItem[]>([]); const [saving, setSaving] = useState(false); const [localError, setLocalError] = useState<string | null>(null);\n  const [deliveryMethod, setDeliveryMethod] = useState<'pickup' | 'spx' | 'jnt'>('spx');\n  const [deliveryFee, setDeliveryFee] = useState(0);\n  useEffect(() => {\n    if (!order) return;\n    const rawDelivery = norm(order.delivery || order.courier);\n    const method: 'pickup' | 'spx' | 'jnt' = rawDelivery.includes('pickup') ? 'pickup' : (rawDelivery.includes('jnt') || rawDelivery.includes('j&t')) ? 'jnt' : 'spx';\n    setDateNeed(String(order.dateNeed || '').slice(0, 10));\n    setRemark(order.adminRemark || '');\n    setDeliveryMethod(method);\n    setDeliveryFee(method === 'pickup' ? 0 : Math.max(0, Number(order.deliveryFee || 0)));\n    setItems((detail?.items || []).map((i) => ({ ...i, qty: Number(i.qty || 1), price: Number(i.price || 0), customText: i.customText || '', previewUrl: i.previewUrl || '' })));\n  }, [detail, order]);\n  const canEdit = permissions.includes('edit_order'); const canVerify = permissions.includes('verify_payments'); const canApprove = permissions.includes('approve_production');\n  const deliveryLocked = Boolean(order?.tracking || ['picked_up','shipped','in_transit','out_for_delivery','delivered'].includes(norm(order?.shipmentStatusGroup)) || ['picked_up','shipped','in_transit','out_for_delivery','delivered'].includes(norm(order?.fulfillmentStage)));\n  const itemSubtotal = items.reduce((sum, item) => sum + Math.max(1, Number(item.qty || 1)) * Math.max(0, Number(item.price || 0)), 0);\n  const effectiveDeliveryFee = deliveryMethod === 'pickup' ? 0 : Math.max(0, Number(deliveryFee || 0));\n  const previewTotal = itemSubtotal + effectiveDeliveryFee;\n  const save = async () => {\n    if (!order) return; setSaving(true); setLocalError(null);\n    const payload: Record<string, unknown> = { order_db_id: order.dbId, date_need: dateNeed, admin_remark: remark, delivery_fee: effectiveDeliveryFee, items: items.map((i) => ({ id: i.id, qty: i.qty, price: i.price, custom_text: i.customText, design_preview_url: i.previewUrl })) };\n    if (!deliveryLocked) payload.delivery_method = deliveryMethod;\n    const { error } = await supabase.rpc('icetak_admin_order_update', { p_payload: payload });\n    setSaving(false); if (error) { setLocalError(error.message); return; } await onReload();\n  };"
if old not in s:
    raise SystemExit('state/save anchor not found')
s = s.replace(old, new, 1)

old_card = "<DrawerCard title=\"Admin Edit\"><FilterField label=\"Date Need\"><input type=\"date\" disabled={!canEdit} value={dateNeed} onChange={(e) => setDateNeed(e.target.value)} /></FilterField><FilterField label=\"Admin Remark\"><textarea rows={4} disabled={!canEdit} value={remark} onChange={(e) => setRemark(e.target.value)} /></FilterField>{canEdit && <button className=\"btn btn-primary btn-sm\" disabled={saving} onClick={() => void save()}>{saving ? 'Saving…' : 'Save Changes'}</button>}</DrawerCard>"
new_card = "<DrawerCard title=\"Admin Edit\"><FilterField label=\"Date Need\"><input type=\"date\" disabled={!canEdit} value={dateNeed} onChange={(e) => setDateNeed(e.target.value)} /></FilterField><FilterField label=\"Delivery / Courier\"><select disabled={!canEdit || deliveryLocked} value={deliveryMethod} onChange={(e) => { const value = e.target.value as 'pickup' | 'spx' | 'jnt'; setDeliveryMethod(value); if (value === 'pickup') setDeliveryFee(0); }}><option value=\"pickup\">Pickup</option><option value=\"spx\">SPX</option><option value=\"jnt\">J&amp;T</option></select></FilterField><FilterField label=\"Shipping Fee (RM)\"><input type=\"number\" min=\"0\" step=\"0.01\" disabled={!canEdit || deliveryMethod === 'pickup'} value={effectiveDeliveryFee} onChange={(e) => setDeliveryFee(Math.max(0, Number(e.target.value || 0)))} /></FilterField><div className=\"erp-kv\"><span>Order Total</span><b>{money(previewTotal)}</b></div><p className=\"cell-sub\">Item {money(itemSubtotal)} + Shipping {money(effectiveDeliveryFee)}. Payment transaction asal tidak diubah.</p>{deliveryLocked && <p className=\"cell-sub erp-text-danger\">Courier dikunci sebab tracking sudah dibuat. Shipping Fee masih boleh dibetulkan.</p>}<FilterField label=\"Admin Remark\"><textarea rows={4} disabled={!canEdit} value={remark} onChange={(e) => setRemark(e.target.value)} /></FilterField>{canEdit && <button className=\"btn btn-primary btn-sm\" disabled={saving} onClick={() => void save()}>{saving ? 'Saving…' : 'Save Changes'}</button>}</DrawerCard>"
if old_card not in s:
    raise SystemExit('Admin Edit card anchor not found')
s = s.replace(old_card, new_card, 1)

old_payment = "<DrawerCard title=\"Payment Summary\"><KV k=\"Status\" v={order.payment || '—'} /><KV k=\"Method\" v={order.paymentMethod || '—'} /><KV k=\"Total\" v={money(order.total)} />"
new_payment = "<DrawerCard title=\"Payment Summary\"><KV k=\"Status\" v={order.payment || '—'} /><KV k=\"Method\" v={order.paymentMethod || '—'} /><KV k=\"Shipping Fee\" v={money(order.deliveryFee)} /><KV k=\"Total\" v={money(order.total)} />"
if old_payment not in s:
    raise SystemExit('Payment summary anchor not found')
s = s.replace(old_payment, new_payment, 1)

path.write_text(s)
print('patched', path)
