// @ts-nocheck
import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
import { applyLearningRules, buildLearningPrompt, filterOrderEvidenceMessages } from '../_shared/ai-learning-engine.ts';
const U=Deno.env.get('SUPABASE_URL')||'',K=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'',db=createClient(U,K,{auth:{persistSession:false}});
const H={'content-type':'application/json','access-control-allow-origin':'*','access-control-allow-methods':'POST,OPTIONS','access-control-allow-headers':'content-type,x-order-draft-token','cache-control':'no-store'};
const out=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H}),t=(v:any)=>String(v??'').trim(),B=/^[A-Z]{2}\.\d+$/i;
const phone=(v:any)=>{const raw=t(v);if(!raw||B.test(raw))return'';let d=raw.replace(/\D/g,'');if(d.startsWith('0'))d='60'+d.slice(1);else if(d.startsWith('1'))d='60'+d;return/^601\d{8,9}$/.test(d)?d:''};
async function setting(k:string){const q=await db.from('private_runtime_settings').select('setting_value').eq('setting_key',k).maybeSingle();return t(q.data?.setting_value)}
async function auth(req:Request){const token=t(req.headers.get('x-order-draft-token'));return!!token&&token===await setting('qrpay_ai_worker_token')}
async function resolve(body:any){
  const id=t(body.conversation_id),inputPhone=phone(body.phone),inputBsuid=t(body.bsuid||body.user_id||body.recipient_bsuid||body.recipient),select='id,customer_id,last_message_at,customers(display_name,order_system_master_customer_id)';
  let conversation:any=null,identity:any=null;
  if(id){const q=await db.from('conversations').select(select).eq('id',id).eq('channel','whatsapp').maybeSingle();if(q.error)throw q.error;conversation=q.data}
  if(!conversation&&inputBsuid){const q=await db.from('customer_identities').select('customer_id,external_id,normalized_phone,username').eq('channel','whatsapp').eq('external_id',inputBsuid).maybeSingle();if(q.error)throw q.error;identity=q.data}
  if(!conversation&&!identity&&inputPhone){const q=await db.from('customer_identities').select('customer_id,external_id,normalized_phone,username').eq('channel','whatsapp').eq('normalized_phone',inputPhone).limit(1).maybeSingle();if(q.error)throw q.error;identity=q.data}
  if(!conversation&&identity?.customer_id){const q=await db.from('conversations').select(select).eq('channel','whatsapp').eq('customer_id',identity.customer_id).order('last_message_at',{ascending:false,nullsFirst:false}).limit(1).maybeSingle();if(q.error)throw q.error;conversation=q.data}
  if(!conversation)throw Error('WhatsApp conversation not found for phone or user ID');
  const identities=await db.from('customer_identities').select('external_id,normalized_phone,username').eq('customer_id',conversation.customer_id).eq('channel','whatsapp');if(identities.error)throw identities.error;
  identity=(identities.data||[]).find((x:any)=>inputBsuid&&x.external_id===inputBsuid)||(identities.data||[]).find((x:any)=>x.username||x.normalized_phone)||(identities.data||[])[0]||identity||{};
  const external=t(identity.external_id),bsuid=inputBsuid||(/^[A-Z]{2}\.(?:ENT\.)?[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/i.test(external)?external:'');
  return{...conversation,phone:phone(identity.normalized_phone)||inputPhone||null,bsuid:bsuid||null,username:t(identity.username||body.username)||null,customer_master_id:conversation.customers?.order_system_master_customer_id||null,name:conversation.customers?.display_name||'WhatsApp Customer'}
}
async function bridge(body:any){const url=await setting('qrpay_ai_order_bridge_url'),token=await setting('qrpay_ai_worker_token');if(!url||!token)throw Error('Order bridge config missing');const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json','x-qrpay-ai-token':token},body:JSON.stringify(body)}),j=await r.json().catch(()=>({}));if(!r.ok||j.ok===false)throw Error(j.error||`Bridge ${r.status}`);return j}
async function history(id:string,opened:string,cutoff:string){const q=await db.from('messages').select('id,direction,text_content,caption,message_type,media_url,provider_message_id,created_at,sent_at').eq('conversation_id',id).gt('created_at',opened).lte('created_at',cutoff).order('created_at').limit(220);if(q.error)throw q.error;return q.data||[]}
async function activeSellerSnippets(){const q=await db.from('quick_snippets').select('id,shortcut,title,message').eq('active',true);if(q.error){console.error('seller snippet filter',q.error);return[]}return q.data||[]}
const msgText=(m:any)=>t(m.text_content||m.caption);
function refs(ms:any[]){return ms.filter(m=>m.media_url||['image','document'].includes(m.message_type)).slice(-12).map(m=>({message_id:m.id,provider_message_id:m.provider_message_id,type:m.message_type,media_url:m.media_url||null,caption:msgText(m)||null,created_at:m.created_at}))}
const STATES=[['johor','Johor'],['kedah','Kedah'],['kelantan','Kelantan'],['melaka','Melaka'],['negeri sembilan','Negeri Sembilan'],['pahang','Pahang'],['perak','Perak'],['perlis','Perlis'],['pulau pinang','Pulau Pinang'],['penang','Pulau Pinang'],['sabah','Sabah'],['sarawak','Sarawak'],['selangor','Selangor'],['terengganu','Terengganu'],['kuala lumpur','Kuala Lumpur'],['putrajaya','Putrajaya'],['labuan','Labuan']];
const ADDR_CUE=/\b(no\.?|lot|pt|jalan|jln|lorong|taman|kampung|kg\.?|felda|bandar|persiaran|blok|block|apartment|pangsapuri|condo|residensi)\b/i;
function extractAddress(ms:any[]){const inbound=ms.filter(m=>m.direction==='inbound').map(m=>({text:msgText(m),at:new Date(m.created_at||m.sent_at||0).getTime()})).filter(x=>x.text);let best:any=null;for(let i=0;i<inbound.length;i++){const raw=inbound[i].text.trim();if(raw.length<8||raw.length>1200)continue;let score=0;if(/\b(alamat|address)\b/i.test(raw))score+=6;if(/\b\d{5}\b/.test(raw))score+=6;if(ADDR_CUE.test(raw))score+=3;if(STATES.some(([k])=>new RegExp(`\\b${k.replace(/ /g,'\\s+')}\\b`,'i').test(raw)))score+=2;if(/\b(rm|qrpay|duitnow|payment|bayar|total)\b/i.test(raw)&&!/\b(alamat|address)\b/i.test(raw)&&!/\b\d{5}\b/.test(raw))score-=5;if(score<5)continue;if(!best||score>best.score||(score===best.score&&inbound[i].at>best.at))best={raw,score,at:inbound[i].at};}if(!best)return{address_line1:'',postcode:'',city:'',state:'',source:'none'};const labeled=best.raw.match(/\b(?:alamat|address)\b\s*[:\-]?\s*([\s\S]+)/i);let cleaned=(labeled?.[1]||best.raw).trim();let lines=cleaned.split(/\n+/).map((x:string)=>x.trim()).filter(Boolean).filter((line:string)=>!/^\s*(?:tel|telefon|phone|hp|whatsapp)\s*[:\-]/i.test(line)&&!/^(?:\+?6?0?1\d[\d\s-]{7,})$/.test(line));if(lines.length>1&&!ADDR_CUE.test(lines[0])&&!/\b\d{5}\b/.test(lines[0])&&lines.slice(1).some((x:string)=>ADDR_CUE.test(x)||/\b\d{5}\b/.test(x)))lines=lines.slice(1);cleaned=lines.join('\n');const postcode=cleaned.match(/\b(\d{5})\b/)?.[1]||'';let state='';for(const [k,v] of STATES){if(new RegExp(`\\b${k.replace(/ /g,'\\s+')}\\b`,'i').test(cleaned)){state=v;break}}let city='';if(postcode){const escState=state?state.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'):'';const re=new RegExp(`\\b${postcode}\\s+([^\\n,]{2,40}?)(?:${escState?`\\s*,?\\s*${escState}`:''}|$|\\n)`,'i');const m=cleaned.match(re);if(m)city=t(m[1]).replace(/\s{2,}/g,' ')}return{address_line1:cleaned,postcode,city,state,source:'current_session_message'}}
function heuristic(ms:any[],conv:any){
  const readable=ms.map(m=>({direction:m.direction,text:msgText(m)})).filter(m=>m.text),all=readable.map(m=>m.text).join('\n'),lower=all.toLowerCase();
  let k='printed',title='Cake Topper';
  if(/edible|icing sheet/.test(lower)){k='edible';title='Edible Image'}else if(/acrylic|akrilik/.test(lower)){k='acrylic';title='Acrylic Cake Topper'}else if(/wafer/.test(lower)){k='wafer';title='Wafer Paper'}
  const sellerQuotes=readable.filter(m=>m.direction==='outbound'&&m.text.length<=240&&!/price\s*list|harga\s*panduan/i.test(m.text))
    .flatMap(m=>m.text.split(/\n+/))
    .filter(line=>!/\b(spx|j\s*&?\s*t|jnt|ninja(?:van)?|courier|shipping|postage|delivery|pos)\b/i.test(line));
  let price=0;for(const line of sellerQuotes){const match=line.match(/\brm\s*(\d+(?:\.\d{1,2})?)/i);if(match&&!/total/i.test(line))price=Number(match[1])}
  const customerText=readable.filter(m=>m.direction==='inbound').map(m=>m.text).join('\n');
  const qty=Number([...customerText.matchAll(/\b(\d{1,2})\s*(?:pcs?|set|unit)\b/gi)].at(-1)?.[1]||1);
  const dimension=[...customerText.matchAll(/\b(\d+(?:\.\d+)?)\s*[x×]\s*(\d+(?:\.\d+)?)\b/gi)].at(0);
  const explicitSize=[...customerText.matchAll(/\b(A[4-7]|\d+(?:\.\d+)?\s*(?:inch|in|cm))\b/gi)].at(-1)?.[1]||'';
  const size=explicitSize||(dimension?`${dimension[1]} inch`:'');
  const wording=[...customerText.matchAll(/(?:wording|tulisan|nama|name)\s*[:=-]\s*([^\n]{2,100})/gi)].at(-1)?.[1]||'';
  let delivery='unknown',delivery_fee=0;
  if(/\bspx\b/i.test(customerText)){delivery='spx';delivery_fee=4.5}else if(/\bj\s*&?\s*t\b|\bjnt\b/i.test(customerText)){delivery='jnt';delivery_fee=5.9}else if(/\bninja(?:van)?\b/i.test(customerText)){delivery='ninja';delivery_fee=6.9}else if(/pickup|ambil|self collect/i.test(customerText)){delivery='pickup'}
  const addr=extractAddress(ms);
  if(!addr.state&&/\bkl\b/i.test(addr.address_line1))addr.state='Kuala Lumpur';
  return{customer:{name:conv.name,phone:conv.phone,address_line1:addr.address_line1,postcode:addr.postcode,city:addr.city,state:addr.state},items:[{k,product_type:k,title,qty:Math.max(1,qty),price,size,style:dimension&&dimension[1]===dimension[2]?'Square / Petak':k==='printed'?'Editing / Existing Design — Glossy':'',wording,custom_text:wording,review:'Need Review',review_required:true,customization:{source:'chat_trigger'}}],delivery,delivery_fee,date_need:null,admin_remark:addr.address_line1?'Draft extracted from current WhatsApp order session. Address found in current session.':'Draft extracted from current WhatsApp order session. Address not found; customer can fill later.',address_evidence:addr.source}
}
async function llm(base:any,ms:any[],opened:string,cutoff:string,rules:any[]){const key=await setting('openai_api_key')||Deno.env.get('OPENAI_API_KEY')||'';if(!key)return null;const model=await setting('qrpay_ai_model')||Deno.env.get('OPENAI_MODEL')||'gpt-4o-mini';const transcript=ms.slice(-120).map(m=>`${m.direction==='inbound'?'CUSTOMER':'SELLER'} [${m.created_at}]: ${msgText(m)||`[${m.message_type}]`}`).join('\n');const learned=buildLearningPrompt(rules);const sys=`You reconstruct ONE current cake-decor order session from WhatsApp for iCetak/DecoCake Malaysia. Session starts ${opened} and freezes at ${cutoff}. Return JSON only: customer{name,phone,address_line1,postcode,city,state}, items[{k,product_type,title,qty,price,size,style,wording,custom_text,review,review_required,customization}], delivery(pickup|spx|jnt|ninja|unknown), delivery_fee, date_need YYYY-MM-DD|null, admin_remark. Rules: never invent. Preserve distinct products. Seller explicit latest quote is authoritative for unit price/qty/shipping. A line like 'edible 24x2pcs 48' means unit price 24 qty 2. Do not use price-list/template messages unless seller applies them to this deal. Latest correction wins. Extract explicit wording/name. Extract delivery address ONLY when explicitly present inside THIS current session. Never reuse an address from a previous/closed order. If address is absent leave address_line1/postcode/city/state empty. If information missing use empty string/0/unknown/null. Do not pull any previous order outside this supplied session.${learned?`\n\n${learned}`:''}`;const r=await fetch('https://api.openai.com/v1/chat/completions',{method:'POST',headers:{authorization:`Bearer ${key}`,'content-type':'application/json'},body:JSON.stringify({model,temperature:0,response_format:{type:'json_object'},messages:[{role:'system',content:sys},{role:'user',content:`Known customer: ${JSON.stringify(base.customer)}\n\n${transcript}`}]})});if(!r.ok)return null;const j=await r.json();try{return JSON.parse(j?.choices?.[0]?.message?.content||'')}catch{return null}}
function normalize(base:any,ai:any,conv:any,ms:any[],opened:string,cutoff:string){const p={...base,...(ai||{}),customer:{...base.customer,...(ai?.customer||{})}};p.customer.phone=phone(p.customer.phone)||conv.phone;p.customer.name=t(p.customer.name)||conv.name;p.whatsapp_identity={phone:conv.phone||null,bsuid:conv.bsuid||null,username:conv.username||null,customer_master_id:conv.customer_master_id||null};p.customer.address_line1=t(p.customer.address_line1);p.customer.postcode=t(p.customer.postcode);p.customer.city=t(p.customer.city);p.customer.state=t(p.customer.state);p.items=(Array.isArray(p.items)&&p.items.length?p.items:base.items).map((x:any,i:number)=>{let k=t(x.k||x.product_type).toLowerCase();if(k==='topper')k='printed';if(!['printed','edible','acrylic','wafer','burnaway','mirror'].includes(k))k='printed';const w=t(x.wording||x.custom_text);return{...x,k,product_type:k,title:t(x.title)||({printed:'Cake Topper',edible:'Edible Image',acrylic:'Acrylic Cake Topper',wafer:'Wafer Paper'} as any)[k]||'Item',qty:Math.max(1,Number(x.qty||1)),price:Math.max(0,Number(x.price||0)),size:t(x.size),style:t(x.style),wording:w,custom_text:w,review:'Need Review',review_required:true,customization:{...(x.customization||{}),source:'chat_trigger',set_hint:i+1}}});p.delivery=t(p.delivery||'unknown').toLowerCase();p.delivery_fee=Math.max(0,Number(p.delivery_fee||0));p.evidence={conversation_id:conv.id,session_opened_at:opened,cutoff_at:cutoff,message_ids:ms.map(m=>m.id),messages:ms.slice(-80).map(m=>({id:m.id,direction:m.direction,type:m.message_type,at:m.created_at,text:msgText(m).slice(0,600)})),reference_media:refs(ms),address_from_current_session:Boolean(p.customer.address_line1),extractor:ai?'openai+heuristic':'heuristic',worker_version:'order-draft-trigger-v3-address-clean'};return p}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:H});if(req.method!=='POST')return out({ok:false,error:'POST required'},405);if(!await auth(req))return out({ok:false,error:'Unauthorized'},401);try{
  const b=await req.json().catch(()=>({})),conv=await resolve(b),cutoff=t(b.cutoff_at)||new Date().toISOString(),providerMessageId=t(b.provider_message_id||b.message_id),ctx=await bridge({action:'order_session_context',conversation_id:conv.id,phone:conv.phone,bsuid:conv.bsuid}),opened=t(ctx.opened_at)||new Date(Date.now()-45*86400000).toISOString(),[sessionMessages,snippets]=await Promise.all([history(conv.id,opened,cutoff),activeSellerSnippets()]),filtered=filterOrderEvidenceMessages(sessionMessages,snippets),ms=filtered.messages;
  if(!ms.length)throw Error('No order messages in current order session');
  const localTrigger=t(b.trigger_message_id),uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i,triggerMessageId=uuid.test(localTrigger)?localTrigger:(ms.find((m:any)=>m.provider_message_id===providerMessageId)?.id||null);
  const source=t(b.source_type)||'chat_trigger',paymentMode=t(b.payment_mode)||'prepaid',base=heuristic(ms,conv);if(source==='pickup_trigger'&&base.delivery==='unknown')base.delivery='pickup';const context=await bridge({action:'learning_context'}).catch(()=>({rules:[]})),rules=Array.isArray(context.rules)?context.rules:[],ai=await llm(base,ms,opened,cutoff,rules),payload=applyLearningRules(normalize(base,ai,conv,ms,opened,cutoff),ms,rules,{flow:source,referenceTime:cutoff,promptInjected:Boolean(ai),customerIdentity:{name:conv.name,phone:conv.phone,bsuid:conv.bsuid}}),requestKey=t(b.request_key)||t(b.request_id)||`${source}:${conv.id}:${providerMessageId||triggerMessageId||cutoff}`;
  payload.evidence={...payload.evidence,order_session_id:ctx.session_id||null,session_boundary_at:ctx.boundary_at||opened,session_boundary_enforced:true,seller_template_filter:{total_messages:sessionMessages.length,included_messages:ms.length,excluded_count:filtered.excluded.length,excluded:filtered.excluded},whatsapp_identity:payload.whatsapp_identity,provider_message_id:providerMessageId||null,event_timestamp:b.event_timestamp||b.timestamp||null};
  if(b.dry_run)return out({ok:true,dry_run:true,request_key:requestKey,order_session_id:ctx.session_id||null,session_opened_at:opened,cutoff_at:cutoff,conversation_id:conv.id,phone:conv.phone,bsuid:conv.bsuid,username:conv.username,excluded_seller_messages:filtered.excluded.length,extraction:payload});
  const created=await bridge({action:'create_generic_draft',source_type:source,payment_mode:paymentMode,request_key:requestKey,conversation_id:conv.id,phone:conv.phone,bsuid:conv.bsuid,username:conv.username,customer_master_id:conv.customer_master_id,customer_name:conv.name,cutoff_at:cutoff,trigger_message_id:triggerMessageId,provider_message_id:providerMessageId||null,payload,actor:'order-draft-trigger'});
  const masterId=t(created.result?.customer_master_id);if(masterId&&masterId!==conv.customer_master_id)await db.from('customers').update({order_system_master_customer_id:masterId,updated_at:new Date().toISOString()}).eq('id',conv.customer_id);
  return out({ok:true,request_key:requestKey,order_session_id:created.result?.order_session_id||ctx.session_id||null,session_opened_at:opened,cutoff_at:cutoff,conversation_id:conv.id,phone:conv.phone,bsuid:conv.bsuid,username:conv.username,customer_master_id:masterId||conv.customer_master_id||null,excluded_seller_messages:filtered.excluded.length,extraction:payload,result:created.result})
}catch(e){console.error('order-draft-trigger',e);return out({ok:false,error:e instanceof Error?e.message:String(e)},500)}});
