/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false worker/worker-configuration.d.ts` (hash: 70020d1ce251851dedc71e1934c44216)
interface __BaseEnv_Env {
	BROWSER: BrowserRun;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./render-output");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
