import {PRODUCTS,Customer,Address,collect,createOrder,esc,lookup,money} from './admin-whatsapp-paid-order-model';
import {formHtml,itemRow,successHtml} from './admin-whatsapp-paid-order-template';
let dialog:HTMLElement|null=null,seq=1,requestId='';
function note(m:string,bad=false){const x=document.createElement('div');x.className=`wa-order-toast${bad?' error':''}`;x.textContent=m;document.body.append(x);setTimeout(()=>x.remove(),2800)}
function close(){dialog?.remove();dialog=null}
function modal(title:string,html:string){close();const w=document.createElement('div');w.className='modal-wrap wa-order-modal-wrap';w.innerHTML=`<section class="modal wa-order-modal"><button class="modal-x" data-wa-close>×</button><h2>${title}</h2>${html}</section>`;document.body.append(w);w.onclick=e=>{const t=e.target as HTMLElement;if(t===w||t.closest('[data-wa-close]'))close()};dialog=w;return w}
function renumber(w:HTMLElement){const rows=w.querySelectorAll<HTMLElement>('[data-wa-item]');rows.forEach((r,i)=>{r.querySelector<HTMLElement>('[data-wa-item-number]')!.textContent=String(i+1);r.querySelector<HTMLButtonElement>('[data-wa-remove-item]')!.hidden=rows.length===1})}
function calc(w:HTMLElement){let items=0;w.querySelectorAll<HTMLElement>('[data-wa-item]').forEach(r=>items+=Math.max(1,Number(r.querySelector<HTMLInputElement>('input[name^="qty_"]')?.value||0))*Math.max(0,Number(r.querySelector<HTMLInputElement>('input[name^="price_"]')?.value||0)));const delivery=w.querySelector<HTMLSelectElement>('[name="delivery"]')?.value||'pickup',f=w.querySelector<HTMLInputElement>('[name="delivery_fee"]');if(delivery==='pickup'&&f)f.value='0';const fee=Math.max(0,Number(f?.value||0)),total=items+fee;w.querySelector<HTMLElement>('[data-wa-items-total]')!.textContent=money(items);w.querySelector<HTMLElement>('[data-wa-delivery-total]')!.textContent=money(fee);w.querySelector<HTMLElement>('[data-wa-grand-total]')!.textContent=money(total);w.querySelector<HTMLInputElement>('[name="payment_amount"]')!.value=total.toFixed(2)}
function delivery(w:HTMLElement){const courier=w.querySelector<HTMLSelectElement>('[name="delivery"]')?.value!=='pickup',a=w.querySelector<HTMLElement>('[data-wa-address]')!;a.hidden=!courier;a.querySelectorAll<HTMLInputElement>('input').forEach(i=>i.required=courier&&['address_line1','city','postcode','state'].includes(i.name));calc(w)}
function address(w:HTMLElement,a?:Address){if(!a)return;for(const k of ['address_line1','address_line2','city','postcode','state']){const i=w.querySelector<HTMLInputElement>(`[name="${k}"]`);if(i)i.value=String((a as any)[k]||'')}}
function customer(w:HTMLElement,c:Customer){w.querySelector<HTMLInputElement>('[name="name"]')!.value=c.name||'';w.querySelector<HTMLInputElement>('[name="phone"]')!.value=c.phone||'';address(w,[...(c.addresses||[])].sort((a,b)=>Number(!!b.is_default)-Number(!!a.is_default))[0]);w.querySelector<HTMLElement>('[data-wa-customer-results]')!.innerHTML='<span class="wa-customer-found">✓ Customer lama dijumpai dan detail diisi.</span>'}
async function findCustomer(w:HTMLElement){const q=w.querySelector<HTMLInputElement>('[name="phone"]')!.value.trim(),out=w.querySelector<HTMLElement>('[data-wa-customer-results]')!,b=w.querySelector<HTMLButtonElement>('[data-wa-lookup]')!;if(!q)return note('Masukkan nombor WhatsApp dahulu',true);b.disabled=true;b.textContent='Searching…';try{const m=await lookup(q);if(!m.length)out.innerHTML='<span>Customer baru — isi nama dan alamat.</span>';else if(m.length===1)customer(w,m[0]);else{out.innerHTML=m.map((c,i)=>`<button type="button" data-customer="${i}"><b>${esc(c.name)}</b><span>${esc(c.phone)}</span></button>`).join('');out.querySelectorAll<HTMLButtonElement>('[data-customer]').forEach(x=>x.onclick=()=>customer(w,m[Number(x.dataset.customer)]))}}catch(e){note(e instanceof Error?e.message:'Lookup gagal',true)}finally{b.disabled=false;b.textContent='Find Customer'}}
async function submit(w:HTMLElement,f:HTMLFormElement){const v=collect(f),d=v.data;if(!v.phone)return note('Nombor WhatsApp Malaysia tidak sah',true);if(!v.name)return note('Nama customer diperlukan',true);if(!v.items.length)return note('Tambah item dan harga',true);if(v.delivery!=='pickup'&&['address_line1','city','postcode','state'].some(k=>!String(d.get(k)||'').trim()))return note('Lengkapkan alamat penghantaran',true);if(!v.transactionId)return note('Masukkan transaction/reference ID QR',true);const b=f.querySelector<HTMLButtonElement>('button[type="submit"]')!;b.disabled=true;b.textContent='Creating paid order…';try{const r=await createOrder({client_request_id:requestId,customer:{name:v.name,phone:v.phone,address_line1:String(d.get('address_line1')||'').trim(),address_line2:String(d.get('address_line2')||'').trim(),city:String(d.get('city')||'').trim(),postcode:String(d.get('postcode')||'').trim(),state:String(d.get('state')||'').trim()},items:v.items,date_need:String(d.get('date_need')||''),delivery:v.delivery,delivery_fee:Number(d.get('delivery_fee')||0),admin_remark:String(d.get('admin_remark')||'').trim(),notify_whatsapp:Boolean(d.get('notify_whatsapp')),payment:{method:'Manual QR Pay',transaction_id:v.transactionId,sender_name:String(d.get('sender_name')||'').trim(),paid_at:String(d.get('paid_at')||''),amount:Number(d.get('payment_amount')||0),receipt_note:String(d.get('receipt_note')||'').trim()}});const done=modal('',successHtml(r,v.name,v.phone,String(d.get('date_need')||'')));done.querySelector<HTMLButtonElement>('[data-copy-order]')!.onclick=async e=>{await navigator.clipboard.writeText((e.currentTarget as HTMLButtonElement).dataset.copyOrder||'');note('Customer link copied')}}catch(e){note(e instanceof Error?e.message:'Order gagal dicipta',true);b.disabled=false;b.textContent='Create Paid WhatsApp Order'}}
function open(){seq=1;requestId=crypto.randomUUID();const w=modal('Create WhatsApp QR Order',formHtml()),f=w.querySelector<HTMLFormElement>('#waPaidOrderForm')!;w.querySelector<HTMLButtonElement>('[data-wa-lookup]')!.onclick=()=>void findCustomer(w);w.querySelector<HTMLButtonElement>('[data-wa-add-item]')!.onclick=()=>{seq++;w.querySelector<HTMLElement>('[data-wa-items]')!.insertAdjacentHTML('beforeend',itemRow(seq));renumber(w);calc(w)};w.addEventListener('click',e=>{const x=(e.target as HTMLElement).closest<HTMLButtonElement>('[data-wa-remove-item]');if(x){x.closest('[data-wa-item]')?.remove();renumber(w);calc(w)}});w.addEventListener('input',e=>{if((e.target as HTMLElement).matches('[data-wa-money]'))calc(w)});w.addEventListener('change',e=>{const x=e.target as HTMLSelectElement;if(x.name==='delivery')delivery(w);if(x.matches('[data-wa-kind]')){const i=x.closest<HTMLElement>('[data-wa-item]')?.querySelector<HTMLInputElement>('[data-wa-title]');if(i)i.value=PRODUCTS[x.value as keyof typeof PRODUCTS]||'Item'}});f.onsubmit=e=>{e.preventDefault();void submit(w,f)};renumber(w);delivery(w);calc(w)}
document.addEventListener('click',e=>{if(!(e.target as HTMLElement).closest('#adminCreateOrderBtn'))return;e.preventDefault();e.stopImmediatePropagation();open()},true);
function enhance(){const b=document.querySelector<HTMLButtonElement>('#adminCreateOrderBtn');if(b&&b.dataset.waUpgraded!=='1'){b.dataset.waUpgraded='1';b.textContent='＋ Create WhatsApp QR Order'}document.querySelectorAll<HTMLElement>('.admin-users section').forEach(s=>{const u=s.querySelector('h3')?.textContent?.trim()||'';if(!u||s.querySelector('[data-wa-verify-payment-permission]'))return;const l=document.createElement('label');l.dataset.waVerifyPaymentPermission='1';const checked=!!s.querySelector('input[value="create_order"]:checked');l.innerHTML=`<input type="checkbox" data-perm-user="${esc(u)}" value="verify_payments" ${checked?'checked':''}> verify_payments`;const save=s.querySelector('[data-save-perms]');save?s.insertBefore(l,save):s.append(l)})}
let timer=0;new MutationObserver(()=>{clearTimeout(timer);timer=window.setTimeout(enhance,40)}).observe(document.body,{childList:true,subtree:true});enhance();
