export type ProductDetail={intro:string;highlights:string[];specs:string[];usage?:string[];notes:string[]};
export const PRODUCT_DETAILS:Record<string,ProductDetail>={
 edible:{intro:'Cetakan gambar dan wording menggunakan icing paper serta edible ink. Sesuai diletakkan di atas buttercream atau fondant untuk kek kecil hingga besar.',highlights:['Pre-order dengan review dan preview design','Urgent tanpa review tertakluk kepada slot sebelum 12 PM','Edit asas susunan wording dan saiz termasuk dalam servis'],specs:['A6 RM6: sehingga 3.7 × 5.5 inci','A5 RM12: sehingga 5.5 × 7.5 inci','A4 RM24: sehingga 7.5 × 11 inci','Bentuk: bulat, petak, hati, potret, landskap atau custom','Material: icing paper dengan edible ink, boleh dimakan'],usage:['Pastikan permukaan kek rata dan kering','Keluarkan image dari plastik dan gunting lebihan','Letak perlahan di atas kek dan tekan lembut','Elakkan semburan air terus pada image','Simpan kek dalam kotak tertutup jika dimasukkan ke peti sejuk'],notes:['Proses biasa 1–3 hari bekerja bergantung kepada queue dan respon customer','Warna cetakan mungkin sedikit berbeza daripada skrin','Servis cetakan sahaja dan tidak termasuk potong','Simpan di tempat sejuk dan kering; guna dalam 2 minggu hingga 1 bulan untuk kualiti terbaik']},
 burnaway:{intro:'Set dua lapisan untuk Burn Away Cake: satu edible image di bahagian bawah dan satu wafer paper di bahagian atas untuk dibakar.',highlights:['Termasuk 1 edible image dan 1 wafer paper','Saiz setiap lapisan boleh dipilih berasingan','Sesuai untuk kek viral burn away'],specs:['Saiz tersedia 3 hingga 7.5 inci','Custom A5 dan custom A4 tersedia','Saiz tetap adalah bulat; bentuk lain perlu custom','Edible image disaran lebih kecil daripada diameter kek','Wafer paper boleh sama saiz atau sedikit lebih besar mengikut dekorasi baker'],notes:['Kek dan hiasan tidak termasuk','Pemilihan saiz akhir sebaiknya ikut cadangan baker','Custom shape atau ukuran khas perlu dimaklumkan sebelum order']},
 wafer:{intro:'Servis cetakan wafer paper sahaja untuk Burn Away Cake atau dekorasi kek.',highlights:['Ringan dan mudah digunakan sebagai lapisan atas','Boleh cetak gambar atau wording custom','Sesuai untuk burn away cake'],specs:['Saiz 3, 3.5, 4, 4.5, 5, 5.5, 6, 6.5, 7, 7.5 dan 8 inci','Custom A5 dan custom A4 tersedia','Bentuk: bulat, petak atau hati'],notes:['Wafer paper sahaja; edible image dan kek tidak termasuk','Saiz atau bentuk khas perlu dimaklumkan terlebih dahulu','Hasil warna wafer lebih lembut berbanding icing paper']},
 printed:{intro:'Cake topper bercetak menggunakan artpaper glossy, sesuai untuk nama, umur, ucapan hari jadi dan tema majlis.',highlights:['Custom nama, umur atau wording','Satu bahagian bercetak','Sesuai untuk kek kecil dan sederhana'],specs:['Topper nama utama sekitar 4–6 inci','Hiasan kecil sekitar 1–3 inci','Standard set: 1 topper besar dan 5–10 topper kecil','Material: glossy photo artpaper'],notes:['Masukkan wording lengkap semasa checkout','Proses biasa sekitar 1 hari bekerja selepas detail lengkap','Warna dan bilangan hiasan kecil bergantung pada design']},
 mirror:{intro:'Cake topper daripada artpaper premium mirror gold yang tebal, ringan dan tidak mudah patah.',highlights:['Warna mirror gold','Boleh custom nama atau wording','Ringan dan sesuai untuk pelbagai saiz kek'],specs:['Harga bermula RM15','Boleh custom sehingga A5, maksimum 8 × 5.5 inci','Material: premium mirror artpaper'],notes:['Warna lain tidak termasuk dalam variasi ini','Saiz sebenar akan disesuaikan supaya design kekal seimbang','Sesuai untuk birthday, wedding dan anniversary']},
 acrylic:{intro:'Cake topper acrylic custom 2mm untuk birthday, wedding, anniversary dan majlis khas.',highlights:['Design custom percuma berdasarkan nama atau wording','Pilihan warna acrylic yang luas','Datang dengan clear stick standard'],specs:['A7 mini: sehingga 2.5 × 4 inci','A6 standard: sehingga 5.5 × 4 inci','A5 large: sehingga 8 × 5.5 inci','Material: acrylic 2mm, satu lapisan','Warna termasuk mirror gold, silver, rose gold, hitam, clear, glitter dan pilihan warna lain'],notes:['Double layer dan stick berwarna memerlukan caj tambahan','Proses biasa 2–3 hari bekerja bergantung kepada queue','Saiz akhir boleh disesuaikan mengikut kek dan design','A4 atau saiz lebih besar perlu semakan khas']}
};
