create extension if not exists pg_cron;

create table if not exists public.admin_whatsapp_window_monitor (
  admin_phone text primary key,
  last_inbound_at timestamptz not null,
  window_expires_at timestamptz not null,
  window_status text not null default 'open' check (window_status in ('open','expired')),
  warn_6h_sent_at timestamptz,
  warn_2h_sent_at timestamptz,
  warn_30m_sent_at timestamptz,
  last_warning_level text check (last_warning_level is null or last_warning_level in ('6h','2h','30m')),
  last_provider_message_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_whatsapp_window_warning_log (
  id bigint generated by default as identity primary key,
  admin_phone text not null,
  warning_level text not null check (warning_level in ('6h','2h','30m')),
  window_expires_at timestamptz not null,
  provider_message_id text,
  sent_at timestamptz not null default now()
);

create index if not exists admin_whatsapp_window_warning_log_phone_sent_idx
  on public.admin_whatsapp_window_warning_log(admin_phone, sent_at desc);

alter table public.admin_whatsapp_window_monitor enable row level security;
alter table public.admin_whatsapp_window_warning_log enable row level security;

revoke all on public.admin_whatsapp_window_monitor from anon, authenticated;
revoke all on public.admin_whatsapp_window_warning_log from anon, authenticated;

grant all on public.admin_whatsapp_window_monitor to service_role;
grant all on public.admin_whatsapp_window_warning_log to service_role;

insert into public.private_runtime_settings(setting_key, setting_value, updated_at)
values (
  'admin_whatsapp_window_monitor_url',
  'https://buivecgahhmrhlmfujgt.supabase.co/functions/v1/admin-whatsapp-window-monitor',
  now()
)
on conflict (setting_key) do update
set setting_value = excluded.setting_value,
    updated_at = now();

create or replace function public.icetak_check_admin_whatsapp_window()
returns bigint
language plpgsql
security definer
set search_path = 'public'
as $$
declare
  monitor_url text;
  monitor_token text;
  request_id bigint;
begin
  select setting_value into monitor_url
  from public.private_runtime_settings
  where setting_key = 'admin_whatsapp_window_monitor_url'
  limit 1;

  select setting_value into monitor_token
  from public.private_runtime_settings
  where setting_key = 'qrpay_ai_worker_token'
  limit 1;

  if nullif(monitor_url, '') is null or nullif(monitor_token, '') is null then
    return null;
  end if;

  select net.http_post(
    url := monitor_url,
    headers := jsonb_build_object(
      'content-type', 'application/json',
      'x-admin-window-token', monitor_token
    ),
    body := jsonb_build_object('action', 'check')
  ) into request_id;

  return request_id;
end;
$$;

revoke all on function public.icetak_check_admin_whatsapp_window() from public, anon, authenticated;
grant execute on function public.icetak_check_admin_whatsapp_window() to service_role;

select cron.unschedule(jobid)
from cron.job
where jobname = 'icetak-admin-whatsapp-window-every-5-minutes';

select cron.schedule(
  'icetak-admin-whatsapp-window-every-5-minutes',
  '*/5 * * * *',
  'select public.icetak_check_admin_whatsapp_window();'
);
